habitat-sh/core-plans

kibana/config/kibana.yml, kibana/default.toml, kibana/hooks/init, kibana/hooks/run, kibana/plan.sh
=> add plan for kibana

.travis.yml, travis.sh
=> Add travis

re2c/plan.sh
re2c is a public domain C/C++ lexer generator.
=> re2c 0.16 (new plan)

rust/plan.sh
=> Update to Rust 1.10.0.

python/plan.sh
=> Upgrade pip when building python

aws-cli/plan.sh
=> Write out requirements.txt in aws-cli plan

lua/plan.sh
=> lua 5.3.3 (new plan)

travis.sh
=> set origin to auto on auto

travis.sh
=> don't run pre-commit on auto

inspec/plan.sh
=> inspec plan

pixman/plan.sh
A pixel manipulation library used in a number of graphics related
libraries and packages.
=> pixman 0.34.0 (new plan)

.mention-bot
Copied from the .mention-bot in habitat-sh/habitat.
=> Add .mention-bot

elfutils/plan.sh
Was needed to make flow work (used in mention-bot)
=> Add elfutils

.travis.yml
=> fix webhook

mention-bot/default.toml, mention-bot/hooks/run, mention-bot/plan.sh
=> Add mention-bot

python2/plan.sh
- License corrected
- Metadata compliant
- Add sqlite to runtime
- Add check case
=> python2 (updated)

sqlite/plan.sh
- New version, changelog here:
https://www.sqlite.org/releaselog/3_13_0.html
- Metadata updated for compliance.
=> sqlite (updated)

lynx/plan.sh
=> Add Lynx plan

htop/plan.sh
Signed-off-by: Brian Scott <brainscott@gmail.com>
=> Add htop package

tmux/plan.sh
=> Add tmux 2.2

jbigkit/libjbig-shared-library.patch, jbigkit/plan.sh, libtiff/plan.sh
=> Add libtiff and jbigkit

libunwind/plan.sh
=> Add libunwind 1.1

bdwgc/plan.sh, guile/plan.sh, libatomic_ops/plan.sh, libunistring/plan.sh
Guile is an implementation of scheme that is used as an extension
language in many GNU programs.
=> Add guile and its dependencies

ninja/plan.sh
=> ninja 1.7.1 (new plan)

valgrind/plan.sh
=> Add valgrind 3.11.0

swig/plan.sh
=> swig 3.0.10 (new plan)

doxygen/plan.sh
=> doxygen 1.8.11 (new plan)

ed/plan.sh, lzip/plan.sh
Ed is the standard text editor! Free yourself from the bloat of vim and
emacs.
quit
?
exit
?
^C
?
q
=> Add ed 1.13 and lzip 1.18

jre8/plan.sh
- copied from core/jdk8
- linted
Signed-off-by: bdangit <me@bdang.it>
=> add a plan for jre8

libpcap/plan.sh, tcpdump/plan.sh
=> Add tcpdump and libpcap

rsync/plan.sh
=> Add rsync plan

.travis.yml
=> Use old-bots for homu

tomcat-native/plan.sh
Signed-off-by: bdangit <me@bdang.it>
=> Add tomcat-native

libwebp/plan.sh
A library to encode/decode images in WebP format.
Depends on #120
=> libwebp 0.5.1 (new plan)

gdb/plan.sh
Sorry for overlooking this in the last pull request :disappointed:
=> Switch --with-system-gdbinit from system-wide path to package specific.

jdk8/plan.sh
=> updated to latest jdk8u102

github_changelog_generator/plan.sh
=> Add github changelog generator package

gecode/plan.sh
The first step towards making a ChefDK hart
I do not have the core key so I cannot upload this. Is there a process for becoming a core maintainer, or will someone with permissions upload it to the depot?
=> Adding a plan for gecode 3.7.3

nspr/plan.sh, nss/plan.sh, popt/plan.sh, rpm/plan.sh
Plans for RPM and its dependencies.
=> Add plans for RPM, NSS, NSPR and Popt

autogen/plan.sh
=> autogen 5.18.10 (new plan)

kibana/config/kibana.yml, kibana/default.toml
Update kibana toml to properly format integers and booleans
=> Update kibana to listen to binding for elasticsearch

gnatsd/plan.sh
Currently supports running with default configuration.
=> Create plan for gnatsd, a lightweight go based messaging server.

rabbitmq/config/rabbitmq.config, rabbitmq/default.toml, rabbitmq/hooks/init, rabbitmq/hooks/run, rabbitmq/plan.sh
This is an initial pass and certainly doesn't cover all configuration cases (including HA)
=> Add rabbitmq to core plans

repo/README.md, repo/plan.sh
Signed-off-by: bdangit <me@bdang.it>
=> Add new plan for `repo`

binutils/plan.sh, gcc/plan.sh
=> Use core/bash over /bin/bash in binutils & gcc plans

gcc/plan.sh
=> [gcc] Add fortran to enabled languages

delivery-cli/plan.sh
This builds upon the Original PR #57 to push it over the finish line
=> Add Delivery-CLI plan

vim/plan.sh
Vim 8.0 announcement: https://groups.google.com/forum/#!topic/vim_announce/EKTuhjF3ET0
=> Update to Vim 8.0

postgresql/hooks/init, postgresql/hooks/run
=> Postgres hooks: perms are dropped earlier than expected

mysql/plan.sh
Signed-off-by: Steven Murawski <steven.murawski@gmail.com>
=> fix quoting for the mysql plan

mongodb/config/mongod.conf, mongodb/config/mongos.conf, mongodb/default.toml, mongodb/hooks/init, mongodb/hooks/run, mongodb/plan.sh
Added the mongodb plans with configurations for mongod and mongos servers.
=> Mongodb addition

redis/plan.sh
=> fix path for pkg_svc_run

cmake/plan.sh
1/408 tests failed.
```
7/408 Test   #7: kwsys.testSystemTools ............................***Failed    0.00 sec
```
I searched for the issue and could not find people to hit the same issue. Don't know what was the problem.
=> Update CMake to version 3.6.2 and other small improvements

elixir/plan.sh
Update Elixir plan for 1.3.2 release
=> Update Elixir plan for 1.3.2 release

openssl/plan.sh
This addresses the following CVEs:
- OCSP Status Request extension unbounded memory growth (CVE-2016-6304)
- SWEET32 Mitigation (CVE-2016-2183)
- OOB write in MDC2_Update() (CVE-2016-6303)
- Malformed SHA512 ticket DoS (CVE-2016-6302)
- OOB write in BN_bn2dec() (CVE-2016-2182)
- OOB read in TS_OBJ_print_bio() (CVE-2016-2180)
- Pointer arithmetic undefined behaviour (CVE-2016-2177)
- Constant time flag not preserved in DSA signing (CVE-2016-2178)
- DTLS buffered message DoS (CVE-2016-2179)
- DTLS replay protection DoS (CVE-2016-2181)
- Certificate message OOB reads (CVE-2016-6306)
See https://www.openssl.org/news/cl102.txt for more info
=> [openssl] Update to 1.0.2i

cyrus-sasl/plan.sh, openldap/config/slapd.ldif, openldap/default.toml, openldap/hooks/init, openldap/hooks/run, openldap/plan.sh
New plans for OpenLDAP and Cyrus SASL
=> Add OpenLDAP and Cyrus SASL

ruby-rails-sample/config/database.yml
Fixes #209 - this template never got updated when we switched from Mustache to Handlebars in https://github.com/habitat-sh/habitat/pull/559
=> Update rails-sample database.yml handlebars syntax

flatbuffers/plan.sh
=> Add flatbuffers

jfrog-cli/plan.sh
- Variablized the `${pkg_source}`
- removed the `core/patchelf` from the build_deps
=> Cleaned up the jfrog-cli plan

tree/plan.sh
Signed-off-by: kmacgugan kmacgugan@chef.io
=> Add plan for tree

sysstat/plan.sh
Signed-off-by: kmacgugan kmacgugan@chef.io
=> Add plan for sysstat

sudo/plan.sh
Released on 2016-10-10.
Changelog: https://www.sudo.ws/changes.html
Signed-off-by: Mike Fiedler miketheman@gmail.com
=> sudo 1.8.18p1 (updated)

README.md
[ci skip] for doc-only update.
Signed-off-by: Mike Fiedler miketheman@gmail.com
=> :books: Update README with some fancy badges

MAINTAINERS.md
git blame: @eeyun & @smurawski
Signed-off-by: Mike Fiedler miketheman@gmail.com
=> Add maintainer

jdk8/plan.sh, jre8/plan.sh, server-jre/plan.sh
http://www.oracle.com/technetwork/java/javase/8u111-relnotes-3124969.html
=> Update Java plans to v8u111 security release

jdk8/plan.sh, jre8/plan.sh
Add build line for oracle license
=> Update java plans to properly link shared object files.

jemalloc/plan.sh
Signed-off-by: Sean OMeara <sean@sean.io>
=> adding jemalloc plan

libpipeline/plan.sh
=> Add libpipeline plan

rabbitmq/default.toml, rabbitmq/hooks/init, rabbitmq/hooks/run, rabbitmq/plan.sh
=> Add ability to turn on rabbitmq management console

tzdata/plan.sh
This also adds proper install logic
=> Update tzdata to 2016i

virtualenv/plan.sh
=> Add virtualenv (for python2)

curator/plan.sh
=> Add elasticsearch curator

go/plan.sh
=> Updated go version

.pre-commit-config.yaml, .travis.yml, bin/travis.sh
This is the theoretical fix to correct travis' behavior against new core-plans PRs.
=> WIP: Corrected travis calls to pre-commit

openjpeg/plan.sh
This is dependent on #275 being merged first
=> Added openjpeg

vault/config/settings.hcl, vault/default.toml, vault/hooks/run, vault/plan.sh
This habitizes vault in a dev mode and pulls down from hashicorp.
=> hashicorp vault plan

lz4/plan.sh
=> Update lz4 plan

mariadb/config/init.sql, mariadb/config/my.cnf, mariadb/default.toml, mariadb/hooks/init, mariadb/hooks/run, mariadb/plan.sh
Hello, I have created a plan for mariadb. If you have any comments or concerns please tell me.
=> Add mariadb plan

libossp-uuid/plan.sh
=> Add ossp-uuid library plan

postgresql/plan.sh
=> Update core postgres to support UUIDs through ossp-uuid

postgresql/plan.sh
=> Added all postgres extensions from world

openresty/config/fastcgi.conf, openresty/config/fastcgi_params, openresty/config/koi-utf, openresty/config/koi-win, openresty/config/mime.types, openresty/config/nginx.conf, openresty/config/scgi_params, openresty/config/uwsgi_params, openresty/config/win-utf, openresty/default.toml, openresty/plan.sh
=> Added plan for OpenResty

ccache/plan.sh
=> Add ccache plan

elasticsearch/config/elasticsearch.yml
=> Allow elasticsearch to update member hosts in unicast mode from bind peers

elasticsearch/config/elasticsearch.yml, elasticsearch/default.toml, elasticsearch/hooks/run
updates from onsite work ping @elliott-davis
=> es_config_updates

elasticsearch/config/elasticsearch.yml, elasticsearch/config/logging.yml, elasticsearch/default.toml, elasticsearch/plan.sh
=> Update paths for ES plan to allow other plans to inherit

kibana/config/kibana.yml, kibana/hooks/init, kibana/hooks/run, kibana/plan.sh
onsite edits @elliott-davis, thumbs?
=> update to 4.6.1, update hooks

kibana/config/kibana.yml
=> Add port for bind member in kibana config.

repo/plan.sh, tomcat-native/plan.sh
=> Fix incorrect origin in repo & tomcat-native packages

gradle/plan.sh
=> Add plan for Gradle

logstash/plan.sh
=> Update Logstash to 5.1.1

go/plan.sh
=> Fix go path issue for included paths

mssql/default.toml, mssql/hooks/init, mssql/hooks/run, mssql/plan.sh
=> add MSSQL plan

lessmsi/plan.ps1, node/plan.ps1
This also adds a handy utility for popping open MSIs: lessmsi
=> add a powershell based node plan

jdk7/plan.sh
Mostly a copy/paste from jdk8 with a few minor tweaks.
=> Adding jdk7

jre7/plan.sh
When adding jre7, I discovered I did not have the latest jdk.
=> Adding jre7 and bumping jdk7 to match

tomcat7/README.md, tomcat7/config/conf_server.xml, tomcat7/config/conf_tomcat-users.xml, tomcat7/config/webapps_host-manager_META-INF_context.xml, tomcat7/default.toml, tomcat7/hooks/init, tomcat7/hooks/run, tomcat7/plan.sh
=> Add Tomcat7 plan

erlang16/plan.sh
Lets try this one more time!  :)
=> Add erlang16

logback/plan.sh
=> Improvements to logback plan

7zip/plan.ps1
=> Adding 7zip plan

percona-xtrabackup/plan.sh
Adds a plan for the Percona Xtrabackup utilities.
=> adding percona-xtrabackup plan

jetty/hooks/init, jetty/hooks/run, jetty/plan.sh
=> adding plan for jetty 9.1.5

postgresql/plan.sh
Hi Habitants,
Very small changes here to bump the version of Postgres up to latest stable.
best,
@arochaf & @bixu
=> update postgres version to 9.6.1

icu/plan.sh, icu56/plan.sh
=> Add icu56 and lint icu plans

lessmsi/plan.ps1
I had this before building it before but missed it in my commit
=> copy next directory level which missed my last pr

node/plan.ps1
=> fix node install on windows

python/plan.sh
This also includes changes from #335
=> Update python to 3.6.0

powershell/plan.ps1
=> fix install and copy contents of cache src

rust/plan.ps1
=> adding a windows rust plan

openssh/config/sshd_config, openssh/default.toml, openssh/hooks/init, openssh/hooks/run, openssh/plan.sh
Also, make default port configurable.
=> Fix sshd so it will start

mysql-client/plan.sh
* Add missing cmake flags
* Sort deps
* Remove static libs and mysqld scripts
Fixes #196.
=> Make mysql-client compile

postgresql/hooks/health_check, postgresql/plan.sh
=> [postgresql] add health check

node/plan.ps1
=> avoid long path errors in node on windows

rq/plan.sh
=> Add plan for rq

powershell/plan.ps1
=> bumping powershell to 6.0.0-alpha.15

visual-cpp-redist-2013/plan.ps1
=> add visual studio c++ redistributable 2013 binaries

visual-cpp-build-tools-2015/plan.ps1
=> adding visual studio build tools 2015

rust/plan.ps1
=> bump rust to 0.15.0 on windows

cacerts/plan.ps1
=> adding cacert package for windows

cacerts/plan.ps1
=> also save cert to ssl/cert.pem

rust/plan.sh
https://blog.rust-lang.org/2017/02/09/Rust-1.15.1.html
=> Update to Rust 1.15.1.

dotnet-core/plan.ps1
=> bump dotnet core to rc4

lsyncd/plan.sh
=> Add lsyncd plan

nginx/plan.sh
=> Update to NGINX 1.11.10

rust/plan.ps1
=> bumping windows rust to 1.15.1

mysql-client/plan.sh
Introduced this in #396. It makes the build fail :(
=> Fix typo in mysql-client

node/plan.sh, node7/plan.sh
=> Upgrade node to latest LTS release

postgresql93/plan.sh, postgresql94/plan.sh, postgresql95/plan.sh
=> Add postgresql versions 9.3, 9.4 and 9.5

packer/plan.sh
=> Add Packer plan

bats/plan.sh
> Bash Automated Testing System
=> Add bats plan

mc/plan.sh
Midnight commander package added
=> Midnight Commander package added

maven/plan.sh
* Add deps on which and coreutils so scripts run correctly
* Add description and upstream url
* Rearrange some build steps
* Remove pkg_include_dirs because that directory is empty
Fixes #441.
=> Updates to maven

mysql/plan.sh
I've updated the MySQL version to 5.7.17
=> Update MySQL version, SHASUM and OPENSSL_INCLUDE_DIR

consul/config/basic_config.json, consul/plan.sh
Signed-off-by: Sean OMeara <sean@sean.io>
=> updating for consul-0.7.5

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2017/03/16/Rust-1.16.html
=> Update to Rust 1.16.0.

powershell/plan.ps1
=> bump windows powershell to alpha .17

go/plan.sh
=> fix incorrectly named go plan pkg_name variable

handlebars-cmd/plan.sh
cc @smith @schisamo 
Signed-off-by: Yvonne Lam <yvonne@chef.io>
=> Add handlebars-cmd, a handlebars CLI tool.

yarn/plan.sh
=> Update to latest yarn

scaffolding-base/lib/scaffolding.sh, scaffolding-base/plan.sh, scaffolding-go/plan.sh, scaffolding-go17/plan.sh, scaffolding-python/plan.sh, scaffolding-python2/plan.sh
All of the scaffolding plans look a lot alike. Here is a scaffolding for
them.
=> Scaffolding scaffolding to scaffold the scaffolding

node7/plan.sh
=> Fix node7 checksum

man-db/plan.sh
=> man-db plan

terraform/plan.sh
=> Add Terraform 0.8.1

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2017/04/27/Rust-1.17.html
=> Update to Rust 1.17.0.

scaffolding-go/lib/scaffolding.sh, scaffolding-go17/lib/scaffolding.sh, scaffolding-python/lib/scaffolding.sh, scaffolding-python2/lib/scaffolding.sh
References habitat-sh/habitat#2229
=> Update Scaffolding load function name to `scaffolding_load()`.

raml2html/plan.sh
=> raml2html plan for cli use

scaffolding-ruby/README.md, scaffolding-ruby/doc/reference.md
=> [s-ruby] Add documentation for Rails 4.2.x app types.

scaffolding-ruby/CHANGELOG.md, scaffolding-ruby/plan.sh
=> [s-ruby] Release 0.7.0.

node/plan.ps1, node/plan.sh
=> Update node to latest LTS

bin/build-base-plans.sh
=> [build-base-plan.sh] Fix regression due to linting in #475.

scaffolding-ruby/doc/quickstart.md, scaffolding-ruby/doc/reference.md, scaffolding-ruby/lib/scaffolding.sh, scaffolding-ruby/plan.sh
This is a small set of updates to the Ruby Scaffolding which was found
when working on the Node Scaffolding.
=> [s-ruby] Small updates to the Ruby Scaffolding.

yarn/plan.sh
https://github.com/yarnpkg/yarn/releases/tag/v0.24.5
=> [yarn] Update to 0.24.5.

ocaml/plan.sh
=> Update ocaml to 4.04.1

drush/plan.sh
Signed-off-by: Paul Adams <paul.adams@endocode.com>
=> New core/drush package for Habitat

drush/plan.sh
Signed-off-by: Paul Adams <paul.adams@endocode.com>
=> Fix: fix quoting

ponysay/plan.sh
=> Plan for ponysay

postgresql/hooks/run
Bug I found while working on chefconf demo.
=> Fix for pg failover

linux/plan.sh
This is an initial plan for building the Linux kernel as a Habitat package.
=> Initial Linux plan

wordpress-proxy/config/nginx.conf, wordpress-proxy/default.toml, wordpress-proxy/hooks/init, wordpress-proxy/hooks/run, wordpress-proxy/plan.sh
=> added the worpress-proxy

dotnet-core-lts/plan.ps1, dotnet-core-lts/plan.sh, dotnet-core-sdk-lts/plan.ps1, dotnet-core-sdk-lts/plan.sh
=> Created LTS release channel plans for dotnet core runtime and sdk

.gitignore, zsh/plan.sh, zsh/zprofile
This adds a zsh plan, all part of my secret plot for dope userland packages.
=> Adding zsh plan

fish/plan.sh
=> Add fish shell

consul/plan.sh
=> Bump consul version to 0.8.3

vault/plan.sh
=> Bump vault version to 0.7.2

gradle/plan.sh
=> Bump gradle version to 3.5.0

htop/plan.sh
=> make ncurses a runtime dep for htop

cppunit/plan.sh
=> Add new plan cppunit

bundler/plan.sh
Latest version for speed improvements among other things.
=> Update bundler to 1.15.1

terraform/plan.sh
I've tested this out with internal Terraform scripts with no issues.
=> Update terraform to 0.9.8

omniORB/plan.sh
=> Add new plan omniORB

libpcap/plan.sh, tcpdump/plan.sh
=> Update to tcpdump 4.9.0 and libpcap 1.8.1

tor/plan.sh
=> [tor] Update to 0.3.0.8

jdk8/plan.sh
=> Bump java version to 1.8.0_131

dbus/plan.sh, gperf/plan.sh, intltool/plan.sh, systemd/plan.sh
Includes:
* intltool
* gperf
* dbus
Special thanks to ncerny who did a lot of the leg work here.
=> New plan for Systemd

varnish/README.md, varnish/config/varnish.default.vcl, varnish/default.toml, varnish/hooks/run, varnish/plan.sh, varnish/tests/delmo.yml, varnish/tests/docker-compose.yml, varnish/tests/scripts/varnish-fail, varnish/tests/scripts/varnish-ready, varnish/tests/tests.toml
Signed-off-by: Bill Chapman <billchapman@starkandwayne.com>
=> Added basic standalone varnish plan

etcd/config/conf.yml, etcd/default.toml, etcd/docs/README.md, etcd/hooks/health_check, etcd/hooks/run, etcd/plan.sh
Signed-off-by: Djalal Harouni <djalal@endocode.com>
=> New core/etcd package for Habitat

jenkins/README.md, jenkins/default.toml, jenkins/hooks/health_check, jenkins/hooks/run, jenkins/plan.sh
Signed-off-by: Paul Adams <paul.adams@endocode.com>
=> New core/jenkins plan.

libvterm/plan.sh
=> add libvterm plan

libtermkey/plan.sh
=> add libtermkey plan

R/plan.sh
Signed-off-by: Paul Adams <paul@baggerspion.net>
=> Bug fix: somehow we all missed that gcc was a /runtime/ dep

ffmpeg/plan.sh
Adds a basic plan for ffmpeg, this will require additional plans to satisfy the optional dependancies.
=> Add plan ffmpeg

eudev/plan.sh
=> Initial commit for eudev plan

kmod/plan.sh
=> Add kmod plan

nuget/plan.ps1
=> add nuget commandline package

MAINTAINERS.md
Helping put the Habicats in their Habitats 
=> Add Scott Macfarlane as maintainer

gperf/plan.sh
=> remove doubled deps

scaffolding-go/README.md, scaffolding-go/lib/scaffolding.sh, scaffolding-go17/README.md, scaffolding-go17/lib/scaffolding.sh
Here a few improvements for the go scaffolding!
=> Improvements to scaffolding-go

MAINTAINERS.md
Thank you, thank you, thank you!
=> @afiune (Salim) as maintainer

powershell/plan.ps1
This builds powershell from source on windows. This PR is dependent on #669 in order for the native binaries to successfully compile.
This patches the build with a simple change that will prevent `ctrl+break` signals from the habitat supervisor causing powershell to enter a debug prompt and thus not allowing some services to gracefully stop. When https://github.com/PowerShell/PowerShell/pull/4283 is released we can remove the patch.
Further, this updates to the latest alpha even though Powershell Beta releases have recently been made available. We are holding off on the alpha until the beta adds support for Windows 7/2008R2 which will soon be an important Habitat scenario. The Powershell team is planning on adding that support broken in the Beta.
Signed-off-by: Matt Wrock …
=> build powershell from source and patch to fix supervisor stops

cmake/plan.ps1
=> add windows plan for cmake

yarn/plan.sh
=> updated yarn to latest version

powershell/plan.ps1
We found that the current source build did not bring in the core powershell modules. This PR adds that.
`Restore-PSModule` was mostly copied from https://github.com/PowerShell/PowerShell/blob/v6.0.0-alpha.18/build.psm1#L2904
=> add module restore to powershell source build

postgresql/plan.sh
=> update postgresql to 963 from 961

elfutils/plan.sh
Fixes #588 
Signed-off-by: Kristian Vlaardingerbroek <kvlaardingerbroek@schubergphilis.com>
=> Add missing pkg_bin_dirs entry to elfutils

dotnet-47-dev-pack/plan.ps1
=> add targetting pack for dotnet 4.7

powershell/plan.ps1
=> include downlevel api shims in published powershell binaries

powershell/plan.ps1
This builds the latest powershell beta which fixes powershell core beta on win7/2008R2 and also includes our PR.
We should not upload/merge this until we release the latest launcher code that adds the -NonInteractive arg to powershell.
=> bump powershell to latest beta and remove patch

MAINTAINERS.md
=> adds Nell to the maintainers list

telegraf/README.md, telegraf/config/telegraf.conf, telegraf/plan.sh
This grabs @kplimack's changes and supersedes PR #639.
=> Updated plan for telegraf

scaffolding-ruby/lib/scaffolding.sh
=> excludes results director when copying the code base into the package

go/plan.sh
=> Update go to 1.9

terraform/plan.sh
Signed-off-by: Scott Gallagher <sgallag@gmail.com>
=> Updated pkg_version to 0.10.2 && corresponding pkg_shasum

scaffolding-ruby/plan.sh
=> increments version number of scaffolding-ruby

nghttp2/plan.sh
=> Add nghttp2 1.24.0

scaffolding-ruby/plan.sh
=> increments ruby scaffolding version number

bundler/plan.sh
=> updates bundler to latest

scaffolding-ruby/lib/scaffolding.sh, scaffolding-ruby/plan.sh
=> catches bundler errors and cleans up after them

rust/plan.ps1
=> bump windows rust to 1.20.0

libsodium/plan.sh
=> Update libsodium to available version

rust/plan.ps1, rust/plan.sh
Waiting on habitat-sh/habitat#3062 to clear before merging and building.
=> Update to Rust 1.20.0.

node/plan.ps1, node/plan.sh
Signed-off-by: Christian Nunciato <cnunciato@chef.io>
=> Update node to latest LTS (6.11.2)

scaffolding-node/plan.sh
=> updates scaffolding-node version number for new release

caddy/plan.sh
=> Add caddy v0.10.9

rabbitmqadmin/plan.sh
=> Added RabbitMQ Admin

rabbitmq/config/.erlang.cookie, rabbitmq/config/rabbitmq.config, rabbitmq/default.toml, rabbitmq/docker-compose.yml, rabbitmq/hooks/init, rabbitmq/hooks/run, rabbitmq/plan.sh
=> Add clustering support for rabbitmq plan

MAINTAINERS.md
=> add Robb Kidd as a core-plans maintainer

CODEOWNERS, CONTRIBUTING.md
* Add CODEOWNERS file and assign myself to packages
* Add CODEOWNER concept to CONTIBUTING.md
=> Add CODEOWNERS concept and initial seed

artifactory-pro/hooks/run, jetty/hooks/run, kafka/hooks/run, mention-bot/hooks/run, openvpn/hooks/run, sensu/hooks/run, tomcat7/hooks/run, tomcat8/hooks/run, zookeeper/hooks/run
using the helper consistently allows us to demonstrate good practice.
=> Replace `hab pkg path` with pkgPathFor

CODEOWNERS
=> Add fnichol to CODEOWNERS & break out base packages at the end.

CODEOWNERS
=> resset -> reset

scaffolding-node/plan.sh
=> [scaffolding-node] adds explicit dependency on core/node

traefik/plan.sh
=> Fix build paths for traefik

scaffolding-gradle/CHANGELOG.md, scaffolding-gradle/README.md, scaffolding-gradle/doc/quickstart.md, scaffolding-gradle/doc/reference.md, scaffolding-gradle/lib/scaffolding.sh, scaffolding-gradle/plan.sh
Gradle Scaffolding is a Habitat package which helps you build your
Gradle-based **web applications**, **services**, and **processes**
(hereafter referred to as "apps") into a package which runs consistently
on a wide range of containers, virtual machines, or servers via the
Habitat Supervisor. The Supervisor will facilitate clustering, discovery
of database services, dynamically update configuration and credentials,
coordinate reliable rolling updates, and a lot more!
=> [scaffolding-gradle] Initial implementation of Gradle Scaffolding.

CODEOWNERS
* Add default owner for all files in org
* Add owner for scaffolding
=> Additions to CODEOWNERS

wrk/plan.sh
Bringing [wrk](https://github.com/wg/wrk) to life.
=> Adds wrk plan

MAINTAINERS.md
=> add Paul and Josh to maintainers

kibana/plan.sh
=> [kibana] Upgrade kibana to 5.6.1

jdk8/plan.sh, jffi/plan.sh
=> Add a jffi plan and update jdk8 libs to path correctly

R/plan.sh
Signed-off-by: Paul Adams <paul@baggerspion.net>
=> Update core/R to 3.4.2

mysql/config/init.sql, mysql/hooks/init, mysql/hooks/run
=> Remove pipefail to fix #835

elixir/plan.sh
Signed-off-by: Dmitry Fedorov <gmajere@gmail.com>
=> [elixir] Upgrade to 1.5.1

elasticsearch/config/elasticsearch.yml, elasticsearch/hooks/run, elasticsearch/plan.sh
Also standardise templates and hooks formatting.
=> [elasticsearch] Upgrade elasticsearch to 5.6.1

strace/plan.sh
- Upgrade to 4.19
- Include libunwind support
- Add do_check function and required test dependencies
- Update plan with required fields
=> [strace] Upgrade to 4.19

composer/plan.sh
=> Move composer custom do_check into the do_check function

rethinkdb/plan.sh
=> [rethinkdb] Corrects Source Download Location

git/plan.sh
Includes a fix for CVE-2017-1000117
=> [git] Upgrade to 2.14.2

scaffolding-node/lib/scaffolding.sh
=> [scaffolding-node] exclude results/ from files copied for packaging

curl/plan.sh
=> Bump curl version to 7.54.1

.bldr.toml, sumologic/config/log4j.xml, sumologic/config/user.properties, sumologic/config/wrapper-license.conf, sumologic/config/wrapper.conf, sumologic/default.toml, sumologic/hooks/run, sumologic/plan.sh
=> Sumologic collector

scaffolding-node/CHANGELOG.md, scaffolding-node/plan.sh
=> bump version of scaffolding-node to 0.6.5 and update changelog

.bldr.toml
=> Update bldr.toml with xorg packages

python/plan.sh
Signed-off-by: Dipesh Patel <dipthegeezer.opensource@gmail.com>
=> Update python version to 3.6.3

rust/plan.sh
=> Update Rust to 1.21.0

elasticsearch/config/elasticsearch.yml, elasticsearch/plan.sh
=> [elasticsearch] add optional binds, update config to find them

dpkg/plan.sh
=> [dpkg] 1.18.18 No Longer Available

apr-util/plan.sh, apr/plan.sh
=> [apr][apr-util] Bump apr and apr-util

lua/plan.sh
=> Bump lua version to 5.3.4

consul/plan.sh
=> Bump consul version to 0.9.0

vault/plan.sh
=> Bump vault version to 0.7.3

openldap/plan.sh
=> Bump openldap version to 2.4.45

.bldr.toml, mawk/plan.sh
=> Add mawk v1.3.4

ocaml/plan.sh
=> Update ocaml to 4.04.2

mongo-tools/plan.sh
This updates mongo-tools to the latest release.
=> Update mongo-tools to 3.4.2

mongodb/plan.sh
Update to Mongo 3.2.10 before jumping to 3.4.x
=> Mongodb 3.2.10

wal-e/plan.sh
https://github.com/wal-e/wal-e/issues/322
=> Lock wal-e to required version of Python

kubernetes/plan.sh
=> Fix checksum for Kubernetes plan

kibana/config/kibana.yml, kibana/default.toml, kibana/hooks/init
=> [kibana] update configs for kibana > 5.5, fix bindings 

zeromq/plan.sh
https://github.com/zeromq/libzmq/releases/tag/v4.2.2
=> Bump ZeroMQ to 4.2.2

libarchive/plan.sh
=> Bump libarchive to 3.3.2

direnv/plan.sh
=> add direnv plan

scaffolding-ruby/CHANGELOG.md, scaffolding-ruby/plan.sh
=> bump version and update changelog

.bldr.toml, fping/plan.sh
=> [New Plan] Add fping

.bldr.toml, cpputest/plan.sh
Lets add another way to test c++
=> [New Plan] Add cpputest

wget/plan.sh
Including the plan.sh fixes required to pass pre-commit checks.
=> [wget] bump: 1.19.1

musl/plan.sh
Had to add some plan.sh variables... ✔️
=> [musl] bump 1.1.17

ed/plan.sh
=> [ed] bump 1.14.2

scaffolding-go/lib/scaffolding.sh
I think we would benefit of linking the `/src` directory into the workspace so that they are always in sync.
Thoughts?
=> Link the repo inside the Go Workspace

.pre-commit-config.yaml
=> Disable this check for now since it is catching templatized sourced files

.pre-commit-config.yaml, bin/check-bad-patterns.sh, shield/config/shieldd.conf
tested at https://travis-ci.org/habitat-sh/core-plans/builds/293136657?utm_source=github_status&utm_medium=notification
=> Fix up check-bad-patterns

shadow/plan.sh
Note that this also resolves a segmentation fault that @reset and I discovered in `newuidmap` and `newgidmap`.
=> [shadow] Update to 4.5

jdk8/plan.sh, jre8/plan.sh
=> Updates both JDK8 and JRE8 to u151

protobuf-c/plan.sh
=> Updates core/protobuf-c to 1.3.0

README.md
Trivial organizational changes to README.md
=> Trivial README Updates

CODEOWNERS
=> Take some responsibility in life. I hope this is the right place.

innounp/plan.ps1
=> add plan for innounp

CONTRIBUTING.md
=> Separate Package, Separate PR and other contributing notes

rust/plan.ps1
=> bump rust for windows to 1.21

CODEOWNERS
=> Adds myself as code owner for JREs and JDKs

mongo-tools/plan.sh
Signed-off-by: David Wrede <dwrede@chef.io>
=> [mongo-tools] Updated to 3.5.13

grafana/config/grafana.ini, grafana/config/ldap.toml, grafana/default.toml, grafana/plan.sh
Signed-off-by: Stephen Leyva <sleyva1297@gmail.com>
=> [grafana] Added optional grafana and ssl support

_RFCs/0000-template.md, _RFCs/0001-rfc-for-rfcs.md
=> RFC cleanup: whitespace

.editorconfig
In the hopes of maintaining consistent style across contributors,
provide a configuration file for many code editors to use to determine
the rules they should use when editing a file.
See http://editorconfig.org for more details.
=> Add .editorconfig file to project

CONTRIBUTING.md
=> Whitespace

kibana/plan.sh
=> Kibana version up to 5.6.4

elasticsearch/plan.sh
=> Elasticsearch version up to 5.6.4

logstash/plan.sh
=> Logstash version up to 5.6.4

.bldr.toml, shared-mime-info/plan.sh
=> [shared-mime-info] Adds shared-mime-info package (gtk2)

apr-util/plan.sh
Also cleaned up `plan.sh` a bit
=> [apr-util] Bumps to 1.6.1

.bldr.toml, atk/plan.sh
=> [atk] Adds atk package (gtk2)

cairo/plan.sh
=> [cairo] Adds xlib support to cairo (gtk2)

.bldr.toml, gdk-pixbuf/plan.sh
Should be merged after #942 and #944
=> [gdk-pixbuf] Adds gdk-pixbuf (gtk2)

harfbuzz/plan.sh
Should be merged after #942 and #945
=> [harfbuzz] Fixes package config and bump bugfix (gtk2)

CODEOWNERS
To be merged after #949 :tada:
=> [CODEOWNERS] Adds myself for gtk2 related packages

pango/plan.sh
Should be merged after #947 and #945
=> [pango] Package cleanup and bump bugfix (gtk2)

.bldr.toml, gtk2/plan.sh
Should be merged after #942, #943, #944, #945, #946, #947 and #948
This is a prerequisite for #377
=> [gtk2] Adds gtk2

artifactory-pro/hooks/init, artifactory-pro/hooks/run, artifactory-pro/plan.sh
=> [artifactory-pro] Fixes service start & bump to 5.5.2

.bldr.toml, concourse/README.md, concourse/plan.sh
=> [concourse] adds concourse standalone binary package

scaffolding-node/CHANGELOG.md, scaffolding-node/plan.sh
=> Bumps version number and updates changelog

CODEOWNERS
=> [CODEOWNERS] Adds myself for protobuf-cpp go dep wrk pkgs

.bldr.toml, libxrandr/README.md, libxrandr/plan.sh
=> [libxrandr] Add libxrandr 1.5.1

.bldr.toml, at-spi2-atk/README.md, at-spi2-atk/plan.sh
=> [at-spi2-atk] Adds core/at-spi2-atk

docker-credential-helper/plan.ps1, docker/plan.ps1
Will be used for windows studio image publishing.
=> add docker binaries for windows

CODEOWNERS
Share ownership with @rsertelon 
Names listed in alphabetical order.
=> Share code ownership on Java plans

gradle/plan.sh
Signed-off-by: alexey <alexey.pankratev@gmail.com>
=> [gradle] to update gradle to ver 4.3.1

jdk8/plan.sh
Also fixes missing link to libjvm.so in some shared objects
=> [jdk8] Adds X dependencies to jdk8

cairo/README.md, cairo/plan.sh
Include folder was buggy, putting it to include made other packages compile fine.
=> [cairo] Improves build (gtk3)

CODEOWNERS
Signed-off-by: Irving Popovetsky <irving@chef.io>
=> Adding myself as a codeowner of the postgresql and redis plans

scaffolding-node/lib/scaffolding.sh, scaffolding-node/plan.sh
Fixes #1006
This code seems rather complex and could benefit from simplification. For now I'm fixing the issue and cleaning the readability so we can do a future pass through and clean it up better.
=> [scaffolding-node] use more robust compat_regex and fix code readability

scaffolding-node/CHANGELOG.md
=> [scaffolding-node] updates changelog for new scaffolding node release

CODEOWNERS
=> [CODEOWNERS] one ELK stack, plz

scaffolding-ruby/CHANGELOG.md, scaffolding-ruby/plan.sh
=> [scaffolding-ruby] updates ruby scaffolding version and changelog

yarn/plan.sh
This updates the yarn version to the latest.  This builds successfully in a studio.
Fixes #910
=> [yarn] updates yarn version

protobuf-cpp/plan.sh
Closes https://github.com/chef/a2/issues/264
=> Upgrade protobuf-cpp to 3.5.0

CODEOWNERS
=> [CODEOWNERS] Add @predominant to ELK

logstash/plan.sh
=> [Logstash] version up to 6.0.0

kibana/plan.sh
=> [Kibana] version up to 6.0.0

elasticsearch/plan.sh
=> [Elasticsearch] version up to 6.0.0

bundler/plan.sh
=> [bundler] updates to latest version of bundler

.bldr.toml, damageproto/README.md, damageproto/plan.sh
I coudn't figure out what to choose as license :/
=> [damageproto] Adds damageproto (gtk3)

libxdamage/README.md, libxdamage/plan.sh
Couldn't figure out license too.
=> [libxdamage] Adds libxdamage (gtk3)

dri2proto/README.md, dri2proto/plan.sh
=> [dri2proto] Adds dri2proto (gtk3)

glproto/README.md, glproto/plan.sh
=> [glproto] Adds glproto (gtk3)

libpciaccess/README.md, libpciaccess/plan.sh
Couldn't figure out license too :/
=> [libpciaccess] Adds libpciaccess (gtk3)

libxshmfence/README.md, libxshmfence/plan.sh
Couldn't figure out license :/
=> [libxshmfence] Adds libxshmfence (gtk3)

json-glib/README.md, json-glib/plan.sh
=> [json-glib] Adds json-glib (gtk3)

.bldr.toml
=> Add missing packages to .bldr.toml

.bldr.toml, rust-nightly/plan.sh
Note that the version of the nightly will at build time and until a
system is setup to trigger daily builds, the latest published version
will be the last build time of the package.
I built a simple sample application to test this package which uses the
nightly features of Rust in the Rocket project which is at:
https://github.com/fnichol/rocketry
=> [rust-nightly] Add plan for Rust nightly.

jenkins/default.toml, jenkins/hooks/health_check, jenkins/hooks/run, jenkins/plan.sh
=> [Jenkins] version up (2.73.3), more configuration options, and use /bin/sh

.pre-commit-config.yaml, bin/check-bldr-toml.sh
This should help us keep .bldr.toml up to date.
=> [pre-commit] Check that modified plans have .bldr.toml entries

.bldr.toml, inotify-tools/plan.sh
Adding the inotify-tools library. This library allows for notiifications
for file changes.
Signed-off-by: Lance Finfrock <lfinfrock@chef.io>
=> [inotify-tools] Adds inotify-tools 

llvm/README.md, llvm/plan.sh
=> [llvm] Updates LLVM to 3.9.1 (gtk3)

jruby1/plan.sh
Signed-off-by: Irving Popovetsky <irving@chef.io>
=> [jruby1] Fix interpreter for jruby1 and also update to the latest version

.bldr.toml, msgpack/plan.sh
=> msgpack plan

.bldr.toml, nmap/plan.sh
This adds a plan for the nmap utility. This is a pretty straightforward plan. Please check it out and let me know if anything else is needed. 
Thanks!!
=> [nmap] Adding nmap plan

.bldr.toml, meson/README.md, meson/plan.sh
=> [meson] Adds meson package (gtk3)

.bldr.toml, gamin/patches/fix-deprecated-const.patch, gamin/plan.sh
=> [gamin] Adds gamin

.bldr.toml, papi/README.md, papi/plan.sh
=> [papi] Adds PAPI (gtk3)

jdk7/plan.sh, jdk8/plan.sh, jdk9/plan.sh, jre7/plan.sh, jre8/plan.sh, jre9/plan.sh
Will save some variable declarations in dependent packages ;)
=> [jdk7-8-9/jre7-8-9] Adds new environment variables support

apr/plan.sh
=> [apr] Improves APR package

CODEOWNERS
I've been doing a bit with Jenkins lately, might as well take some responsibility for it.
=> [Jenkins] Add self to jenkins CODEOWNERS

.bldr.toml, fluentd/README.md, fluentd/config/fluent.conf, fluentd/default.toml, fluentd/hooks/run, fluentd/plan.sh
[Fluentd](https://github.com/fluent/fluentd) is a CNCF project for logs/events management  and getting popular each day. 
This plan packages core fluentd and allow anyone to configure fluentd easily by using it as dependency to new plan.
Signed-off-by: Rahul Sinha <rahul@rahulwa.com>
=> [fluentd] adding package for fluentd

.bldr.toml, rebar/plan.sh
=> add rebar plan

visual-build-tools-2017/plan.ps1
=> add msbuild tools for vs 2017

ripgrep/plan.sh
=> add ripgrep plan

.bldr.toml
=> added missing ripgrep entry to bldr.toml

unibilium/plan.sh
=> unibilium plan

.bldr.toml
=> added missing unibilium entry to bldr.toml

exercism/default.toml, exercism/plan.sh
=> add exercism cli plan

.bldr.toml
=> adds missing exercism bldr.toml entry

.bldr.toml, libssh2/README.md, libssh2/plan.sh
`make check` do not pass. I'm not sure whether it's bad build or if sshd version is too recent.
=> [libssh2] Adds libssh2

.bldr.toml, rkt/README.md, rkt/plan.sh
=> Carry and update of rkt package from PR #631

crate/README.md, crate/config/crate.yml, crate/config/logging.yml, crate/default.toml, crate/hooks/health_check, crate/hooks/init, crate/hooks/run, crate/plan.sh
Signed-off-by: Paul Adams <paul.adams@endocode.com>
=> New core/crate package for Habitat

libssh2/plan.sh
=> [libssh2] Add do_check function

nmap/plan.sh
Small typo.  This should resolve the most recent build failure.
=> [nmap] Fix misplaced line continuations

.bldr.toml, scowl/plan.sh
For when it's useful to have a wordlist around. (Somewhat similar to tzdata, I suppose.)
=> [scowl] add "Spell Checking Oriented Word Lists" (SCOWL)

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2017/11/22/Rust-1.22.html
=> [rust] Update to Rust 1.22.1.

elasticsearch/config/elasticsearch.yml, elasticsearch/hooks/run, elasticsearch/plan.sh
=> Fix breaking change in ES 6.0.0 upgrade, adding ES_PATH_CONF

jenkins/plan.sh
=> [Jenkins] version upgrade to 2.89.1

.bldr.toml, rlwrap/plan.sh
Signed-off-by: John Jelinek IV <john@johnjelinek.com>
=> Add rlwrap 0.43

.bldr.toml, sccache/plan.sh
=> Add sccache plan for faster rust builds

artifactory-pro/plan.sh
Super simple version bump. Tested locally, looks good. Let me know if there are questions/concerns.
=> [artifactory-pro] Updated to version 5.8.0

kibana/plan.sh
=> [kibana] version bump to 6.1.0

ruby/plan.sh, ruby22/plan.sh, ruby23/plan.sh, ruby24/plan.sh
"Plans are more than shell code. Don't let the extension fool you." 
=> Update ruby22, ruby23, ruby24 plans to include more metadata.

sccache/plan.sh
=> sccache version bump

consul/config/basic_config.json, consul/default.toml, consul/plan.sh
Updating consul plan to 1.0.2.  Modifications were made to reflect changes in consul application. 
Please let me know if you have any questions.
=> [Consul] Updating to 1.0.2

sccache/hooks/run, sccache/plan.sh
=> Make Sccache a service

.bldr.toml, ruby25/plan.sh
@smacfarlane This is an update per your suggestions. I messed up my other repo so  this is a new PR :) Let me know what you think.
Tested locally, looks good. 
-Chris 
=> [Ruby25] Added ruby25 and updated .bldr.toml

terraform/plan.sh
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
=> [terraform] Update terraform to 0.11.2

vault/plan.sh
Updating vault plan to 0.9.1. Modifications made to version and sha256 values.
Please let me know if you have any questions.
=> [vault] Updating vault to 0.9.1

consul/plan.sh
Simple version bump, tested locally. Everything looks good.
-Chris 
=> Updating consul to 1.0.3

direnv/plan.sh
=> [direnv] Update direnv

.bldr.toml, envconsul/README.md, envconsul/plan.sh
=> Add envconsul 0.7.3

terraform/plan.sh
Signed-off-by: Jeremiah Snapp <jeremiah@chef.io>
=> [terraform] Update to 0.11.3

CODEOWNERS
=> add mwrock as owner of powershell plans

MAINTAINERS.md
@smacfarlane : Per our conversation yesterday :) 
@eeyun I was talking with Scott yesterday at ChefHQ. I'd love to join onto the project! 
=> Adding Christopher Maher as maintainer

CODEOWNERS
=> Add myself as a code owner for Builder and Rust related things

CODEOWNERS
=> adds nell as code owner for some plans

.bldr.toml, sshpass/README.md, sshpass/plan.sh
Signed-off-by: John Jelinek <john@johnjelinek.com>
=> Add sshpass 1.06

.bldr.toml, ansible/README.md, ansible/plan.sh
Signed-off-by: John Jelinek <john@johnjelinek.com>
=> Add ansible 2.4.3.0-1

ci/base.yml, ci/repipe, ci/scripts/build-service, ci/scripts/release_notify, ci/scripts/validate-group
First commit of CI code for concourse testing of core-plans
=> [CI] Adds first iteration of CI code to core-plans repo

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2018/02/15/Rust-1.24.html
=> [rust] Update to Rust 1.24.0.

vault/plan.sh
Another simple version bump. Local testing looks good. 
=> [Vault] Updating Vault to 0.9.3

consul/plan.sh
Simple version bump, nothing fancy this time :)
=> [Consul] Updating to 1.0.6

CODEOWNERS, artifactory-pro/plan.sh
Super simple version bump as well as an update to CODEOWNERS to update plan name for artifactory-pro. 
=> [artifactory-pro] Version bump and codeowner update

docker/plan.sh
=> Bump docker-ce version to 17.09.1

cmake/plan.sh
=> [cmake] lets get cmake up-to-date

CODEOWNERS
=> adds nell to codeowners for some plans so she can approve PRs

unzip/plan.sh
=> [unzip] Improves package

linux-headers-musl/plan.sh
=> [linux-headers-musl] Improves package

musl/plan.sh
=> [musl] Updates musl to 1.1.18

.bldr.toml, leiningen/README.md, leiningen/plan.sh
Signed-off-by: John Jelinek IV <john@johnjelinek.com>
=> Add Leiningen 2.8.1

jo/plan.sh
Release notes: https://github.com/jpmens/jo/releases/tag/v1.1
=> [jo] bump 1.0 -> 1.1

ci/base.yml, ci/repipe, ci/settings.yml
=> Refactored CI config to remove credentials from  base.yml

ci/base.yml, ci/dmsetup.yml, ci/repipe
=> Updated to break all packages out into separate pipelines

.bldr.toml, googlemock/README.md, googlemock/plan.sh, googletest/README.md, googletest/plan.sh
because the world needs more ways to make better cpp code. 😄 
=> Add googletest and googlemock

vault/plan.sh
Basic maintenance bump, nothing fancy.
=> [Vault] Update vault to 0.9.5

rust/plan.sh
=> Update the rust package for linux to stable

.bldr.toml, img/README.md, img/plan.sh, runc/README.md, runc/plan.sh
=> Add Img and RunC plans

img/plan.sh
=> [img] version bump

jdk8/plan.sh
=> ups version of jdk8 and fixes the download url

MAINTAINERS.md
I'd like to be involved in core-plans a bit more and help maintain the whole core plans.
So I'm proposing this PR ;)
Romain
=> [MAINTAINERS] Adds rsertelon to maintainers

traefik/plan.sh
=> [traefik] Upgrade to 1.5.4

monit/plan.sh
=> [monit] Upgrades to 5.25.1

mosquitto/plan.sh
=> [mosquitto] Upgrades to 1.4.15

terraform/plan.sh
=> [terraform] Update terraform to 0.11.5

kubectl/plan.sh
=> [kubectl] Update kubectl version to 1.9.2.

.bldr.toml, CODEOWNERS, libtalloc/README.md, libtalloc/plan.sh
Hey all,
This is a pretty straightforward plan for the talloc library. This is a prereq for freeradius (another plan I'm working on) but can come in handy for others too. 
=> [libtalloc] Adding libtalloc

.bldr.toml, docker-compose/README.md, docker-compose/plan.sh
=> [docker-compose] Add docker-compose 1.20.1

curl/README.md
Add readme to core/curl binary package as part of #1252.
=> Add README to core/curl

README_TEMPLATE_FOR_PLANS.md
=> clarifies scaling and monitoring sections

.bldr.toml, mono4/README.md, mono4/plan.sh, mono5/README.md, mono5/plan.sh
=> Add Mono 4.8.1 and Mono 5.10.1 plans.

tree/README.md
This adds the README to core/tree as part of #1252. 
=> Add README to core/tree

googlemock/plan.sh
=> [googlemock] fix plan

nginx/config/nginx.conf, nginx/default.toml
Pretty self explanatory. Fulfills a common use case, and shouldn't impact existing usage. Maybe there's a more elegant way to do it?
=> [nginx] Add support for simple redirector mode

aws-cli/README.md
=> [aws-cli] Add README

socat/README.md
=> [socat] add README

ed/README.md
=> [ed] add README

CONTRIBUTING.md
=> links to template from contributing documentation

scaffolding-node/CHANGELOG.md, scaffolding-node/lib/scaffolding.sh, scaffolding-node/plan.sh
Signed-off-by: Michael Paulauski <mike10010100@gmail.com>
=> [scaffolding-node] adding support for tsoa module

nginx/config/nginx.conf, nginx/default.toml
Replaced a dropped curly and re-arranged placement so the rendered config file looks better. @nellshamrell
=> [nginx] Fix Redirector feature

.bldr.toml, prometheus-cpp/README.md, prometheus-cpp/plan.sh
=> [prometheus-cpp] add new plan

docker17/plan.sh
=> corrects download link for docker 17

jre9/plan.sh
=> [jre9] Fixes package and bumps to 9.0.4

rust/plan.sh
=> Bump Rust to 1.25.0

.bldr.toml, bind/README.md, bind/plan.sh
This adds bind, the name server.
I've not included any run hook because I think it would have no value, unless we set up a complete configuration scheme, which, IIRC is not the aim of core plans.
=> [bind] Adds bind package

mysql-client/plan.sh, mysql/README.md, mysql/config/client.cnf, mysql/config/init.sql, mysql/config/my.cnf, mysql/default.toml, mysql/hooks/health_check, mysql/hooks/post-run, mysql/hooks/reconfigure, mysql/plan.sh
this adds leader/follower capabilities to the MySQL plan, with lightly tested failover support in docker.
Replaces PR #1038
=> [mysql] Adding replication/leader topology and updating to the latest version

.bldr.toml, benchmark/README.md, benchmark/plan.sh
=> [benchmark] add new plan

CODEOWNERS, sqlserver-ha-ag/README.md, sqlserver-ha-ag/config/cluster.ps1, sqlserver-ha-ag/config/feature.ps1, sqlserver-ha-ag/config/firewall.ps1, sqlserver-ha-ag/config/group.ps1, sqlserver-ha-ag/default.toml, sqlserver-ha-ag/hooks/init, sqlserver-ha-ag/hooks/run, sqlserver-ha-ag/plan.ps1
This adds a plan for configuring Sql Server AlwaysOn Availability Groups.
=> adds a plan got sqlserver-ha

protobuf-rust/plan.sh
=> [protobuf-rust] Update rust protobuf version

protobuf-rust/plan.sh
=> [protobuf-rust] Removes useless dependencies

.bldr.toml, compositeproto/README.md, compositeproto/plan.sh
=> [compositeproto] Creates package

.bldr.toml, libtasn1/README.md, libtasn1/plan.sh
=> [libtasn1] Creates package

.bldr.toml, nettle/README.md, nettle/plan.sh
> To be merged after #1335 is merged/promoted
=> [nettle] Creates package

.bldr.toml, p11-kit/README.md, p11-kit/plan.sh
> To be merged after #1335 is merged/promoted
=> [p11-kit] Creates package

.bldr.toml, libxcomposite/README.md, libxcomposite/plan.sh
Need #1332 merged/promoted before.
=> [libxcomposite] Creates package

.bldr.toml, scrnsaverproto/README.md, scrnsaverproto/plan.sh
=> [scrnsaverproto] Creates package

.bldr.toml, libxscrnsaver/README.md, libxscrnsaver/plan.sh
> #1340 must be merged/promoted first
=> [libxscrnsaver] Creates package

.bldr.toml, gnutls/README.md, gnutls/plan.sh
> Note that #1337 #1336 #1335 must be merged/promoted before this can be built
=> [gnutls] Creates package

.bldr.toml, alsa-lib/README.md, alsa-lib/plan.sh
=> [alsa-lib] Creates package

prometheus-cpp/README.md
Plans are much better when you can give as much clarity to those wanting to use it.  :)
=> [prometheus-cpp] Update README with clearer usage

scaffolding-go/plan.sh
Signed-off-by: Sean OMeara <sean@sean.io>
=> [scaffolding-go] separating build and run deps

.travis.yml
Until this issue is fixed https://github.com/travis-ci/travis-ci/issues/9484
=> temporarily removes shellcheck from our Travis config

chef-dk/README.md, chef-dk/plan.ps1
=> add a plan for chef-dk

_RFCs/0005-rfc-java-semantic-versioning.md
=> Adds RFC to change Java8 package versions

_RFCs/0004-testing-pull-requests.md
=> adds rfc around testing pull requests

libxshmfence/plan.sh
=> [libxshmfence] Fixes build for base packages refresh

MAINTAINERS.md
Signed-off-by: Jon Bauman <5906042+baumanj@users.noreply.github.com>
=> Add @baumanj to core-plans maintainers

gox/plan.sh
=> fixes build for gox by getting hashicorp/go-version and fixing checksum

img/plan.sh
=> fixes build for img

libuv/plan.sh
The URL has changed apparently. This fixes the URL ;)
=> [libuv] Fixes package

gdb7/plan.sh
=> fixes pkg_name for gdb7

consul/plan.sh
=> Upgrade Consul to 1.0.7

zookeeper/plan.sh
=> [zookeeper] Updates to 3.4.11

storm/plan.sh
=> [storm] Update to 1.1.2

libpcap/plan.sh
This is a follow up PR for #1376
=> [libpcap] Adds pconfig_dirs

sumologic/plan.sh
=> [sumologic] Updates to 19.209-37

fish/plan.sh
=> [fish] Fixes pkg_source URL

jdk8/plan.sh
=> [jdk8] Updates to 8.172.0

jre8/plan.sh
=> [jre8] Update to 8.172.0

kafka/plan.sh
=> [kafka] Updates to 0.10.2.1

terraform/plan.sh
=> [terraform] Update Terraform to 0.11.7

leiningen/plan.sh
=> [leiningen] Makes use of latest jdk8 package

artifactory-pro/README.md, artifactory-pro/plan.sh
Just another version bump with a first pass README addition.
=> [Artifactory Pro] Version bump and readme

_RFCs/0006-rfc-gh-approval-reset.md
=> Add RFC around pull request approvals

CONTRIBUTING.md
=> [CONTRIBUTING] Adds requirement on dependencies

postgresql/plan.sh
=> [postgresql] Update to 9.6.8

flatbuffers/plan.sh
Fixes #1429 
Also, this builds fine in current base.
=> [flatbuffers] Update to 1.9.0

docker-compose/plan.sh
Also, version is now fixed.
Fixes #1431 and works well in current base
=> [docker-compose] Update to 1.21.0

prometheus-cpp/plan.sh
Fixes #1428 and builds fine on current base
=> [prometheus-cpp] Update to 0.4.1

lsyncd/plan.sh
This is work for #1423 
Also removes pin on lua version
=> [lsyncd] Update to 2.2.1

nss/plan.sh
This fixes #1440 (rpm does build with this fix)
Note that this works perfectly fine in current base too. We can merge in master then ;)
=> [nss] Upgrades to 3.35 (m)

bash-completion/plan.sh
This is a reopening of #1087 which I deleted unintentionally ...
=> [bash-completion] Update to 2.7

cockroach/plan.sh
This is part of the work in #1423 
=> [cockroach] Remove pin on go version

scaffolding-go/lib/scaffolding.sh
=> [scaffolding-go] Changes default GOPATH location

R/README.md, R/plan.sh
Release announcement: https://stat.ethz.ch/pipermail/r-announce/2018/000628.html
=> [R]: bump to 3.5.0 and README

consul/README.md, consul/default.toml, consul/hooks/reload
=> [consul] Readme, Reload hook, and default DC change

vault/README.md, vault/plan.sh
Simple version bump to 0.10.0 with a first-run README too.
=> [Vault] Updating Vault and adding README

grafana/README.md, grafana/config/grafana.ini, grafana/config/ldap.toml, grafana/hooks/run, grafana/plan.sh
=> [grafana] Bump grafana version to 4.6.3

llvm/plan.sh
It was just too long to wait ;-) Didn't noted the speed improvements, as it depends on your harware, but on a 12 vCPUs machine, it was a lot faster ;)
=> [llvm] Speeds up build using -j

gnutls/plan.sh, nettle/plan.sh
Reverts habitat-sh/core-plans#1389
=> Revert "[nettle][gnutls] Fix packages for base refresh"

ffmpeg/plan.sh
=> pin core/gmp until the base plans refresh

sumologic/plan.sh
=> fixes sumologic build

clang-tools-extra/plan.sh, clang/plan.sh
These builds should be parallel to improve build time
=> [clang] speed up build

ffmpeg/plan.sh
=> [ffmpeg] Unpin core/gmp

.bldr.toml, boost159/README.md, boost159/plan.sh
Fixes #1421 and can be merged in current base (this will/should trigger a rebuild of mysql packages).
=> [boost159] Adds package

mono5/plan.sh
=> [mono5] Update to 5.10.1.47

cockroach/plan.sh
* update to latest 2.x version
* ensure we are only building the FOSS components
=> Update CockroachDB plan

.bldr.toml, curator/plan.sh, curator4/README.md, curator4/plan.sh
Signed-off-by: Josh Hudson <jhudson@chef.io>
=> Update version of curator in plan to 5.5.1

.bldr.toml, postgresql-client/README.md, postgresql-client/plan.sh, postgresql93-client/plan.sh, postgresql94-client/plan.sh, postgresql95-client/plan.sh
#1491 requested a lightweight, client-only postgresql package.  Heres a thing, for all major versions we're tracking!
=> Add postgresql[*]-client plans

.bldr.toml, bazel/README.md, bazel/do_not_clear_env.patch, bazel/plan.sh
=> Add plan for Bazel

.bldr.toml, borningssl/README.md, borningssl/plan.sh
=> Add plan for boringssl

.bldr.toml, luajit/README.md, luajit/plan.sh
=> Add LuaJIT plan

.bldr.toml, yaml-cpp/README.md, yaml-cpp/plan.sh
=> add yaml-cpp plan

consul/plan.sh
Another simple bump, just taking it to the latest version :)
Tested locally with native Hab and Docker. 
=> [consul] Upgrade to 1.1.0

tor/plan.sh
Signed-off-by: John Barker <jebarker@gmail.com>
=> Another bump of the Tor version, new stable 0.3.3.6

rethinkdb/README.md, rethinkdb/plan.sh
=> [RethinkDB] Version up to 2.3.6

concourse-fly/plan.sh, concourse/plan.sh
Removed redundant cd from fly plan
=> [concourse] Updated concourse and fly for 3.13.0

packer/plan.sh
Signed-off-by: John Jelinek <john@johnjelinek.com>
=> Uprev packer to 1.2.4

CODEOWNERS
This is a very simple PR. Just adding myself as the terraform owner. :) 
=> [Codeowners] Adopting Terraform

CODEOWNERS
A simple PR, adding myself as an additional CODEOWNER of Terraform
=> Adding myself to Terraform CODEOWNERS

nuget/plan.ps1
Updating nuget to the newest recommended version at https://www.nuget.org/downloads
Updating nuget so that it supports newer csproj formatting for restoring dependencies.
As referenced here:
https://github.com/NuGet/Home/issues/4809#issuecomment-327672213
Added empty invoke-unpack so plan would build
=> [nuget] Updated nuget for 4.6.2

lgpo/README.md, lgpo/plan.ps1
=> Add package for Microsoft LGPO

.bldr.toml, scaffolding-chef/README.md, scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
This is Adam's scaffolding with shellcheck appeased :) https://github.com/habitat-sh/core-plans/pull/1544
=> Scaffolding chef

scaffolding-chef/README.md, scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
This adds a Chef Scaffolding for taking Policyfiles and creating habitat
services.
Signed-off-by: Adam Jacob <adam@chef.io>
=> Add a Chef Scaffolding

scaffolding-chef/lib/scaffolding.sh
This PR contains some trivial fixes to scaffolding-chef for issues which were preventing plans using it from building properly.
Signed-off-by: Jon Cowie <jonlives@gmail.com>
=> Fixes to scaffolding-chef

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2018/06/05/Rust-1.26.2.html
=> [rust] Update to Rust 1.26.2.

hugo/plan.sh
=> [Hugo] Upgrade Hugo to 0.42

.bldr.toml, mksh/.gitignore, mksh/README.md, mksh/plan.sh
=> [mksh] Add mksh (MirBSD Korn Shell)

.bldr.toml, dgraph/README.md, dgraph/plan.sh
=> [Dgraph] New Package - Adds dgraph 

direnv/plan.sh
=> [direnv] update to 2.16.0

MAINTAINERS.md
=> Added @predominant to maintainers.

artifactory-pro/README.md
=> [artifactory-pro] Updates to readme

7zip/README.md
=> [7zip] Updates to readme

.bldr.toml, CODEOWNERS, optipng/README.md, optipng/plan.sh
=> Added new plan for OptiPNG

.bldr.toml, CODEOWNERS, libimagequant/README.md, libimagequant/plan.sh
=> Added new plan for libimagequant

cerebro/README.md
=> [cerebro] Updates to readme

ccache/README.md
=> [ccache] Updates to readme

ant/README.md
=> [ant] Updates to readme

img/plan.sh
Remove scaffolding since it's broken
embed runc statically
Closes: #1571
=> Update img plan

percona-xtrabackup/plan.sh
=> [percona-xtrabackup] Add m4 back to build dependencies

.bldr.toml, CODEOWNERS, pngquant/README.md, pngquant/plan.sh
Has a dependency on #1601 being merged first, and promoted to stable.
=> Added new plan for pngquant

.bldr.toml, CODEOWNERS, nano/README.md, nano/default.toml, nano/plan.sh
=> [nano] Added nano editor

rabbitmq/plan.sh
=> [rabbitmq] Version bump to 3.7.6, cleanup plan.sh

filebeat/hooks/init, filebeat/hooks/run
=> [Filebeat] Add run/init hooks for Filebeat

ansible/README.md
=> [ansible] Updates to readme

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2018/06/21/Rust-1.27.html
=> [rust] Update to Rust 1.27.0

tar/plan.sh, tar/skip-test.patch
This came up in the base plans refresh work but I forgot to add this to the branch.
=> [tar] Skip a test that inconsistently fails.

bzip2-musl/README.md, bzip2/README.md
=> [bzip / bzip-musl] Predominant/readme bzip

acl/README.md
=> [acl] Updates to readme

jre8/plan.ps1
Adds a plan for installing jre8 for windows.
Signed-off-by: skylerto <skylerclayne@gmail.com>
=> jre8 for windows

sqlserver2005/README.md, sqlserver2005/config/config.ini, sqlserver2005/config/dotnet2.ps1, sqlserver2005/config/firewall.ps1, sqlserver2005/config/sql_login.sql, sqlserver2005/config/windows_login.sql, sqlserver2005/default.toml, sqlserver2005/hooks/init, sqlserver2005/hooks/post-run, sqlserver2005/hooks/post-stop, sqlserver2005/hooks/run, sqlserver2005/plan.ps1
=> [sqlserver2005] add a sql server 2005 plan

tmux/plan.sh
=> [tmux] upgrade to 2.7

filebeat/README.md, filebeat/plan.sh
In Studio
```
cd filebeat
hab pkg install core/busybox-static --binlink
ps | grep filebeat
```
Confirm process is running.
=> [filebeat] update to 6.3.1

sql-dmo/README.md, sql-dmo/plan.ps1
=> [sql-dmo] add sql-dmo COM binaries from sql server 2005 backward compat package

.bldr.toml, ghc/README.md, ghc/plan.sh, ghc710-bootstrap/README.md, ghc710-bootstrap/plan.sh, ghc710/README.md, ghc710/plan.sh, ghc80/README.md, ghc80/plan.sh, ghc82-bootstrap/README.md, ghc82-bootstrap/plan.sh, ghc82/README.md, ghc82/plan.sh, ghc84/README.md, ghc84/plan.sh, ncurses5-compat-libs/plan.sh, ncurses5/README.md, ncurses5/plan.sh
Please see #615
This is dependent on #614 
=> Added GHC plan for core

MAINTAINERS.md
=> Added @wduncanfraser to maintainers

boost/plan.sh
=> [boost] Version up to 1_66_0

postgresql-client/plan.ps1, postgresql94-client/plan.ps1, postgresql95-client/plan.ps1, postgresql96-client/plan.ps1
- Added Windows postgresql-client package
Note: This PR does not add a windows package for postgresql93-client as that requires VS C++ 2010 which we do not have in hab yet.
This was split off from #1567
=> [postgresql] Added windows postgresql clients

sensu-agent/config/agent.yml
Signed-off-by: gscho <greg.c.schofield@gmail.com>
=> [sensu] Fix typo in api port config

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2018/07/10/Rust-1.27.1.html
=> [rust] Update to Rust 1.27.1.

node/plan.sh
```
build; source results/last_build.env; hab pkg install results/${pkg_artifact}; hab pkg binlink ${pkg_ident};
node --version
```
```
node --version
v10.7.0
```
```
node
> var x = 'Foo';
> x
> .exit
```
```
> var x = 'Foo';
undefined
> x
'Foo'
> .exit
```
=> [node] Update to version 10.7.0

gnatsd/plan.sh, nats-streaming-server/plan.sh
=> Bump versions for gnatsd and nats-streaming-server

patchelf/plan.sh
=> [patchelf] Update download url

.bldr.toml, redis3/README.md, redis3/config/redis.config, redis3/default.toml, redis3/plan.sh, redis4/README.md, redis4/config/redis.config, redis4/default.toml, redis4/plan.sh
**NOTE:** Ensure you build from the root of core-plans, not inside the redis/redis3/redis4 directories. This will make testing easier.
```
unalias grep egrep fgrep
```
Testing will yield a couple of summary outputs, stating `Pass` or `FAIL` depending on the test result.
```
pushd redis3
build; source results/last_build.env; hab pkg install --binlink --force results/${pkg_artifact}
echo '
requirepass="password"
' | hab config apply redis3.default $(date +%s)
NETSTAT_RESULT=$(netstat -peanut | grep redis-server)
if [ $(echo "${NETSTAT_RESULT}" | wc -l) -eq 2 ]; then printf "Pass"; else printf "FAIL"; fi; echo " - Redis is listening"
for i in {0..24}; do redis-cli -a …
```
=> [redis] Added Redis4, updated redis to be redis4 (stable) and added redis3

kubectl/plan.sh
=> [kubectl] Update Kubectl plan

wordpress-proxy/plan.sh
=> [wordpress-proxy] Fix build failures in wordpress-proxy

go/plan.sh
=> [go] update Go plan

protobuf-rust/plan.sh
=> [protobuf-rust] Update protobuf-rust to 1.7.4

protobuf-cpp/plan.sh
=> [protobuf-cpp] Update protobuf-cpp to 3.6.1

protobuf/plan.sh
=> [protobuf] Update protobuf to 3.6.1

git/README.md
=> [git] Add usage information

git/plan.ps1, git/plan.sh
```
build
hab pkg exec core/git git --version
```
```
git version 2.18.0.windows.1
git version 2.18.0
```
=> [git] Update git to 2.18.0

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2018/08/02/Rust-1.28.html
=> [rust] Update to Rust 1.28.0.

node10/plan.ps1
=> [node] Update Node for Windows to 10.8.0

kubernetes/README.md
=> [kubernetes] clarifies building kubernetes plan requirements

php/plan.sh
Fails some tests, see #1707 for reference.
=> PHP update to 7.2.8

shield-proxy/plan.sh
=> [shield-proxy] Fix build failures in shield-proxy

minio/plan.sh
=> updates minio to the latest version

node/plan.sh, node10/plan.sh, node6/plan.sh, node8/plan.sh
=> [node] updates, all *nix plans

minio/plan.sh
=> [minio] Update minio to 2018-08-18T03-49-57Z

dsc-core/DSCCore.psm1
`Start-DscCore` currently hangs waiting for the LCM to be `Idle` if the LCM is in a `PendingReboot` or `PenfingConfiguration` state. If the LCM is in a `PendingReboot` state, we can go ahead and apply configurations. However, they may not end in the desired state if the configuration to be applied requires the reboot. It will be up to plan authors to verify this.
The LCM may be in a `PendingConfiguration` state if a configuration previously failed. That is fine but in order to apply a configuration in this state, we need to cancel the pending configuration so we are adding back the `force` argument to `SendConfigurationApply` which would cancel any pending configurations. Because we are in a lock, we will not be concerned about cancelling a legitimate apply in progress. However, just for …
=> [dsc-core] fix to handle Pending states

go/plan.sh
=> [Version Bump] Upgrade Go to 1.11

nghttp2/plan.sh
=> [nghttp2] Update nghttp2 to 1.33.0

gnatsd/README.md, gnatsd/plan.sh, gnatsd/test.bats, gnatsd/test.sh
* Upgrade to 1.3.0
* Add README
* Add tests
=> [gnatsd] Upgrade to 1.3.0, add README, add tests

mage/plan.sh
=> fixes mage build

CODEOWNERS, MAINTAINERS.md
=> Add bdangit to some plans and as a maintainer

consul/plan.sh
```
cd consul
./test.sh
```
```
---------------------------------------
Test Output
---------------------------------------
Pass ... Listening on tcp/8300
Pass ... Listening on tcp/8301
Pass ... Listening on tcp/8302
Pass ... Listening on tcp/8500
Pass ... Listening on tcp/8600
Pass ... Listening on udp/8301
Pass ... Listening on udp/8302
Pass ... Listening on udp/8600
```
=> [consul] Update consul to 1.2.3

dotnet-core/plan.sh, dotnet-core/tests/test.bats, dotnet-core/tests/test.sh
=> [dotnet-core] Upgrade dotnet-core to 2.1.4, add tests

node/plan.sh, node10/plan.sh
```
build node
node --version
```
```
v10.11.0
```
=> [node] Update nodejs to 10.11.0

.bldr.toml, cuda/README.md, cuda/plan.sh
Time to get your cuda plans on!
=> [cuda] Add new plan

kafka/config/server.properties
=> [kafka] Fix typo in configuration

minio/plan.sh
Update minio package to include new features and bug fixes
=> [minio] update minio version to 2018-10-05T01-03-03Z

vim/plan.sh
=> [vim] Update vim to 8.1.0450

nghttp2/plan.sh
=> [nghttp2] Update nghttp2 library to 1.34.0

vault/plan.sh
```
```
```
✓ Help command
```
=> [vault] Update vault to 0.11.3

libuv/plan.sh
=> [libuv] Update libuv to 1.23.2

libtalloc/plan.sh
Hey all,
Super simple update. This is just a version bump. Build looks good.
=> [libtalloc] Updating to 2.1.14

CODEOWNERS
=> Add myself to CODEOWNERS for Base Plans

haproxy/plan.sh, haproxy16/plan.sh, haproxy17/plan.sh, haproxy18/plan.sh
Hotfix because bldr had issues with source lines.
=> [haproxy] Fix for builder building plans

consul/plan.sh
=> [consul] Update consul to 1.3.0

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2018/10/12/Rust-1.29.2.html
=> [rust] Update to Rust 1.29.2.

go/README.md, go/plan.sh, go/tests/test.bats, go/tests/test.sh
This is a simple update, just a version bump with some added tests. 
To test this build, enter the Hab Studio and run the following command:
```
```
=> [Go] Updated Go to 1.11.1 and added tests

terraform/plan.sh
```
./terraform/tests/test.sh
```
```
```
=> [terraform] Update to 0.11.10

php/plan.sh
LD_LIBRARY_PATH has to be set to build libzip
Signed-off-by: David Hohengaßner <david@hohengassner.com>
=> [php] adding intl and zip support for php 7 binary

libimagequant/plan.sh
=> [libimagequant] Update libimagequant to 2.12.2

pngquant/plan.sh
=> [pngquant] Update pngquant to 2.12.2

packer/plan.sh
```
./packer/tests/test.sh
```
```
```
=> [packer] Update packer to 1.3.2

jffi/plan.sh
=> [jffi] Update jffi to 1.2.18

jenkins/plan.sh, jenkins/tests/test.bats, jenkins/tests/test.sh
```
./jenkins/tests/test.sh
```
```
✓ Help command
```
=> [jenkins] Upgrade Jenkins to 2.138.2, add tests

hugo/plan.sh
=> [hugo] Update hugo to 0.50

powershell/plan.ps1
=> [powershell] bump powershell to 6.1.0

artifactory/plan.sh
Signed-off-by: Scott Ford <sford@chef.io>
=> [artifactory] updating artifactory to 6.5.2

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html
=> [rust] Bump rust to 1.30.0

dgraph/README.md, dgraph/plan.sh, dgraph/tests/test.bats, dgraph/tests/test.sh
```
./dgraph/tests/test.sh
```
```
✓ Help command is functional
```
=> [dgraph] Update dgraph to 1.0.10, update readme

libuv/plan.sh
=> [libuv] Update libuv to 1.24.0

jruby/plan.sh
=> [jruby] Update jruby to 9.2.4.0, standardize some variable usage

consul/plan.sh
=> [consul] Update consul to 1.3.1

.bldr.toml, chrony/README.md, chrony/plan.sh
=> [chrony] Added core/chrony

MAINTAINERS.md
It is with a heavy heart that I'm removing myself as a maintainer.
Unfortunately, I no longer have time to contribute to the project after leaving Chef.
=> A sad goodbye

direnv/plan.sh
=> [direnv] Update direnv to 2.18.2

node/plan.sh, node11/plan.sh
=> [node/node11] Update node to 11.2.0

protobuf/plan.ps1
Signed-off-by: Scott Hain <shain@chef.io>
=> [protobuf] Add Protobuf for windows

.bldr.toml, goaccess/README.md, goaccess/plan.sh, goaccess/tests/test.bats, goaccess/tests/test.sh
> GoAccess is a real-time web log analyzer and interactive viewer that runs in a terminal in *nix systems or through your browser.
https://goaccess.io
=> [goaccess] add plan

php/plan.sh
=> [php] Update PHP to 7.3.0

.bldr.toml, nload/README.md, nload/plan.sh, nload/tests/test.bats, nload/tests/test.sh
Adding a core plan for nload, the network monitoring cli tool.
=> Add plan for nload

flatbuffers/plan.sh
Minor version update.  Package only includes libs and headers so there are no validation steps.
=> [flatbuffers] Update version

go/plan.sh
https://groups.google.com/forum/#!msg/golang-announce/Kw31K8G7Fi0/z2olKn-QCAAJ
Signed-off-by: Daniel DeLeo <dan@chef.io>
=> Upgrade go to 1.11.3 to address CVEs

libarchive/plan.sh
Signed-off-by: Scott Hain <shain@chef.io>
=> Force PIC rather than PIE for libarchive build

vim/plan.sh
Bugfixes and misc improvements
=> [vim] Update vim from 8.1.0450 -> 8.1.0577

gnutls/plan.sh
NOTE: Requires #2038 to be merged and promoted first.
=> [gnutls] Update gnutls to 3.6.5

tzdata/plan.sh
=> [tzdata] Update tzdata 2018e -> 2018g

vault/config/settings.hcl, vault/default.toml
Signed-off-by: Jeff Moody <fifthecho@gmail.com>
=> [vault] Adding Vault UI toggle

composer/plan.sh
=> [composer] Updated composer to 1.8.0

dgraph/plan.sh
```
✓ Help command is functional
```
=> [dgraph] Updated dgraph to 1.0.11

.bldr.toml, restic/README.md, restic/plan.sh, restic/tests/test.bats, restic/tests/test.sh
> restic is a backup program that is fast, efficient and secure
https://restic.net/
=> [restic] add plan

artifactory/plan.sh
Signed-off-by: Scott Ford <sford@chef.io>
=> [Artifactory] Updates Artifactory open source to version 6.6.5

traefik/plan.sh
Testing beyond basic binary runs is difficult due to networking requirements:
```
build traefik
traefik -h
```
=> [traefik] Update traefik to 1.7.7

bundler/plan.sh
Signed-off-by: Jon Morrow <jmorrow@chef.io>
=> Upgrade bundler to 1.17.3.

alsa-lib/plan.sh
=> [alsa-lib] Updated alsa-lib to 1.1.7

mssql/plan.sh
No real changes to the resulting build. Just removes warnings due to attempted patches to non-ELF files with patchelf.
Refs #2040
=> [mssql] Fix find/patch exec that was attempting to patch non-ELF files

ocaml/plan.sh
=> [ocaml] Updated ocaml to 4.07.0

camlp4/plan.sh
This update won't compile until the ocaml update is merged.
=> [camlp4] Updated camlp4 to 4.07

clingo/plan.sh
=> [clingo] Updated clingo to 5.3.0

ansible/plan.sh
=> [ansible] Updated ansible to 2.7.5

dpkg/plan.sh, dpkg/tests/test.bats, dpkg/tests/test.sh
=> [dpkg] Updated dpkg to 1.19.2

gperftools/plan.sh
Built with `export DO_CHECK=true`
=> [gperftools] Updated gperftools to 2.7

docker-compose/plan.sh, docker-compose/tests/test.bats, docker-compose/tests/test.sh
=> [docker-compose] Updated docker-compose to 1.23.2

eudev/plan.sh
=> [eudev] Updated eudev to 3.2.7

cabal-install/plan.sh
=> [cabal-install] Updated cabal-install to 2.4.1.0

apr/plan.sh
=> [apr] Updated apr to 1.6.5

cairo/plan.sh
=> [cairo] Updated cairo to 1.16.0

freetds/plan.sh
=> [freetds] Updated freetds to 1.00.109

gnuplot/plan.sh, gnuplot/tests/test.bats, gnuplot/tests/test.sh
Built with `export DO_CHECK=true`
`test.sh`:
```
```
=> [gnuplot] Updated gnuplot to 5.2.6

.bldr.toml, ghc/plan.sh, ghc/tests/test.bats, ghc/tests/test.sh, ghc84/plan.sh, ghc84/tests/test.bats, ghc84/tests/test.sh, ghc86/README.md, ghc86/plan.sh, ghc86/tests/test.bats, ghc86/tests/test.sh
For both plans,
`test.sh`:
```
```
=> [ghc] Updated ghc to 8.6.3 and ghc84 to 8.4.4

alex/plan.sh
- Added tests for alex
- Converted alex to specify v1- cabal commands
=> [alex] Add tests and plan cleanup
