habitat-sh/core-plans

.pre-commit-config.yaml, CONTRIBUTING.md
As the project gains more contributors, documentation on how to best
write plans and commits is helpful.
=> Add CONTRIBUTING.md and pre-commit hook config

scons/plan.sh
A Python-based software construction tool.
The installation method supports using a `--prefix`, making this package
installable outside the python2 site-packages directory.
Combined with `fix_interpreter`, it runs with the supplied Python2
interpreter correctly.
=> scons 2.5.0 (new plan)

bison/plan.sh, bison2/plan.sh
The current `bison` plan is 3.x and other software packages like PHP5
restrict their supported bison version to below 3.x.
Using this package:
pkg_build_deps=(... core/bison2)
=> bison2 2.7.1 (new plan)

php5/plan.sh
While there is no current `php` plan, I expect that name to be held by
the current PHP7 release, once a working plans can be produced.
=> php5 5.6.23 (new plan)

build_dependent_order.rb
This change adds a new Ruby program called `build_dependent_order.rb`
which can be used to determine a build ordering of all packages
dependent on a given package identifier.
For example, if one needed to determine which packages need to be
rebuilt if a new release of the `core/openssl` package is published,
then the following would yeild a list:
find . -name plan.sh | ./build_dependent_order.rb core/openssl
To get a complete list for Habitat core packages, a similar invocation
would have to be made from a parent directory containing git clones of
both `habitat` and `core-plans` repos:
find . -name plan.sh \
| ./core-plans/build_dependent_order.rb core/openssl
=> Add `build_dependent_order.rb` to compute rebuild ordering.

aws-cli/plan.sh
The path to `core/groff` should not be present in `$pkg_bin_dirs` but rather the package should be invoked with `hab pkg exec core/aws-cli` in order to get the `groff` command properly set on `$PATH`.
=> Fix aws-cli `$pkg_bin_dirs`.

ruby/plan.sh
* Update to latest rubygems when building
* Add a `do_check`
* Add a `pkg_description`
* Make license use SPDX format
* ShellCheck-suggested fixes
=> Updates to ruby plan

MAINTAINERS.md, README.md
Includes DCO stuff, stuff about ShellCheck, and a license.
=> Update README and add maintainers list

wget/plan.sh
References:
* https://blogs.securiteam.com/index.php/archives/2701
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-4971
=> Update to Wget 1.18 to resolve CVE-2016-4971.

imagemagick/plan.sh
This change:
- Sets the --prefix option to configure so that the final artifact has
the content we expect
- Sets PKG_CONFIG_PATH and depends on core/pkg-config to ensure we can
enable features that require libraries to be configured via pkg-config
- Depends on libpng, xz and gcc-libs to enable a few more useful features
in the built version of ImageMagick
- Sets pkg_lib_dirs and pkg_include_dirs so other plans can depend on
imagemagick.
=> [ImageMagick] Set prefix, enable a few features

.pre-commit-config.yaml, .travis.yml, check-default-variables.sh, travis.sh
pre-commit was introduced in #18 and this addition of a hook that greps
the changed files scope for required metadata should help prevent cycles
of review.
=> Add pre-commit hook to test for variables in plan.sh

libjpeg-turbo/plan.sh
A faster implementation of the libjpeg library.
Depends on #24
=> libjpeg-turbo 1.5.0 (new plan)

travis.sh
do not merge - this doesn't do anything other that help emit some hashes for debugging.
=> wip determine pre-commit range from parents

redis/plan.sh
Version update, includes baseline metadata, tab->space.
=> redis 3.2.1 (updated)

libpng/plan.sh
- Export the `libpng-config` binary for other packages to use to
discover via `pkg-config`
- Add metadata
- ShellCheck style fix
=> libpng (updated)

travis.sh
When homu runs its test on the aut branch, use the values given in the
commit range to make sure it passes.
=> Fix Travis on auto branch

erlang/plan.sh
- Without m4 hipe wasn't being enabled during the ./configure despite
--enable-hipe being passed.
- Erlang 18+ uses the Apache 2 license
- The configure script was complaining a lot about /bin/rm being missing
- We were passing a few configure flags twice
- As far as I can tell, the `--disable-debug` flag doesn't exist.
=> [erlang] Enable hipe and other cleanup

libscrypt/plan.sh, libseccomp/plan.sh, tor/config/torrc, tor/default.toml, tor/plan.sh
This adds a plan for Tor with minimal configuration for operating as a
tor-client. Additionally, it adds two tor dependencies: libseccomp and
libscrypt.
=> Add Tor plan

bin/copy-depot-upload-message.sh, bin/depot-upload-message.sh
I wanted to use this in a studio but I didn't have `pbcopy` in there so
I made it do less.
=> Don't copy in upload message script

serf/pass-env-to-scons.patch, serf/plan.sh
Serf is an C library for HTTP on top of APR.
=> serf (new plan)

subversion/plan.sh
After many yaks shaven, I finally have `svn` working.
Depends on https://github.com/habitat-sh/core-plans/pull/73 and https://github.com/habitat-sh/core-plans/pull/71 for testing.
=> subversion (new plan)

coreutils/plan.sh
coreutils 8.25 was released in January. Release notes are on the GNU
forum: http://savannah.gnu.org/forum/forum.php?forum_id=8445
- Metadata update
- ShellCheck style
=> coreutils 8.25 (updated)

freetype/plan.sh
Previously, libpng was included as a dependency but it wasn't being
recognized by the configure script.  This commit:
- Sets PKG_CONFIG_PATH so the configure script finds libpng and other
deps.
- Adds zlib and bzip2 to the deps list
- Sets pkg_bin_dir to ensure freetype-config is available in the PATH.
=> [freetype] Enable png, zlib, and bzip support

nginx/plan.sh
This updates nginx to the latest stable version. This also addresses the CVEs in 1.8.0 and 1.10.0. Additionally, this adds the core mail and streaming modules using the new dynamic parameters option and replaces the deprecated SPDY module with the HTTP2 module.
=> Update nginx to 1.10.1

go/plan.sh
Fixes CVE-2016-5386. See
https://groups.google.com/forum/#!topic/golang-announce/7jZDOQ8f8tM
Also make ShellCheck fixes for plan and add upstream URL and
description.
=> Update go to 1.6.3

dejagnu/plan.sh, expect/plan.sh, tcl/plan.sh
tclsh would fail on exit with an error about pthread_cance:
% exit
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
134
Similarly tools built on tcl would fail at exit:
expect1.1> exit
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
134
Explicitly linking with gcc_s solves this problem without requiring
users set LD_LIBRARY_PATH when running tcl-based applications.
=> Explicitly link tcl with gcc_s

llvm/plan.sh
This is a longer build - on my system took over 1 hour.
CMake requires use of an intermediate directory other than the source code root dir.
In order to get clang, we have to download a "sidecar" resource and place it into the correct location pre-compilation.
There didn't seem to be a facility to do this yet.
Homebrew leverages a method named `resource` that contains the ability to specify URL/checksum as well as the target unpack location.
=> llvm 3.6.2 (new plan)

openssh/config/sshd_config, openssh/default.toml, openssh/hooks/init, openssh/hooks/run, openssh/plan.sh
This is so we have an SSH binary that can be used by other packages such as core/git so we don't make an assumption that the underlying OS / distribution has SSH available. Also includes sshd configuration.
=> Add a plan for OpenSSH

git/plan.sh
We need to depend on our own core/openssh package because that way we aren't relying or assuming on the underlying OS/distribution having the SSH binary.
This requires #96 - though the packages are uploaded to the depot already.
=> core/git depends on core/openssh

ruby/plan.sh
This plan looks a bit plagiarized from the omnibus ruby script and
carries some cruft that badly needs to get removed.
libiconv hasn't been need in ruby forever.  We attempted to remove
it from omnibus, though, and broke people on upgrade in a minor
version because `$GREAT_NOKOGIRI_SADNESS`.  Lets not start going down
that road in habitat right from the start.
Most of the flags that disable gdbm/dbm/gmp seem pretty pointless
with the clean build system.  We had those in omnibus because we
had to in order to ignore any O/S provided libraries that might
get accidentally slurped up.  This is probably the biggest reason
about why habitat is a better build system than omnibus.
Also swapped out libedit for readline-rb since we're going to want
that instead down the road.  In that case the road …
=> cruft removal and readline-rb

.pre-commit-config.yaml, CONTRIBUTING.md
[SC1090](https://github.com/koalaman/shellcheck/wiki/SC1090) is not
really helpful in a plan, since we usually don't have a direct reference
to the thing we're sourcing while editing a plan. This disables it in
the pre-commit.
=> Exclude ShellCheck rule 1090

ncdu/plan.sh
With the inclusion of ncurses libraries, we can now produce a visual
interface binary application.
=> ncdu 1.11 (new plan)

openssh/hooks/init
When starting core/openssh, the init script needs to create the host keys for the system. However, it needs to ensure that it doesn't run this when the keys already exist for two reasons:
* Existence of the keys will cause ssh-keygen to fail if the service is restarted, e.g., on upgrade
* A user might want to manage their host keys outside of habitat with their own secrets management, with Chef, or in their base OS image
=> Make ssh-keygen idempotent in init

bin/build-dependent-order.rb
In the event that a plan loads and depends on a previous version of
itself - for example `go` - we will get a stack error when trying to
get the dependency list out of the `build-dependent-order.rb` script.
This commit fixes this by using Ruby's `#reject` method. We would
possibly want to use `#grep_v`, but it's not available in all Rubies,
so here we are.
=> Resolve stack error on recursive dependencies

gdb/plan.sh
Update to GDB 7.11.1 and add support for python scripting and expat.
Since coreutils are used, add multiple jobs to "make" with nproc(from coreutils).
Add core/expect and core/dejagnu dependencies to be able to run "do_check".
Bring the entire build process closer to Ubuntu's.
Tested inside a clean Alpine container.
--
Note that even though `make check` runs now, over 300 tests fail(~27000 pass)
=> Update to GDB 7.11.1 and add support for python scripting, lzma, TUI and expat

make/plan.sh
The `make` package was released on 2016-06-10 and contains many fixes.
The full changelog can bee seen here:
http://git.savannah.gnu.org/cgit/make.git/tree/NEWS?id=4.2.1
=> make 4.2.1 (updated)

fontconfig/plan.sh
* Add description/upstream url/maintainer
* Add deps on zlib and bzip2, needed by binaries
* Move environment variable setting into `do_prepare`
* Set `FREETYPE_CFLAGS`, `FREETYPE_LIBS`, and `CFLAGS` to values that
make this build
* Remove `make install` from `do_build` because it already happens in
`do_install`
¯\\(°_o)/¯
=> Fixes for fontconfig

curl/plan.sh, dotnet-core/plan.sh, krb5/plan.sh, lttng-ust/plan.sh, userspace-rcu/plan.sh
Once you have it, you can `hab pkg exec core/dotnet-core dotnet`.
Adds:
* Fixes for the curl plan, mainly compiling in the path to the CA cert
file so libcurl can verify certificates
* A [Kerberos5](http://web.mit.edu/kerberos/www/) plan
* A [LTTng](http://lttng.org/) plan
* An [userspace-rcu](http://liburcu.org/) plan
Requires ICU 52.1, which I'll get uploaded to the depot separately (we have
57.1 currently.)
=> Add dotnet-core

polipo/hooks/init
the `init` hook fails if polipo is started more than once.
```
root@0b7fbcc18b97:/src/components/sup# hab start core/polipo
hab-sup(MN): Starting core/polipo
hab-sup(GS): Supervisor 172.17.0.2: e4c636d1-4a19-4688-8902-f2ddac17e8e6
hab-sup(GS): Census polipo.default: df3544bb-4462-4ffa-ba20-acdf8f8b85e8
hab-sup(GS): Starting inbound gossip listener
hab-sup(GS): Starting outbound gossip distributor
hab-sup(GS): Starting gossip failure detector
hab-sup(CN): Starting census health adjuster
hab-sup(SC): Updated polipo.config
hab-sup(TP): Restarting because the service config was updated via the census
polipo(SV): Starting
^Cpolipo(SV): Stopping
hab-sup(SV): polipo - process 2206 died with signal 2
hab-sup(MN): Finished with core/polipo
root@0b7fbcc18b97:/src/components/sup# hab start …
```
=> allow polipo to start more than once

inspec/plan.sh, net-tools/config.h, net-tools/fix_default.patch, net-tools/plan.sh
- `Inspec` relies on `netstat` to check open ports.
- `net-tools` doesn't compile with `default` switch blocks, the included patch simply adds `;` characters to each `default` block.
=> add net-tools, readline to inspec

redis/plan.sh
Moderate-level upgrade due to server crash when using LSET with Lists,
as well as Sentinel fixes, and more!
Release notes here:
https://raw.githubusercontent.com/antirez/redis/3.2/00-RELEASENOTES
=> redis 3.2.3 (updated)

cargo-nightly/plan.sh
This package is postfixed with `-nightly` because it pulls the latest nightly build of Cargo, determines the version, and releases it. Anyone consuming this package is probably looking for the latest build tools for Rust outside of Rust's release cycle.
Required by: https://github.com/habitat-sh/habitat/pull/1136
=> add cargo-nightly plan

giflib/plan.sh
GIFLIB, also commonly referred to as libgif, is a core library for any
tools manipulating GIF images.
=> giflib 5.1.4 (new plan)

apr/plan.sh
- Metadata update
- Dependencies updated to reflect only what is needed for build/test
- Export lib/include directories for use by other packages (Fixes #123)
=> apr 1.5.2 (updated plan)

.pre-commit-config.yaml
In many cases, plan config files contain Handlebars
and will fail linting.
Docs here, the `exclude` format is underdocumented :-(
http://pre-commit.com/
Signed-off-by: Dave Parfitt <dparfitt@chef.io>
=> exclude plan config dirs from pre-commit tests

cargo-nightly/plan.sh, rust/plan.sh
This change adds a wrapper script for `cargo` in both the rust and
cargo-nightly plans to depend on and set a suitable set of SSL
root certificates.
Prior to this change, and plans that built Rust projects with cargo
would have to export OpenSSL's `CA_CERT_FILE` environment variable,
otherwise fetching dependencies or registry snapshots would fail. Rather
than pushing the reponsibility onto each downstream Plan, this change
"owns" that job as it is an implementation detail after all.
=> [rust,cargo-nightly] Add wrapper for `cargo` to set SSL certs.

bin/build-dependent-order.rb, bin/build-order.rb
This change is to support a refactoring in the Habitat core repo to
source and share one version file across multiple components. As the
paths vary it was necessary to use the `$PLAN_CONTEXT` variable to
compute the correct directory to the `VERSION` file. This change adds
the `PLAN_CONTEXT` variable in the Plan-sourcing inlined Bash program
and will make all Plans sourcable once again.
/cc @reset
=> Add `PLAN_CONTEXT` variable to build order ruby scripts.

mysql/config/init.sql, mysql/config/my.cnf, mysql/default.toml, mysql/hooks/init, mysql/hooks/run, mysql/plan.sh
Create `mysql.toml`:
```toml
root_password = "zanzibar"
app_username  = "soup"
app_password  = "bananas"
bind          = "0.0.0.0"
```
Start it up:
```
HAB_MYSQL="$(cat mysql.toml)" hab start core/mysql
```
Connect from another system:
```
mysql -u soup -h 172.17.0.3 -p
Enter password: bananas
```
And victory is yours!
The default `root_password` is empty - so it should be set at runtime. The default bind address is localhost, so that's probably not usable for most people with application connectivity needs. The app username and password are false, so they won't get rendered if they're not set at run time.
=> Add plan for mysql

bin/depot-upload-message.sh
The `source` command seems to fail if we don't use `/bin/bash`.
Signed-off-by: Dave Parfitt <dparfitt@chef.io>
=> change /bin/sh to /bin/bash to fix upload script

haproxy/plan.sh
CPU=native builds fail on processors that are too “different” than the original build machine (different instruction sets for the CPU model?).
Signed-off-by: Blake Irvin <blake.irvin@gmail.com>
=> support generic cpu builds

tomcat8/hooks/init
Ran into an issue where package would not pass the init phase (process `Aborted`).
See also
http://bash.cumulonim.biz/BashPitfalls.html#function_foo.28.29
=> [tomcat8] fix function syntax for busybox shell

tomcat8/hooks/init, tomcat8/hooks/run, tomcat8/plan.sh
This commit fixes the startup of core/tomcat8:
* Ensure that we're using bash
* Correct the function definition for the debug function in the init
hook
* Use -a instead of -R for the cp command
* Set both the user and group to root so the init script works
* Use chpst (from busybox-static) to set the privileges of tomcat to run
as hab:hab
=> Fix startup of tomcat8

redis/config/redis.config, redis/default.toml
We use Redis to show off leader election in Habitat. Redis 3.2.3 added protected mode by default, which means that out-of-the-box, leader election won't work because this can't be disabled using the current config template that dates from pre-Redis 3.2.x.
In a _production_ environment you would set `masterauth` and `requirepass` appropriately rather than turning this off, but for the purposes of field demos it's easier to turn off one setting because you can do it with a single environment variable rather than having to `cat` two settings into the Habitat supervisor using a TOML file.
=> Allow Redis protected-mode to be a tunable.

haproxy/config/haproxy.conf, haproxy/default.toml
This is useful if we want to HAProxy to quickly respond to slow or unresponsive backend servers.
Signed-off-by: Blake Irvin <blake.irvin@gmail.com>
=> support httpchk

sudo/plan.sh
A plan for the most awesome tool to run commands as another user.
This plan works, but may contain a controversial concept around `visudo`, so I'd appreciate some thoughts on this.
The visudo command is an admin-helper that performs manipulation of an /etc/sudoers file, typically in `vi`, which is included in the runtime deps of this plan.
This is overridable via setting the `EDITOR` environment variable to the desired editor (nano, pico, etc)
The `visudo` command also prodives a utility function to test a sudoers file syntax for accuracy via `visudo -c`.
Is there a problem with declaring a runtime dependency on an editor for a security package?
cc @habitat-sh/habitat-core-plans-maintainers
=> sudo 1.8.17p1 (new plan)

patchelf/plan.sh
I needed this in order to properly `patchelf` MongoDB otherwise it fails with [this](https://github.com/NixOS/patchelf/issues/38)
This PR supersedes #148
=> Patchelf 0.9

netcat/plan.sh
This is the more recent GNU port of the OpenBSD netcat.
If needed, there may be another package named `netcat-openbsd` in the
future.
=> netcat 0.7.1 (new plan)

netcat-openbsd/plan.sh
Some tools use specific `nc` flags that are not compatible with the
newer netcat binary, such as `-q`.
Note: Use of this in other core plans for _runtime dependencies_ should be measured carefully, as any other package using `core/netcat` later may have issues in $PATH selection.
=> netcat-openbsd 1.105 (new plan)

.pre-commit-config.yaml
In #131 we added some exclusion filters for files that are templated and
are not expected to pass a real linting.
The placement of said configuration was not accurate - the directives
must follow the check they are modifying.
=> Update pre-commit configuration for exclusion

mysql-client/plan.sh
Much slimmer package for when all you need is the client tools. In my case, I needed to bootstrap a database but pulling in `core/mysql` added about 500mb to my final package.
=> new plan: mysql-client

gcc/plan.sh
Previously, @miketheman observed the following test failure
counts while assisting with adding gfortran to the gcc package:
=== gcc Summary ===
/hab/cache/src/gcc-build/gcc/xgcc  version 5.2.0 (GCC)
=== g++ Summary ===
/hab/cache/src/gcc-build/gcc/testsuite/g++/../../xg++  version 5.2.0 (GCC)
In addition ot these failures, there were failures across a number of
the library test suites.
The large majority of the test failures were being caused by the test
executable having the wrong path to the program interpreter. The wrong
program interpreter was being choosen because our patching of the gcc
header files was setting `GLIBC_DYNAMIC_LINKER` to point at `<HAB PATH
OF GLIBC>/include/lib/ld-linux-...`.
Changing `${headers}` to `${glibc}` ensures that the
GLIB_DYNAMIC_LINKER path is set to …
=> [gcc] Reduce gcc and g++ test failure count

gdb/plan.sh
Dependency on `core/bdwgc` is necessary because otherwise it does this(it doesn't find `libgc`): https://gist.github.com/lilianmoraru/ee8a9334592bb90c4b5dde1810ab6734
Thanks to @stevendanna for helping me with `pkg-config(PKG_CONFIG_PATH)` and `libgc` issues.
=> Add guile support to gdb

tomcat8/hooks/run, tomcat8/plan.sh
Default permissions included in the tarball don't give any world access. This is now a problem with the fixed svc_user/group in hab 0.9.0 (https://github.com/habitat-sh/habitat/pull/1012)
=> [tomcat8] fix world access permissions

haproxy/config/haproxy.conf
Having the `~` in front of `else` worked on older version of hab, but the version of the handlebars crate has been bumped a couple of times since then.  Likely something changed in the handlebars crate since I added this logic originally.
Verified that this syntax uses config values if no backend binding is specified.
Fixes #166
=> Updating else syntax for Handlebars on haproxy config.

rust/plan.sh
https://blog.rust-lang.org/2016/08/18/Rust-1.11.html
=> Update to Rust 1.11.0.

mercurial/plan.sh
The mercurial built by this plan is capable of cloning HTTP and HTTPS
based mercurial repositories.
Depending on your studio setup, you may see the following post-test
failure:
--- /hab/cache/src/mercurial-3.9.1/tests/test-obsolete.t
+++ /hab/cache/src/mercurial-3.9.1/tests/test-obsolete.t.err
@@ -972,8 +972,6 @@
$ chmod 000 .hg/cache/hidden
$ hg log -r . -T '{node}' --debug
-  cannot read hidden cache
-  error writing hidden changesets cache
8fd96dfc63e51ed5a8af1bec18eb4b19dbf83812 (no-eol)
#endif
ERROR: test-obsolete.t output changed
This fails in containers if the filesystem allows the read on
`.hg/cache/hidden` despite the 000 mode.
A number of other tests are skipped, mostly related to
internationalization and canonical-specific features.
=> Add mercurial 3.8.1

git/plan.sh
Git 2.8: https://github.com/blog/2131-git-2-8-has-been-released
Git 2.9: https://github.com/blog/2188-git-2-9-has-been-released
Git 2.10: https://github.com/blog/2242-git-2-10-has-been-released
=> Update Git to version 2.10.0

binutils/plan.sh, gcc/plan.sh
This reverts commit 22c8f2fb1bfba3d732def3a9e115b1aca9ba879b.
The revert is due to the introduction of a cyclic dependency which
prevents us from running the build-dependent-order.rb script for release
activities.
@reset We can circle back on this post-release to determine what is the
correct solution here.
=> Revert "Use core/bash over /bin/bash in binutils & gcc plans"

httpd/plan.sh
In habitat 0.9.3, the plan build script no longer uses `$pkg_prefix`
in front of the command specified by the `pkg_svc_run` because as long
as the "bin" directory is specified in `pkg_bin_dirs`, the program for
the service will be in the `$PATH` environment variable.
This means we also do not need to specify it in the `$pkg_svc_run`
variable in our plans. And in fact, the `$pkg_prefix` variable itself
isn't populated at the time that a plan is sourced by the build
script, so this will be an empty value, and result in the `run` script
getting rendered as, e.g., `/bin/httpd`.
=> Fix path for httpd binary

vmtouch/plan.sh
Does not contain tests.
Needs `Perl` for `pod2man`.
=> Add a plan for vmtouch

tomcat8/plan.sh
The Tomcat mirrors don't appear to keep older versions online. We may
want to investigate a primary source for older versions.
=> bump version to 8.5.5

python/plan.sh
Discovered that one of the pkg_interpreters that was defined isn't created with the standard build of Python 3.5. Added a symlink to resolve it and support the expectation that a bin/python interpreter would exist.
=> Add symlink to missing `python` interpreter.

openssl/plan.sh
This addresses the following moderate severity CVE:
- Missing CRL sanity check (CVE-2016-7052)
=> [openssl] Update to 1.0.2j

CONTRIBUTING.md
SC2140 is a style focused shellcheck rule that looks for ineffectual quotations and suggests their removal.
https://github.com/koalaman/shellcheck/wiki/SC2140
Because many of our `core-plans` include a block like so:
```
pkg_description="Here is a super awesome package description for my thing :tm:"
```
We end up with SC errors when running it against many of our packages. This brings the contribution docs in line with the style many of our packages are already using.
=> Added SC2140 to list of shellcheck excludes

mongodb/plan.sh
This commit removes the pkg_prefix from the pkg_svc_run in the mongodb
plan. It also adds the default port to pkg_expose. Finally, we run a
number of jobs in scons equal to the number of CPUs, which can cut the
build time in half.
Signed-off-by: Joshua Timberman <joshua@chef.io>
=> Remove prefix from mongodb's pkg_svc_run

elasticsearch/default.toml, elasticsearch/hooks/init, elasticsearch/plan.sh
This commit updates elasticsearch for changes in the latest version of
Habitat, as well as updating elasticsearch itself to 2.4.1.
First, habitat runs the init script as "hab", so we need to have the
logs directory located in a place that hab has write access, like
`pkg_svc_var_path`, so the logs will be in
`/hab/svc/elasticsearch/var/logs`.
Next, the elasticsearch package itself used to have a plugins directory.
It wasn't being created, so startup would fail with a rather misleading
message:
```
elasticsearch(O): Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [logs]. Was the plugin built before 2.0?
elasticsearch(O): Likely root cause: java.nio.file.NoSuchFileException: …
```
=> elasticsearch updates for latest habitat

gdb/plan.sh
Say hello to official support for Rust.
Running with `DO_CHECK` passed most of the tests but it hanged on `gdb-sigterm` test.
I had to interrupt it(the build _without_ `DO_CHECK` passed though):
```
Running /hab/cache/src/gdb-7.12/gdb/testsuite/gdb.base/gdb-sigterm.exp ...
^Cgot a INT signal, interrupted by user 
=== gdb Summary ===
```
If this is merged, I will rebase #185.
=> Update GDB to version 7.12

inspec/README.md, inspec/plan.sh
Inspec is now being shipped as chef/inspec.
Signed-off-by: Dave Parfitt <dparfitt@chef.io>
=> add core/inspec deprecation notice

autogen/plan.sh, bdwgc/plan.sh, fontconfig/plan.sh, freetype/plan.sh, gdb/plan.sh, guile/plan.sh, imagemagick/plan.sh, libatomic_ops/plan.sh, libffi/plan.sh, libpng/plan.sh, libsodium/plan.sh, mg/plan.sh, netcat-openbsd/plan.sh, pixman/plan.sh, wget/plan.sh, zeromq/plan.sh
There might be issues with CI because I did not fix "non-valid" licenses and paths without inverted commas.
Build order:
1. libatomic_ops
2. bdwgc (depends on `libatomic_ops`)
3. libffi (`guile` depends on it)
4. expat
5. guile
6. zlib
7. xz
8. libpng
9. freetype
10. libsodium
11. libbsd
12. openssl
13. zeromq
14. pixman
15. fontconfig
16. gdb
17. imagemagick
18. netcat-openbsd
19. autogen
20. mg
21. wget
Not all but most of the packages do require this exact order(from zeromq and further, the order does not matter).
Every package was built in this order(without `DO_CHECK=true`).
=> Fix all PKG_CONFIG_PATH workarounds

tar/plan.sh
1.29 adds the `--clamp-mtime` option, which some tools depend on.
Also add a description and upstream URL and correct the license format.
=> Update tar to 1.29

dpkg/plan.sh
Based on
https://app.habitat.sh/#/pkgs/cerny-cc/dpkg/1.18.9/20160720025715
=> Add dpkg plan

sassc/plan.sh
* This has to download libsass as well as sassc. It felt like overkill to split libsass into its own plan.
=> Add plan for sassc

node/plan.sh
Upgrade node.js to 5.6.0. This isn't the latest LTS but it's the version
I need right now.
Add description and upstream URL. Make ShellCheck happy.
=> Node 5.6.0

mongodb/hooks/init, rabbitmq/hooks/init
- Found a typo in mongodb
- Didn't have the /bin/sh header for rabbit
=> Typo in mongodb and missing !/bin/sh

rust/plan.sh
=> Bump Rust to 1.12.1

pcre/plan.sh
- Support UTF8
- Correct lint and shellcheck errors
- add `$pkg_pconfig_dirs`
=> Support UTF8 encoding in pcre

erlang/plan.sh
Signed-off-by: Dave Long dlong@cagedata.com
Updates Erlang to 19.1
=> Update Erlang to 19.1

valgrind/plan.sh
Release notes: http://valgrind.org/docs/manual/dist.news.html
=> Update Valgrind to 3.12.0

zstd/plan.sh
Note that the tests run for a relatively long time(as described above `do_check`) - all have passed.
Sadly, no newer release, ~150 commits in master over v1.0.0.
=> Add plan for Facebook's zstd

curl/plan.sh
This addresses the following CVEs:
- CVE-2016-8615: cookie injection for other servers
- CVE-2016-8616: case insensitive password comparison
- CVE-2016-8617: OOB write via unchecked multiplication
- CVE-2016-8618: double-free in curl_maprintf
- CVE-2016-8619: double-free in krb5 code
- CVE-2016-8620: glob parser write/read out of bounds
- CVE-2016-8621: curl_getdate read out of bounds
- CVE-2016-8622: URL unescape heap overflow via integer truncation
- CVE-2016-8623: Use-after-free via shared cookies
- CVE-2016-8624: invalid URL parsing with '#'
- CVE-2016-8625: IDNA 2003 makes curl use wrong host
=> Update curl to 7.51.0

mongo-tools/plan.sh
Since we're building `core/mongodb` from source, the server distribution doesn't include tools.
=> Add the tools for MongoDB

nodejs-tutorial-app/plan.sh
Solution:
change npm start to node server.js, this skips the additional
process that npm start creates
see: https://github.com/habitat-sh/habitat/issues/1340
Signed-off-by: Dave Parfitt dparfitt@chef.io
=> using npm start results in multiple child processes upon reconfigure

boost/plan.sh
I needed a Boost built with zlib support for [a hyper-critical infrastructure component](https://docs.mapcrafter.org/builds/stable/index.html). These changes worked for me to build a `robbkidd/boost` package with zlib and a follow-on build of the hyper-critical component.
I'm not certain of the impact of building this support into the core package, so I'm opening the PR for discussion and consideration. I note that none of the other core plans depend on `core/boost`. mysql comes close, but depends on an earlier version via `core/boost159`.
=> add zlib support to boost

mongodb/config/mongod.conf
This is accomplished by the following:
- Allow for clusterAuthMode to be totally empty. The MongoDB docs say the default is actually "keyFile", but explicitly putting `clusterAuthMode = "keyFile"` has the effect of turning authorization on even if security.authorization is disabled.
- Make `security.authorization` actually tunable (the value was previously settable in `default.toml`, but not actually passed through to the `mongod.conf`)
To run a demo with MongoDB in an unprivileged mode (and to allow others to connect to it) it's only required to inject a TOML into the ring with these contents:
```
[mongod.net]
bind_ip = "0.0.0.0"
[mongod.security]
cluster_auth_mode = ""
```
=> Allow for mongodb to be run completely in insecure mode for demos.

virtualenv/plan.sh
The binary we previously had produced could not find its own libraries.
This edits the file to add the path.
=> Fix virtualenv

rust/plan.sh
=> Bump Rust to 1.13.0

dotnet-core/plan.sh, powershell/filesystemprovider.patch, powershell/plan.sh
This PR was originally to build coreclr from source. I got a long way down that road and learned alot but ended up discovering the value is not worth the cost. The cost being many hours to build the native clr binaries and eventually in the later artifacts, dotnet installs dotnet to build the managed dotnet stack. So it would be a long trip down a rabbit hole to unravel all of that.
Properly relocating the built bits, a binary plan should work fine and runs the accompanying powershell source build on moby linux succesfully.
One change this takes from the previous donet-core plan is to more aggressively patchelf the binaries instead of using the wrapper to set a LD_LIBRARY_PATH. That strategy works when using the dotnet cli but the built .net artifacts will break if calling them directly, …
=> Fix and update dotnet-core and add powershell

iproute2/plan.sh
Contains utilities like `ip`, `ss` and others.
=> iproute2 4.8.0 (new plan)

gox/plan.sh
With the help of @libsysguy, we got this dependency working for [vault](https://www.vaultproject.io/) to compile with go.
=> Added gox plan

rust/plan.sh
PR #290 updated Rust, but failed the build and merge to master due to
violations in the package metadata.
=> rust metadata (updated)

jemalloc/plan.sh
See ChangeLog for highlights:
https://github.com/jemalloc/jemalloc/blob/master/ChangeLog
- Replaces the need for customized `do_build` and simplifies some of the
build dependencies.
- Adds a `do_check` to run tests.
- Fixes metadata.
Refs #262
=> jemalloc 4.3.1 (updated)

consul/config/basic_config.json, consul/hooks/run
- `client_addr` allows for client to be declared in the config file.
Signed-off-by: JJ Asghar <jj@chef.io>
=> Moved the consul client to the config file

libcxx/plan.sh
Adds the llvm family's libc++ library. This is a requirement for ms sql server and I'm breaking up pr #299 to separate PRs for each affected plan.
=> add libc++ plan

python/plan.sh
In #316 @carrete provided a test case in which python fails with the
infamous pthread_cancel error:
Thread 0 has started
Thread 1 has started
Thread 1 is done
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
Explicitly adding `-lgcc_s` to LDFLAGS fixes the test case:
Thread 0 has started
Thread 1 has started
Thread 2 has started
Thread 2 is done
Thread 1 is done
Thread 0 is done
Note that `make test` is currently failing with other unrelated errors.
We've used this method of linking gcc_s in the plans for apr, guile,
tcl, and tor.
=> [python] Explicitly link gcc_s

logstash/config/logstash.conf, logstash/hooks/init, logstash/hooks/run, logstash/log4j2.properties, logstash/plan.sh
Logstash 5+ controls all file-based logging via the `log4j2.properites` file. We need to package a special version of this file that excludes any file appenders as Habitat apps should just log to the console. Packaging this properties file also allows any plans that wrap `core/logstash` to just leverage this file and not need to provide their own copy.
/cc @elliott-davis
=> Ensure Logstash only logs to the console

dotnet-core/plan.sh, icu52/plan.sh
I've already published these to the depot, but these are the changes necessary to get the `dotnet-core` plan building again
=> Add icu52 plan and pin to dotnet-core

libev/plan.sh
Additionally, update the download URL to a location with more than just
the newest available binary in the directory tree
=> Update libev to 4.23

jo/plan.sh
Turns out, jo is insanely great and useful. For example:
```
> hab pkg exec core/jo jo -p pkg_origin=core pkg_name=jo pkg_version=1.0
{
"pkg_origin": "core",
"pkg_name": "jo",
"pkg_version": 1
}
```
Seeing as this is a very small C program, it seemed reasonable to
statically build this program (grand total ~56K binary).
Thanks to @tyler-ball for telling me about this little ditty!
=> [jo] Add plan for jo, a small utility to create JSON objects.

MAINTAINERS.md
Maybe I can stop badgering @elliott-davis now...!
/cc @habitat-sh/habitat-core-maintainers @habitat-sh/habitat-core-plans-maintainers
=> Add Seth Chisamore to Maintainers

rust/plan.sh
https://blog.rust-lang.org/2016/12/22/Rust-1.14.html
=> Update to Rust 1.14.0.

postgresql/hooks/init
We use this flag to get around locale issues on certain Linux or container flavors - without it, and without a complete set of LOCALE environment variables, initdb can fail.
Signed-off-by: Blake Irvin <blake.irvin@gmail.com>
Signed-off-by: Arash Zandi <arash.zandi@gmail.com>
=> use `--no-locale` with initdb

redis/config/redis.config
The current examples of the `bind` directive show the ability to use an
array of strings, but the template implementation currently renders the
array as itself.
Using the `#each` notation, we step into the directive if there are any
values and render each out with a space delimiter.
=> :snowflake: redis template bind addresses

bundler/plan.sh
When using an older version of bundler with a Gemfile.lock that has a
bundler version, you get a warning. Let's update to the current
version and avoid that warning, shall we?
Also, we get several bugfixes according to the bundler changelog
https://github.com/bundler/bundler/blob/018f9b81948a99bead40a0f91d8384b9dd4a80f2/CHANGELOG.md
Signed-off-by: Joshua Timberman <joshua@chef.io>
=> Update bundler version

nginx/plan.sh
Build the latest stable release, 1.10.2.
Without `make install`, we don't actually get the modules that we're
compiling dynamically. 
Signed-off-by: Joshua Timberman <joshua@chef.io>
=> Update nginx to latest stable and install modules

dotnet-core/plan.ps1
We should not upload this to the depot until we have the depot target awareness built.
=> add a powershell based plan for dotnet-core

powershell/plan.ps1
*Note*: we should not upload to the depot until the target awareness is deployed.
There are two items worthy of mention here:
This is not a source build like the bash based plan. My initial attempt was to do just that. I ran into issues with both the cpp build tools and the msbuild installer. The cpp build tools essentially installs a minimal visual studio and visual studio checks that there is only one install on the machine. I then discovered that the MSBuild tools would suffice but because it is MSI based, it enforces one install per machine. Typically I would extract the binaries from the msi and then install them "manually" but it was not clear how to do that for an EXE based installer. I'm hoping this is possible but not worth the time right now.
There are powershell core …
=> Adds a powershell plan for powershell

tomcat8/hooks/run, tomcat8/plan.sh
This bumps Tomcat to 8.5.9 and removes the runtime dependency on `core/jdk8`. We're removing this for two reasons:
1. Tomcat can run with either `core/jdk7` or `core/jdk8` and we don't have a concept of features or optional packages
1. We aren't sure which version of Java the consumers of the Tomcat package will be using and they'll be specifying it themselves
In the occasion where you do want to run just Tomcat and you haven't installed either the `core/jdk8` or `core/jdk7` package, the run hook will error out and prompt the user to install either.
=> Remove dep on jdk8 in Tomcat8 plan

tomcat8/hooks/run
My previous change was a bit off for this run hook. We need to check the exit status AND get the output of stdout assigned to JAVA_HOME
=> Fix Tomcat8 run hook

php5/plan.sh
* Stop doing the thing where we symlink into /usr/bin for xml2-config;
found a way to do this with a variable
* Add glibc as a direct, rather than transitive dep, because it is
* Add curl, exif, fpm, mbstring, opcache, openssl, zlib, and xmlrpc support
* Add sbin to bin_dirs (that's where php-fpm goes)
Fixes #327
=> Updates to php5 plan

jruby1/plan.sh, logstash2/plan.sh
These plans both use shell scripts in their bins that require things
like `dirname`, so that `hab pkg exec core/jruby1 jruby` or `hab pkg
exec core/logstash2 logstash` would not run.
This fixes those problems, and fixes a few things up in the plans.
=> Fixes for jruby1 and logstash2

galera/plan.sh
Adds a plan for installing the Galera replication plugin.
=> adding plan for galera replication plugin

haproxy/config/haproxy.conf, haproxy/default.toml, haproxy/plan.sh
Signed-off-by: Michael Ducy <michael@chef.io>
Added in the ability to turn on the HAProxy Status page. This is useful for demos, and merging these in will allow us (Habitat people and Chefs) to demo using the core/haproxy plan and not a forked plan. 
I also bumped the version to the latest stable version of HAProxy 1.6.x.
=> Bump haproxy to 1.6.11, add status page support

7zip/plan.ps1
=> remove -verb arg which breaks powershel core and is unnecessary on powershell full

rabbitmq/config/env, rabbitmq/default.toml, rabbitmq/hooks/health_check, rabbitmq/hooks/init, rabbitmq/hooks/run, rabbitmq/plan.sh
* Extract env vars set in both init and run hooks into a config/env file
* Annotate default.toml
* Add a health check
* Replace some `$(hab pkg path)`s with `{{pkg.path}}`s
* Don't reference the full path in hooks because we already have it in
`$PATH`
* Multi-line and alphabatize the deps
* Add coreutils dep so scripts in sbin can find `dirname`
* Move env var setting to `do_prepare` so we can use the default
`do_install`
* Remove redundant build deps that are already in deps
=> Improvements to rabbitmq plan

doxygen/plan.sh
Add `ICONV_INCLUDE_DIR`. Fixes #198.
=> Fix doxygen build

mysql/plan.sh
Add some missing lib flags, clean up and sort dependencies, fix
interpreters, and remove a bunch of files that make the package 10x
smaller.
`hab start` will start mysql, but I haven't done much else more with it
than that, but it does indeed compile.
Fixes #197.
=> Make mysql compile

rabbitmq/config/env, rabbitmq/hooks/health_check, rabbitmq/hooks/init
Some operating systems that have versions like "16.04" that I'm very
angry with today happen to, by default, symlink /bin/sh to dash, which
is not bash, which makes some of these hooks fail.
Update the hooks to use /bin/bash because that's what we mean.
=> Use /bin/bash for rabbitmq hook shebangs

node/plan.ps1
I think the change has the potential to cause more problems than it fixes and should be unnecessary on powershell core.
=> reverting long path change

wix/plan.ps1
dark.exe in these tools will allow us to pop open some of the ms exe installers.
=> adding wix toolset binaries

composer/plan.sh
This adds a plan.sh for the PHP package manager, composer.
=> add a plan for composer: php package manager

composer/plan.sh
rather than leaving this job to people who use our package, we create a
simple (build-time) wrapper that will resolve the correct path to php.
Since core/composer has a run-time dependency on core/php5, it will
always rebuild when core/php5 changes.
We also "move" do_check() at the end of do_install(). We cannot check
what we didn't do (build), so we check the end result.
n.b.: The 2>/dev/null hides the following error message from composer:
Do not run Composer as root/super user! See https://getcomposer.org/root for details
I think it's safe for us to ignore… given that we run practically
everything as root.
Signed-off-by: Igor Galić <i.galic@brainsware.org>
=> composer: create a wrapper that resolves php's path

composer/plan.sh
for packages that are not pulled from [packagist](https://packagist.org/),
composer will most likely rely on git, so we should add that runtime dep.
Signed-off-by: Igor Galić <i.galic@brainsware.org>
=> composer: for installtions may need git

python/plan.sh
I found this when calculating dependant package rebuilding today. The
Python plan had a build dependency on GDB, but GDB requires Python at
runtime for its repl integration. Removing `core/gdb` as a *build* dep
doesn't appear to adversely affect the Python package.
=> Remove cyclic dep of gdb in python plan.

jfrog-cli/plan.sh
This is needed to achieve parity with the jfrog-cli package that home brew installs, so we can publish to bintray with a consistent set of command line args from https://github.com/habitat-sh/habitat/blob/master/components/bintray-publish/bin/publish-hab.sh
=> Bump jfrog-cli to 1.7.1

bison2/plan.sh
while working on #437, I've discovered that bison needs m4 to execute its
subscripts. Unfortunately, it's very hard to tell from the outside:
```
[36][default:/hab/cache/src/php-7.1.2:141]# make
bison -y -p ini_ -v -d /hab/cache/src/php-7.1.2/Zend/zend_ini_parser.y -o /hab/cache/src/php-7.1.2/Zend/zend_ini_parser.c
make: *** [Makefile:581: /hab/cache/src/php-7.1.2/Zend/zend_ini_parser.c] Broken pipe
```
`strace(1)` reveals, that bison is trying to `execve(2)` `m4` here.
In all other distros I checked, bison has m4 as run-time dependence:
* https://pkgs.alpinelinux.org/package/v3.5/main/x86_64/bison
* https://www.archlinux.org/packages/core/x86_64/bison/
* http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/bison/wily/view/head:/debian/control#L13
Signed-off-by: Igor Galić …
=> m4 is a run-time requirement for bison

composer/plan.sh, php/plan.sh
This adds a plan for the current PHP 7.1.2, and promotes it to be the
default PHP by naming it `core/php` and using it in `core/composer`
Signed-off-by: Igor Galić <i.galic@brainsware.org>
=> add plan for php 7.1.x and make it the default php

curl-static-musl/plan.sh
Signed-off-by: Chetan Sarva <chetan@pixelcop.net>
=> curl-static-musl: a statically compiled curl binary with no other deps

kibana/plan.sh
* Make description shorter
* Use CA certs setting for git downloads instead of verify none
* Use `pkg_binds_optional` instead of `pkg_binds` so non-habitat-hosted
Elasticsearch works
* Remove unnecessary symlinking of /usr/bin/env
* Disable npm progress bars
* Make copying to the prefix quieter
* Disable `do_strip` because it's slow and gives no benefit
=> Improvements to Kibana plan

dotnet-core-sdk/plan.ps1, dotnet-core-sdk/plan.sh
With the latest release of dotnet core, the runtime and sdk are split. This separates the two into separate packages. Note that the sdk download url has v1.1.1. It actually includes v1.0.1 of the sdk and both 1.0.4 and 1.1.1 runtimes.
This PR updates both windows and linux plans.
=> bump dotnet-core to v1.1.1 and add a dotnet-core-sdk plan

kibana/plan.sh
In #445 the build didn't actually work right because turns out it really
did need /usr/bin/env. Add it back here.
=> Add back symlinks to env

mysql/config/init.sql, mysql/config/my.cnf, mysql/default.toml, mysql/plan.sh
I recently needed to use the mysql plan in a docker environment with binding to other containers. Here are some changes I had to make to get that working:
* Makesure you can login as root on the container
* Error messages were not being translated and this makes language configurable defaulting to english
* Exports port and app creds
=> improvements to mysql plan

7zip/plan.sh
This adds a `plan.sh` to 7zip to facilitate building for Linux.
Signed-off-by: Ryan Hass <rhass@users.noreply.github.com>
=> Add Linux support to 7zip

python2/plan.sh
Package merged this afternoon broke linking to `libpython2.7.so.1.0`.
Local tests show this corrects the issue.
=> Correct the broken linking of `libpython2.7.so.1.0`

scaffolding-python/lib/scaffolding.sh, scaffolding-python/plan.sh, scaffolding-python2/lib/scaffolding.sh, scaffolding-python2/plan.sh
This adds scaffolding for Python packages. We will likely need to integrate the environment separator changes from @georgemarshall so we can set PYTHONPATH appropriately.
/cc @georgemarshall
=> Add Python Scaffolding for Python and Python2.

scaffolding-go/README.md, scaffolding-go/lib/scaffolding.sh, scaffolding-go17/README.md, scaffolding-go17/lib/scaffolding.sh
This adds a callback for `scaffolding_go_clean` and documentation for Scaffolding for both go versions.
=> Add go clean callback and documentation to Go Scaffolding

scaffolding-go/README.md, scaffolding-go17/README.md
This fixes an issue which was caused by a missing `|` which my markdown editor silently corrected in the table for the scaffolding-go README.md files and cleans up the presentation slightly.
=> (Obvious Fix) Fix table formatting issue.

docker/plan.sh
dockerd is the actual daemon. If we want to run docker containers we need that binary.
=> Add dockerd to docker plan

node7/plan.sh
resolves #481 by increasing the node version number and sha256 hash
=> upping the node7 version to 7.6.0

postgresql/config/pg_hba.conf
This updates the pg_hba.conf to use the default superuser rather than `postgres` to ensure the permissions work as expected.
=> Update pg_hba.conf default template.

rabbitmq/hooks/health_check
It was giving
`rabbitmq.default hook[health_check]:(HK): erlexec: HOME must be set`
Set `HOME` the same way it's set in the run hook. Now that health checks return
stdout/stderr, don't need to redirect to /dev/null.
=> Fix RabbitMQ health check

bin/check-default-variables.sh
* A required `$pkg_source` was dropped in habitat-sh/habitat#2074 which
affects Scaffolding package Plans where the code is located with the
Plan.
* A require `$pkg_version` was dropped in habitat-sh/habitat#2235 which
will affect the cacerts and cargo-nightly Plans once updated to use the
new `pkg_version()` helper.
=> [ci] Drop required variable check for pkg_source & pkg_version.

lsof/plan.sh
This adds lsof to the core-plans. `lsof` is used by inspec to perform open port and socket detection.
=> Add lsof to core-plans.

scaffolding-ruby/lib/scaffolding.sh
This was a reasonably simple addition of removing the short-circuiting
failure when a Rails 4.2 app is detected and a prompt to ask an app
developer to add the `rails_12factor` gem to their Gemfile which adds
static assest serving and logging to standard out support for Rails 3.x
and Rails 4.x.
=> [s-ruby] Add support for Rails 4.2 app types.

scaffolding-ruby/lib/scaffolding.sh
This change makes sure that the symlinked directories are created first
in the `init` hook, as they may be required when the app tries to make
its test database connection.
=> [s-ruby] Ensure that symlinked dirs are created first in init hook.

scaffolding-ruby/lib/scaffolding.sh, scaffolding-ruby/plan.sh
This is PR in 2 parts:
This change changes how some Scaffolding data is set when it is in an
associative array. For `scaffolding_env`, `scaffolding_process_bins`,
`pkg_binds`, and `pkg_exports` a key is first checked to see if there is
already a value (which would have been set in a Plan) and a value will
be set only if there is no current value set.
This change attempts to allow a Plan author to write configuration in
their `default.toml` file which will not be overridden by the
Scaffolding code. Before a Scaffolding default entry is added, the
Plan's `default.toml` is checked first to see if a key exists there. If
no key exists, the Scaffolding default is added and otherwise it is not.
This should allow a Plan to always win with their configuration data.
=> [scaffolding-ruby] Allow Plan hash values & default.toml data to win.

camlp4/plan.sh, ocaml/plan.sh, ocamlbuild/plan.sh, opam/plan.sh
This PR adds the following packages:
- ocaml - the OCaml compiler and runtime
- ocamlbuild - build tool for OCaml projects (previously part of OCaml, now split out)
- camlp4 - language parser, sometimes used by deps in compilation step
- opam - package manager for installing deps
With these packages in place it is possible to build OCaml projects in the habitat world.
=> OCaml toolchain

ocamlbuild/plan.sh
This was missing.
When this is uploaded, the camlp4 and opam packages from #502 can be uploaded.
=> Add `pkg_bin_dirs` to ocamlbuild

glibc/plan.sh
(Editor's note) sometimes I really dislike fixing Plan code because
shellcheck has an issue with it--the Plans are guarenteed to run under
GNU Bash 4.x and thus Plans don't fall prey to common shell coding
issues. This was another example of a carefully made lint fix that
resulted in a broken package which took many downstream dependencies to
find. Thankfully, this is only the frustration of someone who needs to
build **all** Plans which include the most complex cases. My hope is
that almost everyone else never has to worry about these details--we do
this in service of the greater good.(/Editor's note)
=> [glibc] Fix regression due to linting in #475.

envdir/plan.sh, wal-e/default.toml, wal-e/hooks/run, wal-e/plan.sh
wal-e is typically used in combination with postgresql to support backups and continuous archiving to various cloud object stores.
=> Add wal-e to core plans

scaffolding-ruby/doc/reference.md, scaffolding-ruby/lib/scaffolding.sh
This change slightly alters the auto-generated service binding when
build a Ruby-based app when a PostgreSQL database requirement is
detected. Before this change a **required** binding was generated,
meaning that the PostgreSQL instance had to be running in joined Habitat
ring under a Supervisor.
Running the database under Habitat and allowing your app service to
detect and connect remains exactly the same (by adding the `--bind
database:<service_group>` option when loading and/or starting the app).
However, if your database is currently running external to a Habitat
ring, or if your database is being managed by a cloud provider (such as
RDS with Amazon Web Services), then you must provide 2 additional config
settings:
* `db.host`: The database hostname. There is no valid default.
* …
=> [s-ruby] Support external database connection via optional bind.

dotnet-core-sdk/plan.ps1, dotnet-core-sdk/plan.sh, dotnet-core/plan.ps1, dotnet-core/plan.sh
Removed checks from dotnet-core runtime that won't execute, as they apply to sdk.
Made source paths use variablized URL so it doesn't need to be changed for each version (same url that the dotnet core install script uses)
Made fix_interpreter in sdk plan use a variabled path based on version
=> Updated dotnet-core plans for newer versions.

pixman/plan.sh
pixman puts its pkg-config data in `lib` rather than `include`.
=> [pixman] Correctly set pkg_pconfig_dir

rq/plan.sh
fixes #572 and I confirmed that this release executes fine in the Windows subsystem for linux.
=> use the 64 bit version of rq

rust/plan.sh
=> bump Rust to 1.18.0

php/plan.sh, php5/plan.sh
The PHP CLI binaries were failing to read input without readline
=> Add missing readline dependency for php plans

sensu/Gemfile, sensu/plan.sh
In testing the bundler update I rebuilt this and uploaded it with the appropriate version. Whoops!
https://bldr.habitat.sh/#/pkgs/core/sensu/0.29.0
=> Corrects broken sensu (accidentally already built and uploaded before PR)

libyajl2/plan.sh
This library is required to build the chef gem.
Doc page: https://lloyd.github.io/yajl/
Code repo: https://github.com/lloyd/yajl
=> Add libyajl2

gsl/plan.sh
GSL is a numerical library for C and C++. All tests are currently
passing. I've compiled with -O2 since I think most people would expect
an optimized build of GSL.
=> Add gsl plan

artifactory-pro/default.toml, artifactory-pro/plan.sh
Signed-off-by: Christopher Maher <defilan@gmail.com>
This is a pretty simple update. This is to bring the Artifactory Pro plan to version 5.3.1 with an updated hash. I also added a note to the default toml file indicating the need for a valid license key in order to successfully start this application (requirement added to Artifactory v5).
=> Updated Artifactory Pro to version 5.3.1

lsof/plan.sh
The lsof Makefile uses grep to search for constants in standard header
files to determine whether to enable IPv6. LSOF_INCLUDE sets where it
should look for those header files. Setting this variable correctly
results in IPv6 support being enabled.
=> [lsof] IPv6 support

socat/plan.sh
With the addition of openssl and readlines the only socat features we
don't support are libwrap and openssl-fips. We've stayed away from
libwrap so far and I think that is a good idea.  FIPS is a can of
worms I don't want to open right now.
I've also chronicled my attempt and getting the test suite passing.
It appears that our build of socat is fine and most of the issues are
environmental; however, after solving a half dozen small problems I
decided it was OK to not have the tests for now.
=> [socat] Upgrade to latest, add openssl and readline support

net-tools/config.h
Without AFINET6 support, tools like ifconfig won't show you IPv6
addresses bound to an interface.
=> [net-tools] Enable IPv6

aspcud/plan.sh, clingo/plan.sh, opam/plan.sh
aspcud is used by opam (when available) to resolve versions of dependencies. Without it it has a very naive and often faulty version resolution mechanism.
For opam build to succeed ocamlbuild and camlp4 will need to rebuilt first with the latest ocaml package (4.04.1)
=> Adding aspcud as standard relsover to opam

scaffolding-node/doc/reference.md
Signed-off-by: Paul Adams <paul@baggerspion.net>
=> Typo: bind should have said 'elasticsearch' not 'elastic search'

postgresql/config/postgresql.conf, postgresql/default.toml
This adds an additional config item,  `max_locks_per_transaction`, and sets the default value (64) based on the PostgreSQL 9.6 documentation:
https://www.postgresql.org/docs/9.6/static/runtime-config-locks.html
Signed-off-by: Christian Nunciato <cnunciato@chef.io>
=> Add max_locks_per_transaction to the postgresql plan

openssh/default.toml, openssh/hooks/run, openssh/plan.sh
* Update to OpenSSH 7.5p1
* Set hab_svc_user/group to root so it can bind to the default ssh port
* Use full path to sshd binary so that it can execute
=> Update OpenSSH Plan

visual-cpp-build-tools-2015/plan.ps1
This adds several libraries and include directories to make an MSBUILD build successful. It also copies assemblies that a normal VS install would GAC to the msbuild bin so that they will be propperly referenced at runtime with no GACage.
=> add missing pieces to be included in working msbuild builds

dotnet-core-sdk-preview/plan.ps1
We currently have an LTS and a release package for dotnet-core. With a forthcoming update to the powershell plan, we need to be able to use a preview sdk which we do not want added to the release package. This adds a preview package to accomodate preview bits.
=> add a preview package for dotnet-core

.pre-commit-config.yaml
I'm not entirely sure what happened, but pre-commit now depends on any
repo hosting hooks to provide a .pre-commit-hooks.yaml file.
This change bumps the versions of the referenced hooks to the latest
ones available, which have those files.
=> [pre-commit] update versions to have travis pass again

node8/plan.sh
Adds a plan for node version 8.3.0.
Signed-off-by: Matthew Peck <mpeck@chef.io>
=> add plan for node 8

scaffolding-ruby/doc/reference.md, scaffolding-ruby/lib/scaffolding.sh
This is needed to support using the https://github.com/rgeo/activerecord-postgis-adapter which expects the database adapter to be `postgis` even though it is talking to a postgresql database.
Signed-off-by: Will Fisher <will@alaska.edu>
=> Add config option for db.adapter in scaffold-ruby

traefik/config/traefik.toml, traefik/default.toml, traefik/hooks/run, traefik/plan.sh
So far, this builds the startable service, including the web ui on a
configurable address.
Most of the configuration is assumed to happen in a wrapper (see README).
-----
Example usage:
```
$ hab studio run 'build . && hab pkg export docker srenatus/traefik'
...
$ docker run -t -p 8080:8080 srenatus/traefik:latest
```
You'll then see the (pretty empty) dashboard on http://localhost:8080
----
Note that it might seem weird to build web stuff, and then not copy it. But it's actually built into the binary -- it only has to be _built before the binary_, so the compile process finds the static assets to pick up.
=> add traefik

httpd/config/httpd.conf, httpd/hooks/init, httpd/hooks/reconfigure, httpd/hooks/reload
* Log access log and error log to stdout
* Fix location of pid file to be in svc_var_path
* Add a reconfigure hook to fix permissions back to hab on reconfigure
and init
* Add a reload hook to kill with USR1 and gracefully reload rather than
doing a full restart.
Note that doing a reconfigure (via `hab config apply` or otherwise) in a
studio will still cause you to log out. This does nothing to change that
but doesn't make it any worse. See habitat-sh/habitat#2153.
=> Improvements to httpd

scaffolding-ruby/doc/reference.md, scaffolding-ruby/lib/scaffolding.sh
The correct name for the PostgreSQL adapter is `postgresql`.
Signed-off-by: David Wrede <dwrede@chef.io>
=> Changing default adapter value to postgresql

dep/plan.sh
This add the go dependency management tool to core-plans which help for making more complete scaffolding for go.
=> Add Go Dependency Management Tool

httpd/plan.sh
=> Bump httpd version to 2.4.27

scaffolding-ruby/README.md
Adds in temporary work around steps for dealing with bundler versioning error when using the ruby scaffolding.  I have also opened #734 to explore a longer term solution.
=> adds in troubleshooting for bundler error to readme of ruby scaffolding

foulkon/config/environment.sh, foulkon/config/proxy.toml, foulkon/config/worker.toml, foulkon/default.toml, foulkon/hooks/init, foulkon/hooks/run, foulkon/plan.sh
This adds a plan for [Foulkon](https://github.com/Tecsisa/foulkon/), an IAM-like authz service.
It contains _two services_: [Worker](https://github.com/Tecsisa/foulkon/blob/4e778b4a8f60c10067b61ab39a232397a0daeb49/doc/deploy/worker.md#deploy-foulkon-worker) and [Proxy](https://github.com/Tecsisa/foulkon/blob/4e778b4a8f60c10067b61ab39a232397a0daeb49/doc/deploy/proxy.md#deploy-foulkon-proxy). As added here, `core/foulkon` will [start the worker](https://github.com/habitat-sh/core-plans/compare/master...srenatus:sr/add-foulkon?expand=1#diff-bf5cdec83b952b2d52670605bb7a4e38R4). To start the proxy, wrap this plan and override [the run hook](https://github.com/habitat-sh/core-plans/compare/master...srenatus:sr/add-foulkon?expand=1#diff-bf5cdec83b952b2d52670605bb7a4e38).
=> add foulkon (v0.4.0)

scaffolding-go/lib/scaffolding.sh
This corrects an issue that was occurring for the use of *scaffolding-go* when opting to use local source instead of downloaded from external.
It was previously resulting in a directory copy error:
```
cp: cannot copy a directory, '/src/src', into itself, '/src/src/github.com/predominant/hello_string/src'
```
This fixes the issue, but might need some adjustments regarding temporary location, and exact commands.
=> Fix local src build of scaffolding-go

scaffolding-ruby/plan.sh
We have a version 0.8.4 that was built and up-loaded ad-hoc. That version is the latest, but no longer correct as it is dependent on a deprecated version of Ruby. So we need to bump up the package version.
Signed-off-by: Salim Alam <salam@chef.io>
=> Bump package version

scaffolding-node/lib/scaffolding.sh, scaffolding-node/plan.sh, scaffolding-ruby/lib/scaffolding.sh, scaffolding-ruby/plan.sh
`scaffolding_app_prefix` isn't truly needed until `do_prepare()` or later. Moved setting it into scaffold's `do_default_prepare()`.
Before it was being set suuuuper early in the scaffolding build. Because it uses `$pkg_prefix`, when set so early, it did not benefit from `$pkg_prefix` getting updated by `update_pkg_version()` which would leave some paths to things with a version of `__pkg__version__unset__`.
Instead, at the early point where `scaffolding_app_prefix` used to be set, `$app_prefix` is set to denote the directory inside the package into which the application will be copied.
For setting `pkg_bin_dirs`, `$app_prefix` ("app") is used instead of computing the basename of `$scaffolding_app_prefix` (also just "app").
For `pkg_svc_run`, because the `bin/` directory has already been …
=> move setting scaffolding prefix until after pkg_version is computed

aws-cli/plan.sh
Update to query pip for the latest available version and use that as the
pkg_version.
Disable do_strip and remove unneeded do_download/verify/unpack as well
Fixes #546.
=> Dynamically determine aws-cli version

scaffolding-node/lib/scaffolding.sh
This is the beginning of a fix for #821 (with much more to come).
This will strip extra characters off when someone defines the node version as "=5" or "v5" in their package.json.  Additionally, it adds zeros when needed to the version number (making it easier to correspond with core/node version numbers) - so "5" becomes "5.0.0".
This does not yet handle characters like ">=", etc. - I am still working on those.  This, however, gets some of my work into master, adds some functionality, and does not break any existing functionality.
=> Strip extra version chars

sensu/hooks/run
The current Sensu package fails to start:
```
sensu.default(O):
/hab/pkgs/nsdavidson/sensu/0.29.0/20171009174405/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:8:in
`require': libssl.so.1.0.0: cannot open shared object file: No such file
or directory -
/hab/pkgs/nsdavidson/sensu/0.29.0/20171009174405/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.2/lib/rubyeventmachine.so
(LoadError)`
```
Adding `core/openssl` to `LD_LIBRARY_PATH` resolves this and allows
sensu to start.
=> [sensu] Add openssl to LD_LIBRARY_PATH

CONTRIBUTING.md
Until the Supervisor is made more intelligent about which shell
interpreter to execute, all hooks written for core Plans must assume a
minmal bourne shell, such as BusyBox's `sh`, and never assume GNU
Bashims. This will cause breakages when running on systems which have
`/bin/sh` using a dash or non GNU Bash mode.
=> [CONTRIBUTING] Add note about only using BusyBox sh in hooks.

varnish/plan.sh
Varnish has updated their download URL. The previous one no longer works
=> Update Varnish Download URL

go/plan.sh
> Two security-related issues were recently reported.
> To address this issue, we have just released Go 1.8.4 and Go 1.9.1.
>
> We recommend that all users update to one of these releases (if you're not sure which, choose Go 1.9.1).
https://groups.google.com/forum/#!topic/golang-nuts/sHfMg4gZNps
=> [go] bump 1.9.1

tcpdump/plan.sh
Version 4.9.2 primarily addresses a number of vulnerabilities.  See
the change log for the (long) list:
http://www.tcpdump.org/tcpdump-changes.txt
=> [tcpdump] Upgrade to 4.9.2

openssl/ca-dir.patch
This completes the original effort to get openssl to use the cacerts
from the core/cacerts package by default.
Additionally, this eliminates the need for SSL_CERT_FILE to be set for
most, if not all, packages that depend on our version of openssl.
Signed-off-by: Christopher Webber <cwebber@chef.io>
=> Use core/cacerts for cacerts

sensu/config/config.json, sensu/config/server.json
The templates are currently using the older `has_<bindname>` method
which results in the `else` block always being used with default values.
=> [sensu] Config template fixes

jdk7/plan.sh
Around 2-3 months ago Oracle changed how users can access older versions of the JDK. JDK7 was affected. You can no longer download jdk7 without authenticating with an Oracle SSO.
This change points the pkg source to Arch Linux hosted download location. Oracle JDK7u80  is hosted there in its entirety. I've tested this build and the sha is exactly the same.
=> [JDK7] Stop depending on Oracle's unreliable download links

jre7/plan.sh
This change sets the JRE7 package source to point to the Arch Linux Project's hosted package.
=> [JRE7] Stop relying on Oracle's unreliable download links

MAINTAINERS.md
I've added or contributed to 40 core-plans:
autogen, bdwgc, curl, dejagnu, ed, erlang, expect, freetype
gcc, git, gsl, guile, haproxy, httpd, icu, imagemagick, jbigkit
libatomic_ops, libpcap, libscrypt, libseccomp, libtiff, libunistring
libunwind, libxslt, lsof, lua, lzip, mercurial, openssl, pixman, python
rsync, socat, strace, tcl, tcpdump, tmux, tor, valgrind
In addition I've made a couple of minor contributions to Habitat and
try to stay up-to-date on the state of the code base.  Currently, I'm
working on packaging X client libraries.
I've also served as an omnibus-software maintainer and have experience
solving a variety of software build problems across a number of
language ecosystems and on a number of platforms.
My personal goals as a maintainer would be to (1) work on policies …
=> Application to be a core-plans maintainer

openssl/plan.sh
Updates the openssl plan to version 1.0.2l and provides the pkg_shasum for the new version.
=> [openssl] update openssl plan to 1.0.2l 

curl/plan.sh
This depends on https://github.com/habitat-sh/core-plans/pull/676 to be accepted.
=> [curl] Add HTTP2 protocol support to curl

sumologic/config/wrapper.conf
Couple of minor tweaks to the sumologic wrapper configuration - change the default console logging level to Error in order to not have a ton of spew in the hab syslog, and also fix the collector logging directory location.
Signed-off-by: Salim Alam <salam@chef.io>
=> Change logging level and dir

haproxy/config/haproxy.conf, haproxy/default.toml
I found that when launching `core/haproxy` that the binding
is required so I don't know a situation where the supervisor
would ever use the default values found in the configuration.
I found that `has_backend` to not work correctly and always
return a false value. Making it so the members found in the
backend binding to never appear in the configuration and
for haproxy to always fall back on the default values.
I replaced the loop for writing out the backends with an
`eachAlive` which is an equivalent of `each` with the check
to see if it is alive inside the loop.
Signed-off-by: Franklin Webber <franklin@chef.io>
=> [haproxy] Removes config servers and relies on binding

envdir/plan.sh, wal-e/plan.sh
The `envdir` and `wal-e` plans contain `core/python/3.5.2` as a dependency, wrecking having if they're in your dep tree with anything that isn't similarly locked to 3.5.2. This overspecification was part of the original commit of the two plans and I can't find any indication they were included for any particular reason. They build fine and the upstream projects don't indicate any python3 version restrictions.
=> Remove python version specification

lz4/plan.sh
Relevant NEWS section since last hab package:
https://github.com/lz4/lz4/blob/810e2ca27b3561e0f6bfa7a88e0fde6faf807064/NEWS#L6-L36
Release notes for 1.8.0:
https://github.com/lz4/lz4/releases/tag/v1.8.0
=> Update lz4 v1.8.0

systemd/plan.sh
SystemD apparently uses one or more of these compression algorithms when
sending messages, especially large ones, as well as for compressing core
dumps. Making these binaries, libraries and header files available at
compile time helps prevent difficult-to-debug issues around shipping
logs, for example: https://github.com/habitat-sh/core-plans/issues/751
Signed-off-by: Blake Irvin <blakeirvin@me.com>
=> [systemd] make both `core/lz4` and `core/xz` available to `core/systemd`

goreplay/plan.sh
GoReplay is an open-source tool for capturing and replaying live HTTP traffic into a test environment in order to continuously test your system with real data.
=> Add plan for GoReplay

kmod/plan.sh
This updates the kmod package to create symlinks to its alternative names (insmod, depmod, modprobe, etc.)
=> Create symlinks to kmod alternative names

scaffolding-ruby/lib/scaffolding.sh
Reported in [HabiChat](http://slack.habitat.sh/):
> Following [these instructions](https://www.habitat.sh/blog/2017/08/habitat-rails-postgres-3-different-ways/) to convert an existing rails 5 app to habitat.  Everything works fine, until the build.  The scaffolding detects and runs Rake 'assets:precompile', but then crashes because it can't find config/database.yml.  This confuses me on two fronts:  1) This is the build phase, and I haven't deployed a database for it to talk to; b) I do have a config/database.yml, albeit configured with dummy data.
> If the database isn't available during build phase, but the scaffolding ultimately provides the database configuration during runtime, shouldn't the scaffolding provide a dummy-but-connectable database configuration so that the rake commands …
=> [scaffolding-ruby] provide a default database config for asset compilation

libxml2/plan.sh, libxslt/plan.sh
Latest versions -- at least [one libxml2 CVE](https://nvd.nist.gov/vuln/detail/CVE-2017-9047) should be resolved (but I haven't tried to accumulate a list of CVEs between old_vsn and new_vsn).
=> bump libxslt, libxml2

gdal/plan.sh, geos/plan.sh, postgresql/plan.sh, proj/plan.sh
This PR adds the popular PostGIS extension to the main postgresql build. This seems to be the best way to make PostGIS available to habitat users because:
- Postgresql developers are of the opinion that because users can load extensions, it would be a security vulnerability to allow extensions to be loaded from anywhere other than the official extensions path within the postgresql tree. There is no path without patching postgresql to load extensions from somewhere else in the filesystem: http://www.postgresql-archive.org/Configurable-location-for-extension-control-files-td5757897.html
- Because of this, the PostGIS build tools mostly ignore `--prefix` and just add files to the postgresql tree wherever it detects it: https://trac.osgeo.org/postgis/ticket/635
- So to use Postgresql and …
=> Add PostGIS extension to postgresql

dpkg/plan.sh
Pull in sbin to get all of dpkg's binaries.  Also, the Makefile doesn't follow normal gnu patterns, so explicitly set the prefix prior to making.  This gets all of the binaries and libraries into the correct location.
Signed-off-by: Nathan Cerny <ncerny@gmail.com>
=> dpkg - Add sbin, and fix build and install

go/plan.sh
> go1.9.2 (released 2017/10/25) includes fixes to the compiler, linker, runtime, documentation, go command, and the crypto/x509, database/sql, log, and net/smtp packages. It includes a fix to a bug introduced in Go 1.9.1 that broke go get of non-Git repositories under certain conditions.
=> [go] bump 1.9.2

.bldr.toml
This change will pick up changes in related plans to trigger rebuilds.
Most of these fall into either older versions of a package or packages
which are linked differently (using musl libc, statically compiled,
etc.). The following plans should benefit from this change:
* bash-static
* busybox-static
* bzip2-musl
* coreutils-static
* curl-static-musl
* gcc-libc
* gcc
* gnupg-static
* libarchive-musl
* libressl-musl
* libsodium-musl
* node8
* openssl-musl
* postgresql93
* postgresql94
* postgresql95
* wget-static
* xz-musl
* zlib-musl
=> [bldr.toml] Add additional paths to plans that source other plans.

.bldr.toml, certstrap/plan.sh
A simple certificate manager written in Go, to bootstrap your own
certificate authority and public key infrastructure. Adapted from
etcd-ca.
Signed-off-by: Seth Falcon <seth@chef.io>
=> Add certstrap plan

dotnet-core-lts/plan.sh, dotnet-core-sdk-lts/plan.sh, dotnet-core-sdk/plan.sh, dotnet-core/plan.sh
This change will ignore the user/group metadata when extracting tar
archives in privilege-reduced environments.
=> [dotnet-core-*] Add `--no-same-owner` flag to custom tar extraction.

node/plan.ps1, node/plan.sh
Testing process:
On Linux/OS X:
1) Build this version of core/node
2) Build new version of core/scaffolding-node with this version of core/node
3) Clone and build new app using this version of core/scaffolding-node
```
$ git clone git@github.com:alik0211/pokedex.git
$ cd pokedex
$ npm install
$ hab plan init -s node
$ hab studio enter
$ (studio) build
$ (studio) hab pkg export docker ./results/<hart file>
$ (studio) exit
$ docker run -it -p 8000:8000 core/pokedex
```
Everything built and ran successfully!
On Windows
1) Build this version of core/node
Scaffolding-node currently does NOT work on Windows.  I'm working on finding a way to build a generic node app on Windows using the plan.ps1 files, though the fact that it build …
=> upgrades core/node to latest LTS release

elasticsearch/hooks/health_check
Elasticsearch's health api returns three color coded values: green,
yellow, and red. Orange is never returned.
=> Fix health check for elasticsearch

traefik/plan.sh
Note: the node-sass stuff happening as part of the build breaks for node
versions that aren't listed on https://github.com/sass/node-sass/releases/tag/v3.13.0
(For the lazy: that's node 0.10, 0.12, 1, 2, 3, 4, 5, 6, 7 on Linux)
So, this pins the node-dependency to the latest version we have < 8.9.0.
=> [traefik] bump: 1.4.1 -> 1.4.2

.bldr.toml, c-ares/plan.sh
This package is courtesy of @nandub I just copied it, and created this pull request.
This package is needed as a dependency of `core/mosquitto` for which there's another pull request here: #902
=> Adds c-ares package

postgresql/default.toml
Remove the nested table `wal-e.aws` as it is not rendered into any config
templates.
Use integer type for port. While this won't matter for what gets
rendered in config, using an integer describes intent and follows
examples in Habitat docs.
Signed-off-by: Seth Falcon <seth@chef.io>
=> Remove unused section from default.toml

CODEOWNERS, acbuild/plan.sh
This updates the `acbuild` tool to 0.4.0.
I changed the build from existing binary modified with patchelf to source build because it seems that patchelf cannot work correctly with the binary (https://github.com/NixOS/patchelf/issues/66).
I did this update while trying to fix ACI export for habitat, but couldn't really test it for now, so I publish this first.
=> [acbuild] Updates to 0.4.0

caddy/plan.sh
This addresses an issue where Caddy, when installed in isolation, would not have access to glibc.
=> Add glibc as a dep to caddy

dex/plan.sh
I'm not entirely sure what has changed in scaffolding-go to make this
necessary, but the binary wasn't found in the place the plan was looking
for.
Now, it will be put in the right place directly in do_build.
=> dex: fix build and bump to 2.8.0

httpd/hooks/init, httpd/hooks/reconfigure, httpd/hooks/reload, httpd/plan.sh
This prevented core/httpd to start on ubuntu for example
=> [httpd] Fixes hooks shebangs

traefik/plan.sh
https://github.com/containous/traefik/releases/tag/v1.4.3
=> [traefik] bump 1.4.2 -> 1.4.3

node/plan.sh
Updated this and used `scaffolding_node_pkg="echohack/node/8.9.1"` in one of my nodejs projects to confirm it works~!
=> update to node 8.9.1 LTS

scaffolding-node/lib/scaffolding.sh
in order to use the scaffolding with Angular Seed
I will be doing a blog post highlighting this process when this is merged and released.
```
$ git clone https://github.com/mgechev/angular-seed
$ cd angular-seed
$ npm install
$ rm yarn.lock # only use one package manager
$ hab plan init -s node
```
Open up habitat/plan.sh and add in this content:
```
pkg_svc_user=root
```
Now, open up up your app's package.json file and downgrade these two dependencies to these versions:
```
"typescript": "2.4.2",
(...)
"@compodoc/compodoc": "1.0.3",
```
$ hab studio enter
$ (studio) build
$ (studio) hab pkg export docker ./results/<hart file>
$ (studio) exit
$ docker run -it -p 5555:5555 core/angular-seed
Navigate to http://localhost:5555 and check out the app!
Signed-off-by: Nell Shamrell …
=> [scaffolding-node] Support Angular Seed Applications

.bldr.toml, randrproto/README.md, randrproto/plan.sh
randrproto is required to build libxrandr (to be submitted shortly)
=> [randrproto] Add version 1.5.0

.bldr.toml, CODEOWNERS, monit/README.md, monit/config/monit.conf, monit/default.toml, monit/hooks/run, monit/plan.sh
This package provides the `monit` binary. Monit is a monitoring agent which can react to service failure.
There's a simple configuration that will act as a model for users of the package as there's no point in just starting this package (or I cannot foresee one).
=> [monit] Adds monit package

.bldr.toml, CODEOWNERS, jdk9/README.md, jdk9/plan.sh, jre9/README.md, jre9/plan.sh
Fortunately they only changed the directory structure of the tarball slightly. Some additional requirements in deps. But here we have it! Java 9!
=> Added Java 9: JRE and JDK

.bldr.toml, CODEOWNERS, mosquitto/README.md, mosquitto/config/mosquitto.conf, mosquitto/default.toml, mosquitto/hooks/run, mosquitto/plan.sh
This packages provides mosquitto, an MQTTv3.1/v3.1.1 broker.
In its current form, it allows generic configuration of mosquitto (based on simple template of default config file), and can be used as a service without much efforts.
It provides:
* binaries `mosquitto` and `mosquitto_passwd`
* libraries `libmosquitto.so` and `libmosquittopp.so`
* clients `mosquitto_sub` and `mosquitto_pub`
=> [mosquitto] Adds mosquitto package

.editorconfig, .pre-commit-config.yaml
Since patch files are typically generated from upstream code diffs,
we should not enforce our own style on these files.
Resolves #1004
=> Allow patch files to have trailing whitespace

scaffolding-ruby/lib/scaffolding.sh
Separating the swap out of `.bundle/config` and the execution of `bundle install` to different plan phases allows plan authors the opportunity to write to the config file before the install occurs. As described in Issue #927, some gems have hyphens in their name which prevents the usual trick of setting bundler build configs via an environment variable like:
```
BUNDLE_BUILD__GEMNAME="--some-config-switcheroos"
```
An attempt to set `BUNDLE_BUILD_GEM-NAME` with a hyphen results in the shell error: "not a valid identifier."
Closes #927
=> [scaffolding-ruby] move the bundle config swap out to do_default_prepare

scaffolding-node/CHANGELOG.md, scaffolding-node/plan.sh
So that we can more easily find that scaffolding-node depends on yarn (the dependency is currently dynamically added in lib/scaffolding.sh).
=> [scaffolding-node] adds explicit dependency on yarn

libdrm/README.md, libdrm/plan.sh
Some libs are not linked explicitly. However, `./configure` recommends them.
=> [libdrm] Adds libdrm (gtk3)

glib/README.md, glib/plan.sh
There are two libs recommended by `./configure` that are not linked from any of package members.
Should they be left in runtime deps, or do they belong to build deps?
=> [glib] Improves build (gtk3)

rust-nightly/plan.sh
update_pkg_version call fails due to misaligned context, this change should correct the issue
=> [rust-nightly] fixes pkg_version function

traefik/plan.sh
https://github.com/containous/traefik/releases/tag/v1.4.4
=> [traefik] bump 1.4.3 -> 1.4.4

etcd/config/conf.yml, etcd/default.toml, etcd/docs/README.md, etcd/hooks/health_check, etcd/hooks/run, etcd/plan.sh
This pull request does the following updates:
* Fix a copypaste typo in the README
* Fix what appears to be a bug in the run scripts (`../cfg...` vs `cfg...`)
* Update etcd to current stable, 3.2.9
* Add support for client and peer cert authentication (and update the health_check hook for that)
* Update the README
=> [etcd] various updates

traefik/plan.sh
https://github.com/containous/traefik/releases/tag/v1.4.5
=> [traefik] bump: 1.4.4 -> 1.4.5

scaffolding-node/CHANGELOG.md, scaffolding-node/doc/reference.md, scaffolding-node/lib/scaffolding.sh, scaffolding-node/plan.sh, scaffolding-ruby/CHANGELOG.md, scaffolding-ruby/doc/reference.md, scaffolding-ruby/lib/scaffolding.sh, scaffolding-ruby/plan.sh
This changes the git detection from checking for a `.git/` directory in only the `SRC_PATH` to using git itself to determine whether the current working directory exists within a git work tree.
An example where looking for `.git/` in `SRC_PATH` returns a false negative is git repositories with multiple components in sub-directories. The studio is generally entered at the root of the git repository and the build command executed with a sub-directory path. The fallback to `find | tar` ends up including many unnecessary or undesired files in the resultant package.
So long as the studio is entered from a location that includes the git repo root, this new git detection will be correct and the `git ls-files` used to collect the file list for packaging will be relative to the `SRC_PATH`.
* …
=> [scaffolding-(node,ruby)] make git a build dep in dynamic language scaffolds

nmap/plan.sh
Improvements:
* `core/pcre` instead of local `libpcre`
* adds packages to satisfy `./configure` checks
* adds compiler flags to avoid warnings and, I think, compile closer to what authors of nmap intended
* `do_check()` implementation (all tests pass, yay!)
I couldn't use `core/libpcap`, the build failed because there were the same libpcap stuff declared twice. I suspect the `--with-libpcap="$(pkg_path_for "core/libpcap")"` doesn't work properly, I'll continue investigating on it. If you have any pointers, they're most welcome :)
=> [nmap] Improves package

llvm/plan.sh
The build was failing because UID 1000 is the owner on some files in
the upstream tar archive but doesn't exist on the builder.
=> [llvm] Don't set file ownership on archive extract

.bldr.toml, kubectl/README.md, kubectl/plan.sh
While `core/kubernetes` also contains kubectl, it's a large package and
overkill for users which only need access to a Kubernetes cluster via
CLI. Hence, provide a separate kubectl package.
Due to https://github.com/kubernetes/kubernetes/issues/56346 1.8.3 is
currently used and not latest stable 1.8.5
Signed-off-by: Michael Schubert <michael@kinvolk.io>
=> [kubectl] Add kubectl plan

llvm/plan.sh
It turns out, we call tar twice.  Let's try using this flag on both
calls and see if that helps.
=> [llvm] Don't set file ownership redux

openldap/config/slapd.ldif
Bumped version to the latest OpenLDAP stable. 
The server failed to start correctly because of an extra newline in the slapd.ldif. I've removed that line which fixes that issue.
=> Fix syntax error in slapd.ldif

nmap/plan.sh
I discovered that there is a bug with the current build of core/nmap where libpcap was getting installed with nmap's source build, but wasn't working properly. I removed that from the build and added core/libpcap, which worked properly. Upon local testing, I can confirm this fix works when using nmap as a dependency in other projects. 
Please let me know if there are any questions or concerns. 
=> [nmap] Fixing core/nmap libpcap bug

nmap/plan.sh
There is no default value for pkg_bin_dirs.  Thus, without setting
this, `hab pkg exec` doesn't work for this package.
=> [nmap] Add pkg_bin_dirs so that hab pkg exec works

cyrus-sasl/plan.sh
This fixes a problem with cyrus-sasl looking for its plugins in the default location `/usr/lib/sasl2`
=> [cyrus-sasl] Fix plugindir path at compile time

fluentd/plan.sh
Upgrading to fluentd 1.0 release. It doesn't have breaking changes from previous 0.14.xx releases.
Signed-off-by: Rahul Sinha <rahul@rahulwa.com>
=> [fluentd] upgrading to 1.0.2

jenkins/plan.sh
Ref: https://jenkins.io/security/advisory/2017-12-14/
Ref: https://jenkins.io/blog/2017/12/14/security-update/
Should be promoted to stable above 2.89.1 also.
=> Jenkins upgrade to 2.89.2 (Security update)

.bldr.toml, libpq/README.md, libpq/plan.sh
This includes the psql tool as well as the libpq client side library. It might well be named postgresql-client for better discoverability, but that seemed like a bit of a mysql'ism (there's a utility named mysql-client, but nothing named postgresql-client)
Signed-off-by: Mark Anderson <mark@chef.io>
=> Add libpq (postgres client library)

logstash/plan.sh
also removed unused jruby dependency (it's vendored in by elastic)
=> [logstash] version bump to 6.1.0, fix startup issue

traefik/plan.sh
https://github.com/containous/traefik/releases/tag/v1.4.6
Signed-off-by: Stephan Renatus <srenatus@chef.io>
=> [traefik] bump 1.4.5 -> 1.4.6

.bldr.toml, ruby/plan.sh, ruby22/plan.sh, ruby23/plan.sh, ruby24/plan.sh
* Updates to the latest Ruby 2.4.x.
* Adds plans for all currently-maintained upstream Ruby versions.
These plans source `ruby/plan.sh` because so far it looks like the steps to build Ruby are the same for all these versions.
`update_pkg_version` is used to handle updating attributes to the different version from the latest Ruby. Some attributes aren't recomputed there, though--like `pkg_source` and `pkg_dirname` (because it's set to _something_ already)--so they are set again in the specific version plans.
The specific plan that tracks the latest version--`ruby24` here--is a simple sourcing of the main `ruby` plan with a sanity check that the `pkg_version` already set is the `X.Y` expected. This is intended to safeguard against the ruby plan moving to `X.Z` and having the specific …
=> [ruby] track and package multiple upstream releases

postgresql/config/functions.sh
habitat-sh/habitat@c61953650b (released in 0.52.0) changed the default
data directory permissions from 0700 to 0770. While postgresql can
initially start up because initdb will set the correct permissions on
the data directory, subsequent restarts of the service will fail
because the supervisor will change the directory permissions, leading
to the following postgresql error:
FATAL:  data directory "/hab/svc/postgresql/data" has group or world access
DETAIL:  Permissions should be u=rwx (0700).
Setting the data directory permissions explicitly resolves this issue
=> [postgresql] Fix data directory permissions

node/plan.sh
Signed-off-by: Matthew Peck <mpeck@chef.io>
Bumps the node version to 8.9.4. I noticed that there is a powershell file in the dir as well. It wasn't updated with the last version bump. I didn't make any changes to it because I have no way to test it.
=> Bump node version to 8.9.4

rust/plan.ps1, rust/plan.sh
This should also fix appveyor and travis plan builds breaking on:
```
--> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rusoto_credential-0.10.0/src/profile.rs:178:46
|
178 |         let lower_case_line = unwrapped_line.to_ascii_lowercase().to_string();
|                                              ^^^^^^^^^^^^^^^^^^
|
= help: items from traits can only be used if the trait is in scope
= note: the following trait is implemented but not in scope, perhaps add a `use` for it:
candidate #1: `use std::ascii::AsciiExt;`
= help: did you mean `to_lowercase`?
error: aborting due to previous error
error: Could not compile `rusoto_credential`.
```
=> bump rust to 1.23.0

powershell/plan.ps1
This is the RTM'd 6.0.0 released a couple weeks ago. I'm reverting from a source build back to a binary build. This release introduced breaking changes to the source build and we no longer need to update the source so their is little value in going through the effort of reverse engineering MSBUILD hell.
=> bump powershell to RTM 6.0 and revert to binary build

MAINTAINERS.md
Cleaning up alumni and adding myself to the list here. As I'm already an approved core-plans maintainer listed in the habitat repo this does not require a majority vote.
=> Cleanup Maintainers.md

postgresql/config/postgresql.conf, postgresql/default.toml
This gives us the ability to turn off logging to a file which will cause
postgresql to log to stderr. This behavior is prefered when running in a
container and when running under systemd.
ref: https://www.postgresql.org/docs/9.6/static/runtime-config-logging.html
Signed-off-by: Christopher Webber <cwebber@chef.io>
=> Allow postgres to write logs to stderr

postgresql/README.md, postgresql/config/.pgpass, postgresql/config/functions.sh, postgresql/config/postgresql.conf, postgresql/default.toml, postgresql/hooks/init, postgresql/hooks/reconfigure, postgresql/hooks/run, postgresql/plan.sh
This PR updates postgresql and postgis to the latest (9.6.6 and 2.4.2 respectively) and also enables it to run without root permissions.  In order to accomplish that I had to:
- reorganize `svc_data_path` to include the `pgdata` and `archive` subfolders
- remove all chown/chmod commands that require root permissions
- remove all chpst statements which are no longer needed
=> Update postgresql to latest and enable it to run without root permissions

go/plan.sh
Addresses CVE-2018-6574, see also
https://groups.google.com/forum/#!topic/golang-nuts/Gbhh1NxAjMU
=> [go] Bump: 1.9.2 -> 1.9.4

postgresql/hooks/health_check
We need to specify the configured port for pg_isready. This patch also
adds the configured superuser which will quiet the postgresql log and
prevent each health check from emitting a log entry.
The health check will now return CRITICAL if the checker is unable to
connect as well as if the connection is rejected (a not yet ready
state). While transient, this answers more clearly the question of
health from the perspective of a service depending on postgresql,
namely, "can you accept my connection and answer my queries?".
Signed-off-by: Seth Falcon <seth@chef.io>
=> Fix postgresql health_check when alternate port is specified

jenkins/README.md, jenkins/plan.sh
Addresses security advisory: https://jenkins.io/security/advisory/2018-02-14/
=> Jenkins upgrade to 2.89.4 (Security update), and readme update

postgresql/config/functions.sh
This PR extends the current functionality to allow for non-root services by detecting the effective user id and primary group and accounting for those to ensure proper path ownership.
=> fix postgresql chown assumptions

elasticsearch/plan.sh
This updates Elasticsearch to the recently-release version 6.2.2
Signed-off-by: Stephen Delano <stephen@chef.io>
=> Update Elasticsearch from 6.0.0 to 6.2.2

memcached/plan.sh
1.4.25 is about 2 years old. 1.5.4 is the latest
=> [memcached] Update memcached to 1.5.4

nginx/plan.sh
Latest nginx stable. v1.12.1 addressed [CVE-2017-7529](http://mailman.nginx.org/pipermail/nginx-announce/2017/000200.html)
=> [nginx] upgrade to 1.12.2

.bldr.toml, helm/README.md, helm/plan.sh
Once we have helm in the core origin, the Helm exporter can then depend on
this and be able to use this binary from the studio. This would mean that
the exporter can then take care of the `helm dep up` command for you.
Signed-off-by: Zeeshan Ali <zeeshan@kinvolk.io>
Fixes https://github.com/habitat-sh/habitat/issues/4637.
=> Add helm 2.7.2

.bldr.toml, rpm2cpio/README.md, rpm2cpio/hab-path.patch, rpm2cpio/plan.sh
Although there is an rpm2cpio implementation in busybox-static, there is
value in a very lightweight rpm2cpio implementation that stands alone.
This uses perl and the appropriate decompression libary by inspecting
the file magic number.
You will need cpio on your path to do anything useful with this.
Signed-off-by: Stephen Nelson-Smith <stephen@atalanta-systems.com>
=> Add: Plan for lightweight rpm2cpio

.bldr.toml, dovecot/README.md, dovecot/plan.sh
This adds dovecot, the IMAP server.
I've not included any run hook because I think it would have no value, unless we set up a complete configuration scheme, which, IIRC is not the aim of core plans :)
=> [dovecot] Add dovecot package

.bldr.toml, libepoxy/README.md, libepoxy/plan.sh
Many libs are wanted by `./configure` but not linked at all in built binaries... If someone knows if we should move them to build deps or if it's normal :)
Note that it builds perfectly fine like this, up to gtk3... ;)
=> [libepoxy] Adds libepoxy (gtk3)

dep/plan.sh
Our current `core/dep` package happens to be version 0.3.0 (I believe!),
however, rebuilding it would give us the latest version.
This change of plan.sh adds an explicit reset to the desired version of
dep to the download function.
Using the upstream-provided build script instead of the scaffolding lets
us build a dep binary that comes with proper version output:
[18][default:/src:0]# dep version
dep:
version     : v0.4.1
build date  : 2018-02-12
git hash    : 37d9ea0a
go version  : go1.9.4
go compiler : gc
platform    : linux/amd64
Also, this commit updates the version to the latest release of dep.
=> [dep] fix build version, bump version (v0.4.1)

.bldr.toml, libidn2/plan.sh
This should fix #1218 
As told on slack, I've already changed core/wget to include core/libidn2 as soon as base package refresh is merged and promoted.
=> [libidn2] Adds package

_RFCs/0002-rfc-process-revisions.md
Hello all!
We've been having issues with the current RFC process - mainly that getting a consensus from the majority of core maintainers and having FCP be fourteen days is taking much too long in order to move this project at the velocity it needs to.  As I have been working through old issues and PRs, I've realized there are some things we need to codify, and to do that we need to go through the RFC process, and I'd like to improve that RFC process before opening up a bunch of new RFCs.
The main changes this proposes are:
1) Change the requirement of approvals from core maintainers from a majority to 5.
2) Change the FCP period from fourteen days to seven days.
As this proposed change must go through the old process, we will need a majority of core maintainers and this will be FCP for …
=> [RFC] updates rfc process to move quicker

README_TEMPLATE_FOR_PLANS.md
This removes the link to the binary wrapper package documentation and clarifies what a "binary package" means in the context of core plans.
=> Readme template

MAINTAINERS.md
Signed-off-by: Tasha Drew <tasha.drew@gmail.com>
=> Add Tasha to core-plans maintainers

postgresql/README.md
Updates the PostgreSQL README to use the [README template](https://github.com/habitat-sh/core-plans/blob/master/README_TEMPLATE_FOR_PLANS.md).
=> [postgres] updates postgres readme to use the readme template

nmap/plan.sh
> Fixes #1063
Note that `core/libssh2` needs to be promoted to stable for this PR to work correctly
=> [nmap] Upgrades to 7.70 + link to core/libssh2

packer/README.md, packer/plan.sh
As part of this change, I updated the `plan.sh` to match what other Hashicorp binary packages look like (e.g. terraform). 
=> [packer] Update packer to 1.2.1

nginx/plan.sh
Changelog is here: http://nginx.org/en/CHANGES
Quite a bit of stuff. Verified that the built binary doesn't go up in smoke
like this:
[11][default:/src:0]# /hab/pkgs/srenatus/nginx/1.13.10/20180328103646/bin/nginx -V
nginx version: nginx/1.13.10
built with OpenSSL 1.0.2l  25 May 2017
TLS SNI support enabled
configure arguments: --prefix=/hab/pkgs/srenatus/nginx/1.13.10/20180328103646 --conf-path=/hab/svc/nginx/config/nginx.conf --sbin-path=/hab/pkgs/srenatus/nginx/1.13.10/20180328103646/bin/nginx --pid-path=/hab/svc/nginx/var/nginx.pid --lock-path=/hab/svc/nginx/var/nginx.lock --user=hab --group=hab --http-log-path=/dev/stdout --error-log-path=stderr --http-client-body-temp-path=/hab/svc/nginx/var/client-body --http-proxy-temp-path=/hab/svc/nginx/var/proxy …
=> [nginx] bump: 1.12.2 -> 1.13.10

jo/README.md
=> [jo] add README.md

nghttp2/README.md, nghttp2/plan.sh
Release notes for 1.31.0 are here:
http://nghttp2.org/blog/2018/02/27/nghttp2-v1-31-0/
But we're skipping some versions in this bump.
I've built core/curl against this version locally; and it seemed to work fine:
[5][default:/src:2]# /hab/pkgs/srenatus/curl/7.54.1/20180329122510/bin/curl -V
curl 7.54.1 (x86_64-pc-linux-gnu) libcurl/7.54.1 OpenSSL/1.0.2l zlib/1.2.8 nghttp2/1.31.0
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
=> [nghttp2] bump and add README

scaffolding-node/CHANGELOG.md, scaffolding-node/lib/scaffolding.sh, scaffolding-node/plan.sh
This is referenced later in the build process, and is important when using custom NPM repos.
=> [scaffolding-node] Copy over .npmrc if defined by the project

ninja/README.md, ninja/plan.sh
The `do_check` copies what the source had placed here: https://github.com/ninja-build/ninja/blob/master/.travis.yml#L6
=> [ninja] bump to 1.8.2 and add do_check

glib/plan.sh
Python is used in `${pkg_prefix}/bin/gdbus-codegen` as an interpreter. As it was rightly put by the build, we never saw it. Until I tried to build gtk3 ;)
=> [glib] Fixes python requirement at runtime

wal-e/plan.sh
Previously, the version of Python for `wal-e` was pinned to
3.5.2. Current `core/envdir`, however, depends on version 3.6.3,
creating a conflict.
Version 1.0.2 of wal-e does not appear to be officially supported on
Python 3.6, but the current 1.1.0 version is. Thus, we update to 1.1.0
and remove the version pin on `core/python` to march bravely forward
into the future.
=> [wal-e] Update to 1.1.0

.bldr.toml, CODEOWNERS, grpcurl/README.md, grpcurl/plan.sh
The `grpcurl` binary is just like cURL, but for gRPC. A Command-line tool for interacting with gRPC servers. 
Code base lives at https://github.com/fullstorydev/grpcurl
Extra: Ordered `CODEOWNERS` packages alphabetically
=> New core-plan 'grpcurl' 

.bldr.toml, gtk/README.md, gtk/plan.sh
Some libs are recommended by `./configure` and not linked in built binaries. Any idea if it's normal/wanted?
=> [gtk] Adds gtk package (gtk3)

CODEOWNERS, dsc-core/DSCCore.psd1, dsc-core/DSCCore.psm1, dsc-core/README.md, dsc-core/plan.ps1
We have several example windows service plans that take advantage of DSC for initial setup. Applying a DSC configuration in a hook requires extra ceremony because they run in Powershell Core which lacks native cmdlets for applying dsc. This package wraps up that ceremony so that consuming plan authors can just use a single command to apply their DSC configs.
=> adding a dsc-core plan

zeromq/README.md, zeromq/plan.sh
Bump to [4.2.5](https://github.com/zeromq/libzmq/releases/tag/v4.2.5) and also add in a `do_check`.
=> [zeromq] bump zeromq to 4.2.5

node/plan.sh
All node version plans appear to be affected by this issue.
`npm install` fails when `node-gyp` needs to be called in due to various uncorrected non-node shebangs and one rogue bare `node` invocation:
```
> msgpack@https://registry.npmjs.org/msgpack/-/msgpack-1.0.2.tgz install /src/node_modules/msgpack
> node-gyp rebuild
sh: /hab/pkgs/core/node/8.9.1/20171116162209/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: /usr/bin/env: bad interpreter: No such file or directory
> posix@4.1.1 install /src/node_modules/posix
> node-gyp rebuild
sh: /hab/pkgs/core/node/8.9.1/20171116162209/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: /usr/bin/env: bad interpreter: No such file or directory
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: msgpack@https://registry.npmjs.org/msgpack/-/msgpack-1.0.2.tgz …
```
=> [node] Fix bad interpretters in node-gyp and some other scripts

.bldr.toml, clang-tools-extra/README.md, clang-tools-extra/plan.sh, clang/README.md, clang/plan.sh, llvm/plan.sh
Everyone ❤️  smaller plans and more modular!
- Changed from `ninja` to `cmake/make` since the former did not allow to build and install parts of the tools.
- `core/llvm` needs to be built first before building `core/clang` and `core/clang-tools-extra`
=> Breakout LLVM and upgrade to 5.0.1

scaffolding-go/plan.sh
Reverts habitat-sh/core-plans#1138
Unfortunately, this change caused plans that depended on the go scaffolding to break.  I tested this with core/dex, when it was pointing to this version of the plan (rather than the previous stable version), it broke with:
```
dex: Layering buildtime environment on top of system environment
dex: go get -d github.com/coreos/dex
/hab/cache/src/go/src/github.com/coreos/dex /src/dex
dex: checking out v2.10.0
/src/dex/plan.sh: line 35: git: command not found
dex: Build time: 0m2s
dex: Exiting on error
```
I believe we need '${pkg_deps[@]}' under 'pkg_deps', rather than 'pkg_build_deps' for plans that depend upon git, etc being present in the go scaffolding.  While we could potentially change the plans depending on the go scaffolding to all require git, …
=> Revert "[scaffolding-go] separating build and run deps"

jdk9/plan.sh
JDK9 does not build anymore, due to source package not available anymore.
This fixes that by updating to 9.0.4 (was 9.0.1)
=> [jdk9] Updates to 9.0.4 (fixes build)

elfutils/plan.sh
This updates elfutils to latest version. Current version does not build in base package refresh (but I don't have the details anymore)
=> [elfutils] Update to 0.170

go14/plan.sh
This is for base package refresh. It works fine with current base packages (the env var isn't used for now)
=> [go14] Fixes build with latest base package

curl-static-musl/plan.sh
The package sources `core/curl` but curl was updated without this one. Thus it failed to build.
=> [curl-static-musl] Fixes package

clingo/plan.sh
This fixes clingo build in stage3 environment.
It should build without problem in current builder (not tested).
=> [clingo] Update to 5.2.2

iproute2/plan.sh
This fixes iproute2 build in stage3 environment.
It should build without problem in current builder (not tested).
=> [iproute2] Update to 4.16.0

e2fsprogs/README.md, e2fsprogs/plan.sh
This fixes e2fsprogs build in stage3 environment.
It should build without problem in current builder (not tested).
=> [e2fsprogs] Updates to 1.44.1

mssql/plan.sh
This fixes #1214 The package location has been changed on ms servers, this is why the build failed.
=> [mssql] Update to 14.0.3025.34-1

.bldr.toml, gnuplot/patches/configure-using-pkgconfig.patch, gnuplot/plan.sh, libcerf/plan.sh, libgd/plan.sh
+ included deps: libgd libcerf
Notes:
- This should not be merged until we discuss how to handle libgd's license; it is not in the SPDX list. I included it, verbatim, in the pkg_license field but, I'm guessing, this is gonna break all sorts of things in all sorts of places. Advice on how to proceed will be much appreciated.
Otherwise, this PR is good to go.
Signed-off-by: Paul Adams <paul@baggerspion.net>
=> New plan: Gnuplot

lynx/ncurses.patch, lynx/plan.sh
This is a backwards compatible change
This fixes #1432 
=> [lynx] Allows build in base refresh

qemu/glibc-2.27.patch, qemu/plan.sh
Also allows the build to work for glibc 2.27
This fixes #1438 (grub builds fine)
=> [qemu] Update to 2.11.1

.bldr.toml, CODEOWNERS, CONTRIBUTING.md, concourse-fly/README.md, concourse-fly/plan.sh
This plan adds the concourse Fly CLI plan to core-plans.
=> add concourse-fly plan

ruby22/plan.sh
Updates Ruby 2.2 to 2.2.10.
Fixes #1436 
This also introduces pinning to make this plan build with the base plans refresh.  Unfortunately, Ruby 2.2 will not work with the latest version of gcc and glibc (which the base packages refresh updates those package to).  As it's an older version of Ruby, it requires older versions of gcc and glibc, so this introduces pinning to those older versions.
Additionally, every dependency that also depends on gcc and glibc must be built with the older versions of those two packages.  Often, when a dependency of a package is updated and the dependent package is rebuilt, the version number of the dependent package is not bumped.  Therefore, for some of the dependencies, I have had to pin to specific timestamps, in most cases the last stable timestamp …
=> updates ruby 2.2 to latest version and pins certain versions of dependencies

rethinkdb/plan.sh
Fixes #1452
According to [this Github issue](https://github.com/rethinkdb/rethinkdb/issues/6536) - rethinkdb only compiles with gcc 5.x or earlier.  As the base plans refresh updates gcc to 7.x, we need to pin rethinkdb to 5.x.  We also need to pin all dependencies built with gcc to the versions that were built with gcc 5.x.
I'm hoping that support for gcc5 will come in the near future.
=> [rethinkdb] fixes rethinkdb for base plans refresh

ttyrec/README.md, ttyrec/plan.sh
TTYREC appears to have not been updated since 2010, which means it needs an older version of glibc.  This pins it to that older version. 
Fixes #1434 
=> [ttyrc] pins ttyrec to older version of glibc

zookeeper/plan.sh
This fixes the build too. (older release removed from upstream)
Closes #1495 
=> [zookeeper] Update to 3.4.12

pax-utils/plan.sh
Fixes #1494 by updating the package (upstream removed the source tarball)
=> [pax-utils] Update to 1.2.3

nginx/plan.sh
This change adds the stream_ssl_module to the nginx configuration, in order to support SSL reverse proxy out of the box - see https://docs.nginx.com/nginx/admin-guide/security-controls/securing-tcp-traffic-upstream/ 
Resolves issue: https://github.com/habitat-sh/core-plans/issues/1502
Signed-off-by: Salim Alam <salam@chef.io>
=> Add stream_ssl_module

.bldr.toml, CODEOWNERS, sqitch_pg/README.md, sqitch_pg/plan.sh
The `core/sqitch` plan is valuable, but requires the inclusion of database-specific perl modules in order to provide a good user experience.  This PR solves that by providing a `core/sqitch_pg` package which wraps sqitch in all the Postgres love. 
Based on the discussion from #1510, supersedes that PR
Signed-off-by: Irving Popovetsky <irving@chef.io>
=> [sqitch_pg] Add the sqitch_pg core plan, which provides sqitch ready to use with PostgreSQL

erlang/plan.sh
Previously, this plan built the crypto.so file shipped in the
crypto package with the following RUNPATH:
```
Library runpath: [/hab/pkgs/core/openssl/1.0.2l/20171014213633/lib/lib:/usr/local/lib64:/usr/sfw/lib64:/usr/lib64:/opt/local/lib64:/usr/pkg/lib64:/usr/local/openssl/lib64:/usr/lib/openssl/lib64:/usr/openssl/lib64:/usr/local/ssl/lib64:/usr/lib/ssl/lib64:/usr/ssl/lib64://lib64:/usr/local/lib:/usr/sfw/lib:/usr/lib:/opt/local/lib:/usr/pkg/lib:/usr/local/openssl/lib:/usr/lib/openssl/lib:/usr/openssl/lib:/usr/local/ssl/lib:/usr/lib/ssl/lib:/usr/ssl/lib://lib:/hab/pkgs/core/erlang/20.0/20171014214153/lib:/hab/pkgs/core/glibc/2.22/20170513201042/lib:/hab/pkgs/core/zlib/1.2.8/20170513201911/lib:/hab/pkgs/core/ncurses/6.0/20170513213009/lib:/hab/pkgs/core/openssl/1.0.2l/20171014213633/lib] …
```
=> [erlang] Fix erroneous RUNPATH on crypto.so

boringssl/plan.sh
Since Google doesn't have a release of their openssl fork we are forced to pull from a branch. Unfortunately, there are commits going into the branches which causes shasum validation to fail.
=> Remove sha validation on boringssl

.bldr.toml, envoy/README.md, envoy/plan.sh
Let me start out with apologizing for how gross this plan is.
Envoy doesn't publish binaries that I could find and the Bazel build proved too difficult for my mere mortal abilities.
So, that led me to download the dockerfile they publish to extract the envoy binary, then patch it.
=> Add Envoy plan

consul/default.toml, consul/hooks/run
Signed-off-by: qubitrenegade <qubitrenegade@gmail.com>
This commit adds an environment variable to easily toggle the new beta WebUI that ships with consul 1.1.0
Since this is a beta feature, defaults to off or the old WebUI.
See [Consul Docs](https://www.consul.io/intro/getting-started/ui.html#how-to-use-the-new-ui) for complete details.
=> Add option to enable beta webui in consul plan

elasticsearch/plan.sh
in #1209 we swapped out a dependency on `core/busybox-static` for
`core/coreutils-static` because of a behavior change in elasticsearch
that didn't support busybox. little did we know, `busybox-static` was
also providing the `wget` binary, so now we're relying on a binary in
the `health_check` that we don't have a hard dependency on
Signed-off-by: Stephen Delano <stephen@chef.io>
=> elasticsearch: depend on wget for health_check

consul/config/basic_config.json, consul/hooks/run
This change adds the `-retry-join` parameter to add each _alive_ member of the service pool to the run command to allow consul to discover its peers using the built-in habitat gossip layer.
This resolves #1524
=> Enable Consul to autodiscover peers based on service group

dotnet-47-dev-pack/plan.ps1, dotnet-471-dev-pack/plan.ps1, dotnet-472-dev-pack/plan.ps1
New plans reference and override dotnet-47-dev-pack
Changed dotnet-47-dev-pack upstream URL to be more generic
=> [dotnet-dev-pack] Addded plans for dotnet-471-dev-pack and dotnet-472-dev-pack

popt/plan.sh
The DNS registration for the specified `pkg_source` has expired, blocking builds.  This changes the source_url to the Linux From Scratch mirror of popt. 
=> [popt] Update source_url & fix variable name

consul/hooks/reload, consul/hooks/run, consul/plan.sh
Refs #1467 
- Change user to hab (from root)
- change bash to sh
- reload hook output redirection
- and some cleanup
Testing this change manually is simple.
```
hab svc load core/consul
```
Watch the log output, confirm its listening / started.
=> [Consul] Change user to hab (from root)

vault/plan.sh
Another simple update, taking the plan to Vault version 0.10.2. 
=> [Vault] Updated plan to Vault 0.10.2

rust/plan.sh
This change ensure that the following additional ELF binaries get
patched:
- `cargo-fmt`
- `rls`
- `rustfmt`
Additionally, this change adds a comment which captures why the `cargo`
binary gets wrapped with a small shell script, and why it should remain.
Closes #1576
=> [rust] Patch additional ELF binaries in Rust package.

sqlserver-ha-ag/hooks/init, sqlserver-ha-ag/hooks/run
Found that on AWS, as opposed to azure, machines went into a pending reboot state after enabling failover clustering. Rebooting resolves this.
This also ensures that we use the domain of the computer and not the current user when adding the secondary node logins and it creates an empty database on the primary node if the configured db does not exist.
=> [sqlserver-ha-ag] Impovements to sql HA plan based on customer engagement

python/plan.sh
This upgrades the version of python in the python plan. I ran a test build on hab 0.56.0 with no issues.
Also fixes a minor linking issue where the pkg_interpreters was still pointing to bin/python3.5
=> upgrade version of python

.bldr.toml, CODEOWNERS, filebeat/README.md, filebeat/config/filebeat.yml, filebeat/default.toml, filebeat/plan.sh
New plan for filebeat, optional bindings for Kibana and Elasticsearch.
Filebeat collects and ships logs, from Elastic.co
=> [Filebeat] Added new plan for filebeat

.bldr.toml, libfcgi/README.md, libfcgi/plan.sh, libfcgi/stdio.patch
The binary is this package is useful for health checking a FastCGI application without a web server running: https://easyengine.io/tutorials/php/directly-connect-php-fpm/
Here's how you might use it in the `health_check` hook for a PHP-FPM application:
```bash
#!/bin/bash -e
{{#if cfg.path.ping}}
SCRIPT_NAME="{{ cfg.path.ping }}" \
SCRIPT_FILENAME="{{ cfg.path.ping }}" \
REQUEST_METHOD="GET" \
{{pkgPathFor "core/libfcgi"}}/bin/cgi-fcgi \
-bind \
-connect {{ sys.ip }}:{{ cfg.network.port }} \
| grep pong
{{/if}}
```
=> [libfcgi] Add libfcgi

libgcrypt/README.md, libgcrypt/plan.sh
References:
* http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-0495
* https://access.redhat.com/security/cve/cve-2018-0495
=> [libgcrypt] Version bump to 1.7.10 to address CVE-2018-0495

php/plan.sh, php5/plan.sh
This one is my bad...didn't notice until now that PHP isn't explicitly pulling readline into its runtime env
=> [php*] Move readline to runtime deps and bump php5 to 5.6.35

git/plan.sh
Reference:
* https://nvd.nist.gov/vuln/detail/CVE-2018-11235
Affected versions:
* 2.13.x before 2.13.7
* 2.14.x before 2.14.4
* 2.15.x before 2.15.2
* 2.16.x before 2.16.4
* 2.17.x before 2.17.1
=> [git] Minor version bump for CVE-2018-11235

CODEOWNERS, postgresql-client/plan.sh, sqitch/plan.sh
The `postgresql-client` package stripped out the `pg_config` binary, which impacts Sqitch's ability to determine information about the version and location of Postgres it is talking to.  This PR corrects that, while also improving the sqitch plan to push PERL5LIB to the runtime_env.
also adds this plan to CODEOWNERS
Fixes #1572 
Signed-off-by: Irving Popovetsky <irving@chef.io>
=> [postgresql-client] Fix sqitch_pg and dbdpg building against postgresql-client, they depend on pg_config.

rabbitmq/hooks/reconfigure
bash will want `SIGTERM`, sh wants to see `TERM`.
Fixes #1583 
=> [rabbitmq] Fix reconfigure hook for sh

scaffolding-node/lib/scaffolding.sh, scaffolding-node/plan.sh
Fixes #1613 
Also addresses issue where windows node packages are taken into account on Linux, and can result in a "Package Not Found" error if the latest Windows package is newer than latest Linux package. 
=> [scaffolding-node] Update scaffolding-node to handle double-digit version constraints.

postgresql93-client/plan.sh, postgresql94-client/plan.sh, postgresql95-client/plan.sh
Fixes #1596 and aligns the 9X-client packages with the postgresql-client package. 
=> Update postgresql9X-client plans to include pg_config

libsodium/plan.sh
libsodium uses the ISC license
=> [libsodium] Use the SPDX license identifier

mc/plan.sh
Testing:
```
cd mc; build; source results/last_build.env; hab pkg install --binlink results/${pkg_artifact};
mc
```
You will see Midnight Commander open.
=> [mc] Update to 4.8.21, prefer xz tarball

sqlserver/hooks/init
On a clean node, the nuget provider must be installed before installing modules from the powershell gallery.
=> [sqlserver] add nuget provider download

jre8/plan.ps1
This ensures that the jre binaries are confined to `\hab\pkgs` and there are no OS side effects involved in installing the package.
Would love to know if this continues to work for @skylerto 
=> [jre8] make the windows jre plan portable

logstash/plan.sh
```
cd logstash
hab pkg install core/busybox-static --binlink
ps | grep logstash
```
Confirm logstash is running and port is open (owned by java).
=> [logstash] update to 6.3.1

postfix/plan.sh
```
nc -z localhost 25
echo 'EHLO localhost' | nc localhost 25
> 220 localhost ESMTP Postfix
> 250-localhost
> 250-PIPELINING
> 250-SIZE 10240000
> 250-VRFY
> 250-ETRN
> 250-ENHANCEDSTATUSCODES
> 250-8BITMIME
> 250 DSN
```
=> [postfix] Version bump to 3.3.1, fix path problem

jenkins/README.md, jenkins/plan.sh
```
HAB_DOCKER_OPTS="-p 10080:80" hab studio enter
sl
hab pkg binlink core/busybox-static ifconfig
IP_ADDRESS=$(ifconfig eth0 | grep 'inet addr' | awk -F'[: ]+' '{print $4}')
nc -z ${IP_ADDRESS} 80
```
For reference, the admin password/unlock code in supervisor logs looks like this:
```
jenkins.default(O): *************************************************************
jenkins.default(O): *************************************************************
jenkins.default(O): …
```
=> [jenkins] Upgrade to 2.121.1

memcached/README.md, memcached/plan.sh
```
hab pkg install core/busybox-static --binlink
nc -z localhost 11211
echo 'stats' | nc localhost 11211
```
=> [memcached] Upgrade to 1.5.9, add readme

mongodb/plan.sh
Fix mongodb linking. Fixes #1647 
cc: @scottvidmar @smacfarlane 
```
hab pkg binlink ${pkg_ident} mongos
hab pkg binlink ${pkg_ident} mongo
hab pkg binlink ${pkg_ident} mongod
hab pkg binlink ${pkg_ident} mongoperf
mongod --version
mongos --version
mongo --version
mongoperf -h
```
```
[19][default:/src:130]# mongos --version
mongos version v3.6.4
git version: d0181a711f7e7f39e60b5aeb1dc7097bf6ae5856
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
allocator: tcmalloc
modules: none
build environment:
distarch: x86_64
target_arch: x86_64
[20][default:/src:0]# mongo --version
MongoDB shell version v3.6.4
git version: …
```
=> [mongodb] Fix mongodb linking

hugo/plan.sh
```
hugo version
```
```
Hugo Static Site Generator v0.43 linux/amd64 BuildDate: 2018-07-09T10:00:08Z
```
=> [hugo] Version up to 0.43

.bldr.toml, CODEOWNERS, gocd-server/README.md, gocd-server/default.toml, gocd-server/hooks/run, gocd-server/plan.sh
```
HAB_DOCKER_OPTS="-p 8153:8153" hab studio enter
build; source results/last_build.env; hab pkg install results/${pkg_artifact}; hab svc load ${pkg_ident}
nc -z localhost:8153
```
Finally, if you did enable the port forwarding, you can browse to GoCD server via: http://localhost:8153
=> [gocd-server] New package - GoCD Server

.bldr.toml, alex/README.md, alex/plan.sh, cabal-install/README.md, cabal-install/plan.sh, happy/README.md, happy/plan.sh
- Added cabal-install
- Added alex
- Added happy
This is dependent on #616 
This progresses #615 
=> Added Haskell Standard Tooling

.bldr.toml, shellcheck/README.md, shellcheck/plan.sh
This is dependent on #616 and #1665 
=> Added shellcheck plan

CODEOWNERS
=> Added @wduncanfraser as codeowner for haskell packages

consul/default.toml, consul/hooks/run, consul/plan.sh
```
build; source results/last_build.env; hab pkg install results/${pkg_artifact}; hab svc load ${pkg_ident}
netstat -peanut | grep consul
```
```
tcp        0      0 127.0.0.1:8300          0.0.0.0:*               LISTEN      203/consul
tcp        0      0 127.0.0.1:8301          0.0.0.0:*               LISTEN      203/consul
tcp        0      0 127.0.0.1:8302          0.0.0.0:*               LISTEN      203/consul
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN      203/consul
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      203/consul
udp        0      0 127.0.0.1:8600          0.0.0.0:* …
```
=> [consul] Update to 1.2.1, Allow legacy UI

.bldr.toml, unixodbc/README.md, unixodbc/plan.sh
Added binary plan for unixodbc
I've built and compiled haskell projects against this that depends on the libs and headers.
Still working out usage details as far as driver management. You can set the path to your ODBC config files using env variables ODBCINI and ODBCSYSINI, so you can bundle your ODBC config with your app/service that depends on unixODBC.
=> [unixodbc] Added plan for unixodbc

.bldr.toml, freetds/README.md, freetds/plan.sh
Added binary plan for freetds
This depends on #1678 
I've built compiled haskell projects against this that depends on the libs and headers.
Still working out usage details as far as driver/config management, similar to the unixODBC PR.
=> [freetds] Added plan for freetds

mongodb/config/mongod.conf, mongodb/default.toml
MongoDB deprecated the settings for the REST interface in MongoDB 3.2 and officially removed them in MongDB 3.6.  The settings remained in the `config/mongod.conf` file causing the service to fail at start up.  This commit removes the `net.http` settings related to the REST interface to allow proper startup of MongoDB 3.6
See #1677
=> [mongodb] Remove deprecated settings from mongod.conf

hugo/plan.sh
```
hugo version
```
```
Hugo Static Site Generator v0.44 linux/amd64 BuildDate: 2018-07-13T06:03:11Z
```
=> [hugo] Update hugo to 0.44

scaffolding-chef/lib/scaffolding.sh
Updating scaffolding-chef to no longer attempt an initial chef-run in the init hook. Performing a potentially long-running chef-run there can cause the supervisor to hang.
=> Remove chef-run in init hook

gnatsd/config/default.conf, gnatsd/default.toml, gnatsd/plan.sh
This PR adds config files for gnatsd as well as exporting the gnatsd and nats-http ports.  The config file was sourced from https://nats.io/documentation/server/gnatsd-config/ and the clustering section has been removed.
=> [gnatsd] added config files for gnatsd

.bldr.toml, python/plan.sh, python2/README.md, python2/plan.sh, python34/README.md, python34/plan.sh, python35/README.md, python35/plan.sh, python36/README.md, python36/plan.sh, python37/README.md, python37/plan.sh
- Rolled python version forward to 3.7.0
- Broke out major versions of python in accordance with RFC 0003
General plan updates
- Build python with system libffi (This was required for 3.7 to build properly)
- Build python with system expat
- Removed idle since it isn't usable without tk/x11
Some TODOs/Questions:
It would make sense to compile with optimizations. This takes build time from 5 minutes up to ~40. Do others agree?
Should python2 be renamed to python27 in accordance with RFC 0003. Or since it is the only remaining python 2 version in support, does it make sense to leave it as python2? If we should rename, the python2 packages/namespace would need to be deprecated per RFC 0007.
=> [python] Updated python for rfc 0003

packer/plan.sh
```
build; source results/last_build.env; hab pkg install ${pkg_ident} --binlink;
packer --version
packer help
$ packer --version
1.2.5
$ packer help
Usage: packer [--version] [--help] <command> [<args>]
Available commands are:
build       build image(s) from template
fix         fixes templates from old versions of packer
inspect     see components of a template
push        push a template and supporting files to a Packer build service
validate    check that a template is valid
version     Prints the Packer version
```
=> [packer] Update packer to 1.2.5

libpng/plan.sh
Add testing and upgrade
```
DO_CHECK=1 build
============================================================================
Testsuite summary for libpng 1.6.35
============================================================================
============================================================================
```
=> [libpng] Update libpng to 1.6.35

node/plan.sh
This is a strange one.
We already have 8.11.3 in `core/node8`, but it was never updated in `core/node`. This aligns the two to the same version.
=> [node] Update core/node to 8.11.3 for consistency with core/node8

dgraph-ratel/README.md, dgraph-ratel/plan.sh
This plan was already in the .bldr.toml but there wasn't actually a plan for it :joy:
Also, bump the version for dgraph.
=> Add dgraph-ratel plan

cmake/plan.sh
`cmake` requires special flags to be able to find system libraries for `core/curl` and `core/zlib`.
Since we're including them as build deps, this commit adds the necessary flags for `cmake` to use `core/curl` and `core/zlib` libraries.
Additionally, this resolves #1689.
=> [cmake]  Build cmake against `core/curl` and `core/zlib` libraries

.bldr.toml, node/plan.sh, node10/README.md, node10/plan.sh
Should be merged after #1711 which adds node 10 to the common `core/node` plan.
=> [node10] New plan - node10

.bldr.toml, protobuf/README.md, protobuf/plan.sh, protobuf2/README.md, protobuf2/plan.sh
Our `core/protobuf` package was pretty old; this brings it back up to date with the current release.
I've verified this by generating some protobuf-based code over in the Habitat repo.
=> [protobuf] Update to version 3.6.0

caddy/README.md, caddy/config/Caddyfile, caddy/default.toml, caddy/plan.sh
```
HAB_DOCKER_OPTS="-p 18080:8080" hab studio enter
sl
hab pkg binlink core/busybox-static ifconfig
IP_ADDRESS=$(ifconfig eth0 | grep 'inet addr' | awk -F'[: ]+' '{print $4}')
nc -z ${IP_ADDRESS} 8080
echo '<h1>Hello Habitat, via Caddy!</h1>' > /hab/svc/${pkg_name}/data/index.html
```
=> [caddy] Update caddy to v0.11.0 and enable service!

php/plan.sh
```
php -r "echo phpinfo(INFO_MODULES);"
```
```
phpinfo()
Core
PHP Version => 7.2.7
Directive => Local Value => Master Value
allow_url_fopen => On => On
allow_url_include => Off => Off
arg_separator.input => & => &
arg_separator.output => & => &
auto_append_file => no value => no value
auto_globals_jit => On => On
auto_prepend_file => no value => no value
browscap => no value => no value
default_charset => UTF-8 => UTF-8
default_mimetype => text/html => text/html
disable_classes => no value => no value
disable_functions => no value => no value
display_errors => STDOUT => STDOUT
display_startup_errors => Off => Off
doc_root => no value => no value …
```
=> [php] Update to PHP 7.2.7

scaffolding-chef/lib/scaffolding.sh
By default, the chef scaffolding will wait for ```cfg.interval``` seconds before performing the initial chef-client run in the run hook. This change makes it perform an initial chef-client run without waiting, and then hand over to the chef-client with interval and splay configured going forwards.
Signed-off-by: Jon Cowie <jonlives@gmail.com>
=> Add initial chef-client run with no splay or interval

strace/plan.sh
```
strace strace
```
```
execve("/hab/bin/strace", ["strace"], 0x7ffe9f9626f0 /* 14 vars */) = 0
brk(NULL)                               = 0x1166000
access("/hab/pkgs/core/glibc/2.27/20180608041157/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/hab/pkgs/rakops/strace/4.23/20180725025254/lib/tls/x86_64/x86_64/librt.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/hab/pkgs/rakops/strace/4.23/20180725025254/lib/tls/x86_64/x86_64", 0x7fff5060f330) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/hab/pkgs/rakops/strace/4.23/20180725025254/lib/tls/x86_64/librt.so.1", …
```
=> [strace] Update strace to 4.23

rabbitmq/plan.sh
Run with `DO_CHECK=1` set.
```
DO_CHECK=1 build; source results/last_build.env; hab pkg install results/${pkg_artifact}; hab svc load ${pkg_ident};
sl
```
```
hab-sup(MR): Supervisor Member-ID 4d9f8a6e97224a228ea615c5999d9d36
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting ctl-gateway on 127.0.0.1:9632
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
hab-sup(AG): The rakops/rabbitmq/3.7.7/20180725044148 service was successfully loaded
hab-sup(MR): Starting rakops/rabbitmq/3.7.7/20180725044148
rabbitmq.default(UCW): Watching user.toml
rabbitmq.default(HK): health_check, compiled to /hab/svc/rabbitmq/hooks/health_check
rabbitmq.default(HK): reconfigure, compiled to /hab/svc/rabbitmq/hooks/reconfigure …
```
=> [rabbitmq] Update RabbitMQ to 3.7.7

etcd/plan.sh
```
build; source results/last_build.env; hab pkg install results/${pkg_artifact}; hab svc load ${pkg_ident}
sl
netstat -pelnut | grep etcd
```
```
--> Tailing the Habitat Supervisor's output (use 'Ctrl+c' to stop)
etcd.default(O): 2018-07-25 02:32:14.050153 I | raft: b16aadee8296ea55 became candidate at term 2
etcd.default(O): 2018-07-25 02:32:14.050212 I | raft: b16aadee8296ea55 received MsgVoteResp from b16aadee8296ea55 at term 2
etcd.default(O): 2018-07-25 02:32:14.050253 I | raft: b16aadee8296ea55 became leader at term 2
etcd.default(O): 2018-07-25 02:32:14.050279 I | raft: raft.node: b16aadee8296ea55 elected leader b16aadee8296ea55 at term 2 …
```
=> [etcd] Update etcd to 3.3.9

rabbitmqadmin/plan.sh
Testing of this requires a RabbitMQ server up. Use the core/rabbitmq to load up, and change settings:
```
build; pkg_origin=rakops; hab pkg install results/${pkg_artifact} --binlink; 
hab pkg install core/python2 --binlink
rabbitmqadmin --help
```
=> [rabbitmqadmin] Update RabbitMQ Admin to 3.7.7

hugo/plan.sh
```
hugo version
```
```
Hugo Static Site Generator v0.45.1 linux/amd64 BuildDate: 2018-07-25T08:56:24Z
```
=> [hugo] Update hugo to 0.45.1

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
The initial chef-client run performed in the run hook of scaffolding-chef is missing the --once option, which makes it continue running without interval and splay. This commit fixes that.
Signed-off-by: Jon Cowie <jonlives@gmail.com>
=> [scaffolding-chef] Add --once option to initial run in chef scaffolding

filebeat/plan.sh
Filebeat has a runtime dependency on `ld-linux-x86-64.so.2` which is provided by  core/glibc.
=> [Filebeat] Add runtime glibc dep to filebeat

dep/plan.sh
```
dep version
```
```
dep:
version     : v0.5.0
build date  : 2018-07-27
git hash    : 224a564a
go version  : go1.10.1
go compiler : gc
platform    : linux/amd64
features    : ImportDuringSolve=false
```
=> [dep] Update golang dep to 0.5.0

consul/plan.sh, consul/test.sh
This does a minor upgrade (addresses security/bugfixes in consul). But also adds testing.
```
cd consul
./test.sh
```
```
---------------------------------------
Test Output
---------------------------------------
Pass ... Listening on tcp/8300
Pass ... Listening on tcp/8301
Pass ... Listening on tcp/8302
Pass ... Listening on tcp/8500
Pass ... Listening on tcp/8600
Pass ... Listening on udp/8301
Pass ... Listening on udp/8302
Pass ... Listening on udp/8600
```
=> [consul] Update consul to 1.2.2, and add testing

.bldr.toml, sbt/README.md, sbt/plan.sh
Add a plan for Scala build tool `sbt`.
[plan in bldr](https://bldr.habitat.sh/#/pkgs/afiore/sbt/1.1.6/20180731063806)
Other implementations, like [cvasquez/sbt](https://bldr.habitat.sh/#/pkgs/cvasquez/sbt/latest) didn't require `core/bash`, `core/grep` and `core/sed`. These are all used by sbt's bootstrapping, so I thought to add them as run-time dependencies. 
Signed-off-by: Andrea Fiore <andrea.giulio.fiore@gmail.com>
=> [sbt] add new plan using version 1.1.6

node/plan.sh, node10/plan.sh
```
node --version
```
```
v10.8.0
```
Combined node and node10 into the same PR as they're approved by the same people.
=> [node/node10] Update NodeJS to 10.8.0

redis3/plan.sh, redis4/plan.sh
```
unalias grep egrep fgrep
echo '
requirepass="password"
' | hab config apply redis3.default $(date +%s)
NETSTAT_RESULT=$(netstat -peanut | grep redis-server)
if [ $(echo "${NETSTAT_RESULT}" | wc -l) -eq 2 ]; then printf "Pass"; else printf "FAIL"; fi; echo " - Redis is listening"
for i in {0..24}; do redis-cli -a password incr habitat-test-key > /dev/null; done
REDIS_RESULT=$(redis-cli -a password get habitat-test-key)
if [ $(echo "${REDIS_RESULT}") -eq 25 ]; then printf "Pass"; else printf "FAIL"; fi; echo " - Basic Redis functionality"
hab svc unload …
```
=> [redis3] Update redis to 3.2.12

.bldr.toml, leproxy/README.md, leproxy/plan.sh
New plan for leproxy (Lets Encrypt Proxy).
```
leproxy -version
```
Running the above test will show command usage.
=> [leproxy] Add new plan for leproxy

.bldr.toml, mage/README.md, mage/plan.sh
Adding mage, for magefile / golang builds.
Testing just with a simple version check:
```
mage --version
```
```
Mage Build Tool 2.1
Build Date: 2018-08-08T06:14:44Z
Commit: 771ebed
```
=> [mage] New plan: mage

zookeeper/plan.sh
```
build; source results/last_build.env; hab pkg install results/${pkg_artifact}
netstat -peanut | grep java
```
```
tcp        0      0 0.0.0.0:34573           0.0.0.0:*               LISTEN      962/java
tcp        0      0 0.0.0.0:2181            0.0.0.0:*               LISTEN      962/java
```
=> [zookeeper] Update zookeeper to 3.4.13

zsh/plan.sh
Note: Previous builds don't pass any tests.
This improves, with a strange `echo` failure, but still working fine. Improvement, but not perfect on the testing front:
```
DO_CHECK=1 build
```
Old output:
```
**************************************
0 successful test scripts, 48 failures, 0 skipped
**************************************
```
New output:
```
**************************************
49 successful test scripts, 2 failures, 0 skipped
**************************************
```
=> [zsh] Update to zsh 5.5.1, fix tests

hugo/plan.sh
This requires #1769 before it can be merged.
Allows cacerts to be used from patched go source.
This is required for shortcodes like `{{< twitter >}}` in hugo content.
The test for this is just checking the version, unless you want to create a full site that tests the cacerts usage. Fortunately, I have done that!
Here's the previous core/hugo **failing**: https://bldr.habitat.sh/#/pkgs/grahamweldon/grahamweldon-website/builds/1043869293629317120
Here's the modified one (as rakops/hugo) **passing**: https://bldr.habitat.sh/#/pkgs/grahamweldon/grahamweldon-website/builds/1043939221711544320
=> [hugo] Change to build hugo from source

openresty/plan.sh
```
build; source results/last_build.env; hab pkg install results/${pkg_artifact}; hab svc load ${pkg_ident}
```
```
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      12304/nginx.conf
```
=> Openresty update to 1.13.6.1

lessmsi/plan.ps1
```
build
hab pkg exec core/lessmsi lessmsi h
```
Windows build is uploaded, needs to be set to stable after approval/merge : https://bldr.habitat.sh/#/pkgs/core/lessmsi/1.6.1/20180810160745
=> [lessmsi] Update lessmsi to 1.6.1

bzip2/plan.sh
bzip.org domain name expired. Switch to an unofficial github mirror until bzip.org is back online.
checksums match on the tarball so we can be reasonably confident that it is the same file.
=> Update pkg_source for bzip2

node/plan.ps1, node10/plan.ps1, node6/plan.ps1
Discovered when testing node on Windows that I could only build the plan once, files were not being cleaned up that needed to be and I was receiving errors.  This fixes those issues.
```
build node
hab pkg exec core/node node --version
build node6
hab pkg exec core/node6 node --version
build node10
hab pkg exec core/node10 node --version
```
=> [Node] windows enhancements

memcached/plan.sh
```
hab pkg binlink core/busybox-static telnet
build; source results/last_build.env; hab svc load ${pkg_ident}
netstat -alpn | grep LISTEN | grep memcached
```
```
tcp        0      0 0.0.0.0:11211           0.0.0.0:*               LISTEN      2969/memcached
```
```
$ telnet localhost 11211
set greeting 1 0 11
Hello world
STORED
END
ERROR
quit
Connection closed by foreign host
$ telnet localhost 11211
get greeting
VALUE greeting 1 11
Hello world
END
quit
Connection closed by foreign host
```
=> [memcached] Update memcached to 1.5.10

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
Currently the `chef-client` run with `--once` will exit the run hook after completion.
This results in the Supervisor continuously running `chef-client` and never running it
with the configured interval and splay times.
In the generated `default.toml` file the `data_collector.enable` property is set to a string `"false"` which evaluates to true.
This PR resolves both issues by removing `exec` so the shell isn't replaced by the `chef-client` process, and changing the generated `default.toml`.
Fixes #1775.
=> [scaffolding-chef] don't use exec to run chef-client and fix a configuration issue

sensu/Gemfile, sensu/config/config.json, sensu/config/server.json, sensu/default.toml, sensu/hooks/run, sensu/plan.sh
Fixes #1743 
```
echo '
default_vhost = "/sensu"
default_user = "sensu"
default_pass = "sensu"' | hab config apply rabbitmq.default $(date +%s)
echo '
protected-mode = "no"' | hab config apply redis.default $(date +%s)
echo 'log_level="debug"' | hab config apply sensu.default $(date +%s)
hab svc load core/rabbitmq
hab svc load core/redis
build; source results/last_build.env; hab pkg install results/${pkg_artifact}
hab svc load ${pkg_ident} --bind rabbitmq:rabbitmq.default --bind redis:redis.default
netstat -p | grep ESTABLISHED | grep ruby | grep 6379 > /dev/null
if [ $? -ne 0 ]; then echo "FAILED: No connection to Redis"; else echo "PASS: Redis connected"; fi
netstat -p | grep ESTABLISHED | grep ruby | grep …
```
=> [sensu] security updates

strace/plan.sh, strace/test.bats, strace/test.sh
Adds some testing, requires bats.
```
./test.sh
```
```
✓ Can strace
```
=> [strace] Update strace to 4.24, add testing

terraform/plan.sh, terraform/test.bats, terraform/test.sh
* Upgrade version
* Add testing with bats
Testing is evolving each time I add some. This adds a simple filter to skip the actual build. This is super handy when you're in the process of building out tests for something that takes a long time to build, or something that is already built.
```
./test.sh
```
```
```
=> [terraform] Update terraform to 0.11.8, add testing

docutils/README.md, docutils/plan.sh
This includes python2 as a runtime dep for the docutils package.
=> [docutils] Move core/python2 to pkg_deps from pkg_build_deps.  Fixes #1780

docutils/plan.sh
The version of docutils in `core/docutils` is really really really really old (the last commit was July 2014).
This commit bumps the version of `core/docutils` to the current v14.
This depends on #1781 and may need to be rebased...?  I had already done the work so wanted to get the PR submitted while I was thinking about it.
=> [docutils] Bump version of package to current

ps-lock/PSLock.psd1
There is nothing in this module that depends on ps v6. Ran into someone who wanted to use this outside of habitat but did not want to be in v6.
=> [ps-lock] lift powershell version restriction

jenkins/plan.sh
Fixes #1806
```
HAB_DOCKER_OPTS="-p 10080:80" hab studio enter
sl
hab pkg binlink core/busybox-static ifconfig
IP_ADDRESS=$(ifconfig eth0 | grep 'inet addr' | awk -F'[: ]+' '{print $4}')
nc -z ${IP_ADDRESS} 80
```
=> [jenkins] Update to 2.121.3 - Security updates

kubernetes-apiserver/plan.sh, kubernetes-controller-manager/plan.sh, kubernetes-kubelet/plan.sh, kubernetes-proxy/plan.sh, kubernetes-scheduler/plan.sh, kubernetes/plan.sh
This PR updates the following packages to version 1.11.2
- kubernetes
- kubernetes-apiserver
- kubernetes-controller-manager
- kubernetes-kubelet
- kubernetes-proxy
- kubernetes-scheduler
**Testing:**
The packages have been built and uploaded to builder with `kosy` as the package origin.
**Prerequisites**
* Linux or MacOS on the host (Windows is not supported)
* [Vagrant](https://www.vagrantup.com/downloads.html)
* [Virtual Box](https://www.virtualbox.org/wiki/Downloads)
* [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/)
* [cfssl](https://github.com/cloudflare/cfssl#installation) (with cfssljson)
* [jq](https://stedolan.github.io/jq/download/) Command-line JSON processor
**Steps**
```
$ git clone https://github.com/kinvolk/kubernetes-the-hab-way.git
$ sed -i …
```
=> [kubernetes] Upgrade to k8s 1.11.2

CODEOWNERS, MAINTAINERS.md
I'd like to add myself to maintainers for core-plans, along with as a CODEOWNER of openssl.
=> add echohack to maintainers

nginx/plan.sh, nginx/test.bats, nginx/test.sh
Testing:
```
cd nginx
./test.sh
```
Sample output:
```
✓ Help command
```
=> [nginx] Upgrade nginx to 1.15.3, add tests

vault/plan.sh, vault/test.bats, vault/test.sh
Testing:
```
cd vault
./test.sh
```
Sample output:
```
✓ Help command
```
=> [vault] Upgrade to 0.11.1

dex/plan.sh
https://github.com/dexidp/dex/releases/tag/v2.11.0
This includes a change of the repository.
=> [dex] bump v2.10.0 -> v2.11.0

packer/plan.sh
```
build packer
packer --version
```
```
1.3.0
```
=> [packer] Update packer to 1.3.0

node8/plan.sh
```
build node8
node --version
```
```
v8.12.0
```
=> [node8] Update node8 to 8.12.0

postgresql/config/functions.sh, postgresql93/plan.sh, postgresql94/config/functions.sh, postgresql94/plan.sh, postgresql94/tests/extra_data_files.bats, postgresql94/tests/test.bats, postgresql94/tests/test.sh, postgresql95/plan.sh, postgresql96/plan.sh, postgresql96/tests/extra_data_files.bats, postgresql96/tests/test.bats, postgresql96/tests/test.sh
If you mount the data volume for postgres (e.g. via k8s) there will be
the usual `lost+found` directory owned by root.  We were trying to chown
it, failing and then postgres wouldn't start.
This PR changes the permissions setting logic in the init hook to only
cheange the permissions on the 2 data directories we create (`pgdata`
and `archive`)
Testing
```
cd postgresql96
./tests/tests.sh
```
Exact same process works for `postgresql94` too.
Sample output
```
✓ Non-hab owned files in /data are allowed
✓ Version matches, via --version
✓ Listening on port 5432
```
Signed-off-by: James Casey <james@chef.io>
=> [postgresql] Only chown data directories we create

.bldr.toml, libsasl2/README.md, libsasl2/plan.sh
Refs #1808
Testing is tricky, as its a library.
```
build libsasl2
hab pkg install results/${pkg_artifact}
```
Confirm that the libraries are available:
```
ls -la /hab/pkgs/${pkg_ident}/lib/
```
```
-rwxr-xr-x 1 root root    833 Sep 14 00:22 libsasl2.la
lrwxrwxrwx 1 root root     17 Sep 14 00:22 libsasl2.so -> libsasl2.so.3.0.0
lrwxrwxrwx 1 root root     17 Sep 14 00:22 libsasl2.so.3 -> libsasl2.so.3.0.0
-rwxr-xr-x 1 root root 139248 Sep 14 00:22 libsasl2.so.3.0.0
drwxr-xr-x 2 root root   4096 Sep 14 00:22 pkgconfig
drwxr-xr-x 2 root root   4096 Sep 14 00:22 sasl2
```
=> [libsasl2] New plan for libsasl2

memcached/plan.sh, memcached/tests/test.bats, memcached/tests/test.sh
Fixes #1808 
**Note:** This PR requires that #1849 is merged, built and promoted first.
```
./memcached/tests/test.sh
```
```
✓ Help command
```
=> [memcached] Added SASL support to memcached, and added tests

packer/plan.sh, packer/tests/test.bats, packer/tests/test.sh
```
./packer/tests/test.sh
```
```
```
=> [packer] Upgrade packer to 1.3.1, add simple test

libsodium/plan.sh
This updates the download URL
Signed-off-by: Scott Hain <shain@chef.io>
=> Libsodium moved 1.0.13 source to the 'old' directory

gocd-server/plan.sh
Testing from #1671 are the same:
```
HAB_DOCKER_OPTS="-p 8153:8153" hab studio enter
build gocd-server; source results/last_build.env; hab pkg install results/${pkg_artifact}; hab svc load ${pkg_ident}
nc -z localhost:8153
```
=> [gocd-server] Upgrade gocd to 18.9.0

scaffolding-node/lib/scaffolding.sh
Ref: habitat-sh/habitat#5646
This ensures that /usr/bin is created before attempting to symlink into it. 
=> [scaffolding-node] Add mkdir -p before symlink

dsc-core/DSCCore.psm1, dsc-core/plan.ps1
If a DSC Apply fails, the reseting of the LCM refresh state may fail because the LCM is still busy. This adds a wait for it to be available before changing its refresh state. Validated this with user.
=> [dsc-core] wait for LCM before changing LCM refresh state

scaffolding-ruby/CHANGELOG.md, scaffolding-ruby/lib/scaffolding.sh, scaffolding-ruby/plan.sh
This commit ensures that the `_bundler_version` variable is set only
to the version as returned by the `bundle --version` command. Bundler
itself does not differentiate error and warning messages to STDERR, so
if there are problems such as a non-extistent $HOME directory, those
messages aren't partially captured in this output.
See habitat-sh/habitat#5569 for background.
Example of warning output:
```
> bundler --version
`/root` is not a directory.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
Bundler version 1.16.2
```
Which the previous code would parse and set `_bundler_version` to:
```
directory.
temporarily.
1.16.2.gem
```
This breaks the attempt to `gem install --local "$(pkg_path_for bundler)/cache/bundler-${_bundler_version}.gem" ...` in …
=> [scaffolding-ruby] ensure bundler version is the version number

README_TEMPLATE_FOR_PLANS.md
I think it should read "for example", not "that is".
Signed-off-by: David Somers-Harris <david@somers-harris.com>
=> e.g. not i.e.

hugo/plan.sh
`core/glibc` is dynamically linked in the hugo binary and needs to be added to `pkg_deps`, otherwise you get the following error using it
```
$ hab pkg exec core/hugo hugo
✗✗✗
✗✗✗ No such file or directory (os error 2)
✗✗✗
```
hugo binary info
```
$ file $(hab pkg path core/hugo)/bin/hugo
/hab/pkgs/core/hugo/0.46/20180810030420/bin/hugo: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /hab/pkgs/core/glibc/2.27/20180608041157/lib/ld-linux-x86-64.so.2, stripped
```
Signed-off-by: Will Fisher <wfisher@chef.io>
=> [hugo] Add missing core/glibc to pkg_deps

concourse-fly/plan.sh, concourse/plan.sh
Rolled concourse and fly forward to 4.2.1
Converted deps to multi-line arrays
Added glibc as a dependency:
```
[17] concourse-fly(do_build)> ldd ./fly
linux-vdso.so.1 (0x00007ffeeb3d9000)
libpthread.so.0 => /hab/pkgs/core/glibc/2.27/20180608041157/lib/libpthread.so.0 (0x00007fe943402000)
libc.so.6 => /hab/pkgs/core/glibc/2.27/20180608041157/lib/libc.so.6 (0x00007fe94304e000)
/hab/pkgs/core/glibc/2.27/20180608041157/lib/ld-linux-x86-64.so.2 => /hab/pkgs/core/glibc/2.27/20180608041157/lib64/ld-linux-x86-64.so.2 (0x00007fe943620000)
```
=> [concourse] Rolled concourse and fly forward to 4.2.1

memcached/plan.sh
It turns out `core/cyrus-sasl` has existed for a while, and so I should not have created `core/libsasl2`. This commit changes the dependency. Following this merge, and promotion, all builds of memcached that use core/libsasl2 should be demoted from stable, and libsasl2 should be deprecated.
```
./memcached/tests/test.sh
```
```
The rakops/memcached/1.5.10/20180927000454 service was successfully loaded
✓ Help command
```
=> [memcached] Change to use core/cyrus-sasl

.bldr.toml, libsasl2/README.md
`core/libsasl2` was added recently, however `core/cyrus-sasl` provides the same libraries, and has existed for some time. This deprecates libsasl2 in favor of cyrus-sasl.
Followup steps to perform post-merge (per [RFC](https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0007-deprecating-packages.md)):
* Delist the package by setting to private
* Disconnect plan from builder
=> [libsasl2] Deprecate libsasl2

yarn/plan.sh
```
./yarn/tests/test.sh
```
```
✓ Help command
```
=> [yarn] Upgrade yarn to 1.11.0

pngquant/plan.sh, pngquant/tests/test.bats, pngquant/tests/test.sh
```
./pngquant/tests/test.sh
```
```
```
=> [pngquant] Fix library deps, Upgrade to 2.12.0, add tests

cabal-install/plan.sh
Rolled cabal-install forward to 2.4.0.0
This is needed for #1883 as GHC 8.6 fails to build cabal 2.2.0.0
=> [cabal-install] Rolled cabal-install forward to 2.4.0.0

gifsicle/plan.sh, gifsicle/tests/test.bats, gifsicle/tests/test.sh
```
./gifsicle/tests/test.sh
```
```
```
=> [gifsicle] Upgrade gifsicle to 1.91, add tests

.bldr.toml, cppcheck/README.md, cppcheck/plan.sh, cppcheck/tests/test.bats, cppcheck/tests/test.sh
```bash
DO_CHECK=1 ./cppcheck/tests/test.sh
```
```bash
...
test 1
Start 1: testrunner
1: Test command: /hab/cache/src/cppcheck-1.84/_build/bin/testrunner
1: Test timeout computed to be: 9.99988e+06
1: Test64BitPortability::novardecl
1: Test64BitPortability::functionpar
1: Test64BitPortability::structmember
1: Test64BitPortability::ptrcompare
...
1: Testing Complete
1: Number of tests: 3224
1: Number of todos: 207
1: Tests failed: 0
1:
1/1 Test #1: testrunner .......................   Passed   35.57 sec
100% tests passed, 0 tests failed out of 1
...
★ Binlinked cppcheck from bdangit/cppcheck/1.84/20181006230920 to /bin/cppcheck
```
=> [cppcheck] new plan

prometheus/hooks/run, prometheus/plan.sh, prometheus/tests/test.bats, prometheus/tests/test.sh
- upgraded prometheus to 2.4.2, which means the hook had to be modified slightly
- build from tarball releases which now means we can verify the integrity via shasum
- add in do_check() for unit testing
- add in tests for functional testing
```bash
DO_CHECK=1 ./prometheus/tests/test.sh
```
```
prometheus: Running post-compile tests
/hab/cache/src/prometheus-2.4.2/src/github.com/prometheus/prometheus /hab/cache/src/prometheus-2.4.2 /hab/cache/src /src/prometheus
>> running all tests
go test -race ./...
ok      github.com/prometheus/prometheus/cmd/prometheus 19.989s
ok      github.com/prometheus/prometheus/cmd/promtool   1.120s
ok      github.com/prometheus/prometheus/config 1.541s
ok      github.com/prometheus/prometheus/discovery      7.560s
ok …
```
=> [prometheus] upgrade to 2.4.2, build from tarball release, and add tests

.bldr.toml, CODEOWNERS, dotnet-asp-core/README.md, dotnet-asp-core/plan.ps1, dotnet-asp-core/plan.sh, dotnet-asp-core/tests/test.bats, dotnet-asp-core/tests/test.sh
Hey all,
This is a new plan for asp.net core. I have added and tested both the Linux and Windows builds. Here is how to test the Linux plan:
``` 
```
Response:
```
✓ Help command
✓ ASP check
```
All reports should come back happy if all is well :)
=> [dotnet-asp-core] Adding ASP.NET Core Plan

dotnet-core-sdk/README.md, dotnet-core-sdk/plan.ps1, dotnet-core-sdk/plan.sh, dotnet-core-sdk/tests/test.bats, dotnet-core-sdk/tests/test.sh
Hey all,
This update brings the dotnet-core-sdk to version 2.1.403. Tests were added as well.
To test the Linux plan, log into the Hab Studio and run the following commands:
```
```
```
✓ Info command
```
=> [dotnet-core-sdk] Updating Version and Adding Tests

nginx/plan.ps1, nginx/plan.sh
```
```
```
✓ Help command
```
Windows version also updated, but I haven't got network access to upload it(from the windows PC), can do later.
=> [nginx] Upgrade nginx to 1.15.5

.bldr.toml, CODEOWNERS, cuda-libs/README.md, cuda-libs/plan.sh
This allows cuda apps just to package the runtime libs.
---
```
hab studio build
hab pkg install "results/${pkg_artifact}"
```
1. Build this test `plan.sh`
```bash
pkg_origin=bdangit
pkg_name=cuda-samples
pkg_version='9.2'
pkg_description="$(cat << EOF
Samples for CUDA Developers which demonstrates features in CUDA Toolkit
EOF
)"
pkg_source="https://github.com/NVIDIA/${pkg_name}/archive/v${pkg_version}.tar.gz"
pkg_license=('custom')
pkg_maintainer='Ben Dang <me@bdang.it>'
pkg_upstream_url="https://github.com/NVIDIA/cuda-samples"
pkg_shasum="4b172847196d5b2ab645625dd7953ddf5cffa04b2a3c45689d33ef92fc953d90"
pkg_deps=(
core/cuda-libs
core/gcc-libs
core/glibc
)
pkg_build_deps=(
core/cuda
core/make
)
pkg_bin_dirs=(bin) …
```
=> [cuda-libs] new plan

sbt/plan.sh
Testing is manual at the moment:
```
build sbt
hab pkg install --binlink core/jre8
sbt --help
```
Performs some downloads / maven package resolution as expected.
=> [sbt] Update sbt to 1.2.4

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2018/09/25/Rust-1.29.1.html
Note that the download URL for Linux was updated from an `http://`
scheme to `https://` as the distribution server is now issuing
`HTTP/301` redirects to the TLS-enabled URL.
=> [rust] Update to Rust 1.29.1.

mage/plan.sh, mage/tests/test.bats, mage/tests/test.sh
```
./mage/tests/test.sh
```
```
✓ Binlink dependencies
✓ Help command
✓ Mage init works
```
=> [mage] Update mage to 1.7.0, move tests into test directory

rabbitmq/config/env, rabbitmq/hooks/init, rabbitmq/plan.sh, rabbitmq/tests/test.bats, rabbitmq/tests/test.sh
Refs: #1871 - Fixes the log error issue.
Fixed dependency on elixir, by restricting dependency to core/elixir/1.6.5. Was failing build due to:
```
==> rabbitmqctl
** (Mix) You're trying to run :rabbitmqctl on Elixir v1.7.3 but it has declared in its mix.exs file it supports only Elixir ~> 1.6.0
```
```
./rabbitmq/tests/test.sh
```
```
✓ Listening on port 4369, 5672, 25672
```
=> [rabbitmq] Fix log path issue and Elixir dependency, Add tests

httpd/plan.sh, httpd/tests/test.bats, httpd/tests/test.sh
```
httpd/tests/test.sh
```
```
✓ Help command
✓ Multiple processes
```
=> [httpd] Update to 2.4.35, add tests

mage/plan.sh
Minor version bump for Mage to 1.7.1
```
$ hab studio run mage/tests/test.sh
. . .
1..5
ok 1 Binlink dependencies
ok 2 Command is on path
ok 3 Version matches
ok 4 Help command
ok 5 Mage init works
```
=> [mage] Update to 1.7.1

prometheus-cpp/README.md, prometheus-cpp/plan.sh
- Update version to 0.5.0.
- This plan adds injecting paths of cmake configs to the CMAKE_FIND_ROOT_PATH to
allow cmake users have a better cmake experience. Just include
`-DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}` when calling `cmake`.
```
DO_CHECK=1 build prometheus-cpp
```
=> [prometheus-cpp] Update version and add CMAKE_FIND_ROOT_PATH

terraform/plan.sh
```
hab studio run terraform/tests/test.sh
```
```
1..2
ok 1 Version matches
ok 2 Terraform default workspace
```
=> [terraform] Update to 0.11.9

.bldr.toml, libzip/README.md, libzip/plan.sh
this is a C library for reading, creating, and modifying zip archives
the plan is added because we need it to extend the php plan
Signed-off-by: David Hohengaßner <david@hohengassner.com>
=> add plan for libzip

.bldr.toml, llvm/README.md, llvm/plan.sh, llvm/tests/test.bats, llvm/tests/test.sh, llvm5/README.md, llvm5/plan.sh, llvm5/tests/test.bats, llvm5/tests/test.sh, llvm7/README.md, llvm7/plan.sh, llvm7/tests/test.bats, llvm7/tests/test.sh
- switched to ninja
- enable rtti and ffi
- install llvm utils which is used by clang
- add in tests
- add CMAKE_FIND_ROOT_PATH for better cmake ux
- implement RFC3 to track major versions in parallel
```
DO_CHECK=1 ./llvm/tests/test.sh
DO_CHECK=1 ./llvm5/tests/test.sh
DO_CHECK=1 ./llvm7/tests/test.sh
```
> note: building this plan takes awhile - should be ~60 minutes with tests each.
`core/libcxx` and `libcxxabi` depends on this package and I have rebuilt them locally.  The plan as in master works just as fine.
=> [llvm] Upgrade llvm to 7.0.0 and implement RFC3

vault/plan.sh
```
```
```
★ Binlinked vault from rakops/vault/0.11.4/20181025015044 to /bin/vault
✓ Help command
```
=> [vault] Updated vault to 0.11.4

artifactory-pro/plan.sh, artifactory-pro/tests/helpers.bash, artifactory-pro/tests/test.bats, artifactory-pro/tests/test.sh
Hey all,
This is a simple version bump but with tests added in. To test this build:
```
```
The output should read:
```
```
Please let me know if you have any questions. 
=> [artifactory-pro] Updating version and adding tests

googletest/README.md, googletest/plan.sh
This plan adds injecting paths of cmake configs to the CMAKE_FIND_ROOT_PATH to
allow cmake users have a better cmake experience. Just include
`-DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}` when calling `cmake`.
```
DO_CHECK=1 build googletest
```
=> [googletest] Add CMAKE_FIND_ROOT_PATH to make cmake ux better

benchmark/plan.sh
- Patch update for google benchmark.
- This plan adds injecting paths of cmake configs to the CMAKE_FIND_ROOT_PATH to
allow cmake users have a better cmake experience. Just include
`-DCMAKE_FIND_ROOT_PATH=${CMAKE_FIND_ROOT_PATH}` when calling `cmake`.
```
DO_CHECK=1 build benchmark
```
This commit depends on #1925.
=> [benchmark] Update version and add CMAKE_FIND_ROOT_PATH

elixir/plan.sh
```
./elixir/tests/test.sh
```
```
```
=> [elixir] Update elixir to 1.7.4

.bldr.toml, opa/README.md, opa/default.toml, opa/hooks/run, opa/plan.sh, opa/tests/helpers.bash, opa/tests/test.bats, opa/tests/test.sh
OPA is https://openpolicyagent.org/. v0.10.0 is [hot off the press](https://github.com/open-policy-agent/opa/releases/tag/v0.10.0).
The included configuration is minimal, I assumed that was how a core-plan should be. Also, I mostly want this (right now) for using the CLI tool, which is part of the package (it's one binary to be used in a myriad of ways).
Includes a README and some tests. 😃 (With the latter modeled after dex's tests, the former after gnatsd's README.)
=> [opa] add OPA v0.10.0

ansible/plan.sh, ansible/tests/test.bats, ansible/tests/test.sh
```
hab studio run ansible/tests/test.sh
```
```
1..2
ok 1 Version matches
ok 2 Help Command
```
=> [ansible] Update to 2.6.6, add tests

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
We should use the safe and secure default of `:verify_peer` for the `ssl_verify_mode` in the configuration generated by the Chef scaffolding. This is in line with the default within Chef itself. End users can override this with `:verify_none` by changing the configuration passed into Habitat if they wish.
=> scaffolding-chef: secure ssl default

ansible/plan.sh
```
./ansible/tests/test.sh
```
```
✓ Help Command
```
=> [ansible] Update ansible to 2.7.1

strace/plan.sh
```
./strace/tests/test.sh
```
```
✓ Can strace
```
=> [strace] Update strace to 4.25

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
This modifies the method by which we run the chef-client, to ensure we aren't consuming unnecessary system resources. It also fixes an edge case where the chef-client could spawn multiple times if the habitat supervisor was restarted rapidly. This method instead will always give us a clean run, and will still respect the interval and splay options by using a simple `sleep`. It also ensures that Habitat's application lifecycle hook (the run hook) executes the chef-client directly, which is nice because you don't have to wait for the chef-client to execute. (This is why there were two calls to chef-client -z in the previous code).
This is a subtle but important change.
Would like some extra throughts from @jonlives before merging.
=> [scaffolding-chef] Use non-daemonized chef-client run

curl/plan.sh
Addresses security vulnerabilities:
[CVE-2018-16839](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16839)
[CVE-2018-16840](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16840)
[CVE-2018-16842](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16842)
=> [curl] Update curl to 7.62.0

dotnet-core/plan.ps1, dotnet-core/plan.sh
Hey all,
This update brings both the Windows and Linux versions up to 2.1.5. To test this build, run the following commands in the hab studio:
```
./test/test.sh
```
You should see the following results:
```
✓ Help command
```
Please let me know if there are any questions. Thanks!!
=> [dotnet-core] Updated version to 2.1.5

node6/plan.ps1
We are running into issues with scripting that uses the core plans directory manifest because the node 6 plan.ps1 file has Windows line endings.  This fix converts the line endings to Unix style. This conforms with other Windows ps1 files (eg, node10).
Signed-off-by: Salim Alam <salam@chef.io>
=> Convert to unix-style line endings

.bldr.toml, clang-tools-extra/README.md, clang/plan.sh, clang/tests/test.bats, clang/tests/test.sh, clang5/README.md, clang5/plan.sh, clang5/tests/test.bats, clang5/tests/test.sh, clang7/README.md, clang7/plan.sh, clang7/tests/test.bats, clang7/tests/test.sh
This plan ugrades clang to 7.0.0 and with that we implement RFC3 to
include versions for clang5 and clang7.  We also include the
clang-tools-extra bins into this plan, which means `core/clang-tools-extra` is deprecated.
Furthermore, we append cmake configs into CMAKE_FIND_ROOT_PATH for better cmake ux.
Depends on #1918 to be merged in before this.
```
DO_CHECK=1 ./clang/tests/test.sh
DO_CHECK=1 ./clang5/tests/test.sh
DO_CHECK=1 ./clang7/tests/test.sh
```
> note: building these plans takes awhile - should be 60-70 minutes **each** pending on the machine.
=> [clang] upgrade clang to 7.0.0 and implement RFC3

memcached/plan.sh
```
./memcached/tests/test.io
```
```
✓ Help command
```
=> [memcached] Update memcached to 1.5.12

netdata/plan.sh
Some of the stock collector scripts need `curl` and `awk`, this PR fixes some of them and eliminates error log noise in environments that don't otherwise provide them
=> [netdata] add missing runtime shell dependencies

scaffolding-chef/lib/scaffolding.sh
This exposes the `--run_lock_timeout` option as its own configuration option in the default.toml. We set it to 1800 seconds (30 minutes) by default (which is how interval was previously set) so this is not a breaking change.
=> [scaffolding-chef] Expose run_lock_timeout

dex/plan.sh, dex/tests/test.bats, dex/tests/test.sh
- plan.sh now contains pkg_version=2.13.0, not pkg_version=v2.13.0
- tests/test.sh should work from dex/ and top-level
- added a test for asserting the version as reported by the CLI
------
I had promised to update these test files when the same issue came up in #1942  -- so, finally. 😄
=> [dex] bump v2.12.0 -> v2.13.0; minor fixes to plan and tests

bats/plan.sh
This is a really hard one to test, as it only appears in failure cases when run under `hab pkg exec`.     I haven't found a good way to express 'I expect this failure case to not fail in its reporting'
=> [bats] Add sed to pkg_deps

dejagnu/plan.sh, dejagnu/tests/test.bats, dejagnu/tests/test.sh
This moves `coreutils` and `sed` from `pkg_build_deps` to `pkg_deps` and adds `grep` to `pkg_deps`
=> [dejagnu] Update deps

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
This adds the ability for other software to run in reaction to the first converge of the chef-client after a package upgrade. For example, you could have your InSpec Habitat package have this in its plan:
```
pkg_binds_optional=(
[chef]="chef_client_ident"
)
```
which will cause the package to re-run the run hook when the bind is updated. In our case, this bind is updated automatically in the chef-client package's run hook using `hab config apply`.
In fact, this is exactly the use case I've used to test this out, but I can see other software reacting to this value as well.
I currently have a test environment using an InSpec package that uses this bind all spun up. If you'd like to have access to the environment, please let me …
=> [scaffolding-chef] add ability for other software to bind off chef_client_ident

nginx/plan.ps1, nginx/plan.sh
* Version update
* Contains Fixes for:
* [CVE-2018-16843](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16843)
* [CVE-2018-16844](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16844)
```
```
```
✓ Help command
```
=> [nginx] Update Nginx to 1.15.6 for Linux and Windows

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
Shortly after merging #1985, I realized that some people are deleting their default.toml, and it was required by the scaffolding to provide a default for `chef_client_ident`. In this case, empty string is the best option, since we don't want to assume any previous values.
Thank you @robbkidd for the additional details here:
- In #1985, chef_client_ident is set to the pkg.ident of the package using the Chef scaffolding.
- pkg.ident is the fully qualified identifier for a Habitat package—origin/name/version/release—so this is expected to change whenever a new release of a Chef package has started up in an existing service group.
- The config version_number advances and the value of the chef_client_ident bind changes when the …
=> [scaffolding-chef] bugfix to add default value for bind in default.toml

filebeat/plan.sh, filebeat/tests/test.bats, filebeat/tests/test.sh
```
./filebeat/tests/test.sh
```
```
✓ Help command
```
=> [filebeat] Update filebeat to 6.4.3, add tests

vault/config/settings.hcl
Fixes #1897
Change `backend` to `storage` in configuration.
=> [vault] Change backend to storage in configuration

vault/plan.sh
```
```
```
✓ Help command
```
=> [vault] Update Vault to 0.11.5

artifactory-pro/plan.sh
Hey all,
Just a version bump this time. Nothing fancy. I tested this locally, build looks good. To test the build, enter the studio and run 
```
```
Expected output:
```
```
=> [Artifactory-Pro] Updating 6.5.3

elasticsearch/plan.sh, elasticsearch5/README.md, elasticsearch5/plan.sh, elasticsearch5/tests/test.bats, elasticsearch5/tests/test.sh
This does a number of things:
* Restructure plan to source the `elasticsearch` plan to avoid duplication
* Upgrade to 5.6.13
* Add tests
* Add missing deps (elasticsearch binary was complaining about missing commands)
```
./elasticsearch5/tests/test.sh
```
If you get failures related to the process or ports, it can be caused by a slow startup of Elasticsearch. While the delay to check has been increased to 15 seconds, it may be necessary to wait a little longer, and retry the tests without building it again:
```
SKIPBUILD=1 ./elasticsearch5/tests/test.sh
```
```
✓ Help command
✓ Listening on ports 9200, 9300
```
=> [elasticsearch5] Update elasticsearch5 to 5.6.13, fix missing deps, added tests

go/plan.sh
[Release notes](https://golang.org/doc/devel/release.html#go1.11.minor)
=> [go] bump 1.11.1 -> 1.11.2

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
The bootstrap-config.rb configuration file is designed to be run via ```hab pkg exec``` when provisioning instances (ie, the habitat package is installed but not started) so we can't use config macros here. This commit changes the default to verify_peer, and keeps the existing config macro for the rendered client-config.rb.
Signed-off-by: Jon Cowie <jonlives@gmail.com>
=> Fix chef scaffolding to default to verify_peer in bootstrap config

curl-static-musl/plan.sh
Refs #1956
Same version bump for musl build.
=> [curl-static-musl] Update curl-static-musl to 7.62.0

php/plan.sh, php/test/libzip_support.php, php/test/test.sh
This PR resolves downstream build errors in Drupal
https://bldr.habitat.sh/#/pkgs/core/drupal/jobs/1103619923366256640
=> [php] Add gcc-libs to pkg_deps

postgresql-client/plan.ps1, postgresql-client/plan.sh, postgresql/plan.sh, postgresql96-client/plan.ps1, postgresql96-client/plan.sh, postgresql96/plan.sh
Release Notes for 9.6.11: https://www.postgresql.org/docs/9.6/release-9-6-11.html
(where also those other version skipped here are listed)
So many pg plans... 💭 _Did I catch them all?_
=> [postgresql] bump 9.6.9 -> 9.6.11

glibc/x86_64-linux-kernel2/0005-fix-binutils-2-29-build.patch, glibc/x86_64-linux-kernel2/dont-use-system-ld-so.patch, glibc/x86_64-linux-kernel2/gcc-implicit-boolean.patch, glibc/x86_64-linux-kernel2/glibc-2.23-upstream_fixes-1.patch, glibc/x86_64-linux-kernel2/nss-nisplus-gcc7.patch, glibc/x86_64-linux-kernel2/plan.sh, glibc/x86_64-linux-kernel2/remove-sun-rpm-bug.patch, glibc/x86_64-linux-kernel2/rpcgen-path.patch, glibc/x86_64-linux-kernel2/testsuite-fix.patch, libcap/x86_64-linux-kernel2/README.md, libcap/x86_64-linux-kernel2/libcap-old-kernel-headers.patch, libcap/x86_64-linux-kernel2/plan.sh, libsodium/plan.sh, linux-headers/x86_64-linux-kernel2/plan.sh
This is the set of base plans that require variations to work under the "x86-64-linux-kernel2" package target introduced in habitat-sh/core#42. These plans are specifically locked to older versions of software in order to ensure compatibility with Linux kernel versions as low as 2.6.32.
There will be no differences from how you build and run Habitat plans and packages today. As we build out packages for the "kernel2 variant" you will see a hab cli with an Active Target of 'x86-64-linux-kernel2'. This will allow you to build and consume packages for the "kernel2 variant" if your environment requires support for Linux systems running on that era of the kernel.
As this is foundational for work that is still in flight, we don't have any new blog posts or documentation to share at this time. …
=> Initial commit of plan variants

geoip/README.md, geoip/plan.sh
Not sure if there's a licensing reason not to do this, but without it I was seeing this while using `goaccess`:
```
Error Opening file /hab/pkgs/core/geoip/1.6.0/20180608185811/share/GeoIP/GeoIP.dat
```
The [maxmind site provides a wget command](https://dev.maxmind.com/geoip/legacy/install/country/) for downloading this file so it seams reasonable to assume they don't mind scripted downloads
According to [license section on the main page for the database](https://dev.maxmind.com/geoip/legacy/geolite/), attribution is required so I added that to the README
=> [geoip] download GeoIP.dat

clang/plan.sh
Need to a remove an include since these are built-in headers that `clang` knows how to get too.  An example of how this conflicts is when you have both `gcc` and `clang` in the same plan, gcc will complain about pthread missing.
=> [clang] Remove an include that shouldn't be there

dotnet-core/plan.ps1, dotnet-core/plan.sh
Hey all,
This updates both the Linux and Windows plans to version 2.1.6. To test the Linux build, enter the studio and run:
```
```
```
✓ Help command
```
=> [dotnet-core] Updating dotnet-core to 2.1.6

artifactory-pro/plan.sh
Hey all,
This just updates Artifactory Pro to version 6.5.9. To test this build, please run the following command in the studio: 
```
```
```
```
=> [artifactory-pro] Updating version to 6.5.9

consul/plan.sh
Hey all,
This is a minor update to version 1.4.0. To test this build, enter the studio and run the following command:
```
```
The results should look like:
```
```
=> [consul] Updating version to 1.4.0

etcd/plan.sh, etcd/tests/test.bats, etcd/tests/test.sh
Hey all,
This updates etcd to 3.3.10 and adds basic tests. To test this build, run the following command:
```
```
The results should return:
```
```
=> [etcd] Update to 3.3.10 w/tests

libpng/plan.sh
```
DO_CHECK=1 build libpng
```
Runs checks:
```
============================================================================
Testsuite summary for libpng 1.6.36
============================================================================
============================================================================
```
=> [libpng] Update libpng to 1.6.36

sbt/plan.sh
```
build sbt
hab pkg install --binlink core/jre8
sbt --help
```
I promise to automate tests soon for this.
=> [sbt] Update sbt to 1.2.7, minor cleanup

dotnet-core-sdk/plan.ps1, dotnet-core-sdk/plan.sh
Hey all,
This updates both the Linux and Windows plans to version 2.1.500. To test the Linux build, enter the studio and run:
```
```
The results of a successful run would be:
```
✓ Info command
```
=> [dotnet-core-sdk] Updating Linux and Windows plans to 2.1.500

vault/README.md, vault/config/settings.hcl, vault/default.toml, vault/hooks/init, vault/plan.sh, vault/tests/test.bats, vault/tests/test.sh
Since this is a major version up, I've rolled in the breaking change proposed in #1973 
* Upgrade to 1.0.0
* Default storage backend changed to fiule
* Added notice about file backend change to readme
* Added service tests
```
...
✓ Help command
```
=> [vault] Upgrade vault to 1.0.0, add tests, change storage

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
The goal of this small PR is to allow folks a separate tunable for the initial run.
When you're running < 100 nodes, nobody wants to wait for the initial run. And they shouldn't have to. Waiting for the initial run is only something that should be done for large node upgrades and rollouts of large masses of infrastructure where the thundering herd problem is a real issue.
The thundering herd problem only becomes a larger problem when you are upgrading thousands of nodes simultaneously. Let me elaborate how this would all go down:
The Habitat Supervisor checks for updates once per minute. This isn't a splay (randomized), so you will achieve fairly consistent network timings and load timings when pulling artifacts from Builder. …
=> [scaffolding-chef] add a first_run splay tunable

hugo/plan.sh
=> [hugo] Update Hugo to 0.52

papi/plan.sh
Minor version update to papi.  
Validation:
You can run `hab pkg exec $HAB_ORIGIN/papi papi_version` to get the version.
`hab pkg exec $HAB_ORIGIN/papi papi_mem_info` will return information about memory cache.
=> [papi] Update version

postfix/plan.sh
Minor version update.  
Validation can be performed by running `hab svc load $HAB_ORIGIN/postfix` and verifying the service starts.
=> Update postfix version

sumologic/plan.sh
Minor sumologic version update.  
Validation requires a valid license. Without one, the service goes into a boot-loop.
=> [sumologic] Update version

nss/plan.sh
Minor version update to nss. 
Validation can be performed by running `hab pkg exec $HAB_ORIGIN/nss vfyserv google.com` and inspecting the output.
=> [nss] Update version

lsof/plan.sh
Minor version update.  Validation can be performed by running `hab pkg exec $HAB_ORIGIN/lsof losf` and inspecting the output.
=> [lsof] Update version

openssl/plan.ps1, openssl/plan.sh
There's multiple CVEs in 1.0.2n and the other versions before 1.0.2q
=> [openssl] Update openssl from 1.0.2n to 1.0.2q

filebeat/plan.sh
```
./filebeat/tests/test.sh
```
```
✓ Help command
```
=> [filebeat] Update filebeat to 6.5.3

opa/plan.sh
[Release notes](https://github.com/open-policy-agent/opa/releases/tag/v0.10.2)
=> [opa] bump 0.10.1 -> 0.10.2

git/plan.sh
git-submodule is using `sed` inside the code. Currently we are getting the following err when run `hab pkg exec core/git git submodule init`:
```
/hab/pkgs/core/git/2.18.0/20181212192153/libexec/git-core/git-submodule: line 7: sed: not found
/hab/pkgs/core/git/2.18.0/20181212192153/libexec/git-core/git-submodule: /hab/pkgs/core/git/2.18.0/20181212192153/libexec/git-core/git-sh-setup: line 105: sed: not found
```
=> [git] Add core/sed as dependency for core/git

node8/plan.sh
* [Node 8.14.0 Changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.14.0)
* [Node 8.13.0 Changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.13.0)
```
$ hab studio enter
v8.14.0
```
=> [node8] Update Node8 to 8.14.0

terraform/plan.sh
Hey all,
Just another simple update. This updates Terraform to version 0.11.11. To test this build, please enter the studio and run:
```
```
```
```
Please let me know if there are any issues or questions. 
=> [terraform] Updating to 0.11.11

nettle/plan.sh
Security updates for:
```
CVE-2018-16868 gnutls: Bleichenbacher-like side channel leakage in
PKCS#1 1.5 verification and padding oracle verification
CVE-2018-16869 nettle: Leaky data conversion exposing a manager oracle
```
Ref: http://lists.gnu.org/archive/html/info-gnu/2018-12/msg00001.html
Closes #2020
=> [nettle] Upgrade nettle to 3.4.1

dotnet-core/plan.ps1, dotnet-core/plan.sh
Hey all,
Here is another simple bump in version here for both Windows and Linux. To test the Linux plan, please enter the studio and run this:
```
```
```
✓ Help command
```
Please let me know if there are any questions. 
=> [dotnet-core] Updated Windows/Linux Plans to 2.2.0

dotnet-core-sdk/plan.ps1, dotnet-core-sdk/plan.sh
Hey all,
Here is another simple update. This updates both the Windows and Linux plans. To test the Linux build, please enter the studio and run:
```
```
The results should be: 
```
✓ Info command
```
Please let me know if there are any questions. 
=> [dotnet-core-sdk] Updating to version 2.2.101

bundler/plan.sh
See https://forums.habitat.sh/t/new-build-issue-after-ruby-2-4-2-rebuild/594/2 and https://github.com/habitat-sh/core-plans/pull/1598
I'm getting the same issue, only with 1.16.2 and 1.16.6:
```
Vendoring 'bundler' version 1.16.6
ERROR:  Could not find a valid gem '/hab/pkgs/core/bundler/1.16.2/20181212193253/cache/bundler-1.16.6.gem' (>= 0) in any repository
```
=> [bundler] Bump bundler version

.pre-commit-config.yaml
This PR disables [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164) in CI.  [plan-build sets](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L334) `-e` which normally disables this check, but shellcheck isn't aware of that due how `plan.sh` is source by plan-build.  
`--exclude` args were also re-ordered for readability as part of this PR.
=> Disable SC2164

.bldr.toml, mention-bot/README.md, mention-bot/plan.sh
This PR deprecates mention-bot per our [deprecation guidelines](https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0007-deprecating-packages.md). 
=> [mention-bot] Deprecate mention-bot

.bldr.toml, ruby22/README.md, ruby22/plan.sh
This PR deprecates Ruby22 per our [deprecation guidelines](https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0007-deprecating-packages.md). 
=> [ruby22] Deprecate Ruby22

.bldr.toml, jdk9/README.md, jdk9/plan.sh, jre9/README.md, jre9/plan.sh
This PR deprecates JRE9 and JDK9 per our [deprecation guidelines](https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0007-deprecating-packages.md). 
=> [jdk9/jre9] Deprecate Java9

packer/plan.ps1, packer/plan.sh, packer/tests/test.bats
Testing:
```
./packer/tests/test.sh
```
Output:
```
✓ Help command
```
Windows package uploaded, needs promotion to stable when this PR is approved: https://bldr.habitat.sh/#/pkgs/core/packer/1.3.3/20181229145152
=> [packer] Update packer to 1.3.3, windows and linux, add extra run tests

cppcheck/plan.sh
```
cppcheck: hab-plan-build cleanup
cppcheck: 
cppcheck: Source Path: /hab/cache/src/cppcheck-1.86
cppcheck: Installed Path: /hab/pkgs/core/cppcheck/1.86/20181227215628
cppcheck: Artifact: /src/cppcheck/results/core-cppcheck-1.86-20181227215628-x86_64-linux.hart
cppcheck: Build Report: /src/cppcheck/results/last_build.env
cppcheck: SHA256 Checksum: 04879ddf93338cfd578fea25309dd3c786b1c02fcd81534401522ceaf2e4d592
cppcheck: Blake2b Checksum: 6f0aed71b67b59568da3fe5d419629a1a2d7426be4a4ff593d495c0fc88ad0bd
cppcheck: 
cppcheck: I love it when a plan.sh comes together.
cppcheck: 
cppcheck: Build time: 1m20s
» Installing results/core-cppcheck-1.86-20181227215628-x86_64-linux.hart
→ Using core/cppcheck/1.86/20181227215628
★ Install of …
```
=> [cppcheck] Updated cppcheck to 1.86

hugo/plan.sh
Testing:
```
```
Output
```
```
=> [hugo] Update hugo to 0.53

scaffolding-chef/lib/scaffolding.sh
Signed-off-by: Sandra Tiffin <stiffin@chef.io>
It can be very useful to be able to override default node attributes defined within a Habitat Managed Chef package at run time.
Example use case that I created it for: an S3 bucket is defined as a Terraform variable. Terraform can then install the hab package and create a user.toml with an [attributes] section to override the value of the s3bucket node variable.
Sample toml file:
```
[attributes]
[attributes.mycookbook]
s3bucket = "mybucket"
```
recipe:
``log "s3bucket = #{node['mycookbook']['s3bucket']}"``
output:
``* log[s3bucket = mybucket] action write``
Tested and works with or without attributes defined in the toml configs.
=> [scaffolding-chef] Add json attribute file to chef-client run

scaffolding-chef/plan.sh
This is a version bump for releasing #2008 as version 0.3.0 of scaffolding-chef.
=> bump version for json runtime config

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
In PR #1831 @jsirex originally wrote this code. I am submitting a portion of it here for a smaller patch.
This PR allows users to override the scaffolding's chef-client and chef-dk package. This is so a user can pin their package to previous (old) versions.
Furthermore it fixes some essential bugs with permissions on files and directories.
I have tested it by building packages with the override set and successfully built and stood up my app with it.
=> [scaffolding-chef] add @jsirex code for fixing permissions and allowing chef-client/chef-dk overrides

vault/plan.sh
```
```
```
✓ Help command
[3][default:/src:0]#
```
=> [vault] Update vault to 1.0.2

artifactory-pro/plan.sh
Another simple one. Just bumped the version.
To test this build, log into the studio and run:
```
```
The output should be: 
```
```
=> [Artifactory-Pro] Updated plan to 6.6.5

visual-cpp-redist-2015/plan.ps1
Gonna be shipping this with Habitat to fix bug where hab does not run on clean install of win 2k8r2 or win 7.
Uploaded core/visual-cpp-redist-2015/14.0.23026/20190128180056 to unstable
=> [visual-cpp-redist-2015] adding visual-cpp-redist-2015

ruby/plan.sh, ruby25/plan.sh
`gem update --system` will bring in rubygems 3.x, which is causing a number of issues with downstream projects. This locks us to the rubygems version in use pre-base-plans-refresh.  
=> [ruby] Lock rubygems version to 2.7.8

rust/plan.ps1
This uses the new 2015 CPP redist package and I have tested that using the rust toolchain with that dep works fine. This will prevent habitat builds from pulling 2 CPP packages.
This also cleans up the builds so that nothing is extracted directly into the `src` dir. This is something I will need to do across all plans using this pattern.
=> [rust] use 2015 CPP and do not dirty repo in build

consul/plan.sh
Blog post / release notes: https://www.hashicorp.com/blog/hashicorp-consul-1-4-1
```
```
```
```
=> [consul] Update consul to 1.4.1, security update

go/plan.sh
This is a security release that addresses CVE-2019-6486. See
https://groups.google.com/forum/#!msg/golang-announce/mVeX35iXuSw/Flp8FX7QEAAJ
for more information.
=> [go] Bump to 1.11.5

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
See discussion in #2203 
Removing this feature for now until we can build a more robust version of it.
=> [scaffolding-chef] remove binding feature for chef-client consumer packages for now

ruby25/plan.sh
This corrects the download url for the ruby25 package.  Prior to this change, it would evaluate to `ruby25/ruby25-2.5.3.tar.gz` which is not how upstream distributes the source.
=> Fix ruby25 download url

curl-static-musl/plan.sh, curl-static-musl/tests/test.bats, curl-static-musl/tests/test.sh, curl/plan.sh, curl/tests/test.bats, curl/tests/test.sh
```
curl: hab-plan-build cleanup
curl: 
curl: Source Path: /hab/cache/src/curl-7.63.0
curl: Installed Path: /hab/pkgs/core/curl/7.63.0/20181227232311
curl: Artifact: /src/results/core-curl-7.63.0-20181227232311-x86_64-linux.hart
curl: Build Report: /src/results/last_build.env
curl: SHA256 Checksum: 8db48b6a9481b75148987235f295f14a112916c7582ca05e58e91f912b02bbe6
curl: Blake2b Checksum: 801b0e8736745fd3e784e92c4e5a93adbca1bf8fbfed0461bf6e1c38b6390e2c
curl: 
curl: I love it when a plan.sh comes together.
curl: 
curl: Build time: 1m58s
```
=> [curl] Updated curl to 7.63.0

dpkg/plan.sh
dpkg: Source Path: /hab/cache/src/dpkg-1.19.4
dpkg: Installed Path: /hab/pkgs/tas50/dpkg/1.19.4/20190201004320
dpkg: Artifact: /src/dpkg/results/tas50-dpkg-1.19.4-20190201004320-x86_64-linux.hart
dpkg: Build Report: /src/dpkg/results/last_build.env
dpkg: SHA256 Checksum: 35209e1e016e097e47303c3d22c0e2d6d129c4a6d5b420992a4ad7e6f658fa3f
dpkg: Blake2b Checksum: dc9a2f1ea84c5e998e88d512bec4cb3c9649358ef9c57984b58ef99776f02ec5
dpkg:
dpkg: I love it when a plan.sh comes together.
dpkg:
dpkg: Build time: 1m1s
[33][default:/src/dpkg:2]# /hab/pkgs/tas50/dpkg/1.19.4/20190201004320/bin/dpkg --help
Usage: dpkg [<option> ...] <command>
pkg (1.19.4) unstable; urgency=medium
start-stop-daemon: Do not sanity check the pidfile when it is specified as
/dev/null, as that implies the caller wants to start …
=> [dpkg] Update dpkg from 1.19.2 -> 1.19.4

jenkins/plan.sh, jenkins/tests/test.sh
Testing
```
./jenkins/tests/test.sh
```
Output
```
✓ Help command
```
=> [jenkins] Update jenkins to 2.150.1, add extra timeout for service load

zstd/plan.sh
Testing:
```
DO_CHECK=1 build zstd
```
Note: the build time is lengthy ~20 mins on an average machine.
=> [zstd] Update zstd to 1.3.8

dbus/plan.sh, dbus/tests/test.bats, dbus/tests/test.sh
```
dbus: hab-plan-build cleanup
dbus: 
dbus: Source Path: /hab/cache/src/dbus-1.13.8
dbus: Installed Path: /hab/pkgs/core/dbus/1.13.8/20181228001153
dbus: Artifact: /src/results/core-dbus-1.13.8-20181228001153-x86_64-linux.hart
dbus: Build Report: /src/results/last_build.env
dbus: SHA256 Checksum: 6d8ba3db4af416425ae7f56fb4d0a55dafc6b1eca9fc446dbef7ed6dcd858761
dbus: Blake2b Checksum: 0cf2d7a02a7529c103848a181eef35a66fea50293fae0e085fbfd6c474807b31
dbus: 
dbus: I love it when a plan.sh comes together.
dbus: 
dbus: Build time: 1m4s
```
=> [dbus] Updated dbus to 1.13.8

zsh/plan.sh
Ref #1772 - 2 tests were failing. This is still the case, but testing of ZSH post-build and install seems fine. Not a regression.
```
DO_CHECK=1 build zsh
```
Note: 2 tests will fail (see not above)
Build without tests:
```
build zsh
```
=> [zsh] Update ZSH to 5.6.2

curator/plan.sh, curator/tests/test.bats, curator/tests/test.sh, curator4/plan.sh
```
curator: hab-plan-build cleanup
curator: 
curator: Source Path: /hab/cache/src/curator-5.6.0
curator: Installed Path: /hab/pkgs/core/curator/5.6.0/20181227231616
curator: Artifact: /src/results/core-curator-5.6.0-20181227231616-x86_64-linux.hart
curator: Build Report: /src/results/last_build.env
curator: SHA256 Checksum: 71dac7c6ccf33b09d8bfe75eb258e0caa56871a59a0ab7092555edfeb200f042
curator: Blake2b Checksum: b5cd7fc791cc140aa337769e3d78a34119fe8d765f0a5ed2689b746455321253
curator: 
curator: I love it when a plan.sh comes together.
curator: 
curator: Build time: 1m18s
```
=> [curator] Updated curator to 5.6.0

node/plan.ps1, node/plan.sh, node11/plan.ps1, node11/plan.sh
Testing:
```
build node
node --version
```
=> [node/node11] Update Node and Node11 to 11.6.0

ed/plan.sh
ed: Source Path: /hab/cache/src/ed-1.15
ed: Installed Path: /hab/pkgs/tas50/ed/1.15/20190201003722
ed: Artifact: /src/ed/results/tas50-ed-1.15-20190201003722-x86_64-linux.hart
ed: Build Report: /src/ed/results/last_build.env
ed: SHA256 Checksum: be8b3a8d98f4ce7b6c5a09be149e7589833b01b36f13cf83a9d781b9f97a62c8
ed: Blake2b Checksum: 4b8483112b9a95b916fc578912bcb0694f143423bbe44c93a773080f243b3d05
ed:
ed: I love it when a plan.sh comes together.
ed:
ed: Build time: 0m4s
[27][default:/src/ed:1]# /hab/pkgs/tas50/ed/1.15/20190201003722/bin/ed --help
GNU ed is a line-oriented text editor. It is used to create, display,
modify and otherwise manipulate text files, both interactively and via
shell scripts. A restricted version of ed, red, can only edit files in
the current directory and cannot …
=> [ed] Update ed from 1.14.2 -> 1.15

dex/plan.sh
Release notes: https://github.com/dexidp/dex/releases/tag/v2.14.0
⚠️ ~Something's odd there, I'll have to investigate this. Can't build it anymore...~ 🤔 ([Update below](https://github.com/habitat-sh/core-plans/pull/2190#issuecomment-453919676))
```
mkdir: created directory '/hab/cache/src'
package github.com/dexidp/dex: build constraints exclude all Go files in /hab/cache/src/scaffolding-go-gopath/src/github.com/dexidp/dex
dex: Build time: 1m4s
dex: Exiting on error
[3][default:/src:1]#
```
=> [dex] bump v2.13.0 -> v2.14.0, declutter plan.sh

ansible/plan.sh
```
./ansible/tests/test.sh
```
```
✓ Help Command
```
Happy to wait for base plans refresh.
This PR should follow #2093
=> [ansible] Update Ansible to 2.7.6

alsa-lib/plan.sh
alsa-lib:
alsa-lib: Source Path: /hab/cache/src/alsa-lib-1.1.8
alsa-lib: Installed Path: /hab/pkgs/tas50/alsa-lib/1.1.8/20190205044343
alsa-lib: Artifact: /src/alsa-lib/results/tas50-alsa-lib-1.1.8-20190205044343-x86_64-linux.hart
alsa-lib: Build Report: /src/alsa-lib/results/last_build.env
alsa-lib: SHA256 Checksum: 19610cb86c99fd2994f2616d83935ab2dfeaef0753a2bb99f380a8fa078ed693
alsa-lib: Blake2b Checksum: aa86629e0d86a025484491605c1121f2d1c730b86c68f4180e26902b05f1eb99
alsa-lib:
alsa-lib: I love it when a plan.sh comes together.
alsa-lib:
alsa-lib: Build time: 0m49s
Changes
Core
Release v1.1.8
conf: rename snd_conf_load1() to _snd_config_load_with_include()
conf/ucm: bytcht-es8316: Add long-name UCM profiles
conf/ucm: Add UCM profile for bytcht-es8316 boards
Create shared …
=> [alsa-lib] update alsa-lib 1.1.7 -> 1.1.8

graphviz/plan.sh, graphviz/tests/input.dot, graphviz/tests/test.bats, graphviz/tests/test.sh
The current build of this package is rather broken.  First, expected
executables are not available via `hab pkg exec`
```
hab pkg exec core/graphviz dot
✗✗✗
✗✗✗ `dot' was not found on the filesystem or in PATH
✗✗✗
```
If you call the executables directly, they fail because the package is
missing dependencies:
```
ldd /hab/pkgs/core/graphviz/2.40.1/20190116235243/bin/dot
linux-vdso.so.1 (0x00007ffecbae5000)
libgvc.so.6 => /hab/pkgs/core/graphviz/2.40.1/20190116235243/lib/libgvc.so.6 (0x00007fd50fb89000)
libltdl.so.7 => not found
libdl.so.2 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libdl.so.2 (0x00007fd50fb82000)
libxdot.so.4 => /hab/pkgs/core/graphviz/2.40.1/20190116235243/lib/libxdot.so.4 (0x00007fd50fb7a000)
libcgraph.so.6 => …
```
=> [graphviz] Add libtool to runtime deps, add bin dir

devicemapper/plan.sh, devicemapper/tests/test.bats, devicemapper/tests/test.sh
```
devicemapper: hab-plan-build cleanup
devicemapper: 
devicemapper: Source Path: /hab/cache/src/LVM2.2.03.00
devicemapper: Installed Path: /hab/pkgs/core/devicemapper/2.03.00/20181228005216
devicemapper: Artifact: /src/results/core-devicemapper-2.03.00-20181228005216-x86_64-linux.hart
devicemapper: Build Report: /src/results/last_build.env
devicemapper: SHA256 Checksum: 73f463c44cd4646d57867b226d7ceb7421665ba6c6951b3e27929d7f54823287
devicemapper: Blake2b Checksum: 5d55e59a9b6d4f5a2752e8c5b2cd28e9c2d1165021f25f3304ac516e350a118c
devicemapper: 
devicemapper: I love it when a plan.sh comes together.
devicemapper: 
devicemapper: Build time: 1m6s
```
=> [devicemapper] Updated devicemapper to 2.03.00

nss/plan.sh
Fixes #2224 
```
build nss
ldd /hab/pkgs/${pkg_ident}/lib/libgtest1.so
ldd /hab/pkgs/${pkg_ident}/lib/libgtestutil.so
```
```
[47][default:/src:0]# ldd /hab/pkgs/${pkg_ident}/lib/libgtest1.so
linux-vdso.so.1 (0x00007ffc2d386000)
libnssutil3.so => /hab/pkgs/rakops/nss/3.40.1/20190130063830/lib/libnssutil3.so (0x00007f31f72ae000)
libplc4.so => /hab/pkgs/core/nspr/4.12/20190115184843/lib/libplc4.so (0x00007f31f72a7000)
libplds4.so => /hab/pkgs/core/nspr/4.12/20190115184843/lib/libplds4.so (0x00007f31f72a1000)
libnspr4.so => /hab/pkgs/core/nspr/4.12/20190115184843/lib/libnspr4.so (0x00007f31f7260000)
libssl3.so => /hab/pkgs/rakops/nss/3.40.1/20190130063830/lib/libssl3.so (0x00007f31f720a000) …
```
=> [nss] Adds gcc-libs dep for nss

node10/plan.ps1, node10/plan.sh
Testing
```
build node10
node --version
```
=> [node10] Update node10 to 10.15.0

php/plan.sh
```
build php
./php/test/test.sh ${pkg_ident}
php --version
```
```
» Installing core/php/7.3.1/20190109050058
→ Using core/php/7.3.1/20190109050058
★ Install of core/php/7.3.1/20190109050058 complete with 0 new packages installed.
Libzip is supported.
PHP 7.3.1 (cli) (built: Jan  9 2019 05:11:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
```
=> [php] Update PHP to 7.3.1

telegraf/plan.sh, telegraf/tests/test.bats, telegraf/tests/test.sh
This supersedes #2184
```
./telegraf/tests/test.sh
```
```
```
=> [telegraf] Update telegraf to 1.9.4, add tests

node8/plan.sh
Testing
```
build node8
node --version
```
=> [node8] Update node8 to 8.15.0

.bldr.toml, clang5/README.md, clang5/plan.sh, llvm5/README.md, llvm5/plan.sh
In the recent base-plans-refresh #1767 we updated the version of GCC from 7 to 8.    llvm5 is unable to build with this new version and needs to be deprecated. Since clang5 requires llvm5 to build, it is deprecated as part of this PR as well.
Adding a gcc7 plan would be a relatively safe operation as it would be primarily used at build time, but would necessitate the addition of a gcc7-libs package. With gcc7-libs, you could potentially end up in a state where you have two different versions of gcc libraries that your software would consume at runtime leading to unexpected behavior. 
Consider two fictional packages, A and B.  A has a runtime dependency on `gcc-libs` and `B`. `B` has a runtime dependency on `gcc7-libs`.  When you execute a command from A, it will start to load the …
=> [llvm5][clang5] Deprecate llvm5 and clang5

elixir/plan.sh
```
./elixir/tests/test.sh
```
```
```
=> [elixir] Update Elixir to 1.8.0

gnatsd/plan.sh, gnatsd/tests/test.sh
```
./gnatsd/tests/test.sh
```
```
The rakops/gnatsd/1.4.0/20190116003341 service was successfully loaded
✓ Help command
✓ Listening on port 8222 (HTTP)
✓ Listening on port 4242 (NATS)
```
=> [gnatsd] Update gnatsd to 1.4.0, extend test sleep delay

ansible/plan.sh, ansible/tests/test.sh
Fixes #2206 - Also fixed tests to work correctly based on users / test server origin settings.
```
./ansible/tests/test.sh
source ansible/plan.sh
find $(hab pkg path "${HAB_ORIGIN}/${pkg_name}") -iname "*.so" -exec ldd \{\} \; | grep -i "not found"
```
```
✓ Help Command
[57][default:/src:0]# find $(hab pkg path "${HAB_ORIGIN}/${pkg_name}") -iname "*.so" -exec ldd \{\} \; | grep -i "not found"
[58][default:/src:1]# 
```
NOTE: The exit code from the `find | ldd` should be `1` to indicate no instances of "not found" entries were in the ldd output.
=> [ansible] Move OpenSSL dep

.bldr.toml, scaffolding-inspec/lib/scaffolding.sh, scaffolding-inspec/plan.sh
In doing some work on making scaffolding-chef able to drop a file on disk to other packages can react to it, it's really becoming necessary to publish a scaffolding-inspec.
Really, the guts of this scaffolding is just the standardized run hook and inspec.json. Authors that consume this scaffolding will be writing their own default.toml.
This scaffolding is well suited to become a generator, should generators become a thing™
=> [scaffolding-inspec] first stab at an inspec scaffolding

rpm/plan.sh
- Added missing runtime deps for RPM
- Rolled version forward to 4.14.2.1
- Cleaned up plan
This resolves #2225 
=> [rpm] Added missing runtime deps for RPM and updated to 4.14.2.1

sensu/Gemfile, sensu/README.md, sensu/hooks/run, sensu/plan.sh
- Updated sensu to 1.6.2
- Fixed library linking issues
- Minor plan cleanup
- Updated plan so it actually runs the build from HAB_CACHE_SRC, so it doesn't dump bundler files into the source directory
- Cleaned up readme headers
This resolves #2227 
It looks like the run hook was setting LD_LIBRARY_PATH due to bad rpaths. Removed this as extensions are now properly linked
=> [sensu] Update to 1.6.2 and fix library linking issues

.bldr.toml, CODEOWNERS, openjdk11/README.md, openjdk11/plan.sh
OpenJDK 11 is an [LTS Release](https://dzone.com/articles/jdk-11-release-candidate-update-and-openjdk-jdk-11) of OpenJDK.
Given [Oracle's licensing changes](https://www.aspera.com/en/blog/oracle-will-charge-for-java-starting-in-2019/) I recommend we deprecate all Oracle Java SE plans in core-plans, and only support OpenJDK moving forward.
=> [openjdk11] Create a plan for OpenJDK 11

clang/plan.sh
Add in `-DLLVM_ENABLE_RTTI=ON` since this flag was also enabled from `core/llvm`.  This will close #2270. 
Note: Looked at Archlinux [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/llvm#n43) and choosing not to use shared libs.  Rationale: most builds in hab are deterministic.
```bash
DO_CHECK=1 clang/tests/test.sh
```
```bash
...
clang: I love it when a plan.sh comes together.
clang:
clang: Build time: 76m26s
...
✓ Commands are on path
✓ Check libclang.so exists
✓ Check libclang.so does not have any "not found" shared libs
```
Note: the version test tries to execute `clang --version`, so if that fails then there is most likely a segfault.
Signed-off-by: Ben Dang …
=> [clang] Fix clang bins from segfaulting

caddy/plan.sh, caddy/tests/test.bats, caddy/tests/test.sh
```
./caddy/tests/test.sh
```
```
✓ Help command
```
=> [caddy] Update caddy 0.11.3, add tests

buildkite-cli/plan.sh
Release Notes: https://github.com/buildkite/cli/releases/tag/v0.4.0
=> [buildkite-cli] Update to 0.4.0

iproute2/plan.sh
I've also included a small tool to check all the files in a given
package directory. Perhaps over time we can integrate something
similar into the CI tests:
Before:
```
> bin/check-bins.sh /hab/pkgs/core/iproute2/4.16.0/20190216142156/
MISSING DEPENDENCIES
/hab/pkgs/core/iproute2/4.16.0/20190216142156/lib/tc/m_xt.so:
libxtables.so.11
> echo $?
1
```
After:
```
> bin/check-bins.sh /hab/pkgs/core/iproute2/4.16.0/20190216150620
> echo $?
0
```
Fixes #2218
=> [iproute2] Fix missing iptables dependency in m_xt.so

bin/check-bins.sh
This script reports any files in the given pkg directory that have
missing dynamic dependencies according to ldd.
Example output:
```
> bin/check-bins.sh /hab/pkgs/core/iproute2/4.16.0/20190216142156/
MISSING DEPENDENCIES
/hab/pkgs/core/iproute2/4.16.0/20190216142156/lib/tc/m_xt.so:
libxtables.so.11
> echo $?
1
```
The goal of this script is to help us check packages for missing
dependencies.
=> Add bin/check-bins.sh

scaffolding-node/lib/scaffolding.sh, scaffolding-node/plan.sh
- Change bash if check file test from -c to -f. This changes from testing if the .npmrc file is a character special file (/dev/random, /dev/null, etc...) to testing if the file exists.
Can see changes with scottvidmar/scaffolding-node in public builder
Signed-off-by: Scott Vidmar <svidmar@chef.io>
=> Fix for scaffolding-node plan not detecting .npmrc files.

leveldb/plan.sh
Fixes #2220 
```
build leveldb
find /hab/pkgs/${pkg_ident}/lib -type f -exec echo "{}" \; -exec ldd {} \;
```
```
/hab/pkgs/rakops/leveldb/1.20/20190131001554/lib/libleveldb.so
linux-vdso.so.1 (0x00007ffe58e91000)
libsnappy.so.1 => /hab/pkgs/core/snappy/1.1.4/20190117153136/lib/libsnappy.so.1 (0x00007f087efd9000)
libstdc++.so.6 => /hab/pkgs/core/gcc-libs/8.2.0/20190115011926/lib/libstdc++.so.6 (0x00007f087ec23000)
libm.so.6 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libm.so.6 (0x00007f087ea90000)
libgcc_s.so.1 => /hab/pkgs/core/gcc-libs/8.2.0/20190115011926/lib/libgcc_s.so.1 (0x00007f087efbf000)
libpthread.so.0 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libpthread.so.0 …
```
=> [leveldb] Add gcc libs

libfcgi/plan.sh
Fixes #2221 
```
build libfcgi
ldd /hab/pkgs/${pkg_ident}/lib/libfcgi++.so.0.0.0
```
```
linux-vdso.so.1 (0x00007ffe9cbaa000)
libfcgi.so.0 => /hab/pkgs/rakops/libfcgi/2.4.0/20190131014632/lib/libfcgi.so.0 (0x00007f5039893000)
libgcc_s.so.1 => /hab/pkgs/core/gcc-libs/8.2.0/20190115011926/lib/libgcc_s.so.1 (0x00007f5039879000)
libc.so.6 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libc.so.6 (0x00007f50396c1000)
/hab/pkgs/core/glibc/2.27/20180608041157/lib64/ld-linux-x86-64.so.2 (0x00007f5039687000)
```
=> [libfcgi] Add gcc libs to deps

boost/plan.sh, boost159/plan.sh
Fixes #2208 and Fixes #2209 
```
build boost
ldd /hab/pkgs/${pkg_ident}/lib/libboost_iostreams.so.1.66.0
```
```
ldd /hab/pkgs/${pkg_ident}/lib/libboost_iostreams.so.1.66.0
linux-vdso.so.1 (0x00007ffcfa5b1000)
libz.so.1 => /hab/pkgs/core/zlib/1.2.11/20190115003728/lib/libz.so.1 (0x00007ff4cba49000)
librt.so.1 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/librt.so.1 (0x00007ff4cba3f000)
libstdc++.so.6 => /hab/pkgs/core/gcc-libs/8.2.0/20190115011926/lib/libstdc++.so.6 (0x00007ff4cb65b000)
libm.so.6 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libm.so.6 (0x00007ff4cb8ac000)
libgcc_s.so.1 => /hab/pkgs/core/gcc-libs/8.2.0/20190115011926/lib/libgcc_s.so.1 (0x00007ff4cb892000) …
```
=> [boost/boost159] Move gcc-libs to pkg_deps

openresty/plan.sh
```
build openresty
hab pkg install --binlink core/curl
curl http://localhost
```
```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      16641/nginx.conf
tcp        0      0 0.0.0.0:9631            0.0.0.0:*               LISTEN      81/hab-sup
tcp        0      0 127.0.0.1:9632          0.0.0.0:*               LISTEN      81/hab-sup
tcp        0      0 0.0.0.0:9638            0.0.0.0:* …
```
=> [openresty] Update OpenResty to 1.13.6.2

elasticsearch5/plan.sh
This defines the do_install function inside the elasticsearch5 plan.  Previously it relied on the sourced definition from Elasticsearch.  Necessary changes to the build of that package were made that are unfortunately incomparable with elasticsearch5. 
=> [elasticsearch5] Add do_install to elasticsearch5

.bldr.toml, metricbeat/README.md, metricbeat/config/metricbeat.yml, metricbeat/default.toml, metricbeat/hooks/init, metricbeat/hooks/run, metricbeat/plan.sh, metricbeat/tests/test.bats, metricbeat/tests/test.sh
Adding a new plan for metricbeat. This is very similar to filebeat in operation and structure.
Includes tests and tested this on a live elasticsearch cluster.
```
curl 10.1.1.188:9200/_cat/indices
yellow open metricbeat-6.6.0-2019.02.20 mssQCM1OSZu571zBKA1CUg 5 1 1753 0 1.8mb 1.8mb
```
=> [metricbeat] added metricbeat

haproxy/plan.sh
The current build of haproxy cannot resolve IPv6 only hosts.  If you
try to proxy to hostname that only has IPv6 entries you'll get:
```
haproxy.default(O): [ALERT] 051/143308 (2616) : parsing
[config/haproxy.conf:15] : 'server atest' : could not resolve address
'ipv6.test-ipv6.com'.
```
From
https://github.com/haproxy/haproxy/blob/fba74ea7b0bc55dfd8a84ba5ecb78ff363e61bc4/INSTALL#L420-L429:
> Recent systems can resolve IPv6 host names using getaddrinfo(). This primitive
> is not present in all libcs and does not work in all of them either. Support in
> glibc was broken before 2.3. Some embedded libs may not properly work either,
> thus, support is disabled by default, meaning that some host names which only
> resolve as IPv6 addresses will not resolve and configs might emit an error
> …
=> [haproxy] Compile with USE_GETADDRINFO=1

mesa/patches/000-llvm7-support.patch, mesa/plan.sh
closes #2241 
This patches the current version of mesa to build with llvm7.  
There is a new major version of mesa available, however it requires X libraries that we currently don't have in the core origin. This is a temporary workaround to allow downstream dependencies (libepoxy, gtk) to build again after our update to gcc8. 
Package contains no binaries to test, so I built a dependency (`core/libepoxy`) against it to verify.
=> [mesa] Patch mesa to build with llvm7

consul/plan.sh
Hey all,
Another simple update. This brings Consul to 1.4.2. To test this build, please enter the studio and run:
```
```
```
```
=> [Consul] Updating Consul to 1.4.2

ghc/plan.ps1
Added GHC plan for windows
This uses the binary GHC distribution with bundled mingw. This is going to be our best option until we have replicated a full toolchain for windows.
=> [ghc] Add ghc plan for windows

cabal-install/plan.ps1
Added cabal-install plan for windows
This uses the binary cabal-install distribution built against mingw. This is going to be our best option until we have replicated a full toolchain for windows.
This is dependent on #2265
=> [cabal-install] Added cabal-install plan for windows

bdwgc7/README.md, bdwgc7/plan.sh, bdwgc8/README.md, bdwgc8/plan.sh
The `pkg_name` for `bdwgc7` and `bdwgc8` did not correspond to what the folder name was.  This fixes that.  Closes #2311 
=> [bdwgc*] Fix pkg_names to match folder name

visual-build-tools-2017/plan.ps1
We noticed that building this plan was taking well over an hour and failing after filling up disk space. It was last build in 2017 and was reasonably sized at the time. Either there has been a ton more components added since then or the installer logic has changed to install everything instead of a smaller subset.
This add the msbuild and c++ workloads along with the optional ATLMFC component which seems to match up closely to what this package originally included and it builds in a reasonable amount of time.
I've tested to ensure that plans that use this still build successfully with this change.
=> [visual-build-tools-2017] pull in alacarte workloads

msodbcsql17/plan.sh
Looks like newer versions of file recognize the ODBC driver as application/x-pie-executable rather than application/x-sharedlib, which was causing the patchelf to fail.
This resolves #2223
=> [msodbcsql17] Fixed file type for msodbcsql patchelf

ruby23/README.md, ruby23/plan.sh, ruby24/README.md, ruby24/plan.sh, ruby25/README.md
There are multiple CVEs in the existing packages that have been fixed since last March.
[5][default:/src/ruby23:130]# /hab/pkgs/tas50/ruby23/2.3.8/20190226234706/bin/gem list
*** LOCAL GEMS ***
bigdecimal (default: 1.2.8)
bundler (default: 1.16.6)
did_you_mean (1.0.0)
io-console (default: 0.4.5)
json (default: 1.8.3.1)
minitest (5.8.5)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (default: 2.1.0.1)
rake (10.4.2)
rb-readline (0.5.5)
rdoc (default: 4.2.1)
rubygems-update (2.7.8)
test-unit (3.1.5)
[9][default:/src/ruby24:0]# /hab/pkgs/tas50/ruby24/2.4.5/20190226235513/bin/gem list
*** LOCAL GEMS ***
bigdecimal (default: 1.3.2)
bundler (default: 1.16.6)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.4)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.9) …
=> [ruby24][ruby23] Updates packages to the latest releases to resolve multiple CVEs

c-ares/README.md, c-ares/plan.sh
Minor bump to 1.15.
[Changelog](https://c-ares.haxx.se/changelog.html#1_15_0)
- Switch to ninja for faster builds
- Build both shared libs and static libs
- Inject cmake config into `CMAKE_FIND_ROOTH_PATH`
- This adds in do_check() tests
- Switch to github.com for the authoriative source files
Note: this tarball contains all source files packaged in
`test/fuzzinput` and `test/fuzznames`
```
DO_CHECK=1 build
```
=> [c-ares] minor bump to 1.15

dotnet-asp-core/plan.sh
Hey all,
This is just a version bump, bringing the Linux plan up to the latest version (2.2.2). To test this build, enter the studio and run:
```
```
```
✓ Help command
✓ ASP check
```
Let me know if there are any questions or comments.
=> [dotnet-asp-core] Updating Linux plan to 2.2.2

mesa/patches/001-llvm-enable-new-fast-math-flags.patch, mesa/plan.sh
This is a follow-on to #2288.   
Mesa contains only libraries, so this was tested by building libepoxy against a build with this patch applied.
=> [mesa] Additional patch build against llvm 7.0.1

.bldr.toml, ruby26/README.md, ruby26/plan.sh
[9][default:/src/ruby26:126]# /hab/cache/src/ruby-2.6.1/ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
=> [ruby] Add ruby26 plan

artifactory-pro/plan.sh
Hey all,
This is a simple version bump. To test this, please enter the studio and run:
```
```
The result should be: 
```
```
Please let me know if there are questions or comments.
=> [Artifactory Pro] Updating Artifactory Pro to 6.8.2

caddy/plan.sh
```
./caddy/tests/test.sh
```
```
✓ Help command
```
=> [caddy] Update caddy to 0.11.5

jenkins/plan.sh
```
./jenkins/tests/test.sh
```
```
✓ Help command
```
=> [jenkins] Update Jenkins to latest LTS 2.150.3

nginx/plan.ps1, nginx/plan.sh
Testing
```
```
Output
```
The core/nginx/1.15.8/20181227044533 service was successfully loaded
✓ Help command
```
=> [nginx] Update nginx to 1.15.8

openssl/plan.ps1, openssl/plan.sh
openssl: hab-plan-build cleanup
openssl:
openssl: Source Path: /hab/cache/src/openssl-1.0.2r
openssl: Installed Path: /hab/pkgs/tas50/openssl/1.0.2r/20190227000817
openssl: Artifact: /src/openssl/results/tas50-openssl-1.0.2r-20190227000817-x86_64-linux.hart
openssl: Build Report: /src/openssl/results/last_build.env
openssl: SHA256 Checksum: 2dfc0984cc15dfb0ebdeb9604752ce448f8e13778e07f39b6bd489da54ad3ea9
openssl: Blake2b Checksum: bdd39174be5c43741a684aaa483f16c7288bd0483828e1e475c40161fd7689b8
openssl:
openssl: I love it when a plan.sh comes together.
openssl:
openssl: Build time: 2m57s
=> [openssl] Update plans to 1.0.2r to patch the latest CVE

telegraf/plan.sh
```
./telegraf/tests/test.sh
```
```
```
=> [telegraf] Update telegraf to 1.10.0

dd-agent/plan.sh
```
./dd-agent/tests/test.sh
```
```
```
Note that this is testing the supervisor version still, but its the best test we have.
Starting the service works, but you will need to BYO datadog API Key.
=> [dd-agent] Update dd-agent to 5.32.1

php/plan.sh
```
build php
./php/tests/test.sh ${pkg_ident}
```
```
./php/test/test.sh rakops/php/7.3.3/20190307005119
» Installing rakops/php/7.3.3/20190307005119
→ Using rakops/php/7.3.3/20190307005119
★ Install of rakops/php/7.3.3/20190307005119 complete with 0 new packages installed.
Libzip is supported.
```
=> [php] Update PHP to 7.3.3

consul/plan.sh
```
```
```
```
Removed user declaration, as it was the default.
=> [consul] Update consul to 1.4.3, cleanup a bit

node/plan.ps1, node/plan.sh, node11/plan.ps1, node11/plan.sh
```
build node
hab pkg install --binlink --force results/${pkg_artifact}
node --version
```
```
v11.11.0
```
=> [node] Update node to 11.11.0

kubernetes-apiserver/default.toml, kubernetes-apiserver/hooks/run
**Prerequisites**
* Linux or MacOS on the host (Windows is not supported)
* [Vagrant](https://www.vagrantup.com/downloads.html)
* [Virtual Box](https://www.virtualbox.org/wiki/Downloads)
* [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/)
* [cfssl](https://github.com/cloudflare/cfssl#installation) (with cfssljson)
* [jq](https://stedolan.github.io/jq/download/) Command-line JSON processor
**Steps**
```
$ git clone https://github.com/kinvolk/kubernetes-the-hab-way.git
$ git checkout origin/indradhanush/configure-requestheader-client
```
This branch has the necessary changes required that uses the config flags added in this PR. To test the changes I had build the package and uploaded under my personal origin at: `indradhanush/kubernetes-apiserver`. As a result, it uses this …
=> [kubernetes-apiserver] Add config flags for requestheaders

.bldr.toml, rebar/README.md, rebar3/plan.sh, rebar3/tests/test.bats, rebar3/tests/test.sh
This PR:
* Updates rebar3 to 3.9.0
* Deprecates rebar
Following merge, according to [RFC7](https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0007-deprecating-packages.md) we need to:
* Mark `core/rebar` as private
* Disconnect `core/rebar` from builder
```
./rebar3/tests/test.sh
```
```
✓ Help command
```
=> [rebar/rebar3] rebar3 update to 3.9.0, deprecate rebar

rebar/plan.sh, rebar3/plan.sh
Incorrect deprecation flagging.
=> [rebar/rebar3] Fix incorrect deprecation flag

CONTRIBUTING.md, openssl/README.md
Merging #2323 took a lot longer than I would have liked due to the lack of automation and documentation.
Here is a first step to resolve that issue.
Merging this will also close out #2339
=> [openssl] add docs for openssl maintainers

redis3/plan.sh
```
build redis3
netstat -peanut | grep redis
```
```
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      4890/redis-server *
tcp        0      0 :::6379                 :::*                    LISTEN      4890/redis-server *
```
=> [redis3] Update Redis3 to 3.2.13

postgresql11-client/plan.ps1
xlog executables are not part of the pg11 package for windows provided by upstream. This removes the attempted removal during our install phase. 
=> [postgresql11-client] Remove reference to xlog executables

node/plan.ps1, node/plan.sh, node11/plan.ps1, node11/plan.sh
```
build node11
hab pkg install --binlink ${pkg_ident}
node --version
```
```
v11.12.0
```
=> [node/node11] Update NodeJS to 11.12.0

redis/plan.sh, redis4/plan.sh
```
build redis4
netstat -peanut | grep redis
```
```
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      108/redis-server *:
tcp        0      0 :::6379                 :::*                    LISTEN      108/redis-server *:
```
=> [redis4] Update Redis4 to 4.0.14

vault/plan.sh
```
```
```
✓ Help command
```
=> [vault] Update Vault to 1.1.0

filebeat/plan.sh
* [Changelog 6.7.0](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.7.0.html)
* [Changelog 6.6.2](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.6.2.html)
* [Changelog 6.6.1](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.6.1.html)
* [Changelog 6.6.0](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.6.0.html)
```
./filebeat/tests/test.sh
```
```
✓ Help command
```
=> [filebeat] Update filebeat to 6.7.0, minor cleanup

metricbeat/plan.sh
* [Changelog 6.7.0](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.7.0.html)
* [Changelog 6.6.2](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.6.2.html)
* [Changelog 6.6.1](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.6.1.html)
```
./metricbeat/tests/test.sh
```
```
✓ Help command
```
=> [metricbeat] Update metricbeat to 6.7.0, minor cleanup

node10/plan.ps1, node10/plan.sh
* (Changelog 10.15.1)[https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.15.1]
* (Changelog 10.15.2)[https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.15.2]
```
build node10
hab pkg install --binlinkresults/${pkg_artifact}
node --version
```
```
v10.15.2
```
Note: While this is not the latest version, to update Kibana to 6.7.0, it needs 10.15.2, so I'm submitting this PR for acceptance and promotion, before doing Node 10.15.3.
=> [node10] Update Node10 to 10.15.2 (required for Kibana)

.bldr.toml, erlang/plan.sh, erlang20/README.md, erlang20/plan.sh, erlang20/tests/test.bats, erlang20/tests/test.sh, erlang21/README.md, erlang21/plan.sh, erlang21/tests/test.bats, erlang21/tests/test.sh
```
./erlang/tests/test.sh
```
```
```
This is a decent test, as it uses erlang itself to evaluate the version.
=> [erlang] Update erlang to 21.3

.github/PULL_REQUEST_TEMPLATE/major-version-up.md, .github/PULL_REQUEST_TEMPLATE/minor-version-up.md, .github/PULL_REQUEST_TEMPLATE/new-plan.md
This PR adds [PR Templates](https://help.github.com/en/articles/about-issue-and-pull-request-templates) for three frequent contribution scenarios.  The goal is to make the expectations for a contribution more transparent to the contributor and provide links to more detailed documentation for why we have set these expectations.  Hopefully maintainers will also benefit from having a checklist as part of each PR.
=> Add Initial PR templates

.expeditor/generate_verify_pipeline.sh
`git merge-base $BUILDKITE_BRANCH master` returns "" in the context it is executed in in the pipeline.   This addresses that by using HEAD which will always give us the thing that we want to test. 
=> Use HEAD instead of BUILDKITE_BRANCH

httpd/plan.sh, httpd/tests/test.bats
* [Changelog](https://svn.apache.org/repos/asf/httpd/httpd/branches/2.4.x/CHANGES)
```
./httpd/tests/test.sh
```
```
✓ Help command
✓ Multiple processes
```
=> [httpd] Update httpd to 2.4.38, Fix tests to allow for ipv6 listening

relx/plan.sh
With the change of core/erlang to version 21, relx builds would fail with 
```
===> Compiling _build/default/lib/erlware_commons/src/ec_plists.erl failed
_build/default/lib/erlware_commons/src/ec_plists.erl:834: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
_build/default/lib/erlware_commons/src/ec_plists.erl:836: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
```
This updates relx to the most recent version to resolve the build issues.  Additionally, it adds `core/coreutils` to the dependencies to allow relx to function. Previous versions of the package would fail as below because the relx escript started with `#!/usr/bin/env escript` . The output of before and after are shown …
=> [relx] update to latest (3.29.0)

.expeditor/generate_verify_pipeline.sh, .expeditor/templates/verify.pipeline.yml
This will hopefully resolve issues like https://buildkite.com/chef-oss/habitat-sh-core-plans-master-verify/builds/49#a8ad4c8c-ff90-41e2-b347-e213045f1c8b where the pipeline is generating pipeline steps unrelated to the PR.   Ref: https://github.com/habitat-sh/core-plans/pull/2386#discussion_r269819442
=> Fetch master at the start of pipeline generation

cabal-install/plan.sh
This should fix the random pthread_cancel errors we have been seeing over the last year when building packages with cabal-install. It looks like depending on the studio environment, this would either work properly or not, depending on the underlying gcc-libs.
https://buildkite.com/chef-oss/habitat-sh-core-plans-master-verify/builds/14#ffc1dd5c-3c8a-47d5-aaa3-b224d77dcff5/161-449 for an example failure.
Credit to @smacfarlane for digging into this.
=> [cabal-install] Added gcc-libs as a runtime dep for cabal-install

.bldr.toml, hspec-discover/README.md, hspec-discover/plan.sh
Adds hspec-discover which is a binary used by GHC and hspec to dynamically discover and run Hspec tests.  
Using cabal flags:
```
--disable-executable-dynamic \
--disable-shared
```
To prevent dynamic linking of haskell libraries and the publishing of libraries that link to internal GHC libraries, as we only care about the binary. This is likely to fix to shellcheck issue #2228. I'll need to update that plan and confirm.
=> [hspec-discover] Added hspec discover plan

artifactory/plan.sh, artifactory/tests/helpers.bash, artifactory/tests/test.bats, artifactory/tests/test.sh
Hey all,
This update brings Artifactory OSS to 6.9.0 and adds tests. To test this build, please enter the studio and run:
```
```
```
```
=> [Artifactory] Update to 6.9.0 and added tests

bin/ci/shellcheck.sh
SC1117 is considered "too pedantic" by the Shellcheck author and has been retired in versions > 0.5.0.  Since we are currently running 0.5.0 in Buildkite, this check causes a lot of erroneous failures. 
Ref: #2395
=> Disable Shellcheck SC1117

CODEOWNERS
=> add echohack to CODEOWNERS for elastic projects [filebeat] [metricbeat] [journalbeat] [elasticsearch]

luajit/plan.sh, luajit/tests/test.bats, luajit/tests/test.sh
This changes the plan name from `LuaJIT` to `luajit`.
Open for discussion, but I feel this makes more sense. The binary is `luajit`.
```
build luajit
luajit -v
```
```
LuaJIT 2.0.5 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
```
=> [luajit] Change LuaJIT plan name to luajit

artifactory-pro/plan.sh
Hey all,
This update brings Artifactory Pro to version 6.9.0. To test this build, enter the Studio and run:
```
```
The output should return:
```
```
Please let me know if there are any questions or suggestions. Thanks!
=> [Artifactory Pro] Updated to 6.9.0

cerebro/plan.sh, cerebro/tests/test.bats, cerebro/tests/test.sh
Also change test order to make sense.
```
./cerebro/tests/test.sh
```
```
```
=> [cerebro] Update Cerebro to 0.8.2, reduce testing wait

dotnet-asp-core/plan.ps1, dotnet-asp-core/plan.sh
This update brings both the Windows and Linux plans up to version 2.2.3. 
To test the Linux build, please enter the Studio and run:
```
```
```
✓ Help command
✓ ASP check
```
Please let me know if there are suggestions or questions. Thanks!
=> [dotnet-asp-core] Updated plans to 2.2.3

node/plan.ps1, node/plan.sh, node11/plan.ps1, node11/plan.sh
```
build node
hab pkg install results/${pkg_artifact}
node --version
```
```
v11.13.0
```
=> [node/node11] Update node to 11.13.0

telegraf/plan.sh, telegraf/tests/test.bats, telegraf/tests/test.sh
```
./telegraf/tests/test.sh
```
```
```
=> Update telegraf to 1.10.2, add minimal service test

elasticsearch/plan.sh
* [Changelog](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/release-notes-6.7.1.html)
```
./elasticsearch/tests/test.sh
```
```
✓ Open port 9200
✓ Open port 9300
✓ Service Healthcheck
```
=> [elsaticsearch] Update elasticsearch to 6.7.1

dotnet-core/plan.ps1, dotnet-core/plan.sh
Hello all,
This PR updates the Linux and WIndows plans to 2.2.3. To test the Linux build, enter the Hab studio and run:
```
```
```
✓ Help command
```
=> [dotnet-core] Updated Linux and Windows plans to 2.2.3

cerebro/plan.sh, cerebro/tests/test.sh
* [Changelog](https://github.com/lmenezes/cerebro/blob/master/CHANGES.md#v083---april-5th-2019)
```
./cerebro/tests/test.sh
```
```
```
=> [cerebro] Update cerebro to 0.8.3, standardize testing

.expeditor/generate_verify_pipeline.sh, .expeditor/templates/verify_linux_pipeline.yml, .expeditor/templates/verify_shared_pipeline.yml
Ref #2414 
This moves the check for a .bldr.toml entry to a "shared" pipeline. This can be used for checks that need to happen that are independent of platform, but only need to be executed once.
=> [CI] Move check for .bldr.toml entry to 'shared' pipeline

.expeditor/templates/verify_shared_pipeline.yml
Specifying 'steps' more than once in a buildkite pipeline definition results in only the last set being run.  This removes the steps key from the shared pipeline definition and relies on its presence in the `verify.pipeline.yml`
=> [CI] Remove 'steps' from shared pipeline definition

.bldr.toml, libmaxminddb/README.md, libmaxminddb/plan.sh, libmaxminddb/tests/test.bats, libmaxminddb/tests/test.sh
@smacfarlane This is the replacement for `geoip`.
When running with `DO_CHECK=true`, I get one test failure that is 32-bit dependent:
```
ok 1 - open ./maxmind-db/test-data/MaxMind-DB-test-mixed-32.mmdb status is success - mmap mode
ok 2 - mmdb struct has been set for ./maxmind-db/test-data/MaxMind-DB-test-mixed-32.mmdb - mmap mode
libgcc_s.so.1 must be installed for pthread_cancel to work
/bin/sh: line 5:  9355 Aborted                 (core dumped) ${dir}$tst
FAIL: threads_t
```
=> [libmaxminddb] Added the libmaxminddb plan.

hugo/plan.sh, hugo/tests/test.bats
* [Changelog](https://github.com/gohugoio/hugo/releases/tag/v0.55.0)
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.55.0 - Add more complete testing

.bldr.toml, dotnet-472-dev-pack/plan.ps1
This updates the donet-472-dev-pack plan.ps1 to include all required metadata so that we are able to connect it to Builder.  
=> [dotnet-472-dev-pack] Include all required metadata 

filebeat/plan.sh
* [Changelog 6.7.1](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.7.1.html)
```
./filebeat/tests/test.sh
```
```
✓ Help command
```
=> [filebeat] minor version up 6.7.1

metricbeat/plan.sh
* [Changelog 6.7.1](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.7.1.html)
```
./metricbeat/tests/test.sh
```
```
✓ Help command
```
=> [metricbeat] minor version up 6.7.1

journalbeat/plan.sh
* [Changelog 6.7.1](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-6.7.1.html)
```
./journalbeat/tests/test.sh
```
```
✓ Help command
```
=> [journalbeat] minor version up 6.7.1

.expeditor/templates/verify.pipeline.yml, .expeditor/templates/verify_linux_pipeline.yml, .expeditor/templates/verify_shared_pipeline.yml, bin/ci/check-bad-patterns.sh
This PR rewrites the the check-bad-patterns script to consider `plan.sh/ps1` and any files in `hooks`  The reason behind this change is previous versions of this script started with the plan.sh and attempted follow any source files. This could cause errors if script wasn't executed from the expected path, for example with node11.  
There was also a bug introduced with the migration to Buildkite that it was no longer checking any files except the plan.sh.   
The rationale behind only checking hooks and plan.sh/ps1 is that those are the only files that are strictly habitat.  Files in config, patch files or other metadata have external requirements imposed upon them, and can't be evaluated for the same patterns as Habitat-specific files. 
Additionally,  since we are now considering a …
=> [CI] Rewrite check-bad-patterns ci script

vault/plan.sh
* [Changelog](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md)
```
```
```
✓ Help command
```
=> [vault] Upgrade vault to 1.1.1

.bldr.toml, dotnet-471-dev-pack/plan.ps1
This updates the donet-471-dev-pack plan.ps1 to include all required metadata so that we are able to connect it to Builder.  
=> [dotnet-471-dev-pack] Include all required metadata 

opam/plan.sh
From https://opam.ocaml.org/doc/Install.html
> Note that opam1.2.2 doesn't build from source with OCaml 4.06.0. Use this command to compile lib_ext
> OCAMLPARAM="safe-string=0,_" make lib-ext
This updates the opam plan.sh so that it is able to build again. 
Note: There is a new major version out, and it appears that they support both the new major and this version.  I'd like to split that task into a later PR and let this fix the builds of the existing version of opam first.
=> Resolve build error with ocaml >= 4.0.6

systemd/plan.sh
* [Changelog](https://github.com/systemd/systemd/blob/master/NEWS)
```
build systemd
systemctl --version
```
```
systemd 242 (242)
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL +XZ +LZ4 -SECCOMP +BLKID -ELFUTILS -KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid
```
=> [systemd] Upgrade systemd to 242

rabbitmq/plan.sh, rabbitmq/tests/test.sh
Fixes #2341 
* [Changelog](https://www.rabbitmq.com/changelog.html)
```
./rabbitmq/tests/test.sh
```
```
✓ Listening on port 4369, 5672, 25672
```
=> [rabbitmq] Upgrade rabbitmq to 3.7.14

.bldr.toml, tap-xunit/README.md, tap-xunit/plan.sh
Adding a new plan for tap-xunit, a nodejs command line tool that converts TAP testing output into xUnit format, for consumption by test analytics systems.
Currently testing is manual.
```
build tap-xunit
echo "1..4
ok 1 - Input file opened
not ok 2 - First line of the input valid
ok 3 - Read the rest of the file
not ok 4 - Summarized correctly # TODO Not written yet" | tap-xunit
```
```
<?xml version="1.0"?>
<testsuites>
<testsuite tests="4" skipped="1" failures="1" errors="0" name="Default">
<testcase name="#1 Input file opened"/>
<testcase name="#2 First line of the input valid">
<failure/>
</testcase>
<testcase name="#3 Read the rest of the file"/>
<testcase name="#4 Summarized correctly"> …
```
=> [tap-xunit] Added tap-xunit

prometheus/plan.sh, prometheus2/plan.sh
* [Changelog](https://github.com/prometheus/prometheus/blob/master/CHANGELOG.md)
```
DO_CHECK=1 build prometheus
exit
```
```
./prometheus/tests/test.sh
```
```
ok      github.com/prometheus/prometheus/cmd/prometheus 382.556s
ok      github.com/prometheus/prometheus/cmd/promtool   1.129s
ok      github.com/prometheus/prometheus/config 1.251s
ok      github.com/prometheus/prometheus/discovery      4.132s
ok      github.com/prometheus/prometheus/discovery/azure        1.105s
?       github.com/prometheus/prometheus/discovery/config       [no test files]
ok      github.com/prometheus/prometheus/discovery/consul       1.091s
ok      github.com/prometheus/prometheus/discovery/dns  1.037s
? …
```
=> [prometheus] Update prometheus to 2.9.0
