habitat-sh/core-plans

buildkite-agent/plan.sh
=> [buildkite-agent] Update buildkite-agent to 3.8.4

.bldr.toml, gradle/plan.sh, gradle/tests/build.gradle, gradle/tests/test.bats, gradle/tests/test.sh, gradle4/README.md, gradle4/plan.sh, gradle4/tests/build.gradle, gradle4/tests/test.bats, gradle4/tests/test.sh, gradle5/README.md, gradle5/plan.sh, gradle5/tests/build.gradle, gradle5/tests/test.bats, gradle5/tests/test.sh
=> [gradle] Updated gradle to 5.1

geos/plan.sh, geos/tests/test.bats, geos/tests/test.sh
=> [geos] Updated geos to 3.7.1

dovecot/plan.sh, dovecot/tests/test.bats, dovecot/tests/test.sh
=> [dovecot] Updated dovecot to 2.3.4

doxygen/plan.sh, doxygen/tests/test.bats, doxygen/tests/test.sh
=> [doxygen] Updated doxygen to 1.8.15

gradle4/plan.sh, gradle5/plan.sh
=> Added necessary fields to gradle4 and gradle5

gradle4/plan.sh, gradle5/plan.sh
=> Update gradle4/5 pkg_name

freetype/plan.sh
This version has depreciated the binary `freetype-config`.
=> [freetype] Updated freetype to 2.9.1

.expeditor/config.yml
=> Add initial configuration for expeditor

.bldr.toml, azure-cli/README.md, azure-cli/plan.sh
=> [azure-cli] Add azure-cli

libarchive/plan.ps1, libarchive/plan.sh
This updated versio fixes a ton of bugs.
=> [libarchive] Update libarchive from 3.3.2 to 3.3.3

.bldr.toml, buildkite-cli/README.md, buildkite-cli/plan.sh
=> [buildkite-cli] Add buildkite-cli

dpkg/plan.sh
- Fixed missing runtime deps for dpkg
- Cleaned up plan
This resolves #2211 
=> [dpkg] Fixed missing runtime deps

dotnet-45-dev-pack/README.md, dotnet-45-dev-pack/plan.ps1, dotnet-45-runtime/README.md, dotnet-45-runtime/hooks/install, dotnet-45-runtime/plan.ps1, dotnet-462-runtime/README.md, dotnet-462-runtime/hooks/install, dotnet-462-runtime/plan.ps1
=> [dotnet] adding more .net framework versions

boost/plan.sh
=> [boost] Updated boost to 1.69.0

llvm/plan.sh, llvm7/plan.sh
=> [llvm] Updated llvm to 7.0.1

.bldr.toml, libnl/plan.sh, libnl/tests/test.bats, libnl/tests/test.sh
New plan hype!
```
./libnl/tests/test.sh
```
```
✓ Commands are on path
✓ Help command
✓ Basic interface listing
```
=> [libnl] Added libnl, Netlink Protocol

dotnet-35sp1-runtime/hooks/install
=> [dotnet-35sp1-runtime] install NetFx3ServerFeatures on non container platforms

hugo/plan.sh
=> [hugo] Update hugo to 0.54.0

elasticsearch5/plan.sh
=> [elasticsearch] Updated elasticsearch5 to 5.6.14

MAINTAINERS.md
I'll be doing some test/CI work for the plans
Thanks!
=> Add James Stocks to maintainers

.bldr.toml, bdwgc/plan.sh, bdwgc7/README.md, bdwgc7/plan.sh, bdwgc8/README.md, bdwgc8/plan.sh
=> [bdwgc] Updated bdwgc to 8.0.0

git/plan.ps1, git/plan.sh, git/tests/test.bats, git/tests/test.sh
=>  [git] Updated git to 2.20.1

envdir/plan.sh, envdir/tests/test.bats, envdir/tests/test.sh
=> [envdir] Updated envdir to 1.0.1

shellcheck/plan.ps1
Added shellcheck plan for windows
This depends on #2266 and #2265
=> [shellcheck] Added shellcheck plan for windows

cpanminus/plan.sh
```
cpanminus: hab-plan-build cleanup
cpanminus: 
cpanminus: Source Path: /hab/cache/src/cpanminus-1.7044
cpanminus: Installed Path: /hab/pkgs/chainetix/cpanminus/1.7044/20181227233726
cpanminus: Artifact: /src/results/chainetix-cpanminus-1.7044-20181227233726-x86_64-linux.hart
cpanminus: Build Report: /src/results/last_build.env
cpanminus: SHA256 Checksum: cc15ca6af2e650c88e6097c8d3bed8156f0140489ccc0bc590d0e97ba952f28f
cpanminus: Blake2b Checksum: 9c49c97503c0961142a6e17a6cdd03cccd660c88d82aa6aee27569fd1c78754e
cpanminus: 
cpanminus: I love it when a plan.sh comes together.
cpanminus: 
cpanminus: Build time: 0m9s
```
=> [cpanminus] Updated cpanminus to 1.7044

go/plan.sh
Go changelog: https://golang.org/doc/go1.12
Test output:
```
✓ Help command
```
=> [go] Update to 1.12

dotnet-asp-core/plan.ps1
=> [dotnet-asp-core] bump to 2.2.2

elfutils/plan.sh, elfutils/tests/test.bats
Fixes #2212
```
./elfutils/tests/test.sh
```
```
✓ Help from commands
```
=> [elfutils] Add gcc-libs, and extra tests to confirm fix

rust/plan.ps1, rust/plan.sh
=> Bump rust to 1.33.0

packer/plan.ps1, packer/plan.sh
```
./packer/tests/test.sh
```
```
✓ Help command
```
=> [packer] Update packer to 1.3.5

cerebro/plan.sh, cerebro/tests/test.bats, cerebro/tests/test.sh
=> [cerebro] Updated cerebro to 0.8.1

nginx/README.md
Adds a readme to Nginx.
Should resolve #336
=> [nginx] Added Nginx readme

apr/plan.sh
Closes #2316 
Tested by building apr, followed by apr-utils and finally httpd to validate. 
=> [apr] Add missing runtime dependencies

dgraph/plan.sh
```
./dgraph/tests/test.sh
```
```
✓ Help command is functional
```
=> [dgraph] Update dgraph to 1.0.12

git/plan.ps1, git/plan.sh
Ran with `./git/tests/test.sh`:
```
```
=> [git] Updated git to 2.21.0.

erlang/plan.sh, erlang/tests/test.bats, erlang/tests/test.sh
=> [erlang] Updated erlang to 20.2

buildkite-agent/plan.sh
=> [buildkite-agent] Update to 3.9.1

buildkite-cli/plan.sh
=> [buildkite-cli] Update to 0.4.1

terraform/plan.sh
=> [terraform] Update to 0.11.13

gdal/plan.sh, gdal/tests/test.bats, gdal/tests/test.sh
=> [gdal] Updated gdal to 2.4.0

cmake/plan.ps1, cmake/plan.sh
=> [cmake] Updated cmake to 3.13

nginx/plan.sh, nginx/tests/test.sh
```
```
```
✓ Help command
```
=> [nginx] Version up for Nginx, 1.15.9

vault/plan.sh
=> [vault] Update to 1.0.3

libuv/plan.sh
```
DO_CHECK=1 build libuv
```
```
PASS: test/run-tests
=============
1 test passed
=============
```
libuv combines all tests into one, so seeing `1 test passed` is success.
=> [libuv] Update libuv to 1.27.0

MAINTAINERS.md
I'll be doing some test/CI work for the plans
Thanks!
=> Add Gavin Didrichsen to maintainers

.bldr.toml, CODEOWNERS, journalbeat/README.md, journalbeat/config/journalbeat.yml, journalbeat/default.toml, journalbeat/hooks/init, journalbeat/hooks/run, journalbeat/plan.sh, journalbeat/tests/test.bats, journalbeat/tests/test.sh
I put together and tested a Journalbeat plan based on echohack's Metricbeat plan.
Signed-off-by: Thomas Cate <tcate@chef.io>
=> [journalbeat] add core plan

journalbeat/plan.sh
```
./journalbeat/tests/test.sh
```
```
✓ Help command
```
=> [journalbeat] update journalbeat to 6.7.0, minor style fixes

strace/plan.sh
```
./strace/tests/test.sh
```
```
✓ Can strace
```
=> [strace] Update strace to 5.0

.expeditor/templates/verify_linux_pipeline.yml
=> Pass plan to build to script

.expeditor/templates/verify_linux_pipeline.yml
=> Use correct script name

consul/plan.sh
* [Changelog](https://github.com/hashicorp/consul/blob/v1.4.4/CHANGELOG.md)
```
```
```
```
=> [consul] Update consul to 1.4.4

.bldr.toml, ipvsadm/Makefile.patch, ipvsadm/README.md, ipvsadm/plan.sh, ipvsadm/tests/test.bats, ipvsadm/tests/test.sh
Needs #2188 merged and promoted first, as its a direct dependency.
```
./ipvsadm/tests/test.sh
```
```
✓ Commands are on path
✓ Display the ipvs table
```
=> [ipvsadm] New plan for ipvsadm

fping/README.md, fping/plan.sh, fping/tests/test.bats, fping/tests/test.sh
do_check() {} results:
```
fping: Running post-compile tests
Making check in doc
make[1]: Entering directory '/hab/cache/src/fping-4.1/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/hab/cache/src/fping-4.1/doc'
Making check in src
make[1]: Entering directory '/hab/cache/src/fping-4.1/src'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/hab/cache/src/fping-4.1/src'
make[1]: Entering directory '/hab/cache/src/fping-4.1'
make[1]: Leaving directory '/hab/cache/src/fping-4.1'
```
=> [fping] Updated fping to 4.2

.bldr.toml, CODEOWNERS, corretto/README.md, corretto/plan.sh, corretto11/README.md, corretto11/plan.sh
Here's an opendjk11 distro by Amazon under GPL2 with Classpath exception.
=> [corretto] Add corretto

.bldr.toml
This includes a path to the parent plan.
=> [corretto11] Update .bldr.toml

.bldr.toml, CODEOWNERS, corretto8/README.md, corretto8/plan.sh
Here's an opendjk8 distro by Amazon under GPL2 with Classpath exception. Note: it also ships with JRE in the same package.
=> [corretto8] Add corretto8

ruby26/plan.sh
=> [ruby26] Update Ruby26 to 2.6.2

happy/plan.sh
- Added tests for happy
- Fixed happy so it doesn't build older Cabal
- Converted happy to specify v1- cabal commands
=> [happy] Add tests and plan cleanup

ruby/plan.sh, ruby25/plan.sh
=> [ruby25] Update Ruby25 to 2.5.5

CONTRIBUTING.md
=> [contributing.md] minor fix for shellcheck rules

openjpeg/plan.sh
=> [openjpeg] Update openjpeg to 2.3.1

MAINTAINERS.md
Signed-off-by: Scott Hain <shain@chef.io>
=> Add me to maintainers

libmaxminddb/plan.sh
=> [libmaxminddb] Updated Licence To Be Apache-2.0.

.expeditor/config.yml, .expeditor/templates/welcome.mustache
Copy/Paste from habitat-sh/habitat#6356
This adds a welcome message to expeditor to replace The Sentinels. 
=> Add welcome message to expeditor config

goaccess/plan.sh
`test.sh`:
```
✓ Parse nginx combined log entry
```
=> [goaccess] Updated goaccess to 1.3

dotnet-472-dev-pack/plan.ps1
=> [dotnet-472-dev-pack] Fix download URL

.bldr.toml, rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2019/04/11/Rust-1.34.0.html
=> [rust] Bump to 1.34.0

ant/README.md, ant/plan.sh, ant/tests/test.bats, ant/tests/test.sh
=> [ant] Updated ant to 1.10.5

reportviewer2010/README.md, reportviewer2010/plan.ps1
=> [reportviewer2010] adds the MS report viewer 2010 redistributable assemblies

nginx/plan.ps1, nginx/plan.sh
* [Changelog](http://nginx.org/en/CHANGES)
```
```
```
✓ Help command
```
=> [nginx] Update nginx to 1.15.11

.bldr.toml, windows-10-sdk/README.md, windows-10-sdk/plan.ps1
=> [windows-10-sdk] add windows 10 sdk plan

.bldr.toml, ffmpeg/plan.sh, ffmpeg/tests/test.bats, ffmpeg/tests/test.sh, ffmpeg3/README.md, ffmpeg3/plan.sh, ffmpeg3/tests/test.bats, ffmpeg3/tests/test.sh, ffmpeg4/README.md, ffmpeg4/plan.sh, ffmpeg4/tests/test.bats, ffmpeg4/tests/test.sh
...Also split version 3 into ffmpeg3.
=> [ffmpeg] Updated ffmpeg to 4.1.3

ffmpeg3/plan.sh, ffmpeg4/plan.sh
This corrects the download urls for ffmpeg3 and ffmpeg4. 
=> [ffmpeg3][ffmpeg4] Correct download urls

ruby/plan.sh, ruby25/plan.sh
This release of rubygems includes CVE fixes.
Signed-off-by: Jon Morrow <jmorrow@chef.io>
=> Update rubygems to 2.7.9

python/plan.ps1, python2/plan.ps1, python34/plan.ps1, python36/plan.ps1, python37/plan.ps1
=> [python] adding windows python plans

nginx/plan.ps1, nginx/plan.sh
* [Changelog](http://nginx.org/en/CHANGES)
Bugfix release.
```
```
```
✓ Help command
```
=> [nginx] Update nginx to 1.15.12

.bldr.toml, grpc-cpp/README.md, grpc-cpp/no_ipv6_port_server.patch, grpc-cpp/plan.sh
```
DO_CHECK=1 build grpc-cpp
```
Should wait for c-ares PR to be merged in #2167 
=> [grpc-cpp] add new plan

libevent/plan.sh
This adds two required metadata fields to the libevent plan.sh.  Ref: #1306 
=> [libevent] Update metadata

libffi/plan.sh
This adds required metadata to the libffi plan.  Ref: #1306 
=> [libffi] Update metadata

scaffolding-chef/lib/scaffolding.sh
As a Chef user, I have some data stored in JSON files that I would
like to use in Chef recipes as Data Bag Items. In order to facilitate
this, one can create a "data_bags" directory and store the bags
(directories) and files (.json within those bags), and then use the
scaffolding with this update to copy them over in the package and
they'll be available in recipes using the Chef DSL's `data_bag` and
`data_bag_item` methods.
I didn't test this using encrypted data bags, though I presume it
would work given a recipe written to make use of a secret dropped off
in a known location.
=> [scaffolding-chef] copy data_bags directory

cmake/patches/000-disable_test_file_access.patch, cmake/patches/001-disable-failing-bundleutlities-tests.patch, cmake/plan.sh
This closes #2357 
Please read #2357 and #2118 for additional context. 
=> [cmake] Disable tests that will always fail

zip/plan.sh
This adds required metadata to the zip plan. Ref: #1306
=> [zip] Update plan metadata

libyaml/plan.sh
This adds required metadata to the libyaml plan. Ref: #1306
=> [libyaml] Update plan metadata

net-tools/plan.sh
This adds required metadata to the net-tools plan. Ref: #1306
=> [net-tools] Update plan metadata

libiconv/plan.sh
This adds required metadata to the libiconv plan. Ref: #1306
=> [libiconv] Update plan metadata

libksba/plan.sh
This adds required metadata to the libksba plan. Ref: #1306
=> [libksba] Update plan metadata

runit/plan.sh
This adds required metadata to the runit plan. Ref: #1306
=> [runit] Update plan metadata

npth/plan.sh
This adds required metadata to the npth plan. Ref: #1306
=> [npth] Update plan metadata

docs/dev/README.md, docs/dev/policy_documents/deprecating-packages.md
https://github.com/habitat-sh/core-plans/pull/1280
https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0003-tracking-package-versions.md
Closes #2500 
Co-authored-by: Nell Shamrell <nellshamrell@gmail.com>
=> Add package deprecation policy

docs/dev/README.md, docs/dev/policy_documents/testing-pull-requests.md
#1281
https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0004-testing-pull-requests.md
Closes #2501 
Co-authored-by: Nell Shamrell <nellshamrell@gmail.com>
=> Add testing pull requests document

docs/dev/README.md, docs/dev/policy_documents/tracking-package-versions.md
#1280 
https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0003-tracking-package-versions.md
Closes #2500 
Co-authored-by: Nell Shamrell <nellshamrell@gmail.com>
=> Add tracking package versions document

docs/dev/README.md, docs/dev/policy_documents/plan-configuration-complexity.md
https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0009-plan-configuration-complexity.md
Contribution by @predominant.
Closes #2505 
=> Add plan-configuration-complexity document

docs/dev/README.md, docs/dev/policy_documents/shebang-line-conventions.md
https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0008-shebang-line-conventions.md
Closes #2504 
Co-authored-by: Christopher Maier <cmaier@chef.io>
=> Add shebang-line-conventions document

buildkite-agent/plan.ps1
=> [buildkite-agent] Add plan.ps1 for buildkite-agent

buildkite-cli/plan.ps1
=> [buildkite-cli] Add plan.ps1 for buildkite-cli

lz4/plan.sh
=> [lz4] Update lz4 to 1.9.1

ruby26/plan.sh
=> [ruby26] Update to 2.6.3

libyaml/plan.sh
=> [libyaml] Update to 0.1.7

docs/dev/README.md, docs/dev/policy_documents/standards-for-tests.md, docs/dev/policy_documents/testing-pull-requests.md
Following [Chef's OSS design process](https://github.com/chef/chef-oss-practices/blob/master/contributors/guide/design-proposals.md) this PR fixes #2473 and finalises the design.
Any feedback on the contents of this design must be left as a comment on #2473 so we keep the discussion in a single place.
Please only add comments to this PR for critique of files structure/formatting, spelling/punctuation/grammar, etc - do not add comments for the semantics of the text.
There are some changes between the text in #2473 and what's being submitted here:
1. I deleted the "`tests` folder structure" section as most of it was no longer applicable due to changes agreed during the design windows.
2. Changed the word "should" to "will" in a number of places to be more direct about what will happen.
3. …
=>  Add dev policy document for testing standards

.bldr.toml, node/plan.ps1, node/plan.sh, node12/README.md, node12/plan.ps1, node12/plan.sh
* [Changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md)
```
build node
node --version
```
=> [node/node12] Add node12, update node to node12

.bldr.toml, pester/README.md, pester/plan.ps1
=> [pester] add a pester package

terraform/plan.sh, terraform/tests/test.sh
Hey all,
This is just a simple version update with a bug fix for the testing framework. To test this build, please enter the studio and run `./tests/test.sh` 
```
```
If you have any questions, please let me know! Thanks.
=> [terraform] Update to 0.11.14

7zip/README.md, 7zip/tests/test.bats, 7zip/tests/test.pester.ps1, 7zip/tests/test.ps1, 7zip/tests/test.sh
=> [7zip] Add Windows and Linux tests

sassc/plan.sh
=> [sassc] Update sassc to 3.6.0

kafka/config/server.properties
Signed-off-by: Yauhen Artsiukhou <jsirex@gmail.com>
=> [kafka] Set topic replication factor

netdata/plan.sh
=> [netdata] Update netdata to 1.15.0

alex/README.md, alex/tests/test.bats, alex/tests/test.sh
=> [alex] Add tests

netdata/plan.sh
=> [netdata] Update checksum for republished version

ansible/plan.sh, ansible/tests/test.bats, ansible/tests/test.sh
[Changelog](https://github.com/ansible/ansible/blob/v2.7.11/changelogs/CHANGELOG-v2.7.rst)
=> [ansible] Update to 2.7.11 and update tests

.bldr.toml, CODEOWNERS, clojure/README.md, clojure/default.toml, clojure/hooks/run, clojure/plan.sh
Finalizing remaining comments from https://github.com/habitat-sh/core-plans/pull/1106.
=> [clojure] Add Clojure 1.10.0.442

rust/plan.ps1, rust/plan.sh
=> [rust] Update to Rust 1.35.0

azure-cli/README.md, azure-cli/tests/tests.bats, azure-cli/tests/tests.sh
Added bats testing and Updated the README.
=> [azure-cli] Add tests and update the README

alsa-lib/README.md, alsa-lib/plan.sh, alsa-lib/tests/test.bats, alsa-lib/tests/test.sh
[CHANGELOG](https://www.alsa-project.org/wiki/Changes_v1.1.8_v1.1.9)
=> [alsa-lib] Bump to 1.1.9, add tests

zsh/tests/test.bats, zsh/tests/test.sh
=> [zsh] Fix non-interactive build, add tests

acbuild/README.md, acbuild/tests/test.bats, acbuild/tests/test.sh
=> [acbuild] Add tests

opa/tests/test.sh
Is this how it's done for services? 😃
=> [opa] update tests

fontconfig/plan.sh
Simple cleanup of the plan file. Spotted some stuff that was nagging at me while I was debugging another plan.
=> [fontconfig] Cleanup fontconfig plan.sh

gradle/README.md, gradle/plan.sh, gradle/tests/test.bats, gradle/tests/test.sh
```
hab pkg build gradle
hab studio run "./gradle/tests/test.sh ${pkg_ident}"
```
```
✓ Run A Scan With Gradle
```
=> [gradle] Update to 5.4.1, update tests

maven/plan.ps1
Apache Maven Plan created for Windows. Tested with Corretto8, Corretto11, Corretto-JRE8 and Tomcat8 for windows.
=> [maven] Apache Maven 3.6.1 for Windows

nspr/README.md, nspr/plan.sh
Signed-off-by: Kristian Vlaardingerbroek <kvlaardingerbroek@schubergphilis.com>
=> [nspr] Update to 4.21

docs/dev/policy_documents/deprecating-packages.md
This updates the package deprecation policy as proposed in #2640 
closes #2640 
=> [doc] Update deprecation policy

bin/refresh-verify-change.sh
I've pulled this out of the `refresh/2019q3` branch so that anyone contributing to the refresh can use their normal workflow to create a branch and have this script available to them.  
=> Add script to help verify changes made to base plans

nss/README.md, nss/plan.sh
Signed-off-by: Kristian Vlaardingerbroek <kvlaardingerbroek@schubergphilis.com>
=> [nss] Update to 3.44

cyrus-sasl/README.md, cyrus-sasl/plan.sh
Signed-off-by: Kristian Vlaardingerbroek <kvlaardingerbroek@schubergphilis.com>
=> [cyrus-sasl] Update to 2.1.27

expat/plan.sh
=> [expat] Updated expat to 2.2.6

file/plan.sh, file/tests/test.bats, file/tests/test.sh
=> [file] Updated file to 5.36

gawk/plan.sh, gawk/tests/test.bats, gawk/tests/test.sh
=> [gawk] Updated gawk to 4.2.1

gdbm/plan.sh, gdbm/tests/test.bats, gdbm/tests/test.sh
Ran with `export DO_CHECK=true`:
```
All 30 tests were successful.
```
`test.sh`:
```
```
=> [gdbm] Updated gdbm to 1.18.1

maven/plan.ps1
Signed-off-by: sam1el <jbrimager@chef.io>
=> [maven] corrected issue with maven not being able to find its executables

powershell/plan.ps1
=> [powershell] bump powershell to 6.2.1

docs/dev/README.md, docs/dev/howto_documents/verifying-base-plan-updates.md
This adds the proposed documentation in #2636 
closes #2636 
=> [docs] Add document on verifying base plan updates

gradle4/plan.sh, gradle5/plan.sh
This introduces updates to the gradle4 and gradle5 package to correct for build errors. 
=> [gradle4][gradle5]Fix builds of gradle4 and gradle5

protobuf-c/plan.sh
=> [protobuf-c] Update protobuf-c to 1.3.2

R/plan.sh, R/tests/test.bats, R/tests/test.sh
=> [R] Fix bin dir, add tests.

automake/README.md, automake/tests/test.bats, automake/tests/test.sh
Signed-off-by: Rachel Rice <rrice@chef.io>
=> [automake] Add test

acl/README.md, acl/tests/test.bats, acl/tests/test.sh
=> [acl] Add tests to core/acl for linux plan

autogen/tests/test.bats, autogen/tests/test.sh
Signed-off-by: Rachel Rice <rrice@chef.io>
=> [autogen] Add tests

bin/refresh-verify-change.sh
Minor fix to URL for rdeps, and the jq filter used to parse the result.
=> Fix rdeps call and jq filters

apr-util/plan.sh
=> [apr-util] Cleanup apr-util plan

.expeditor/generate_verify_pipeline.sh
=> Allow CI to work against base branches other than master.

libuv/plan.sh
=> [libuv] Update libuv to 1.30.0

curl/plan.sh, curl/tests/test.bats, curl/tests/test.sh
This updates curl the latest version to address CVEs and updates the tests to match the current testing policy. 
closes #2774  
=> [curl] Update to latest version

rust/plan.ps1, rust/plan.sh
=> Upgrade to Rust 1.36.0

opa/tests/test.bats, opa/tests/test.sh
Just a small change, some quick quality of life updates.
=> [opa] add small test updates and doc to opa

curl-static-musl/plan.sh, curl-static-musl/tests/test.bats, curl-static-musl/tests/test.sh
Update based on required updates in #2776
=> [curl-static-musl] Update curl-static-musl to 7.65.1

node/plan.ps1, node/plan.sh, node12/plan.ps1, node12/plan.sh
=> [node] Update node to 12.6.0

pkg-config/plan.sh, pkg-config/tests/test.bats, pkg-config/tests/test.sh
=> [pkg-config] update license string

libpipeline/README.md, libpipeline/plan.sh
=> [libpipeline] update libpipeline to 1.5.1, fix minor formatting

atk/plan.sh
```
hab pkg build atk
```
It's just a library, so there's not any tests.
=> [atk] minor version update 2.28.1

man-pages/plan.sh
No tests provided as this is a collection of text documents. 
=> [man-pages] Update to latest version

libaio/plan.sh, libaio/tests/test.sh
=> [libaio] Update version

numactl/plan.sh, numactl/tests/test.bats, numactl/tests/test.sh
This updates numactl to the latest version to allow building against the upcoming updates to the glibc and gcc packages. 
=> [numactl] Update version

flex/plan.sh, flex/tests/test.bats, flex/tests/test.sh
This is a small change to copy the license information into the resulting package, and adds a simple test. 
=> [flex] Add simple test

readline/plan.sh, readline/readline-patches.sh, readline/tests/test.bats, readline/tests/test.sh
=> [readline] Update to 8.0

shadow/plan.sh, shadow/tests/test.bats, shadow/tests/test.sh
Changelog: https://github.com/shadow-maint/shadow/blob/master/ChangeLog
=> [shadow] Update to 4.7, add test

file/plan.sh, file/tests/test.bats, file/tests/test.sh
Release announcement: https://mailman.astron.com/pipermail/file/2019-May/000129.html
=> [file] Update file to 5.37, update tests

psmisc/plan.sh, psmisc/tests/test.bats, psmisc/tests/test.sh
Changelog: https://gitlab.com/psmisc/psmisc/blob/master/ChangeLog
=> [psmisc] Update to 23.2, add tests

rust/tests/test.bats, rust/tests/test.pester.ps1, rust/tests/test.ps1, rust/tests/test.sh
=> [rust] Add tests to core/rust for windows and linux plans

git/tests/test.bats, git/tests/test.pester.ps1, git/tests/test.ps1, git/tests/test.sh
=> [git] Add tests for core/git windows and linux plans

bundler/tests/test.bats, bundler/tests/test.sh
=> [bundler] Add bats tests

leiningen/plan.sh, leiningen/tests/test.bats, leiningen/tests/test.sh
=> [leiningen] Replace jdk with corretto

gawk/plan.sh, gawk/tests/test.bats, gawk/tests/test.sh
High level summary of changes: https://lists.gnu.org/archive/html/info-gnu/2019-04/msg00002.html
Detailed changes: http://git.savannah.gnu.org/cgit/gawk.git/tree/ChangeLog.1
=> [gawk] Update to 5.0, add tests

zookeeper/hooks/run, zookeeper/plan.sh, zookeeper/tests/test.bats, zookeeper/tests/test.sh
=> [zookeeper] Replace jdk with openjdk

artifactory/plan.sh
[Release notes](https://bintray.com/jfrog/artifactory/jfrog-artifactory-oss-zip/6.11.3)
```
hab studio run "./artifactory/tests/test.sh ${pkg_ident}"
```
=> [artifactory] minor version up 6.11.3

storm/config/storm_env.ini, storm/hooks/run, storm/plan.sh
=> [storm] Replace jre8 with corretto8

sbt/README.md, sbt/plan.sh, sbt/tests/test.bats, sbt/tests/test.sh
=> [sbt] Replace jdk with openjdk

bison/plan.sh, bison/tests/test.bats, bison/tests/test.sh
This incorporates #2103 and builds on it to update to bison 3.4.1.
=> [bison] Update to 3.4.1

bzip2/plan.ps1, openssl/plan.ps1, perl/plan.ps1
=> [bzip2, perl, openssl] add runtime dep for 2015 cpp redistributable

jruby/plan.sh, jruby/tests/test.bats, jruby/tests/test.sh
=> [jruby] Replace jdk with corretto

cacerts/tests/test.bats, cacerts/tests/test.pester.ps1, cacerts/tests/test.ps1, cacerts/tests/test.sh
=> [cacerts] Add tests to the core/cacerts for windows and linux

spark/hooks/run, spark/plan.sh
=> [spark] Replace jre8 with openjdk11

tomcat-native/plan.sh, tomcat-native/tests/test.bats, tomcat-native/tests/test.sh
=> [tomcat-native] Replace jdk with openjdk

node/plan.ps1, node/plan.sh, node12/plan.ps1, node12/plan.sh
```
hab pkg build node
hab studio run "./node/tests/test.sh ${pkg_ident}"
```
```
✓ Help Command
```
=> [node] Update node to 12.7.0

gox/plan.sh
We could use our own Go Scaffolding. 🙂
=> [gox] Use scaffolding-go

iana-etc/plan.sh, iana-etc/tests/test.sh
This is a minor change to update the license string to match the SPDX values.
=> [iana-etc] Update  license string

autoconf/plan.sh, autoconf/tests/test.bats, autoconf/tests/test.sh
This is a minor update to the license string of autoconf to match the SPDX short strings. 
=> [autoconf] Update license string

make/plan.sh, make/tests/fixtures/Makefile, make/tests/test.bats, make/tests/test.sh
=> [make] Update license string

util-linux/plan.sh, util-linux/tests/test.bats, util-linux/tests/test.sh
[2.34 release notes](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.34/v2.34-ReleaseNotes)
[2.33 release notes](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.33/v2.33-ReleaseNotes)
=> [util-linux] Update to 2.34

acl/tests/test.bats, acl/tests/test.sh
=> [acl] Add tests to core/acl

libtool/plan.sh, libtool/tests/test.bats, libtool/tests/test.sh
No functional changes. Taking the opportunity with the refresh to update the license string and add some testing around expectations of the output of this package.
=> [libtool] Update license string and add tests

expat/plan.sh, expat/tests/fixtures/mismatched-tag.xml, expat/tests/fixtures/valid.xml, expat/tests/test.bats, expat/tests/test.sh
[Changelog](https://github.com/libexpat/libexpat/blob/master/expat/Changes)
=> [expat] Update to 2.2.7

gettext/plan.sh, gettext/tests/test.bats, gettext/tests/test.sh
[Release notes](https://lists.gnu.org/archive/html/bug-gettext/2019-05/msg00041.html)
[Patch release notes](https://lists.gnu.org/archive/html/bug-gettext/2019-05/msg00095.html)
=> [gettext] Update to 0.20.1

patch/plan.sh, patch/tests/test.bats, patch/tests/test.sh
=> [patch] Update license string

texinfo/plan.sh, texinfo/tests/test.bats, texinfo/tests/test.sh
[Release announcement](https://lists.gnu.org/archive/html/bug-texinfo/2019-02/msg00021.html)
=> [texinfo] Update to 6.6

hugo/plan.sh
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.56.3

binutils/ld-wrapper.sh, binutils/plan.sh, binutils/tests/test.bats, binutils/tests/test.sh
[Release announcement](https://sourceware.org/ml/binutils/2019-02/msg00010.html)
=> [binutils] Update to 2.32

inetutils/plan.sh, inetutils/tests/test.bats, inetutils/tests/test.sh
=> [inetutils] Update license string and add simple tests

zeromq/plan.ps1, zeromq/plan.sh
=> [zeromq] Update ZeroMQ libs to 4.3.1

libimagequant/plan.sh
=> [libimagequant] Update libimagequant to 2.12.5

libsodium/plan.ps1, libsodium/plan.sh
=> [libsodium] Update libsodium to 1.0.18

logstash/tests/test.sh
=> [logstash] Remove commented code from test.sh

.bldr.toml, visual-build-tools-2017/plan.ps1
=> [visual-build-tools-2017] add nuget build tools to vs 2017

node10/plan.ps1, node10/plan.sh
=> [node10] Update node10 to 10.16.2

node/plan.ps1, node/plan.sh, node12/plan.ps1, node12/plan.sh
=> [node/node12] Update node to 12.8.0

scaffolding-ruby/lib/scaffolding.sh
=> [scaffolding ruby] fixes

ghc/README.md
=> [ghc] add build instructions for maintainers

mysql/plan.sh
I needed to amend some of the build deps to get this version to compile.
Signed-off-by: Gary Bright <digitalgaz@hotmail.com>
=> [mysql] Bumped to 5.7.27

linux-headers/plan.sh, linux-headers/tests/test.sh
This PR updates to the latest LTS release of the linux kernel. 
=> [linux-headers] Update to latest LTS version

CODEOWNERS
@nellshamrell  has indicated she'd no longer like to be a CODEOWNER on the following plans. 
=> CODEOWNERS cleanup - nellshamrell

CODEOWNERS
@raskchanky has indicated he'd no longer like to be a CODEOWNER on the following plans.  
=> CODEOWNERS cleanup - raskchanky

dnsmasq/config/dnsmasq.conf, dnsmasq/plan.sh~HEAD, dnsmasq/plan.sh~HEAD_0
Add a plan to install and configure the dnsmasq tool.
=> [dnsmasq] Adding dnsmasq plan

CODEOWNERS
=> Add habitat-core-team as codeowner to rust

yarn/plan.ps1
Yarn package for windows. Been using this since about version 1.9.4 for various node applications, only got around to opening this PR now.
=> [yarn] Adding Windows Package

rust/plan.ps1, rust/plan.sh
=> Bump rust to 1.37.0

jenkins/hooks/run, jenkins/plan.sh, jenkins/tests/test.sh
Hi @predominant.  I hope you don't mind, but I rolled your jenkins changes of PR #2868 into this new PR to save you having to fix the conflicts.  Give me a shout if you have any other suggestions on this.
=> [jenkins] VERSION 2: Update Jenkins to 2.176.2, changed to openjdk, update tests

socat/plan.sh
=> [socat] Upgrade to 1.7.3.3

protobuf/plan.ps1, protobuf/plan.sh
[changelog](https://github.com/protocolbuffers/protobuf/releases/tag/v3.9.1)
=> [protobuf] bump to 3.9.1

git/plan.ps1, git/plan.sh
Release notes:
- https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.22.0.txt
- https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.23.0.txt
=> [git] Upgrade git to 2.23

CODEOWNERS
=> Add myself as co-owner to various packages

go/plan.sh
This is a minor bug-fix release:
https://groups.google.com/forum/#!topic/golang-announce/oeMaeUnkvVE
=> [go] Update to version 1.12.9

go/plan.sh
=> [go] Upgrade go to 1.13

.bldr.toml, libfastjson/README.md, libfastjson/plan.sh
=> [libfastjson] Added libfastjson

maven/plan.ps1, maven/plan.sh
```
hab pkg build maven
hab studio run "./maven/tests/test.sh ${pkg_ident}"
```
```
✓ mvn command
```
=> [maven] Update maven to 3.6.2

jffi/plan.sh
=> [jffi] Update jffi to 1.2.20

nginx/plan.ps1, nginx/plan.sh
```
hab studio run "./nginx/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [nginx] Update nginx to 1.17.4

go/plan.sh
Per https://groups.google.com/forum/m/#!topic/golang-announce/cszieYyuL9Q
Signed-off-by: Blake Johnson <bstier@chef.io>
=> Update go to 1.13.1

packer/plan.ps1, packer/plan.sh
```
hab pkg build packer
hab studio run "./packer/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [packer] Update packer to 1.4.4

sccache/plan.sh
=> [sccache] Bump to 0.2.12

jffi/plan.sh
=> [jffi] Update jffi to 1.2.21

ansible/plan.sh
```
```
```
✓ Help Command
```
=> [ansible] Update ansible to 2.8.6

grpc-cpp/plan.sh
All tests pass for this release.
[Changelog](https://github.com/grpc/grpc/releases/tag/v1.24.1)
=> [grpc-cpp] update to 1.24.1

jenkins/config/fontconfig.properties, jenkins/hooks/init
Adds necessary font configuration for Jenkins, with change you can successfully login to Jenkins. 
Signed-off-by: Eric Calabretta eric.calabretta@gmail.com
=> [jenkins] Fix jenkins

jffi/plan.sh
=> [jffi] Update jffi to 1.2.22

prometheus/config/prometheus.yml, prometheus1/config/prometheus.yml, prometheus2/config/prometheus.yml
This fixes the spacing that yaml requires.
=> [prometheus] fix the configs

.bldr.toml, grafana-loki/README.md, grafana-loki/config/config.yaml, grafana-loki/default.toml, grafana-loki/plan.sh, grafana-loki/tests/test.bats, grafana-loki/tests/test.sh, grafana/README.md, grafana/config/datasource-loki.yaml, grafana/hooks/post-run, grafana/plan.sh
This plan adds grafana-loki so that grafana can see log data.
=> [grafana-loki] add new plan

.bldr.toml, grafana-promtail/README.md, grafana-promtail/config/config.yaml, grafana-promtail/default.toml, grafana-promtail/plan.sh, grafana-promtail/tests/test.bats, grafana-promtail/tests/test.sh
This plan adds grafana-promtail.
~~Note: tests were removed since it requires loki service to be running.~~
=> [grafana-promtail] add new plan

packer/plan.ps1, packer/plan.sh
```
hab pkg build packer
```
```
✓ Help command
```
=> [packer] Update packer to 1.4.5

rust/plan.ps1, rust/plan.sh
=> [rust] Update Rust to 1.39.0

grpc-cpp/plan.sh
=> [grpc-cpp] update to 1.25.0

powershell/plan.sh, powershell/tests/test.bats, powershell/tests/test.pester.ps1, powershell/tests/test.ps1, powershell/tests/test.sh
=> Add powershell plan for linux

pester/README.md, pester/plan.sh, pester/tests/test.bats, pester/tests/test.sh
=> [pester] Pester package for linux

happy/plan.sh
Updated happy to 1.19.12
Removed obsolete patch
=> [happy] Updated happy to 1.19.12

.bldr.toml, ghc/plan.ps1, ghc/plan.sh, ghc88/README.md, ghc88/plan.sh, ghc88/tests/test.bats, ghc88/tests/test.sh
- Updated GHC to 8.8.1
- Added GHC 8.8 plan
- Updated ghc 8.6 as appropriate to maintain build deps
=> [ghc] Updated GHC to 8.8.1

MAINTAINERS.md
Signed-off-by: Scott Hain <elejia@gmail.com>
=> Move me to alumni

elasticsearch/plan.sh
=> [elasticsearch] update to 6.8.5

bash-completion/plan.sh
=> [bash-completion] Update bash-completion to 2.9

file/README.md, file/tests/test.bats
Contributing tests and shellcheck fix from more aggressive #3110
=> [file] fix shellcheck and add tests

dotnet-asp-core/plan.ps1, dotnet-asp-core/plan.sh, dotnet-asp-core/tests/test.bats, dotnet-core-sdk/plan.ps1, dotnet-core-sdk/plan.sh, dotnet-core/plan.ps1, dotnet-core/plan.sh
=> [dotnet-core] bump .net core to v3.1

imagemagick/plan.sh
=> [imagemagick] Update imagemagick to 7.0.9-9

iptables/plan.sh
=> [iptables] Update iptables to 1.8.4

rust/plan.ps1, rust/plan.sh
=> [rust] Update Rust to 1.40.0

libgpg-error/plan.sh
=> [libgpg-error] Update libgpg-error to 1.36

libunwind/plan.sh
=> [libunwind] Update libunwind to 1.2.1

libuv/plan.sh
=> [libuv] Update libuv to 1.34.1

.bldr.toml, oniguruma/README.md, oniguruma/default.toml, oniguruma/plan.sh, oniguruma/tests/test.bats, oniguruma/tests/test.sh
Adds oniguruma. Regular expression library used by new PHP versions.
```
hab pkg build oniguruma
```
```
```
=> [oniguruma] Add oniguruma

opa/plan.sh, opa/tests/test.sh
Changelogs:
https://github.com/open-policy-agent/opa/releases/tag/v0.15.0
https://github.com/open-policy-agent/opa/releases/tag/v0.15.1
https://github.com/open-policy-agent/opa/releases/tag/v0.16.0
=> [opa] bump 0.14.0 -> 0.16.1

libev/plan.sh
=> [libev] Update libev to 4.31

go/plan.ps1, go/plan.sh
=> [go] Upgrade to 1.13.7

maven/plan.ps1, maven/plan.sh, maven/tests/test.sh
=> [maven] Update maven to 3.6.3

nano/plan.sh, nano/tests/test.bats, nano/tests/test.sh
=> [nano] Update nano to 4.7, add tests

node/plan.ps1, node/plan.sh, node12/plan.ps1, node12/plan.sh
=> [node] Update node to 12.14.1

strace/plan.sh
=> [strace] Update strace to 5.4

node8/plan.sh
=> [node8] Update node 8 to 8.17.0

node11/plan.ps1, node11/plan.sh
=> [node11] Update node 11 to 11.15.0

node10/plan.ps1, node10/plan.sh
=> [node10] Update node10 to 10.18.1

php/tests/libzip_support.php, php/tests/test.bats, php/tests/test.sh
Changes the PHP testing to be more like the rest of the core plans testing.
=> [php] Make PHP testing more  standard

yarn/plan.ps1, yarn/plan.sh
```
```
```
✓ Help command
```
=> [yarn] Update yarn to 1.22.0

.bldr.toml, utf8proc/README.md, utf8proc/plan.sh
Library plan only. Used in newer versions of Subversion
=> [utf8proc] Added utf8proc

sudo/plan.sh
=> [sudo] Update sudo to 1.8.31

rust/plan.ps1, rust/plan.sh
=> Update Rust to 1.41.0

CODEOWNERS
After rebasing master into the refresh/2019q3 branch and resolving all conflicts, this is the summation of changes on both branches.
=> Fix CODEOWNERS to prevent a refresh/2019q3 merge conflict

bdwgc/plan.sh, bdwgc8/plan.sh
This appears to be a minor bug-fix release.
https://github.com/ivmai/bdwgc/releases/tag/v8.0.4
=> [bdwgc] Update version to 8.0.4

ffmpeg/plan.sh, ffmpeg4/plan.sh
Both ffmpeg and ffmpeg4 updated to the same version.
```
```
=> [ffmpeg] Update ffmpeg to 4.2.2

.bldr.toml, haproxy/plan.sh, haproxy21/README.md, haproxy21/config/haproxy.conf, haproxy21/default.toml, haproxy21/plan.sh, haproxy21/tests/test.sh
=> [haproxy] Update haproxy to 2.1.3, add haproxy21, update haproxy20 to 2.0.13

git/plan.ps1, git/plan.sh, git/tests/test.bats, git/tests/test.sh
=> [git] Update git to 2.25.1

consul/plan.sh
```
hab pkg build __PKGNAME__
```
```
```
=> [consul] Update consul to 1.7.2

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt
Moving kubernetes to passed from failed.
=> [refresh] - Changing kubernetes to passed

.refresh/remaining_plans_passed.txt
add core/bazel to remaining list
=> [refresh/2020q1] Fix dependency order of core/which

openssl11/plan.sh
=> [refresh] - Changing download link for openssl11

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, sumologic/plan.sh
Changes sumologic distribution to latest version to match pkg_source download.
=> [refresh][sumologic] - Changing sumologic to version 19_288-3

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, intltool/plan.sh
=> [refresh2020q1][intltool] fix elixer in intltool

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, libgpg-error/plan.sh
=> [refresh2020q1][libgpg-error] Upgrade libgpg-error to 1.37

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, libnsl/plan.sh
=> [refresh2020q1][libnsl] Fix autoconf macros in libnsl

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, rabbitmq/plan.sh
=> [refresh2020q1][rabbitmq] Upgrade rabbitmq to 3.8.3

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, msgpack/plan.sh
Fixes #3280
Signed-off-by: MindNumbing SMarshall@chef.io
=> [refresh2020q1][msgpack] Update msgpack to 3.2.1

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, ansible/plan.sh
Minor version increase from 2.9.2 -> 2.9.7
Add python2 dependencies manually
Change from python building/installing to make building/installing
Fixes #3288
=> [refresh2020q1][ansible] - Fix ansible encoding

.refresh/just_the_new_plans.txt
Just the new plans introduced by #3321, #3322, #3324, #3326
=>  [refresh2020q1] Update the new-package list

libuv/plan.sh
=> [libuv] Update libuv to 1.35.0

git/plan.ps1, git/plan.sh
```
hab pkg build git
```
```
✓ Version matches plan
✓ Init a git repo
```
=> [git] Update git to 2.26.2

gnutls/plan.sh
Addresses [CVE-2020-11501](https://nvd.nist.gov/vuln/detail/CVE-2020-11501)
=> [gnutls] Update gnutls to 3.6.13

nginx/plan.ps1, nginx/plan.sh
```
```
```
✓ Help command
```
=> [nginx] Update nginx to 1.18.0

.bldr.toml, btrfs-progs/README.md, btrfs-progs/plan.sh, btrfs-progs/tests/test.bats, btrfs-progs/tests/test.sh
=> [btrfs-progs] Add new core/btrfs-progs plan

rust/plan.ps1, rust/plan.sh
=> [rust] Update Rust to 1.42.0

powershell/plan.ps1, powershell/plan.sh
=> [powershell] bump powershell to 7.0.0

zookeeper/config/log4j.properties, zookeeper/hooks/run, zookeeper/plan.sh, zookeeper/tests/test.bats, zookeeper/tests/test.sh
Updates zookeeper to the latest stable. 
Also fixes some bugs in the package and tests around logging and version checks.
Signed-off-by: Ian Henry <ianjhenry00@gmail.com>
=> [zookeeper] bump 3.4.14 to 3.6.1

graphviz/plan.sh
```
hab pkg build graphviz
```
```
✓ minimal dot to svg works
```
=> [graphviz]  Update graphviz to 2.44.0

rust/plan.ps1, rust/plan.sh
=> [rust] Update Rust to 1.43.1

consul/plan.sh
=> [consul] Update consul to 1.7.3

powershell/plan.ps1, powershell/plan.sh
=> [powershell] bump to 7.0.1

go/plan.ps1, go/plan.sh
=> [go] update to 1.14.4

minio/plan.sh, minio/tests/test.bats
Signed-off-by: Yauhen Artsiukhou <jsirex@gmail.com>
=> Update minio version to 2020-06-01T17-28-03Z

.bldr.toml, ps-lock/README.md, ps-lock/plan.ps1
=> [ps-lock] use -IsPath when setting PSModulePath so it works in a local studio

opa/plan.sh
https://github.com/open-policy-agent/opa/releases/tag/v0.21.1
=> [opa] bump 0.19.2 -> 0.21.1

alex/plan.sh
=> [alex] Cleanup and standardise

artifactory/README.md, artifactory/plan.sh, artifactory/tests/test.sh
=> [artifactory] Cleanup and standardise

scaffolding-ruby/doc/reference.md, scaffolding-ruby/lib/scaffolding.sh
Signed-off-by: username-is-already-taken2 <digitalgaz@hotmail.com>
Referenced issue #2837
Adds Rail6 detection, to be fair didn't really add much, most of the magic was already there.
=> [scaffolding-ruby] Added support for Rails6 apps

artifactory-pro/plan.sh, artifactory-pro/tests/test.sh, artifactory/tests/test.sh
=> [artifactory-pro] Cleanup and standardise

acbuild/README.md, acbuild/plan.sh
=> [acbuild] Cleanup and standardise

alsa-lib/plan.sh
=> [alsa-lib] Cleanup and standardise

apr/plan.sh, apr/tests/test.sh
=> [apr] Cleanup and standardise

apr-util/plan.sh, apr-util/tests/test.sh
=> [apr-util] Cleanup and standardise

asciinema/plan.sh
=> [asciinema] Cleanup and standardise

aspcud/plan.sh
=> [aspcud] Cleanup and standardise

at-spi2-atk/README.md, at-spi2-atk/plan.sh
=> [at-spi2-atk] Cleanup and standardise

at-spi2-core/README.md, at-spi2-core/plan.sh
=> [at-spi2-core] Cleanup and standardise

atk/README.md, atk/plan.sh
=> [atk] Cleanup and standardise

autogen/README.md, autogen/plan.sh
=> [autogen] Cleanup and standardise

azure-cli/README.md, azure-cli/plan.sh
=> [azure-cli] Cleanup and standardise

bash-completion/README.md, bash-completion/plan.sh
=> [bash-completion] Cleanup and standardise

bash-static/README.md, bash-static/plan.sh
=> [bash-static] Cleanup and standardise

go/plan.ps1, go/plan.sh
=> [go] update to 1.14.5

opa/plan.sh
https://github.com/open-policy-agent/opa/releases/tag/v0.22.0
=> [opa] bump 0.21.1 -> 0.22.0

rust/plan.ps1, rust/plan.sh
=> [rust] Update to Rust 1.44.1

go/plan.ps1, go/plan.sh
=> [go] update to 1.15

bin/check-bins.sh
This helps us handle the case of packages that have tools that link to
libraries that they also provide.
I also cleaned up some false-positives I was getting from matching
against TDEPS instead of DEPS.
Finally, we surpress the warnings about RPATH for the moment because
it was getting a bit too noisy.
=> [bin/check-bins.sh] handle links to self, reduce noise

.bldr.toml, xmlsec1/README.md, xmlsec1/plan.sh, xmlsec1/tests/test.bats, xmlsec1/tests/test.sh
=> [xmlsec1] Added xmlsec1

acl/plan.sh, acl/tests/test.sh
=> [acl] Cleanup and standardise

attr/README.md, attr/plan.sh
=> [attr] Cleanup and standardise

autoconf/README.md, autoconf/plan.sh
=> [autoconf] Cleanup and standardise

automake/README.md, automake/plan.sh
=> [automake] Cleanup and standardise

aws-cli/README.md, aws-cli/plan.sh
=> [aws-cli] Cleanup and standardise

bash/README.md, bash/plan.sh
=> [bash] Cleanup and standardise

bats/README.md, bats/plan.sh
=> [bats] Cleanup and standardise

busybox-static/README.md, busybox-static/plan.sh
=> [busybox-static] Cleanup and standardise

sumologic/plan.sh
Updates sumologic to latest version
=> [sumologic] - Update sumologic to 19.308-12

doxygen/plan.sh
This changes the download location for doxygen
=> [doxygen] - Change download location

icu/plan.sh, icu52/plan.sh, icu56/plan.sh
- Add pkg upstream to icu, icu52
- Change pkg source for icu, icu52, icu56
- Minor version change for icu52, icu56
=> [icu][icu52][icu56] - Various fixes

haproxy/plan.sh
=> [haproxy] Update HAProxy to 2.2.2

rust/plan.ps1, rust/plan.sh
=> [rust] Update to Rust 1.46.0

htop/plan.sh
Update Major/Minor version to latest - 3.0.2
Change source to new location
Minor style changes
=> [Refresh2020Q3][htop] - Major version change & source change

CODEOWNERS, MAINTAINERS.md, artifactory-pro/README.md, libtalloc/README.md, vault/README.md
It is with a heavy heart that I am resigning as a maintainer for the core-plans repo. Thanks to all for the fun times during this journey! 
See you all down the git log!
-Chris
=> Removing Defilan (Christopher P. Maher) from Maintainers list

.bldr.toml, visual-build-tools-2019/plan.ps1
=> add plan for visual studio 2019

.bldr.toml, postgresql12-client/plan.sh
Signed-off-by: kmacgugan <kmacgugan@chef.io>
=> Add plan for postgresql 12 client

.bldr.toml, dotnet-5-runtime/README.md, dotnet-5-runtime/plan.ps1, dotnet-5-runtime/tests/test.pester.ps1, dotnet-5-runtime/tests/test.ps1, dotnet-5-sdk/README.md, dotnet-5-sdk/plan.ps1, dotnet-5-sdk/tests/test.pester.ps1, dotnet-5-sdk/tests/test.ps1
=> add dotnet 5 sdk and runtime

powershell/plan.ps1, powershell/tests/test.pester.ps1
=> [powershell] bump powershell to 7.1.0

rust/plan.ps1, rust/tests/test.pester.ps1
=> [rust] Update to 1.47

rust/plan.ps1
=> [rust] bump rust to 1.48.0

rust/plan.ps1
=> [rust] bump rust to 1.49.0

rust/plan.ps1
=> [rust] bump rust to 1.50.0

node/tests/test.ps1, node14/tests/test.ps1
=> fix node pester tests

gnupg2/plan.sh
=> fix package name for gnupg2

.bldr.toml, ruby30/README.md, ruby30/plan.sh, ruby30/tests/test.bats, ruby30/tests/test.sh
Update current `core/ruby` to v3.0.0
Add `core/ruby30` with v3.0.0
Signed-off-by: gscho <greg.c.schofield@gmail.com>
=> Add plan for ruby 3.0.0

.bldr.toml, avisynthplus/README.md, avisynthplus/plan.sh
Please review the Changes.
Signed-off-by: raviduddela <ravishankar.duddela@progress.com>
=> Adding avisynth package which is dependency for ffmpeg

.bldr.toml, python39/README.md, python39/plan.ps1
Signed-off-by: Nimit Jyotiana <nimit.jyotiana@hotmail.com>
=> package added python v3.9

.bldr.toml, python38/README.md, python38/plan.ps1
Signed-off-by: Nimit Jyotiana <nimit.jyotiana@hotmail.com>
=> package added python v3.8

rust/plan.ps1
Signed-off-by: Nimit Jyotiana <nimit.jyotiana@hotmail.com>
=> version bumped rust to 1.52.1

powershell/plan.ps1, powershell/plan.sh, powershell/tests/test.bats
=> bump powershell to 7.1.3

rust/plan.ps1
=> bump rust to 1.54.0

zstd/plan.sh, zstd/tests/test.bats
Updated pkg_version 1.4.0 -> 1.4.9 in support of 2021 Q2 core plans refresh.
=> Update zstd Plan Package Version

yaml-cpp/plan.sh
Updated pkg_version 0.6.2 -> 0.6.3 in support of 2021 Q2 core plans refresh.
=> Update yaml-cpp Plan Package Version

vault/plan.sh, vault/tests/test.bats
Updated pkg_version 1.3.2 -> 1.7.0 in support of 2021 Q2 core plans refresh.
=> Update vault Plan Package Version

helm/plan.sh
Updated pkg_version "3.2.4" -> "3.5.3" in support of 2021 Q2 core plans refresh.
=> Update helm Plan Package Version

tomcat7/plan.sh
Updated pkg_version 7.0.73 -> 7.0.108 in support of 2021 Q2 core plans refresh.
=> Update tomcat7 Plan Package Version

socat/plan.sh
Updated pkg_version 1.7.3.3 -> 1.7.4.1 in support of 2021 Q2 core plans refresh.
=> Update socat Plan Package Version

repo/plan.sh
Updated pkg_version '1.12.33' -> '1.13.11' in support of 2021 Q2 core plans refresh.
=> Update repo Plan Package Version

rabbitmqadmin/plan.sh
Updated pkg_version  ->  in support of 2021 Q2 core plans refresh.
=> Update rabbitmqadmin Plan Package Version

pv/plan.sh
Updated pkg_version "1.6.0" -> "1.6.6" in support of 2021 Q2 core plans refresh.
=> Update pv Plan Package Version

ponysay/plan.sh
Updated pkg_version "3.0.2" -> "3.0.3" in support of 2021 Q2 core plans refresh.
=> Update ponysay Plan Package Version

packer/plan.sh
Updated pkg_version 1.5.6 -> 1.7.0 in support of 2021 Q2 core plans refresh.
=> Update packer Plan Package Version

zsh/plan.sh, zsh/tests/test.bats
Updated pkg_version 5.6.2 -> 5.8 in support of 2021 Q2 core plans refresh.
=> Update zsh Plan Package Version

wget-static/plan.sh
Updated pkg_version 1.19.5 -> 1.21 in support of 2021 Q2 core plans refresh.
=> Update wget-static Plan Package Version

opa/plan.sh
Updated pkg_version "0.23.1" -> "0.27.1" in support of 2021 Q2 core plans refresh.
=> Update opa Plan Package Version

oniguruma/plan.sh, oniguruma/tests/test.bats
Updated pkg_version 6.9.4 -> 6.9.6 in support of 2021 Q2 core plans refresh.
=> Update oniguruma Plan Package Version

npth/plan.sh
Updated pkg_version 1.2 -> 1.6 in support of 2021 Q2 core plans refresh.
=> Update npth Plan Package Version

nano/plan.sh, nano/tests/test.bats
Updated pkg_version 4.7 -> 4.9.3 in support of 2021 Q2 core plans refresh.
=> Update nano Plan Package Version

mawk/plan.sh
Updated pkg_version 1.3.4-20161120 -> 1.3.4-20200120 in support of 2021 Q2 core plans refresh.
=> Update mawk Plan Package Version

userspace-rcu/plan.sh
Updated pkg_version 0.9.2 -> 0.12.2 in support of 2021 Q2 core plans refresh.
=> Update userspace-rcu Plan Package Version

libpipeline/plan.sh
Updated pkg_version 1.5.1 -> 1.5.3 in support of 2021 Q2 core plans refresh.
=> Update libpipeline Plan Package Version

jemalloc/plan.sh
Updated pkg_version 4.3.1 -> 4.4.0 in support of 2021 Q2 core plans refresh.
=> Update jemalloc Plan Package Version

ipvsadm/plan.sh, ipvsadm/tests/test.bats
Updated pkg_version 1.30 -> 1.31 in support of 2021 Q2 core plans refresh.
=> Update ipvsadm Plan Package Version

inotify-tools/plan.sh, inotify-tools/tests/test.bats
Updated pkg_version 3.20.2.2 -> 3.20.11.0 in support of 2021 Q2 core plans refresh.
=> Update inotify-tools Plan Package Version

htop/plan.sh
Updated pkg_version 3.0.2 -> 3.0.5 in support of 2021 Q2 core plans refresh.
=> Update htop Plan Package Version

handlebars-cmd/plan.sh, handlebars-cmd/tests/bats/test.bats, handlebars-cmd/tests/test.sh
Bumping to latest master commit for 0.14, fixing git issue in refresh environment.
=> Handlebars-cmd Version Bump

giflib/plan.sh
Updated pkg_version 5.1.4 -> 5.2.1 in support of 2021 Q2 core plans refresh.
=> Update giflib Plan Package Version

graphviz/plan.sh
Updated pkg_version 2.44.0 -> 2.44.1 in support of 2021 Q2 core plans refresh.
=> Update graphviz Plan Package Version

gnatsd/plan.sh
=> Set GO Modules off for gnatsd

filebeat/plan.sh
Updated pkg_version 7.7.1 -> 7.12.0 in support of 2021 Q2 core plans refresh.
=> Update filebeat Plan Package Version

eudev/plan.sh
Updated pkg_version "3.2.7" -> "3.2.10" in support of 2021 Q2 core plans refresh.
=> Update eudev Plan Package Version

envconsul/plan.sh
Updated pkg_version 0.9.2 -> 0.11.0 in support of 2021 Q2 core plans refresh.
=> Update envconsul Plan Package Version

elfutils/plan.sh
Updated pkg_version 0.175 -> 0.183 in support of 2021 Q2 core plans refresh.
=> Update elfutils Plan Package Version

ed/plan.sh, ed/tests/test.bats
Updated pkg_version 1.16 -> 1.17 in support of 2021 Q2 core plans refresh.
=> Update ed Plan Package Version

docutils/plan.sh
Updated pkg_version '0.14' -> '0.16' in support of 2021 Q2 core plans refresh.
=> Update docutils Plan Package Version

docker-compose/plan.sh
Updated pkg_version 1.23.2 -> 1.28.5 in support of 2021 Q2 core plans refresh.
=> Update docker-compose Plan Package Version

curl-static-musl/plan.sh, curl-static-musl/tests/test.bats, curl-static-musl/tests/test.sh
Updated pkg_version 7.70.0 -> 7.75.0 in support of 2021 Q2 core plans refresh.
=> Update curl-static-musl Plan Package Version

virtualenv/plan.sh
Updated pkg_version 15.0.3 -> 15.2.0 in support of 2021 Q2 core plans refresh.
=> Update virtualenv Plan Package Version

curator/plan.sh
Updated pkg_version 5.6.0 -> 5.8.3 in support of 2021 Q2 core plans refresh.
=> Update curator Plan Package Version

rlwrap/plan.sh
Updated pkg_version 0.43 -> 0.44 in support of 2021 Q2 core plans refresh.
=> Update rlwrap Plan Package Version

lua/plan.sh
Updated pkg_version 5.3.4 -> 5.4.2 in support of 2021 Q2 core plans refresh.
=> Update lua Plan Package Version

nettle/plan.sh
Updated pkg_version 3.5.1 -> 3.7.2 in support of 2021 Q2 core plans refresh.
=> Update nettle Plan Package Version

consul/plan.sh
Updated pkg_version 1.7.3 -> 1.9.4 in support of 2021 Q2 core plans refresh.
=> Update consul Plan Package Version

bind/plan.sh
Updated pkg_version 9.17.1 -> 9.17.11 in support of 2021 Q2 core plans refresh.
=> Update bind Plan Package Version

cacerts/plan.ps1
=> Update cacerts Plan Package Version 

benchmark/plan.sh
Updated pkg_version 1.4.1 -> 1.5.2 in support of 2021 Q2 core plans refresh.
=> Update benchmark Plan Package Version

bash-static/bash-patches.sh, bash-static/plan.sh
Updated pkg_version  ->  in support of 2021 Q2 core plans refresh.
=> Update bash-static Plan Package Version

guile/plan.sh
Updated pkg_version 2.0.12 -> 2.2.7 in support of 2021 Q2 core plans refresh.
=> Update guile Plan Package Version

autogen/plan.sh, autogen/tests/test.bats
Updated pkg_version 5.18.10 -> 5.18.16 in support of 2021 Q2 core plans refresh.
=> Update autogen Plan Package Version

varnish/patches/000-configure.patch, varnish/plan.sh, varnish/tests/scripts/varnish-ready
Updated pkg_version "5.1.2" -> "5.2.1" in support of 2021 Q2 core plans refresh.
=> Update varnish Plan Package Version

ansible/plan.sh, ansible/tests/test.bats
Updated pkg_version 2.9.7 -> 2.11.0b2 in support of 2021 Q2 core plans refresh.
=> Update ansible Plan Package Version

clingo/plan.sh, clingo/tests/test.bats
Updated pkg_version "5.3.0" -> "5.4.1" in support of 2021 Q2 core plans refresh.
=> Update clingo Plan Package Version

strace/patches/000-binutils-wide.patch, strace/plan.sh, strace/tests/test.bats
Updated pkg_version 5.7 -> 5.11 in support of 2021 Q2 core plans refresh.
=> Update strace Plan Package Version

pngquant/plan.sh, pngquant/tests/test.bats
Updated pkg_version 2.12.5 -> 2.14.1 in support of 2021 Q2 core plans refresh.
=> Update pngquant Plan Package Version

msgpack/plan.sh
Updated pkg_version "3.2.1" -> "3.3.0" in support of 2021 Q2 core plans refresh.
=> Update msgpack Plan Package Version

ghc/plan.sh, ghc82/plan.sh
Fixing ghc82 build in support of 2021 Q2 core plans refresh
=> Updating libffi regex for ghc82

gdb/plan.sh, gdb/tests/test.bats
Updated pkg_version 8.3 -> 8.3.1 in support of 2021 Q2 core plans refresh.
=> Update gdb Plan Package Version

mariadb/plan.sh
Updated pkg_version 10.1.24 -> 10.5.9 in support of 2021 Q2 core plans refresh.
=> Update mariadb Plan Package Version

rpm/plan.sh
Updated pkg_version 4.14.2.1 -> 4.16.1.3 in support of 2021 Q2 core plans refresh.
=> Update rpm Plan Package Version

shield/plan.sh, shield/tests/scripts/is-present, shield/tests/scripts/lib/functions, shield/tests/scripts/run, shield/tests/scripts/shield-ready, shield/tests/scripts/tests/postgres
Updated pkg_version "0.10.8" -> "0.10.9" in support of 2021 Q2 core plans refresh.
=> Update shield Plan Package Version

psscriptanalyzer/plan.sh
Updated pkg_version "1.18.3" -> "1.19.1" in support of 2021 Q2 core plans refresh.
=> Update psscriptanalyzer Plan Package Version

msodbcsql17/plan.sh
Updated pkg_version 17.2.0.1-1 -> 17.7.2.1-1 in support of 2021 Q2 core plans refresh.
=> Update msodbcsql17 Plan Package Version

rust/plan.ps1
=> Update rust Plan Package Version

postgresql94-client/plan.ps1
=> Update postgresql-client94 Plan Package Version

nasm/plan.ps1
=> Update nasm Plan Package Version

glib/plan.sh
Updated pkg_version "2.50.3" -> "2.68.0" in support of 2021 Q2 core plans refresh.
=> Update glib Plan Package Version

at-spi2-core/plan.sh
Updated pkg_version 2.26.2 -> 2.40.0 in support of 2021 Q2 core plans refresh.
=> Update at-spi2-core Plan Package Version

cppunit/plan.sh
Updated pkg_version '1.14.0' -> '1.15.1' in support of 2021 Q2 core plans refresh.
=> Update cppunit Plan Package Version

.bldr.toml, lessmsi/plan.ps1
=> Update lessmsi Plan Package Version

go/plan.ps1
=> Update go Plan Package Version 

.bldr.toml, docker-credential-helper/plan.ps1
=> Update docker-credential Plan Package Version 

corretto11/plan.ps1
=> Update corretto11 Plan Package Version

cmake/plan.ps1, cmake/tests/test.pester.ps1
=> Update cmake Plan Package Version

node12/plan.ps1, node12/tests/test.pester.ps1, node12/tests/test.ps1
Updated pkg_version "12.14.1" -> "12.22.1" in support of 2021 Q2 core plans refresh.
=> Update node12 Plan Package Version

php/plan.sh, php/tests/test.bats
Updated pkg_version 7.4.2 -> 7.4.16 in support of 2021 Q2 core plans refresh.
=> Update php Plan Package Version

composer/plan.sh
Updated pkg_version 1.10.5 -> 1.10.20 in support of 2021 Q2 core plans refresh.
=> Update composer Plan Package Version

libxscrnsaver/plan.sh
Updated pkg_version 1.2.2 -> 1.2.3 in support of 2021 Q2 core plans refresh.
=> Update libxscrnsaver Plan Package Version

xeyes/plan.sh
Updated pkg_version 1.1.1 -> 1.1.2 in support of 2021 Q2 core plans refresh.
=> Update xeyes Plan Package Version

artifactory/plan.sh, artifactory/tests/test.bats
Updated pkg_version 6.11.3 -> 6.23.13 in support of 2021 Q2 core plans refresh.
=> Update artifactory Plan Package Version

ant/plan.sh
Updated pkg_version 1.10.7 -> 1.10.9 in support of 2021 Q2 core plans refresh.
=> Update ant Plan Package Version

sumologic/plan.sh
Updated pkg_version "19.308-12" -> "19.338.3" in support of 2021 Q2 core plans refresh.
=> Update sumologic Plan Package Version

kubernetes/plan.sh
Updated pkg_version 1.11.2 -> 1.20.5 in support of 2021 Q2 core plans refresh.
=> Update kubernetes Plan Package Version

kubernetes-controller-manager/plan.sh, kubernetes-scheduler/plan.sh
Updated pkg_version  1.11.2 -> 1.20.5 in support of 2021 Q2 core plans refresh.
=> Update kubernetes-scheduler Plan Package Version

libgd/plan.sh, logback/plan.sh
Updated pkg_version 1.1.8 -> 1.2.3 in support of 2021 Q2 core plans refresh.
=> Update logback Plan Package Version

shield-agent/plan.sh
Updated pkg_version "0.10.8" -> "0.10.9" in support of 2021 Q2 core plans refresh.
=> Update shield-agent Plan Package Version

subversion/plan.sh, subversion/tests/test.bats
Updated pkg_version 1.13.0 -> 1.14.1 in support of 2021 Q2 core plans refresh.
=> Update subversion Plan Package Version

journalbeat/plan.sh, journalbeat/tests/test.sh
Updated pkg_version 7.2.0 -> 7.11.2 in support of 2021 Q2 core plans refresh.
=> Update journalbeat Plan Package Version

ffmpeg3/patches/000-libopenjpeg-2-4.patch, ffmpeg3/plan.sh
Updated pkg_version 3.4.6 -> 3.4.8 in support of 2021 Q2 core plans refresh.
=> Update ffmpeg3 Plan Package Version

llvm/plan.sh
Updated pkg_version 7.0.1 -> 7.1.0 in support of 2021 Q2 core plans refresh.
=> Update llvm Plan Package Version

alex/plan.sh
Updated pkg_version 3.2.5 -> 3.2.6 in support of 2021 Q2 core plans refresh.
=> Update alex Plan Package Version

git/plan.ps1, git/tests/test.pester.ps1
Updated pkg_version -$pkg_version = "2.26.2" -> +$pkg_version = "2.31.1" in support of 2021 Q2 core plans refresh.
=> Update git Plan Package Version

node/plan.ps1, node/tests/test.pester.ps1, node/tests/test.ps1
Updated pkg_version "12.14.1" -> "12.22.1" in support of 2021 Q2 core plans refresh.
=> Update node Plan Package Version

node6/plan.ps1, node6/tests/test.pester.ps1, node6/tests/test.ps1
Updated pkg_version "6.14.3" -> "6.17.1" in support of 2021 Q2 core plans refresh.
=> Update node6 Plan Package Version

corretto/plan.ps1
Updated pkg_version "11.0.8.10.1" -> "11.0.11.9.1" in support of 2021 Q2 core plans refresh.
=> Update corretto Plan Package Version

dotnet-5-sdk/plan.ps1
Updated pkg_version "5.0.100" -> "5.0.202" in support of 2021 Q2 core plans refresh.
=> Update dotnet-5-sdk Plan Package Version

.expeditor/config.yml, xz/plan.ps1, xz/tests/test.pester.ps1, xz/tests/test.ps1
Updated pkg_version "5.2.4" -> "5.2.5" in support of 2021 Q2 core plans refresh.
=> Update xz Plan Package Version

.bldr.toml, .expeditor/config.yml, innounp/plan.ps1
Updated pkg_version "0.46" -> "0.50" in support of 2021 Q2 core plans refresh.
=> Update innounp Plan Package Version

grpc-cpp/plan.sh
Updated pkg_version "1.25.0" -> "1.36.4" in support of 2021 Q2 core plans refresh.
=> Update grpc-cpp Plan Package Version

.expeditor/config.yml, windows-10-sdk/plan.ps1
Signed-off-by: Ravi Duddela <rduddela@progress.com>
=> Bumped 'windows-sdk-10' version 10.0.17763 -> 10.0.19041

dotnet-core-sdk/plan.ps1
=> fix MSBuildSDKsPath for dotnet-core-sdk

visual-build-tools-2019/plan.ps1
=> fixing VC tools version in paths for visual-build-tools-2019

php/plan.sh, php/tests/gettext_support.php, php/tests/test.bats
This doesn't require new dependencies.
I needed it for the latest version of my [ampache](https://www.ampache.org) package.
=> [php] Add support for gettext

openssl/plan.ps1
=> [openssl] fixing missing ssl folder on windows

buildkite-agent/plan.sh
Has updated version in builder.
Need to merge the changes.
Please review
=> Buildkite agent version bump

nspr/plan.sh
https://github.com/habitat-sh/core-plans/issues/4102
=> nspr bumped from 4.30 to 4.32

rabbitmqadmin/plan.sh
https://github.com/habitat-sh/core-plans/issues/4096
=> update rabbitmqadmin issue 4096

telegraf/plan.sh, tmux/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4092
=> updating tmux,telegraf from issue 4092

tomcat7/plan.sh, tomcat8/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4091 
=> Upgrading tomcat7 and 8 versions. issue4091

postgresql11-client/plan.sh, postgresql96-client/plan.sh
postgresql11-client from 11.11 to 11.14
postgresql96-client from 9.6.21 to 9.6.24
=> Issue 4099 [postgresql11-client and postgresql96-client bumped]

man-pages/plan.sh, mongo-tools/plan.sh
https://github.com/habitat-sh/core-plans/issues/4106
man-pages from 5.11 to 5.13
mongo-tools from 3.6.23 to 3.7.9
=> Issue 4106 [man-pages and mongo-tools bumped]

sassc/plan.sh
https://github.com/habitat-sh/core-plans/issues/4094
=> Issue 4094 [sassc bumped from 3.6.1 to 3.6.2]

rust/plan.ps1
Signed-off-by: pozsgaic <pozsgai@progress.com>
=> bump rust to 1.56.1

helm/plan.sh, zstd/plan.sh
details of packages upgraded : https://github.com/habitat-sh/core-plans/issues/4089
=> upgrade of hab packages

libfcgi/plan.sh, libidn/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4111 
=> updating libfcgi and libidn

krb5/plan.sh, libimagequant/plan.sh, libtirpc/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4110
=> updating krb5 libtirpc libimagequant

htop/plan.sh, hwloc/plan.sh, inotify-tools/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4115
=> updating  htop hwloc inotify-tools

gsl/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4117
=> updating gsl

grafana/plan.sh, graphviz/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4118
=> updating grafana and graphviz

c-ares/plan.sh, cabal-install/plan.sh, dgraph/plan.sh, docker-compose/plan.sh, docutils/plan.sh, libunwind/plan.sh
packages upgraded 
- c-ares
- cabal-install
- libunwind
- docutils
- dgraph
- docker-compose
Fixes issue https://github.com/habitat-sh/core-plans/issues/4129
=> hab pkg upgrade

c-ares/plan.sh, cabal-install/plan.sh, dgraph/plan.sh, docker-compose/plan.sh, docutils/plan.sh, etcd/plan.sh, libunwind/plan.sh
package upgraded :
- c-ares
- cabal-install
- libunwind
- docutils
- dgraph
- docker-compose
- etcd
fixes following issues :
https://github.com/habitat-sh/core-plans/issues/4128
https://github.com/habitat-sh/core-plans/issues/4129
https://github.com/habitat-sh/core-plans/issues/4125
https://github.com/habitat-sh/core-plans/issues/4171
=> upgraded hab packages

ocaml/plan.sh
https://github.com/habitat-sh/core-plans/issues/4136
=> Issue4136 [ocaml bumped from 4.12.0 to 4.13.1]

buildkite-agent/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4137
=> Issue4137 [buildkite-agent bumped from 3.28.1 to 3.33.3]

boost/plan.sh
https://github.com/habitat-sh/core-plans/issues/4140
boost bumped from 1.75.0 to 1.77.0
=> Issue4140 [boost bumped from 1.75.0 to 1.77.0]

ruby25/plan.sh, ruby26/plan.sh, ruby30/plan.sh
Issue:https://github.com/habitat-sh/core-plans/issues/4144
ruby25 from 2.5.8 to 2.5.9
ruby26 from 2.6.8 to 2.6.9
ruby30 from 3.02 to 3.0.3
=> Issue4144 [ruby25 to 2.5.9, ruby26 to 2.6.9 and ruby30 to 3.0.3 bumped]

benchmark/plan.sh, bind/plan.sh, ccache/plan.sh, googletest/plan.sh, libatomic_ops/plan.sh, libuv/plan.sh
upgraded packages
- ccache
- libuv
- libatomic_ops
- googletest
- bind
fixes issue https://github.com/habitat-sh/core-plans/issues/4138
=> hab package upgrade

openvpn/plan.sh
fixes issue https://github.com/habitat-sh/core-plans/issues/4146
=> upgraded openvpn to v2.5.4

doxygen/plan.sh, lua/plan.sh, nss/plan.sh, rlwrap/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4134 
=> updating doxygen,lua,nss and rlwrap

ansible/plan.sh, traefik/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4142
=> updating ansible and traefik

flatbuffers/plan.sh, freetds/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4122 
=> upgrading flatbuffers and freetds

camlp4/plan.sh, curator4/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4156
camlp4 from 4.12 to 4.13
curator4 from 4.2.6 to 4.3.1
=> Issue 4156 [camlp4 to 4.13 and curator4 to 4.3.1 bumped]

strace/plan.sh, tcpdump/plan.sh, tor/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4143
=> updating strace,tcpdump and tor

imagemagick/plan.sh, liberation-fonts-ttf/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4151
=> updating imagemagick and liberation-fonts-ttf

rabbitmq/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4160
=> Issue4160 [rabbitmg bumped from 3.8.14 to 3.9.11]

grub/plan.sh, json-glib/plan.sh, metricbeat/plan.sh, systemd/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4165
=> updating grub,json-glib,metricbeat and systemd

fluentd/plan.sh, gdk-pixbuf/plan.sh, mysql-client/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4167
mysql-client from 5.7.32 to 5.7.35
Fluentd from 1.12.1 to 1.14.3
gdk-pixbuf from 2.36.11 to 2.42.6
=> Issue4167 [mysql-client to 5.7.35, fluentd to 1.14.3 and gdk-pixbuf to 2.42.6]

elasticsearch/plan.sh
=> upgraded elasticsearch to v6.8.21

at-spi2-core/plan.sh, httpd/plan.sh, mc/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4164
=> Updating at-spi2-core httpd mc

journalbeat/plan.sh
=> upgraded journalbeat to v7.15.2

percona-xtrabackup/plan.sh, prometheus-cpp/plan.sh, psscriptanalyzer/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4161
=> updating prometheus-cpp psscriptanalyzer percona-xtrabackup

ant/plan.sh, artifactory/plan.sh, sumologic/plan.sh, tomcat-native/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4179
=> uprading ant artifactory sumologic tomcat-native

coredns/plan.sh
https://github.com/habitat-sh/core-plans/issues/4193
=> Issue4193 [coredns bumped from 1.8.3 to 1.8.6]

direnv/plan.sh, dnsmasq/plan.sh
upgraded package
- direnv
- dnsmasq
fixes #4186 
=> package upgrade - direnv, dnsmasq

scowl/plan.sh
=> upgraded scowl to v2020.12.07

jffi/plan.sh, logback/plan.sh
upgraded package
- logback
- jffi
fixes #4189 
=> package upgrade - logback, jffi

elasticsearch5/plan.sh, jruby/plan.sh
upgraded package
- elasticsearch5
- jruby
fixes #4185 
=> package upgrade - elasticsearch5, jruby

artifactory-pro/plan.sh, cerebro/plan.sh, logstash/plan.sh
upgraded packages
- artifacory-pro
- logstash
- cerebro
fixes #4184 
=> package upgrade - cerebro, logstash, artifactory-pro

ghc/plan.sh
packages upgraded
- ghc
fixes #4190
=> package upgrade - ghc

R/plan.sh, sbt/plan.sh, spark/plan.sh, storm/plan.sh
Issue:https://github.com/habitat-sh/core-plans/issues/4180
storm from 1.2.3 to 1.2.4
spark from 2.4.7 to 2.4.8
sbt from 1.4.9 to 1.5.6
R from 3.5.0 to 3.6.3
=> Issue4180 [strom, spark, R and sbt bumped]

envoy/plan.sh, grpcurl/plan.sh, hspec-discover/plan.sh, rethinkdb/datum_endian_fix.patch, rethinkdb/node_heap_fix.patch, rethinkdb/plan.sh, rethinkdb/v8_4-gcc6+.patch
Issue: https://github.com/habitat-sh/core-plans/issues/4191
=> updating envoy,grpcurl,hspec-discover,rethinkdb

.bldr.toml, gobject-introspection/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4346
Added for building atk package.
=> New package gobject-introspection added for building atk package

elasticsearch/plan.sh, logstash/plan.sh, pango/plan.sh
=> updating pango to 1.41.1

drupal/plan.sh, kafka2/plan.sh, xmlsec1/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4192
=> updating drupal kafka2 and xmlsex1

.bldr.toml, .pre-commit-config.yaml, fribidi/README.md, fribidi/plan.sh
Adding fribidi required by other packages gtk,pango...etc.
=> adding fribidi package required by other packages

.bldr.toml, .pre-commit-config.yaml, gobject-introspection/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4346
=> Issue4346 [Removed building subproject and added as dependent packages]

atk/plan.sh
ATK package added to skip list, reverting changes to main
=> Issue4162 [atk changes reverted as atk added to skip list]

elasticsearch/plan.sh, logstash/plan.sh
=> upgraded elasticsearch and logstash to v6.8.23

elasticsearch/plan.sh, logstash/plan.sh
elasticsearch and log stash upgraded to v6.8.23
fixes #4363 
=> package upgrade: elasticsearch, log stash

dotnet-asp-core/plan.sh, dovecot/plan.sh, gnuplot/plan.sh, rpm/plan.sh
upgraded package:
* rpm
* dovecot
* botnet-asp-core
* gnuplot
fixes #4155 #4333 
=> package upgrade: rpm, dovecot, dotnet-asp-core, gnuplot

postgresql13-client/plan.sh
https://github.com/habitat-sh/core-plans/issues/4371
=> postgresql13-client bumped from 13.4 to 13.5

netcat-openbsd/plan.sh
=> build issue fix

certstrap/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4377
=> Fixing the build issue for cloning

aspcud/non-const-MINSIGSTKSZ-fix.patch, aspcud/plan.sh
Issue: https://chefio.atlassian.net/browse/HABP-76 
=> build issue fix for non-const MINSIGSTKSZ

postfix/plan.sh, postfix/postfix-glibc-2.34.patch
Issue: https://chefio.atlassian.net/jira/software/c/projects/HABP/boards/378?modal=detail&selectedIssue=HABP-74
=> Postfix build issue fixed for closefrom error

composer/plan.sh
=> shasum fix for composer package

kafka/plan.sh
=> fetch url fix

gdb/config.h-fix.patch, gdb/plan.sh
Issue: https://chefio.atlassian.net/jira/software/c/projects/HABP/boards/378?modal=detail&selectedIssue=HABP-75
=> Include config.h issue fixed for gdb package

tlog/plan.sh
Issue: https://chefio.atlassian.net/browse/HABP-83
=> build issue with new version of systemd

cppcheck/glibc_SIGSTKSZ_fix.patch, cppcheck/plan.sh
Issue: https://chefio.atlassian.net/browse/HABP-82
=> build issue with newer glibc where SIGSTKSZ is not constant

rabbitmq/plan.sh
fixes https://chefio.atlassian.net/browse/HABP-81?atlOrigin=eyJpIjoiYTJjNWNiN2RkN2NkNDZkMzkwNWI4YTk0MWU2ZWZlNzEiLCJwIjoiaiJ9
=> upgrade rabbitmq to v3.9.13

cabal-install/curl_error60.patch, cabal-install/plan.sh
fixes https://chefio.atlassian.net/browse/HABP-86
=> [cabal-install] revert upgrade to v3.0.0.0

postgresql96-client/plan.sh
Issue: https://chefio.atlassian.net/jira/software/c/projects/HABP/boards/378?modal=detail&selectedIssue=HABP-93
=> postgresql96-client bumped from 9.6.21 to 9.6.24

netcat-openbsd/plan.sh
Issue: https://chefio.atlassian.net/browse/HABP-103
=> update patch url.fixing build issue

corretto/plan.ps1, corretto11/plan.ps1, corretto8/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-38
corretto bumped from 11.0.11.9.1 to 11.0.14.10.1
corretto11 bumped from 11.0.11.9.1 to 11.0.14.10.1
corretto8 bumped from 8.292.10.1 to 8.322.06.1
=> issue HABP-38 [corretto, corretto8 and corretto11 bumped for windows]

libarchive/plan.ps1, maven/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-44
libarchive bumped from 3.5.1 to 3.5.2
maven bumped from 3.6.3 to 3.8.4
=> Issue-HABP-44 [libarchive and maven bumped for windows]

maven/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-44
=> maven 3.8.4 zip missing, so bumped 3.8.5

innounp/plan.ps1, lessmsi/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-43
Innounp bumped from 0.46 to 0.50
lessmsi bumped from 1.8.1 to 1.10.0
=> Issue-HABP-43 [innounp and lessmsi bumped for winodows]

psscriptanalyzer/plan.ps1, python/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-49
psscriptanalyzer from 1.19.1 to 1.20.0
python from 3.9.5 to 3.9.10
=> Issue-HABP-49 [psscriptanalyer and python bumperd for windows]

python39/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-50
Python39 bumped from 3.9.5 to 3.9.10
=> Issue-HABP-50 [python39 bumped for Windows]

rust/plan.ps1, shellcheck/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-51
rust from 1.56.1 to 1.59.0
shellcheck from 0.7.2 to 0.8.0
=> Issue-HABP-51 [rust and shellcheck bumped for Windows]

visual-cpp-redist-2015/plan.ps1, windows-10-sdk/plan.ps1, xz/plan.ps1, yarn/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-53
visual-cpp-redist-2015 bumped from 14.0.23026 to 14.0.24215
windows-10-sdk bumped from 10.0.19041 to 10.0.22000
xz bumped from 5.2.4 to 5.2.5
yarn bumped from 1.22.5 to 1.22.18
=> Issue-HABP-53 [visual-cpp-redist-2015,windows-10-sdk,xz and yarn bumped for Windows]

cacerts/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-118
=> Issue-HABP-118 [Updating date parse format to fix build issue]

.expeditor/generate_verify_pipeline.sh
=> fix build issue

bin/ci/build-and-run-tests.sh
=> adding exception for unsafe git dir CVE-2022-24765

.bldr.toml, erlang24/README.md, erlang24/plan.sh
=> Adding new package erlang24 for chef server

curl-static-musl/plan.sh, curl-static-musl/tests/test.bats, curl-static-musl/tests/test.sh
issue : https://github.com/chef/customer-bugs/issues/747
=> [curl-static-musl] fix for binary not being musl and static

.bldr.toml, bin/ci/build-and-run-tests.sh, ruby31/README.md, ruby31/plan.sh, ruby31/tests/test.bats, ruby31/tests/test.sh
Signed-off-by: John McCrae <john.mccrae@progress.com>
Adding Ruby 3.1 plan into the mix
=> starting to integrate ruby 3.1 into the builds

glibc/LICENSE, glibc/README.md, glibc/controls/correct_abi_version.rb, glibc/controls/correct_ldconfig_cache.rb, glibc/controls/correct_ldd_search_path.rb, glibc/controls/correct_ldd_textdomaindir.rb, glibc/controls/tzselect_works.rb, glibc/dont-use-system-ld-so.patch, glibc/inspec.lock, glibc/inspec.yml, glibc/plan.sh, glibc/tests/bats/test.bats, glibc/tests/test.sh, glibc/x86_64-linux-kernel2/0005-fix-binutils-2-29-build.patch, glibc/x86_64-linux-kernel2/dont-use-system-ld-so.patch, glibc/x86_64-linux-kernel2/gcc-implicit-boolean.patch, glibc/x86_64-linux-kernel2/glibc-2.23-upstream_fixes-1.patch, glibc/x86_64-linux-kernel2/nss-nisplus-gcc7.patch, glibc/x86_64-linux-kernel2/plan.sh, glibc/x86_64-linux-kernel2/remove-sun-rpm-bug.patch, glibc/x86_64-linux-kernel2/rpcgen-path.patch, glibc/x86_64-linux-kernel2/testsuite-fix.patch, gmp/LICENSE, gmp/README.md, gmp/controls/gmp_exists.rb, gmp/inspec.yml, gmp/plan.sh, gmp/tests/test.sh
=> move glibc,gmp to core

geos/LICENSE, geos/README.md, geos/controls/geos_exists.rb, geos/controls/geos_works.rb, geos/inspec.yml, geos/plan.sh, geos/tests/test.bats, geos/tests/test.sh, gettext/LICENSE, gettext/README.md, gettext/controls/gettext_exists.rb, gettext/controls/gettext_works.rb, gettext/disable-test.patch, gettext/inspec.yml, gettext/plan.sh, gettext/tests/test.bats, gettext/tests/test.sh
=> move geos,gettext to core

.bldr.toml, gdbm/LICENSE, gdbm/README.md, gdbm/controls/gdbm_exists.rb, gdbm/controls/gdbm_works.rb, gdbm/inspec.yml, gdbm/plan.sh, gdbm/tests/test.bats, gdbm/tests/test.sh, gecode/LICENSE, gecode/README.md, gecode/controls/gecode_library_exists.rb, gecode/inspec.yml, gecode/plan.sh
=> move gecode,gdbm to core

gcc-libs/LICENSE, gcc-libs/README.md, gcc-libs/controls/gcc-libs_exist.rb, gcc-libs/inspec.yml, gcc-libs/no-sys-dirs.patch, gcc-libs/plan.sh, gdal/LICENSE, gdal/README.md, gdal/controls/gdal_exists.rb, gdal/controls/gdal_works.rb, gdal/inspec.yml, gdal/plan.sh, gdal/tests/test.bats, gdal/tests/test.sh
=> move gcc-libs,gdal to core

fontconfig/LICENSE, fontconfig/README.md, fontconfig/controls/fontconfig_exists.rb, fontconfig/controls/fontconfig_works.rb, fontconfig/glibc-2.25+.patch, fontconfig/inspec.yml, fontconfig/plan.sh, freetype/LICENSE, freetype/README.md, freetype/controls/freetype_works.rb, freetype/inspec.yml, freetype/plan.sh
=> move fontconfig,freetype to core

expat/LICENSE, expat/README.md, expat/controls/expat_exists.rb, expat/controls/expat_works.rb, expat/inspec.yml, expat/plan.sh, expat/tests/fixtures/mismatched-tag.xml, expat/tests/fixtures/valid.xml, expat/tests/test.bats, expat/tests/test.sh, expect/LICENSE, expect/README.md, expect/controls/expect_test.rb, expect/inspec.yml, expect/plan.sh
=> move expat,expect to core

erlang20/LICENSE, erlang20/README.md, erlang20/controls/erlang20_exists.rb, erlang20/controls/erlang20_works.rb, erlang20/inspec.yml, erlang20/plan.sh, erlang20/tests/test.bats, erlang20/tests/test.sh, erlang21/LICENSE, erlang21/README.md, erlang21/controls/erlang21_exists.rb, erlang21/controls/erlang21_works.rb, erlang21/inspec.yml, erlang21/plan.sh, erlang21/tests/test.bats, erlang21/tests/test.sh, erlang22/LICENSE, erlang22/README.md, erlang22/controls/erlang22_exists.rb, erlang22/controls/erlang22_works.rb, erlang22/inspec.yml, erlang22/plan.sh, erlang22/tests/test.bats, erlang22/tests/test.sh
=> move erlang20,21,22 to core

check/LICENSE, check/README.md, check/attributes.yml, check/azure-pipelines.yml, check/botanist.yml, check/controls/check_test.rb, check/inspec.yml, check/plan.sh, clens/LICENSE, clens/README.md, clens/attributes.yml, clens/azure-pipelines.yml, clens/botanist.yml, clens/controls/clens_test.rb, clens/inspec.yml, clens/plan.sh
=> move check,clens to core

protobuf-cpp/README.md, protobuf-cpp/controls/protobuf-cpp_works.rb, protobuf-cpp/inspec.yml, protobuf-cpp/plan.sh, protobuf-rust/README.md, protobuf-rust/controls/protobuf-rust_exists.rb, protobuf-rust/inspec.yml, protobuf-rust/plan.sh
=> moving protobuf-cpp and protobuf-rust from Base-plan to Core-plan

.bldr.toml, hugo/LICENSE, hugo/README.md, hugo/controls/hugo_exists.rb, hugo/controls/hugo_works.rb, hugo/inspec.yml, hugo/plan.sh, hugo/tests/test.bats, hugo/tests/test.sh
=> move hugo to core

gawk/LICENSE, gawk/README.md, gawk/controls/gawk_exists.rb, gawk/controls/gawk_works.rb, gawk/inspec.yml, gawk/plan.sh, gawk/tests/test.bats, gawk/tests/test.sh, gcc/LICENSE, gcc/README.md, gcc/cc-wrapper.sh, gcc/controls/gcc_works.rb, gcc/inspec.yml, gcc/no-sys-dirs.patch, gcc/plan.sh, gcc/tests/bats/test.bats, gcc/tests/test.sh
=> move gawk,gcc to core

.bldr.toml, fixesproto/LICENSE, fixesproto/README.md, fixesproto/controls/fixesproto_library_exists.rb, fixesproto/inspec.yml, fixesproto/plan.sh, flex/LICENSE, flex/README.md, flex/controls/flex_exists.rb, flex/controls/flex_works.rb, flex/inspec.yml, flex/plan.sh, flex/tests/test.bats, flex/tests/test.sh
=> move fixesproto,flex to core

db/LICENSE, db/README.md, db/attributes.yml, db/azure-pipelines.yml, db/botanist.yml, db/controls/db_exists.rb, db/controls/db_works.rb, db/inspec.yml, db/patches/atomic.patch, db/plan.sh, dejagnu/LICENSE, dejagnu/README.md, dejagnu/attributes.yml, dejagnu/azure-pipelines.yml, dejagnu/botanist.yml, dejagnu/controls/dejagnu_exists.rb, dejagnu/controls/dejagnu_works.rb, dejagnu/inspec.yml, dejagnu/plan.sh, dejagnu/tests/test.bats, dejagnu/tests/test.sh
=> move db,dejagnu to core

curl/LICENSE, curl/README.md, curl/attributes.yml, curl/azure-pipelines.yml, curl/botanist.yml, curl/controls/curl_exists.rb, curl/controls/curl_works.rb, curl/inspec.yml, curl/plan.sh, curl/tests/test.bats, curl/tests/test.sh, cyrus-sasl/LICENSE, cyrus-sasl/README.md, cyrus-sasl/attributes.yml, cyrus-sasl/azure-pipelines.yml, cyrus-sasl/botanist.yml, cyrus-sasl/controls/cyrus-sasl_exists.rb, cyrus-sasl/controls/cyrus-sasl_works.rb, cyrus-sasl/inspec.yml, cyrus-sasl/plan.sh, cyrus-sasl/tests/test.bats, cyrus-sasl/tests/test.sh
=> move curl,cyrus-sasl to core

binutils/0001-PR23428-x86-Add-a-GNU_PROPERTY_X86_ISA_1_USED-note-if-needed.patch, binutils/0004-PR23486-Properly-merge-GNU_PROPERTY_X86_ISA_1_USED-x86_64.patch, binutils/0005-PR23486-x86-Properly-merge-GNU_PROPERTY_X86_ISA_1_USED.patch, binutils/0006-PR23428-x86-Properly-add-X86_ISA_1_NEEDED-property.patch, binutils/LICENSE, binutils/README.md, binutils/attributes.yml, binutils/azure-pipelines.yml, binutils/botanist.yml, binutils/controls/binary_tests.rb, binutils/controls/binutils_works.rb, binutils/custom-libs.patch, binutils/inspec.yml, binutils/ld-wrapper.sh, binutils/malformarchive-linking-fix.patch, binutils/plan.sh, binutils/tests/test.bats, binutils/tests/test.sh, bison/LICENSE, bison/README.md, bison/attributes.yml, bison/azure-pipelines.yml, bison/botanist.yml, bison/controls/bison_exists.rb, bison/controls/bison_works.rb, bison/inspec.yml, bison/plan.sh, bison/tests/test.bats, bison/tests/test.sh
=> move binutils,bison to core

.bldr.toml, acl/LICENSE, acl/README.md, acl/attributes.yml, acl/azure-pipelines.yml, acl/botanist.yml, acl/controls/acl_exists.rb, acl/controls/acl_works.rb, acl/inspec.yml, acl/plan.sh, acl/tests/test.bats, acl/tests/test.sh, alsa-lib/LICENSE, alsa-lib/README.md, alsa-lib/attributes.yml, alsa-lib/azure-pipelines.yml, alsa-lib/botanist.yml, alsa-lib/controls/alsa-lib_exists.rb, alsa-lib/controls/alsa-lib_library_exists.rb, alsa-lib/controls/alsa-lib_works.rb, alsa-lib/inspec.yml, alsa-lib/plan.sh, alsa-lib/tests/test.bats, alsa-lib/tests/test.sh
=> moving acl,alsa-lib to core

protobuf2/README.md, protobuf2/controls/protobuf2_exists.rb, protobuf2/controls/protobuf2_works.rb, protobuf2/inspec.yml, protobuf2/plan.sh, psmisc/README.md, psmisc/controls/psmisc_exists.rb, psmisc/controls/psmisc_works.rb, psmisc/inspec.yml, psmisc/plan.sh, psmisc/tests/test.bats, psmisc/tests/test.sh
=> moving protobuf2 and psmisc from Base-plan to Core-plan

python-minimal/README.md, python-minimal/controls/python_works.rb, python-minimal/inspec.yml, python-minimal/plan.sh, python-minimal/tests/test.sh, python35/README.md, python35/controls/python35_works.rb, python35/inspec.yml, python35/plan.sh
=> moving python-minimal and python35 from Base-plan to Core-plan

.bldr.toml, node16/README.md, node16/controls/node_exists.rb, node16/controls/node_works.rb, node16/inspec.yml, node16/plan.sh
=> moving node16 from Base-plan to Core-plan

zlib-musl/README.md, zlib-musl/attributes.yml, zlib-musl/azure-pipelines.yml, zlib-musl/controls/zlib_musl_test.rb, zlib-musl/inspec.yml, zlib-musl/plan.sh
=> [zlib-musl] moved from chef-base-plans org

.bldr.toml, xtrans/README.md, xtrans/attributes.yml, xtrans/azure-pipelines.yml, xtrans/controls/xtrans_library_exists.rb, xtrans/inspec.yml, xtrans/plan.sh, xxhash/README.md, xxhash/attributes.yml, xxhash/azure-pipelines.yml, xxhash/controls/xxhash_exists.rb, xxhash/controls/xxhash_works.rb, xxhash/inspec.yml, xxhash/plan.sh
=> [xxhash] xxhash and xtrans moved from chef-base-plans org

.bldr.toml, xlib/README.md, xlib/attributes.yml, xlib/azure-pipelines.yml, xlib/controls/xlib_library_exists.rb, xlib/inspec.yml, xlib/plan.sh
=> [xlib] moved from chef-base-plans org

unzip/README.md, unzip/attributes.yml, unzip/azure-pipelines.yml, unzip/controls/unzip_test.rb, unzip/inspec.yml, unzip/plan.sh
=> [unzip] moved from chef-base-plan org

util-linux/README.md, util-linux/attributes.yml, util-linux/azure-pipelines.yml, util-linux/controls/util_linux_test.rb, util-linux/inspec.yml, util-linux/plan.sh, util-linux/tests/test.bats, util-linux/tests/test.sh
=> [util-linux] moved from chef-base-plans org

.bldr.toml, util-macros/README.md, util-macros/attributes.yml, util-macros/azure-pipelines.yml, util-macros/controls/util-macros_library_exists.rb, util-macros/inspec.yml, util-macros/plan.sh
=> [util-macros] moved from chef-base-plans org

wget/README.md, wget/attributes.yml, wget/azure-pipelines.yml, wget/controls/wget_exists.rb, wget/controls/wget_works.rb, wget/inspec.yml, wget/plan.sh
=> [wget] moved from chef-base-plan org

.bldr.toml, which/README.md, which/attributes.yml, which/azure-pipelines.yml, which/controls/which_exists.rb, which/controls/which_works.rb, which/inspec.yml, which/plan.sh
=> [which] moved from chef-base-plans org

sqlite/README.md, sqlite/attributes.yml, sqlite/azure-pipelines.yml, sqlite/controls/sqlite_works.rb, sqlite/inspec.yml, sqlite/plan.sh, sqlite/tests/test.bats, sqlite/tests/test.sh, vim/README.md, vim/attributes.yml, vim/azure-pipelines.yml, vim/controls/vim_test.rb, vim/inspec.yml, vim/plan.sh, vim/tests/test.bats, vim/tests/test.sh
=> [vim] moved from chef-base-plan org

.bldr.toml, erlang25/README.md, erlang25/plan.sh
=> Adding new package erlang25 for chef server

go14/LICENSE, go14/README.md, go14/cacerts.patch, go14/controls/go14_exists.rb, go14/controls/go14_works.rb, go14/inspec.yml, go14/plan.sh, go17/LICENSE, go17/README.md, go17/cacerts.patch, go17/controls/go17_exists.rb, go17/controls/go17_works.rb, go17/inspec.yml, go17/plan.sh
=> moving go17 and go14 to core

netdata/plan.sh, netdata/tests/test.sh
=> update rdeps to fetch libs at runtime

.bldr.toml, go19/LICENSE, go19/README.md, go19/cacerts.patch, go19/controls/go19_exists.rb, go19/controls/go19_works.rb, go19/plan.sh, go19/tests/hello.go, go19/tests/test.bats, go19/tests/test.sh
Adding go package required by Automate team.
https://chefio.atlassian.net/browse/IN-885 
=> adding go1.19 pacakge

rust/plan.ps1, rust/plan.sh
Signed-off-by: Jason Heath <jason.heath@progress.com>
=> bumped core/rust from 1.62.1 to 1.67.0

rust/plan.ps1, rust/plan.sh
Signed-off-by: Jason Heath <jason.heath@progress.com>
=> revved core/rust to 1.67.1

rabbitmq/plan.sh, rabbitmq/tests/test.sh
as elixir is built with newer erlang. changing erlang version with rabbitmq
=> updating rabbitmq with newer erlang and elixir

go20/plan.ps1
Add windows plan for go 1.20.7
=> add windows plan for go 1.20.7

libzip/plan.sh, mariadb/plan.sh
update dated value of source url variables in libzip and mariadb packages
=> update plan files due to dated values

.bldr.toml, firejail/plan.sh
adding new package firejail to core-plans; https://chefio.atlassian.net/browse/CHEF-6778
=> adding firejail package

.bldr.toml, terraform1/README.md, terraform1/plan.sh, terraform1/tests/test.bats, terraform1/tests/test.sh
https://chefio.atlassian.net/browse/CHEF-7296
New package for terraform with version 1.5.7 added with name core/terraform1
=> [CHEF-7296] Terraform 1.5.7 package added for Automate

.bldr.toml, ruby32/README.md, ruby32/plan.sh, ruby32/tests/test.bats, ruby32/tests/test.sh
https://chefio.atlassian.net/browse/CHEF-5882
New ruby32 package added for Inspec.
=> New ruby32 package added for Inspec[CHEF-5882]

minio/plan.sh
upgraded minio to version RELEASE.2023-11-01T01-57-10Z
=> [minio] upgraded to RELEASE.2023-11-01T01-57-10Z

ruby/plan.sh
upgraded ruby to version 3.0.6
=> [ruby] upgraded to 3.0.6

ruby30/plan.sh
=> [ruby30] upgraded to 3.0.6

openssl/plan.sh
upgraded openssl to version 1.0.2zi
=> [openssl] upgraded to v1.0.2.zi

gcc-libs/plan.sh
Upgrade gcc-libs to the version of gcc
=> upgrade gcc-libs,CHEF-8303

glibc/plan.sh
=> upgrade glibc,CHEF-8235

gzip/plan.sh
=> upgrade gzip,CHEF-8236

tar/plan.sh
=> upgrade tar,CHEF-8237

zlib/plan.sh
=> upgrade zlib,CHEF-8239

libarchive/plan.sh
upgraded libarchive to version 3.7.2
=> [libarchive] upgraded to 3.7.2

sqlite/plan.sh
=> upgrade sqlite,CHEF-8240

python/plan.sh
=> [python] upgraded to 3.12.0

libssh2/plan.sh
=> upgrade libssh2,CHEF-8244

python/x86_64-linux-kernel2/plan.sh
=> upgrade python for linux2,CHEF-8479

glibc/plan.sh
=> [glibc] downgraded version to 2.35

expat/plan.sh
=> [expat] updated function, build, check and install

python/plan.ps1
https://chefio.atlassian.net/browse/CHEF-8759
=> python bumped for Windows to 3.12.0 [chef-8759]

openssl/plan.ps1
https://chefio.atlassian.net/browse/CHEF-8760
=> openssl bumped for Windows to 1.1.1w [chef-8760]

openssh/plan.sh
=> [openssh] disable zlib version check

aws-cli/plan.sh
=> [aws-cli] update version for compatibility with python pip

libarchive/plan.ps1
https://chefio.atlassian.net/browse/CHEF-8763
=> Bumping libarchive for windows to 3.7.2 [CHEF-8763]

zlib/plan.ps1
https://chefio.atlassian.net/browse/CHEF-8762
=> Bumped zlib for Windows to 1.3 [CHEF-8762]

rust-nightly/plan.sh
=> [rust-nightly] fix for bash interpreter error

node16/plan.sh
=> [node16] fix for incompatibility with python v3.12

pax-utils/plan.sh
=> [pax-utils] fix for invalid source and build function

helm/plan.sh
=> [helm] fix for invalid source url and ssl cert

etcd/plan.sh, filebeat/plan.sh, foulkon/plan.sh, govc/plan.sh, gox/plan.sh, hugo/plan.sh, nats-top/plan.sh, node_exporter/plan.sh, prometheus/plan.sh, prometheus1/plan.sh, restic/plan.sh
fix related to ssl cert while downloading to source or dependencies for build
=> various fix for ssl cert

tree/plan.sh
=> [tree] updated source valid and working url

node16/plan.sh
=> [node16] upgraded to v16.20.2 with core/python (v3.11) as dep

postfix/plan.sh
=> [postfix] fix for ssl cert path

traefik/plan.sh
=> [traefik] fix for ssl cert path

buildkite-agent/plan.sh
=> [buildkite-agent] fix for ssl cert path

certstrap/plan.sh
=> [certstrap] fix for ssl cert path not found

doxygen/plan.sh
=> [doxygen] updated source url

img/plan.sh
=> [img] fix for ssl cert path

buildkite-cli/plan.sh
=> [buildkite-cli] fix for ssl cert path

.bldr.toml, curl8/plan.sh
=> Add curl 8.5.0 package-chef 8493

metricbeat/plan.sh
=> [metricbeat] fix for ssl cert invalid

glib/plan.sh
=> [glib] fix for python related compilation error

atk/plan.sh
=> [atk] fix for compilation error

coredns/plan.sh, kafka2/plan.sh
=> [kafka2] fix for invalid source url

xmlsec1/plan.sh
=> [xmlsec1] fix for invalid source url as v1.2.33 is unavailable

rethinkdb/plan.sh
=> [rethinkdb] fix for ssl cert invalid path

grpcurl/plan.sh
=> [grpcurl] fix for ssl cert invalid path

pango/plan.sh
=> [pango] fix for missing dependency

grafana-promtail/plan.sh
=> [grafana-promtail] fix for ssl cert path

journalbeat/plan.sh
=> [journalbeat] fix for ssl cert path

dd-agent/plan.sh
=> [dd-agent] fix for ssl cert invalid path

boringssl/plan.sh
=> [boringssl] fix for invalid source url

envoy/plan.sh
=> [envoy] fix for ssl cert invalid path

bin/ci/psscriptanalyzer.ps1, node14/controls/node_works.rb, node14/plan.sh
https://chefio.atlassian.net/browse/CHEF-9005
=> node14 bumped from  14.18.1 to 14.21.3 [CHEF-9005]

.bldr.toml, go21/README.md, go21/cacerts.patch, go21/plan.ps1, go21/plan.sh, go21/tests/hello.go, go21/tests/test.bats, go21/tests/test.sh
https://chefio.atlassian.net/browse/CHEF-9548
=> Go 1.21.5 package added for Linux & Windows[CHEF-9548]

.bldr.toml, node18/README.md, node18/controls/node_exists.rb, node18/controls/node_works.rb, node18/inspec.yml, node18/plan.sh, node18/tests/test.pester.ps1, node18/tests/test.ps1
https://chefio.atlassian.net/browse/CHEF-10210
=> Node18 new package added with version 18.19.1[CHEF-10210]

postgresql13-client/plan.sh, postgresql13/plan.sh
https://chefio.atlassian.net/browse/CHEF-10448
postgresql13 and postgresql13-client packages bumped to 13.14 version.
=> postgresql13 and postgresql13-client bumped from 13.5 to 13.14 version [chef-10448]

go22/plan.sh
=> [go] upgraded to v1.22.5

postgresql13-client/plan.sh, postgresql13/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-17529
https://progresssoftware.atlassian.net/browse/CHEF-17800
https://progresssoftware.atlassian.net/browse/CHEF-17801
=> postgresql13 and postgresql13-client bumped from 13.14 to 13.18[CHEF-17529]

.bldr.toml, go23/README.md, go23/cacerts.patch, go23/plan.ps1, go23/plan.sh, go23/tests/hello.go, go23/tests/test.bats, go23/tests/test.sh
https://progresssoftware.atlassian.net/browse/CHEF-19148
=> go23 package added with version 1.23.6 for linux/windows [CHEF-19148]

.bldr.toml, dotnet-9-sdk/plan.ps1
Can you please post this to the Stable channel?
=> adding a plan for the .net9 sdk

ruby31/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-24356
=> ruby31 bumped to 3.1.7 [CHEF-24356]

libarchive/plan.sh, libcap/plan.sh
upgrade libarchive to v3.8.1
upgrade libcap to v2.73
=> upgrade of libarchive and libcap
