habitat-sh/core-plans

libpng/plan.sh
```
DO_CHECK=1 build libpng
```
```
============================================================================
Testsuite summary for libpng 1.6.37
============================================================================
============================================================================
```
=> [libpng] Update libpng to 1.6.37

tmux/plan.sh, tmux/tests/test.bats, tmux/tests/test.sh
* [Changelog](https://raw.githubusercontent.com/tmux/tmux/2.8/CHANGES)
```
./tmux/tests/test.sh
```
```
```
=> [tmux] Upgrade tmux to 2.8, add tests

ffmpeg3/plan.sh, ffmpeg4/plan.sh
This updates the pkg_name for ffmpeg3 and ffmpeg4 to reflect that they are different packages than ffmpeg.  
=> [ffmpeg3][ffmpeg4] Update pkg_name 

rebar3/plan.sh
* [Changelog](https://github.com/erlang/rebar3/releases/tag/3.10.0)
```
./rebar3/tests/test.sh
```
```
✓ Help command
```
=> [rebar3] Update rebar3 to 3.10.0

memcached/plan.sh, memcached/tests/test.sh
* [Changelog](https://github.com/memcached/memcached/wiki/ReleaseNotes1513)
```
DO_CHECK=1 build memcached
exit
```
```
./memcached/tests/test.sh
```
```
All tests successful.
Files=73, Tests=25874, 211 wallclock secs ( 4.14 usr  0.40 sys + 10.79 cusr  8.71 csys = 24.04 CPU)
Result: PASS
```
```
✓ Help command
```
=> [memcached] Update memcached to 1.5.13, add do_check

ripgrep/plan.sh, ripgrep/tests/test.bats, ripgrep/tests/test.sh
* [Changelog](https://github.com/BurntSushi/ripgrep/blob/master/CHANGELOG.md)
```
./ripgrep/tests/test.sh
```
```
✓ Help command
✓ Usage test no params
✓ Usage test with params
```
=> [ripgrep] Update ripgrep to 11.0.1, add tests

telegraf/plan.sh
* [Changelog](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md)
```
./telegraf/tests/test.sh
```
```
```
=> [telegraf] Update telegraf to 1.10.3

gnatsd/plan.sh
* [Changelog](https://github.com/nats-io/gnatsd/releases/tag/v1.4.1)
```
./gnatsd/tests/test.shj
```
```
✓ Help command
✓ Listening on port 8222 (HTTP)
✓ Listening on port 4242 (NATS)
```
=> [gnatsd] Update gnatsd to 1.4.1

minio/plan.sh, minio/tests/test.bats
* [Changelog](https://github.com/minio/minio/releases)
Changes are various. Primarily bug fixes, but includes import TLS/Certificate configuration options.
```
./minio/tests/test.sh
```
```
✓ Version matches, via help output
✓ Listening on port 9000
```
=> [minio] Update minio to 2019-04-09T01-22-30Z, fix tests for IPv6

hugo/plan.sh
* [Changelog](https://gohugo.io/news/0.55.2-relnotes/)
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.55.2

libassuan/plan.sh
This updates the libassuan plan to include required metadata, partially addressing #1306. It also corrects the license string to align with SPDX 3.5. 
=> [libassuan] Update metadata

libedit/plan.sh
This updates the libedit plan to include required metadata, partially addressing #1306. It also corrects the license string to align with SPDX 3.5. 
=> [libedit] Update metadata

gpgme/plan.sh
This updates the gpgme plan to include required metadata, partially addressing #1306. It also corrects the license string to align with SPDX 3.5. 
=> [gpgme] Update metadata

iptables/plan.sh
This updates the iptables plan to include required metadata, partially addressing #1306. It also corrects the license string to align with SPDX 3.5. 
=> [iptables] Update metadata

cpio/plan.sh
This updates the cpio plan to include required metadata, partially addressing #1306. It also corrects the license string to align with SPDX 3.5. 
=> [cipo] Add required metadata

artifactory-pro/plan.sh
Hello, 
This PR updates Artifactory Pro to v.6.9.1. To test this build, enter the Hab Studio ```hab studio enter``` and run the following command: ```./tests/test.sh```
```
```
=> [Artifactory Pro] Updating to 6.9.1

artifactory/plan.sh
Hello, 
This PR updates Artifactory to v.6.9.1. To test this build, enter the Hab Studio ```hab studio enter``` and run the following command: ```./tests/test.sh```
```
```
=> [Artifactory] Updating to 6.9.1

gnupg-static/plan.sh, gnupg/plan.sh
This updates the gnupg and gnupg-static plans to include required metadata, partially addressing #1306. It also corrects the license string to align with SPDX 3.5. 
=> [gnupg][gnupg-static] Update metadata

libgpg-error/plan.sh
This adds required metadata to the libgpg-error plan.  It also corrects the license from LGPL to GPL (https://github.com/gpg/libgpg-error/blob/libgpg-error-1.20/COPYING) and updates the string to match SPDX. 
=> [libgpg-error] Update metadata

hugo/plan.sh
* [Changelog](https://gohugo.io/news/0.55.3-relnotes/)
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.55.4

nginx/plan.sh
* [Changelog](http://nginx.org/en/CHANGES-1.16)
```
```
```
✓ Help command
```
=> [nginx] Update Nginx to 1.16.0

man-pages/plan.sh
This adds required metadata to the man-pages plan. Ref: #1306
=> [man-pages] Update plan metadata

lzo/plan.sh
This adds required metadata to the lzo plan. Ref: #1306
=> [lzo] Update plan metadata

memcached/plan.sh
* [Changelog](https://github.com/memcached/memcached/wiki/ReleaseNotes1514)
```
./memcached/tests/test.sh
```
```
✓ Help command
```
=> [memcached] Update memcached to 1.5.14

tomcat-native/README.md, tomcat-native/plan.sh, tomcat-native/tests/test.bats, tomcat-native/tests/test.sh
=> [tomcat-native] Add core/gcc-libs as runtime dep, add tests

docs/dev/README.md, docs/dev/policy_documents/java-semantic-versioning.md
#1296
https://github.com/habitat-sh/core-plans-rfcs/blob/master/_RFCs/0005-rfc-java-semantic-versioning.md
Co-authored-by: Romain Sertelon <romain@sertelon.fr>
=> Add policy for tracking Java versions

galera/patches/000-add-ld_run_path-to-scons-env.patch, galera/plan.sh
Closes #2213 
This adds the missing dependencies to the `pkg_deps`.
It also patches the build script so that it includes LD_RUN_PATH in environment variables it copies into its internal build environment.  Without the patch, the LD_RUN_PATH is unset during the build and the resulting library is unable to find its dependencies.
```
ldd /hab/pkgs/foo/galera/25.3.19/20190425171738/lib/libgalera_smm.so
linux-vdso.so.1 (0x00007fff04ddc000)
libpthread.so.0 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libpthread.so.0 (0x00007f9a11d47000)
librt.so.1 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/librt.so.1 (0x00007f9a11d3d000)
libssl.so.1.0.0 => /hab/pkgs/core/openssl/1.0.2r/20190305210149/lib/libssl.so.1.0.0 (0x00007f9a11cc9000)
libcrypto.so.1.0.0 => …
```
=> [galera] Update dependencies

freetype/plan.sh
The `freetype` package was missing the `freetype-config` script, which is needed by other packages like `grub` in order to compile with freetype2 support.
See #2329 and #2215 for examples of where it's failing.
This is similar to what LFS does when [installing Freetype](http://www.linuxfromscratch.org/blfs/view/8.3/general/freetype2.html)
Signed-off-by: Will Fisher <wfisher@chef.io>
=> Add missing freetype-config script to the package

caddy/plan.sh, caddy/tests/test.bats
* [Changelog](https://github.com/mholt/caddy/releases/tag/v1.0.0)
```
./caddy/tests/test.sh
```
```
- Version matches (skipped)
✓ Help command
7 tests, 0 failures, 1 skipped
```
* Skipped version check, as its currently outputting `v0.0.0-00010101000000-000000000000` when calling `caddy -version`
* Upstream has been notified here: https://github.com/mholt/caddy/issues/2584
=> [caddy] Update Caddy to 1.0.0, skip version check due to upstream bug

yarn/plan.sh
* [Changelog](https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md)
```
./yarn/tests/test.sh
```
```
✓ Help command
```
=> Update yarn to 1.16.0

hugo/plan.sh, hugo/tests/test.bats, hugo/tests/test.sh
* [Changelog](https://gohugo.io/news/0.55.5-relnotes/)
This PR also includes a new approach for testing to match new proposed requirements for testing:
* Build is done separate to test
* Test takes pkg_ident as argument
* Binaries are executed with `hab pkg exec`
```
hab studio build hugo
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.55.5, implement new testing style

aws-cli/README.md, aws-cli/plan.ps1
=> [aws-cli] Add plan.ps1 to aws-cli

handlebars-cmd/plan.sh, handlebars-cmd/tests/bats/test.bats, handlebars-cmd/tests/test.sh
Closes #1566
This updates the install process for handlebars to pass options to `npm install`, rather than use `npm config` which writes configuration to a global location.
It also adds a simple test to validate behavior.
=> [handlebars-cmd] Update install process

ant/plan.sh, ant/tests/test.bats, ant/tests/test.sh
* [Changelog](https://archive.apache.org/dist/ant/RELEASE-NOTES-1.10.6.html)
```
hab studio build ant
hab studio run "./ant/tests/test.sh ${pkg_ident}"
```
```
```
=> [ant] Update ant to 1.10.6, and update tests

.bldr.toml, sqlserver/hooks/install
It's redundant to run this in the install when it also needs to be run in `init`.
=> [sqlserver] do not apply firewall dsc in install hook

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
This is a pretty small change to keep us working on Chef 15. Also releases a new version of the scaffolding so folks who want to pin to 14 forever can use the 0.5.0 scaffolding forever.
Resolves #2563
=> [scaffolding-chef] automatically accept license for chef15

docs/dev/policy_documents/standards-for-tests.md
Changing the order of the --binlink example in the document to satisfy new requirements in habitat.  See comment from @predominant [here](https://github.com/habitat-sh/core-plans/pull/2584#discussion_r285796038) and [clingo issue](https://github.com/habitat-sh/core-plans/issues/2210)
=> [test document] Update the order of --binlink according to new habitat format

hugo/plan.sh, hugo/tests/test.sh
* [Changelog](https://gohugo.io/news/0.55.6-relnotes/)
```
hab studio build hugo
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.55.6

sassc/plan.sh, sassc/tests/test.bats, sassc/tests/test.sh
Adds version information to the build, and tests.
Fixes #2589 
```
hab studio build sassc
hab studio run "sassc/tests/test.sh ${pkg_ident}"
```
```
✓ Package and library Version matches
✓ Help command
```
=> [sassc] Fix version info in build, add tests

terraform/plan.sh, terraform/tests/test.bats, terraform/tests/test.sh
While the version is minor, the changes included are major, so I've tagged as major version up.
* [Changelog](https://www.hashicorp.com/blog/announcing-terraform-0-12)
```
hab studio build terraform
```
```
```
=> [terraform] Update to 0.12.0, update test approach

tmux/plan.sh, tmux/tests/test.bats, tmux/tests/test.sh
* [Changelog](https://github.com/tmux/tmux/blob/master/CHANGES)
```
hab studio build tmux
hab studio run "./tmux/tests/test.sh ${pkg_ident}"
```
```
```
=> [tmux] Update tmux to 2.9a, update tests

bind/README.md, bind/plan.sh, bind/tests/test.bats, bind/tests/test.sh
```
hab studio build bind
hab studio run "./bind/tests/test.sh ${pkg_ident}"
```
```
✓ Dig
✓ Host
✓ ARPAname
✓ DNSSec Keygen
```
This is still a binary package.
Testing includes some basic tests to ensure the python dependencies are working at a basic level.
In the future we should improve this to a service plan with minimal/basic configuration for `named`.
This supersedes #2101
=> [bind] Update to 9.14.2, add tests

kafka/plan.sh
The version of Kafka we ship has been moved to archive.apache.org, this PR corrects the download URL.  
I've also opened #2606 to investigate shipping a more recent version of Kafka.
=> [kafka] Update download location

go/plan.sh, go/tests/hello.go, go/tests/test.bats, go/tests/test.sh
Adds a simple hello world test to ensure go can run go things :)
```
hab studio build go
hab studio run ./go/tests/test.sh ${pkg_ident}
```
```
✓ Help command
✓ Simple compile
```
=> [go] Update golang to 1.12.5, add trivial test

docs/dev/policy_documents/standards-for-tests.md
As discussed in https://github.com/habitat-sh/core-plans/pull/2604
Testing that the package directory exists can be useful, to provide some context when a test run fails.
However it is not really a test of the core plan, it's a test that the setup is valid.
Having this test in a plan's test suite is acceptable (imo) but to keep the standard as neat as possible, let's remove it from the 7zip example.
=> [docs] remove package dir existence test

scaffolding-chef/lib/scaffolding.sh, scaffolding-chef/plan.sh
This ensures that if defaults are not set in a default/user.toml that the run hook is still able to operate. Variables set in the default.toml or user.toml will always override these defaults.
I tested by building a package with the scaffolding and running chef-client on a node. I was able to observe it run correctly and render out the run hook as intended.
=> [scaffolding-chef] ensure defaults for run hook are always set if undefined

apr-util/README.md, apr-util/tests/test.bats, apr-util/tests/test.sh
Signed-off-by: Davy McAleer <dmcaleer@chef.io>
Addition of simple bats tests and update of README
**Testing**
```
hab studio build apr-util
hab studio run "./apr-util/tests/test.sh ${pkg_ident}"
```
**Sample Output**
```
1..3
ok 1 package directory for package ident core/apr-util/1.6.1/20190603213302 exists
ok 2 apu-1-config exe runs
ok 3 apu-1-config exe output mentions expected version 1.6.1
```
=> [apr-util] Tests and README update

azure-cli/plan.sh
The latest version of the azure-cli is 2.0.66 this updates it to the latest version.
=> [azure-cli] Update azure-cli to version 2.0.66

rebar3/plan.sh, rebar3/tests/test.bats, rebar3/tests/test.sh
```
hab studio build rebar3
hab studio run "./rebar3/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [rebar3] Update rebar3 to 3.11.0

e2fsprogs/plan.sh, e2fsprogs/tests/test.bats, e2fsprogs/tests/test.sh
This PR supersedes #2256 and adds modern testing to avoid the issue discussed there.
* [Changelog](http://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.45.2)
```
hab studio build e2fsprogs
hab studio run "./e2fsprogs/tests/test.sh ${pkg_ident}"
```
```
✓ uuidgen works
```
=> [e2fsprogs] Update to 1.45.2 and add modern tests

filebeat/config/filebeat.yml, filebeat/plan.sh, filebeat/tests/test.bats, filebeat/tests/test.sh
Changelogs are various. Major ones are posted on the [7.0 release notes](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-7.0.0.html). All are listed [here](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes.html).
```
hab studio build filebeat
hab studio run "./filebeat/tests/test.sh ${pkg_ident}"
```
```
The rakops/filebeat/7.1.1/20190529044102 service was successfully loaded
Waiting 10 seconds for service to start...
✓ Help command
Unloading rakops/filebeat/7.1.1/20190529044102
```
This now does the following:
* Build and test in separate studios
* Test loads the service and waits 10 …
=> [filebeat] Update to 7.1.1 + testing + cleanup

metricbeat/default.toml, metricbeat/plan.sh, metricbeat/tests/test.bats, metricbeat/tests/test.sh
```
hab studio build metricbeat
hab studio run "./metricbeat/tests/test.sh ${pkg_ident}"
```
```
The rakops/metricbeat/7.1.1/20190529054138 service was successfully loaded
Waiting 10 seconds for service to start...
✓ Help command
Unloading rakops/metricbeat/7.1.1/20190529054138
```
=> [metricbeat] Update to 7.1.1, update testing

CODEOWNERS
Update a number of code ownership lines to help relieve blockers on plan review.
=> Adjust codeownership for self

artifactory-pro/README.md, artifactory-pro/plan.sh, artifactory-pro/tests/test.sh, artifactory/README.md, artifactory/plan.sh, artifactory/tests/test.sh
[Artifactory Pro Release Notes](https://bintray.com/jfrog/artifactory-pro/jfrog-artifactory-pro-zip)
[Artifactory OSS Release Notes](https://bintray.com/jfrog/artifactory/jfrog-artifactory-oss-zip)
Artifactory 6.10.3 allows you to use JDK11, and [fully supports OpenJDK](https://www.jfrog.com/confluence/display/RTF/System+Requirements
). Since this lands us in a much nicer, more easily buildable and licensable situation, this PR changes over to OpenJDK11.
I also tweaked some of the tests a bit to be more up to standards.
Build the package and run tests like so:
```bash
hab studio build artifactory
hab studio run "./artifactory/tests/test.sh ${pkg_ident}"
```
```bash
hab studio build artifactory-pro …
```
=> [artifactory] [artifactory-pro] update to artifactory 6.10.3

terraform/plan.sh
Hey all,
This is a simple version bump for Terraform to 0.12.2. 
To test this build, please run the following commands:
```
hab studio build terraform
```
```
```
=> [terraform] Updating Terraform to 0.12.2

apr/README.md, apr/tests/test.bats, apr/tests/test.sh
Signed-off-by: Davy McAleer dmcaleer@chef.io
Addition of simple bats tests and update of README
**Testing**
```
hab studio build apr
hab studio run ./apr/tests/test.sh ${pkg_ident}
```
**Sample Output**
```
1..3
ok 1 package directory for package ident bernagh/apr/1.6.5/20190529124535 exists
ok 2 apr-1-config exe runs
ok 3 apr-1-config exe output mentions expected version 1.6.5
```
=> [apr] Addition of tests and README to  plan

nginx/plan.sh
Reference: http://hg.nginx.org/nginx/rev/a6d116645c51
=> [nginx] Remove deprecated --with-ipv6 configure flag

.expeditor/templates/verify_linux_pipeline.yml, bin/ci/build-and-run-tests.sh
Linux only as Windows Buildkite is not yet set up.
This needs tested - either need to get https://github.com/habitat-sh/core-plans/pull/2559/files merged, or this change can be tested against `core/ant` except at the moment ftp.software.ibm.com seems to be down.
=> Run tests/test.sh in CI if it exists.

corretto11/plan.ps1, corretto8/plan.ps1
Signed-off-by: sam1el <jbrimager@chef.io>
Windows core plan for Corretto 8 OpenJDK. I have tested against multiple other windows plans requiring jdk8 and have been successful.
=> [corretto8] Amazon Corretto8 JDK for windows.

corretto/plan.sh, corretto8/plan.sh
Before fix:
```
linux-vdso.so.1 (0x00007ffca45f0000)
libfreetype.so.6 => not found
libawt.so => /hab/pkgs/core/corretto8/8.202.08.2/20190611004012/jre/lib/amd64/libawt.so (0x00007f22dc8c2000)
libm.so.6 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libm.so.6 (0x00007f22dc72f000)
libjava.so => /hab/pkgs/core/corretto8/8.202.08.2/20190611004012/jre/lib/amd64/libjava.so (0x00007f22dc501000)
libjvm.so => not found
libc.so.6 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libc.so.6 (0x00007f22dc349000)
/hab/pkgs/core/glibc/2.27/20190115002733/lib64/ld-linux-x86-64.so.2 (0x00007f22dce03000)
libjvm.so => not found
libdl.so.2 => /hab/pkgs/core/glibc/2.27/20190115002733/lib/libdl.so.2 (0x00007f22dc342000)
libjvm.so => not found
libverify.so …
```
=> [corretto8] Fix linker issues with Corretto8

ghc/plan.ps1, ghc/plan.sh, ghc86/plan.sh
Updated GHC to 8.6.5
Tested by building cabal-install and shellcheck on Linux and Windows.
=> [ghc] Updated GHC to 8.6.5

scaffolding-ruby/CHANGELOG.md, scaffolding-ruby/lib/scaffolding.sh, scaffolding-ruby/plan.sh
Ruby applications that connect to PostgreSQL databases only need to
depend on the postgres client tools. When the scaffolding assembles the
list of `pkg_deps` for a ruby project, it was adding `core/postgresql`
to the list if it detected the `pg` gem, which adds the entire server to
the installation footprint on disk (or your docker images).
This change replaces the dependency with `core/postgresql-client`, which
is smaller in size by > 100MB and ensures we only depend on exactly what
we need.
Closes #2595
Signed-off-by: Keith Walters <keith.walters@cattywamp.us>
=> [scaffolding-ruby] Replace dependency on PG server with PG client

zstd/plan.sh, zstd/tests/test.bats, zstd/tests/test.sh
[CHANGELOG](https://github.com/facebook/zstd/blob/dev/CHANGELOG)
zstdless and zstdgrep need less and grep, respectively.
=> [zstd] Bump to 1.4.0, add dependencies, add tests

.bldr.toml, haproxy/plan.sh, haproxy/tests/test.bats, haproxy16/plan.sh, haproxy17/plan.sh, haproxy18/plan.sh, haproxy19/plan.sh, haproxy20/README.md, haproxy20/config/haproxy.conf, haproxy20/default.toml, haproxy20/plan.sh, haproxy20/tests/test.sh
Major version upgrade for Haproxy. Major difference in compilation is the target:
```
Target 'linux2628' was removed from HAProxy 2.0 due to being irrelevant and
often wrong. Please use 'linux-glibc' instead or define your custom target
by checking available options using 'make help TARGET=<your-target>'.
```
* Added haproxy20
* Update haproxy to 2.0.0
* Made haproxy1x source haproxy19 (for `TARGET=linux2628`)
* Updates to tests for any service/version number
```
hab pkg build haproxy
haproxy_pkg_ident="${pkg_ident}"
hab pkg build haproxy20
haproxy20_pkg_ident="${pkg_ident}"
hab pkg build haproxy19
haproxy19_pkg_ident="${pkg_ident}"
hab pkg build …
```
=> [haproxy] Add Haproxy 2.0.0, Fix tests

man-db/plan.sh, man-db/tests/test.bats, man-db/tests/test.sh
This fixes an error due to a missing runtime dependency.
```
[23][default:/hab/pkgs/core/man-db/2.7.5/20190115180532/bin:0]# ./man --help
man: error while loading shared libraries: libpipeline.so.1: cannot open shared object file: No such file or directory
[24][default:/hab/pkgs/core/man-db/2.7.5/20190115180532/bin:127]# ldd ./man
linux-vdso.so.1 (0x00007ffcd6259000)
libmandb-2.7.5.so => /hab/pkgs/core/man-db/2.7.5/20190115180532/lib/man-db/libmandb-2.7.5.so (0x00007fda041dc000)
libman-2.7.5.so => /hab/pkgs/core/man-db/2.7.5/20190115180532/lib/man-db/libman-2.7.5.so (0x00007fda041b2000)
libgdbm.so.6 => /hab/pkgs/core/gdbm/1.17/20190115012826/lib/libgdbm.so.6 (0x00007fda0419d000)
libpipeline.so.1 => not found
libiconv.so.2 => /hab/pkgs/core/libiconv/1.14/20190115155025/lib/libiconv.so.2 …
```
=> [man-db] Fix missing runtime dependency

xz/plan.ps1, xz/plan.sh
5.2.4 (2018-04-29)
* liblzma:
- Allow 0 as memory usage limit instead of returning
LZMA_PROG_ERROR. Now 0 is treated as if 1 byte was specified,
which effectively is the same as 0.
- Use "noexcept" keyword instead of "throw()" in the public
headers when a C++11 (or newer standard) compiler is used.
- Added a portability fix for recent Intel C Compilers.
- Microsoft Visual Studio build files have been moved under
windows/vs2013 and windows/vs2017.
* xz:
- Fix "xz --list --robot missing_or_bad_file.xz" which would
try to print an unitialized string and thus produce garbage
output. Since the exit status is non-zero, most uses of such
a command won't try to interpret the garbage output.
- "xz --list foo.xz" could print "Internal error (bug)" in a
corner case where a specific memory usage …
=> [xz] Update XZ from 5.2.3 -> 5.2.4

dejagnu/plan.sh
```
dejagnu: Running post-compile tests
Done. Now run 'make install'.
make  unit
make[1]: Entering directory '/hab/cache/src/dejagnu-1.6.2'
depbase=`echo testsuite/libdejagnu/unit.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DPACKAGE_NAME=\"GNU\ DejaGnu\" -DPACKAGE_TARNAME=\"dejagnu\" -DPACKAGE_VERSION=\"1.6.2\" -DPACKAGE_STRING=\"GNU\ DejaGnu\ 1.6.2\" -DPACKAGE_BUGREPORT=\"bug-dejagnu@gnu.org\" -DPACKAGE_URL=\"http://www.gnu.org/software/dejagnu/\" -DPACKAGE=\"dejagnu\" -DVERSION=\"1.6.2\" -I.   -I/hab/pkgs/core/expect/5.45.4/20180608101522/include -I/hab/pkgs/core/make/4.2.1/20180608100733/include -I/hab/pkgs/core/gcc/7.3.0/20180608051919/include -I. -g -I/hab/pkgs/core/expect/5.45.4/20180608101522/include …
```
=> [dejagnu] Updated dejagnu to 1.6.2

wget/plan.sh
> Closes #1217
Note: no need to add `./configure` options, libidn2 is discovered automatically.
=> [wget] Adds support for IRIs

cyrus-sasl/tests/test.bats, cyrus-sasl/tests/test.sh
You can test with
```
hab pkg build cyrus-sasl
hab studio run "./cyrus-sasl/tests/test.sh ${pkg_ident}"
```
Yes, for some reason cyrus-sasl outputs their helptext to stderr. It's not my fault I swear! 🗡
=> [cyrus-sasl] add tests for cyrus-sasl

maven/plan.sh, maven/tests/test.bats, maven/tests/test.sh
Until Maven 3.3, Maven core build could be boostrapped with an Ant build. This bootstrap has been removed in Maven 3.5: you need a pre-built Maven to build Maven from source.
Habitat makes this quite easy: We can just dep on a previous core/maven package.
[Release Notes](https://maven.apache.org/docs/3.6.1/release-notes.html)
[Release History](https://maven.apache.org/docs/history.html)
=> [maven] update maven to 3.6.1

artifactory-pro/plan.sh, artifactory/plan.sh
[Release Notes](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory6.10.4)
```
hab studio run "./artifactory/tests/test.sh ${pkg_ident}"
hab pkg build artifactory-pro
hab studio run "./artifactory-pro/tests/test.sh ${pkg_ident}"
```
=> [artifactory] [artifactory-pro] update to 6.10.4

.bldr.toml
This cleans up an unnecessary path from the .bldr.toml, just to make sure this common mistake doesn't get replicated.
=> clean up unnecessary path

terraform/plan.sh
=> [terraform] Update terraform to 0.12.3

7zip/README.md, 7zip/tests/test.bats, 7zip/tests/test.pester.ps1, 7zip/tests/test.ps1, 7zip/tests/test.sh
This PR:
* updates the test.ps1 to use core/pester instead of downloading the module
* fixes Invoke-Pester to use -PassThru instead of -EnableExit, which aborts the powershell whether tests pass or fail
* updates the [testing standard document](https://github.com/habitat-sh/core-plans/blob/master/docs/dev/policy_documents/standards-for-tests.md) with the new pester testing instructions
=> [7zip] Update windows tests to use new core/pester core plan

dotnet-471-dev-pack/README.md, dotnet-471-dev-pack/tests/test.pester.ps1, dotnet-471-dev-pack/tests/test.ps1
**NOTE:** Opening this PR to replace [this one](https://github.com/habitat-sh/core-plans/pull/2443) so that the PR branch is up-to-date with all master commits before merging into the main core-plans.
Note that this PR:
* adds Pester tests that verify the presence of both the 4.7 and also the 4.7.1 NETFX lib, bin and include directories in a local build of the dotnet-471-dev-pack.  Since [pester](https://github.com/Pester/Pester/wiki) tests can be run from within an isolated windows habitat studio environment and [inspec](https://www.inspec.io) tests cannot, pester was chosen for testing this windows plan.
* adds a README to meet [core-plan requirements](https://github.com/habitat-sh/core-plans/blob/master/CONTRIBUTING.md)
=> [dotnet-471-dev-pack] VERSION 2: Add Pester tests to habitat installation of dotnet-471-dev-pack

artifactory-pro/tests/helpers.bash, artifactory-pro/tests/test.bats, artifactory-pro/tests/test.sh, artifactory/tests/helpers.bash, artifactory/tests/test.bats, artifactory/tests/test.sh
I wanted to add a test that actually hit the API. It looks like this endpoint is the only good one to really hit that is unauthenticated. Unfortunately there isn't any version information that we can compare to -- all of that is behind auth.
I will mention that while writing this, I ran into some weird errors with jq because the Artifactory service wasn't finished yet -- so I added a sleep in, which takes care of the problem.
In other words, this test *does* test something very different than just seeing if the port is available for service. I still think the port test is valuable though, because it gives a fine grain view into what exactly might be failing with the starting service.
=> [artifactory] [artifactory-pro] Add API funtionality test

artifactory/plan.sh
[Release Notes](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory6.11)
```
source ./results/last_build.env
hab studio run "./artifactory/tests/test.sh ${pkg_ident}"
```
=> [artifactory] update artifactory to 6.11.0

artifactory-pro/plan.sh
[Release Notes](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory6.11)
```
hab pkg build artifactory-pro
source ./results/last_build.env
hab studio run "./artifactory-pro/tests/test.sh ${pkg_ident}"
```
=> [artifactory-pro] update to artifactory-pro-6.11.0

metricbeat/plan.sh
```
hab pkg build metricbeat
hab studio run "./metricbeat/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [metricbeat] Update metricbeat to 7.2.0

filebeat/plan.sh
```
hab pkg build filebeat
hab studio run "./filebeat/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [filebeat] Update filebeat to 7.2.0

journalbeat/plan.sh
```
hab pkg build journalbeat
hab studio run "./journalbeat/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [journalbeat] Update journalbeat to 7.2.0

ansible/plan.sh
```
hab studio run "./ansible/tests/test.sh ${pkg_ident}"
```
```
✓ Help Command
```
=> [ansible] Update ansible to 2.8.1

apr/plan.sh
```
hab studio run "./apr/tests/test.sh ${pkg_ident}"
```
```
✓ package directory for package ident rakops/apr/1.7.0/20190701013010 exists
✓ apr-1-config exe runs
✓ apr-1-config exe output mentions expected version 1.7.0
```
=> [apr] Update apr to 1.7.0

consul/plan.sh, consul/tests/helpers.bash, consul/tests/test.bats, consul/tests/test.sh
```
hab studio run "./consul/tests/test.sh ${pkg_ident}"
```
```
```
=> [consul] Update consul to 1.5.2, update tests

artifactory-pro/plan.sh
[Release Notes](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory6.11.1)
🔢 
```
hab studio run ./artifactory/tests/test.sh ${pkg_ident}
```
=> [artifactory-pro] minor version up 6.11.1

artifactory/plan.sh
[Release Notes](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory6.11.1)
🔢 
```
hab studio run ./artifactory/tests/test.sh ${pkg_ident}
```
=> [artifactory] minor version up to 6.11.1

envconsul/plan.sh, envconsul/tests/test.bats, envconsul/tests/test.sh
```
hab pkg build envconsul
hab studio run "/envconsul/tests/test.sh
```
```
✓ Help command
```
=> [envconsul] Update envconsul to 0.8.0, add trivial tests

openresty/plan.sh, openresty/tests/test.bats, openresty/tests/test.sh
```
hab pkg build openresty
hab studio run "./openresty/tests/test.sh ${pkg_ident}"
```
```
```
=> [openresty] Update openresty to 1.15.8.1, add tests

elixir/plan.sh, elixir/tests/test.bats, elixir/tests/test.sh
* [Changelog](https://github.com/elixir-lang/elixir/blob/v1.9/CHANGELOG.md)
```
hab pkg build elixir
hab studio run "./elixir/tests/test.sh ${pkg_ident}"
```
```
```
=> [elixir] Update elixir to 1.9.0, update tests

nginx/plan.ps1, nginx/plan.sh, nginx/tests/test.bats, nginx/tests/test.sh
```
hab studio run "./nginx/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [nginx] Update nginx to 1.17.1, update linux based tests

bin/ci/verify-pr-build.sh
When running elasticsearch builds through the new test workflow in Buildkite, we get out of resource errors:
```
opendistro-for-elasticsearch.default(O): [2019-06-17T22:25:25,746][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
opendistro-for-elasticsearch.default(O): org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/hab/svc/opendistro-for-elasticsearch/data/example-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
```
We should temporarily remove these until Buildkite can handle spinning up Elasticsearch …
=> Buildkite: add elasticsearch to buildkite resource blacklist

glibc/plan.sh
We should not strip the shared objects so that users can debug their
apps with gdb and valgrind
These code is directly from @fnichol's comment: https://github.com/habitat-sh/core-plans/issues/850#issuecomment-376978968
--
Note: I could not build this plan.  I'm guessing I need to be in `stage1` studio?
=> [glibc] Don't strip some .so to support debugging

jq-static/plan.ps1, jq-static/plan.sh, jq-static/tests/test.bats, jq-static/tests/test.pester.ps1, jq-static/tests/test.ps1, jq-static/tests/test.sh
[Release Notes](https://github.com/stedolan/jq/releases)
Linux
```
hab pkg build jq-static
hab studio run "./jq-static/tests/test.sh ${pkg_ident}"
```
Windows
```
hab pkg build jq-static
. results/last_build.ps1
hab studio run "./jq-static/tests/test.ps1 ${pkg_ident}"
```
=> [jq-static] Update to jq 1.6 and add tests

packer/plan.ps1, packer/plan.sh, packer/tests/test.bats, packer/tests/test.sh
```
hab pkg build packer
hab studio run "./packer/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [packer] Update packer to 1.4.2, update tests

caddy/plan.sh, caddy/tests/test.bats, caddy/tests/test.sh
* Updates the source repo since the upstream moved.
* Restore the version test, upstream has fixed the previous issue.
```
hab pkg build caddy
hab studio run "./caddy/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [caddy] Update Caddy to 1.0.1, update tests

opa/plan.sh
I'd recommend merging https://github.com/habitat-sh/core-plans/pull/2677 for test improvements before this PR.
[Release Notes](https://github.com/open-policy-agent/opa/releases/tag/v0.12.1)
```
hab pkg build opa
hab studio run "./opa/tests/test.sh ${pkg_ident}"
```
=> [opa] update to 0.12.1

ansible/plan.sh, ansible/tests/test.bats, ansible/tests/test.sh
* [Changelog](https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst#v2-8-2)
```
hab studio run "./ansible/tests/test.sh ${pkg_ident}"
```
```
✓ Help Command
```
=> [ansible] Update ansible to 2.8.2

httpd/plan.sh, httpd/tests/test.bats, httpd/tests/test.sh
```
hab pkg build httpd
hab studio run "./httpd/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
✓ Multiple processes
```
=> [httpd] Update httpd to 2.4.39, update test style

gdb/plan.sh, gdb/tests/test.bats, gdb/tests/test.sh
```
hab pkg build gdb
hab studio run "./gdb/tests/test.sh ${pkg_ident}"
```
```
```
=> [gdb] Update gdb to 8.3, update test style

php/plan.sh
* [Changelog](https://www.php.net/ChangeLog-7.php#7.3.7)
```
hab pkg build php
hab studio run "./php/tests/test.sh ${pkg_ident}"
```
```
✓ Libzip is supported.
```
=> [php] Update PHP to 7.3.7

netdata/README.md, netdata/plan.sh
Just update the upstream / origin repo for Netdata, which has moved. No promotion necessary after merge.
=> [netdata] Update Netdata repo

rabbitmq/plan.sh, rabbitmq/tests/test.bats, rabbitmq/tests/test.sh
```
hab pkg build rabbitmq
hab studio run "./rabbitmq/tests/test.sh ${pkg_ident}"
```
```
✓ Listening on port 4369, 5672, 25672
```
=> [rabbitmq] Update RabbitMQ to 3.7.16, update test style

corretto/plan.sh, corretto8/plan.sh
This adds jre/bin to the list of directories that contains binaries needing attention from patchelf.  
It also makes a small change to use `--set-interpreter` rather than `--interpreter`. The `--help` for patchelf doesn't list `--interpreter` so the full flag should be preferred (even though it works :smile: )
=> [corretto][corretto8] Add jre/bin to entries to be patched

netdata/plan.sh
* [Restart segfault fix + more](https://github.com/netdata/netdata/blob/master/CHANGELOG.md#v1160-2019-07-08)
=> [netdata] Update netdata to 1.16.0

grub/plan.sh, grub/tests/test.bats, grub/tests/test.sh
Before updating the $pkg_build_deps, the grub build is unsuccessful with something like:
```bash
...
...
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zlib', required by 'freetype2', not found
checking ft2build.h usability... no
checking ft2build.h presence... no
checking for ft2build.h... no
configure: error: grub-mkfont was explicitly requested but can't be compiled (need freetype2 headers)
grub: Build time: 2m53s
grub: Exiting on error
[3][default:/src/grub:1]#
```
However, the build is successful after
* adding the core/zlib and core/libpng to $pkg_build_deps
* re-running the build succeeds:
```diff
diff --git a/grub/plan.sh b/grub/plan.sh
index 8be2a5ec..f5d25116 …
```
=> [grub] Fix failing grub build adding core dependencies

.bldr.toml, dsc-core/DSCCore.psm1, dsc-core/README.md, dsc-core/tests/test.pester.ps1, dsc-core/tests/test.ps1, dsc-core/tests/test_config.ps1
Someone mentioned that they have powershell conditionals in their dsc configuration that could possibly remove a configuration:
```
Configuration dummy_directory
{
$something = $false
if ($something -eq $true){
Node 'localhost'
{
File dummy_directory
{
Type = 'Directory'
DestinationPath = 'C:\temp\a_dummy_test_path'
Ensure = 'Absent'
}
}
}
}
```
This fails with a horrific error:
```
2019-06-26 11:56:50,066 - myapp.default(O): Compiling DSC mof for dummy_directory ...
2019-06-26 11:56:50,770 - myapp.default(E): Invoke-Command : Cannot bind argument to parameter 'Path' because it is null.
2019-06-26 11:56:50,770 - myapp.default(E): At C:\hab\pkgs\core\dsc-core\0.2.1\20180919112142\Modules\DscCore\DSCCore.psm1:104 char:9
2019-06-26 11:56:50,770 - myapp.default(E): +         Invoke-Command …
```
=> [dsc-core] do not fail on config without resources and add tests

zlib/tests/test.bats, zlib/tests/test.sh
There is no new version of zlib available. So for the purposes of the base plan refresh; I have just added tests for the existing plan.
=> [zlib] Add tests to zlib (base plan refresh)

7zip/README.md, 7zip/tests/test.bats
Raising this PR against 7zip:
* to remove the double-brackets from tests.bats according to issue #2716
* to update the README with a link to testing standards document
=> [7zip] Replace '[[' in test.bats

.expeditor/templates/verify_shared_pipeline.yml
This fixes the copy/paste for the name of the pre-commit check to give it a descriptive and correct name. 
=> [CI] Fix name of pre-commit test

bin/ci/build-and-run-tests.sh
Unfortunately in PR #2684 we missed the fact that both the verify step and the build-test steps of CI need to be ignored.... therefore the opendistro-for-elasticsearch build is still failing.
This will need to be fixed as well in order for that PR to land successfully.
=> [opendistro-for-elasticsearch] blacklist the build-test process

etcd/plan.sh
Update etcd signing key.  Skipping adding tests as this is blocking an update to fix a curl CVE. 
=> Update etcd signing key

node/tests/test.bats, node/tests/test.pester.ps1, node/tests/test.ps1, node/tests/test.sh, node10/plan.ps1, node10/plan.sh, node10/tests/test.bats, node10/tests/test.pester.ps1, node10/tests/test.ps1, node10/tests/test.sh, node11/tests/test.bats, node11/tests/test.pester.ps1, node11/tests/test.ps1, node11/tests/test.sh, node12/tests/test.bats, node12/tests/test.pester.ps1, node12/tests/test.ps1, node12/tests/test.sh, node6/tests/test.bats, node6/tests/test.pester.ps1, node6/tests/test.ps1, node6/tests/test.sh, node8/tests/test.bats, node8/tests/test.pester.ps1, node8/tests/test.ps1, node8/tests/test.sh, node9/tests/test.bats, node9/tests/test.pester.ps1, node9/tests/test.ps1, node9/tests/test.sh
This PR updates node10 to 10.16.0 and adds tests for all node plans.
It may be worth discussing a standard for plans with many major versions (like node, postgresql) and how we should be calling these tests -- is it better to have a test script execute the same code for the parent `node` plan? or should each version plan copy-pasta its own boilerplate test code? I can see arguments either way.
```
hab pkg build core/node10
hab pkg run "./node10/tests/test.sh ${pkg_ident}"
```
```
hab pkg build core/node10
. ./results/last_build.ps1
hab pkg run "./node10/tests/test.ps1 $pkg_ident"
```
=> [node10] Update node10 to 10.16.0 and add tests

dsc-core/DSCCore.psd1, dsc-core/DSCCore.psm1, dsc-core/README.md, dsc-core/plan.ps1, dsc-core/tests/test.pester.ps1, dsc-core/tests/test_config.ps1
This rebases and squashes #2788 
- Added support for passing DSC [ConfigurationData](https://docs.microsoft.com/en-us/powershell/dsc/configurations/configdata)
=> [dsc-core] Added support for passing config data

ffmpeg/plan.sh
nettle removed/renamed headers in a recent release that causes ffmpeg 4.1.3 to not build.  This update corrects that.
=> [ffmpeg] Update to 4.1.4

gnutls/plan.sh
nettle removed/renamed headers in a recent release that causes gnutls to not build. This update corrects that.
=> [gnutls] Update version 

php/plan.sh
Bison2 hasn't been released in 7 years while the 3 series is still receiving updates.  This PR updates the build dependency for PHP to use the more modern version of Bison so that we may deprecate the bison2 package. 
=> [php] Update bison dependency

docs/dev/policy_documents/standards-for-tests.md
This updates our testing standard to use the more readable version of grepping for the ${pkg_ident}, and minimal test output.
In addition, it fixes some small syntax to be more `shellcheck` correct.
=> Update testing standard

terraform/plan.sh
Hello all,
This PR brings Terraform up to 0.12.4. To test the build, please run the following:
```
```
```
```
Please let me know if there are any questions.
=> [terraform] Updating to 0.12.4

tor/config/torrc, tor/plan.sh
The previous version of tor in plan.sh is no longer hosted. This updates to the latest release.
=> [tor] Update to latest version

flatbuffers/plan.sh, flatbuffers/tests/test.bats, flatbuffers/tests/test.sh
This update allows us to build against upcoming glibc2.29 and gcc9.1 packages. 
=> [flatbuffers] Update to 1.11

dpkg/plan.sh, dpkg/tests/test.bats, dpkg/tests/test.sh
This updates the version of dpkg, 1.19.4 is no longer hosted.  
The do_build implementation was the default so it was removed. do_check was added, along with a dependency of `gcc-libs` and a build dependency of `diffutils` for `make check` to pass.  
It also updates the testing to match the latest standards. 
=> [dpkg] Update version

papi/plan.sh
This updates to the latest version of papi, which is needed to build under the upcoming glibc/gcc updates. 
=> [papi] Update to latest version

mesa/plan.sh, mesa/tests/test.sh
Mesa download URL has changed. There are new major versions available, but it requires additional X packages to be built. 
=> [mesa] Update download url

ant/plan.sh, jffi/plan.sh, maven/plan.sh
This is in preparation for deprecating the JRE and JDK packages.  I had originally intended to use openjdk as it's been around longer so more Java software declares support for it.  However, jffi won't build with openjdk11 (https://github.com/jnr/jffi/issues/55). Maven for windows is also using corretto and consistency is important. 
jffi depends on maven and ant so these three need to move as a single PR.
This also depends on #2803 being merged and promoted. 
=> [ant][maven][jffi] Change JDK 

libcerf/plan.sh, libcerf/tests/test.sh
The upstream source for this package has moved and no longer hosts versions prior to 1.13. 
=> [libcerf] Update to 1.13

vim/plan.sh, vim/tests/test.bats, vim/tests/test.sh
This updates to the 8.1.1694 to address https://nvd.nist.gov/vuln/detail/CVE-2019-12735 
=> [vim] Update to latest release

patchelf/plan.sh, patchelf/tests/test.bats, patchelf/tests/test.sh
This updates patchelf the the latest version: 
Changelog: https://github.com/NixOS/patchelf/commits/master
=> [patchelf] Update to 0.10

dotnet-asp-core/plan.ps1, dotnet-asp-core/plan.sh
Hey all,
This PR updates both the Windows and Linux plans for dotnet-asp-core. To test the Linux build, please run the following commands:
```
hab pkg build dotnet-asp-core
hab studio run "./dotnet-asp-core/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
✓ ASP check
```
Please let me know if there are any questions.
=> [dotnet-asp-core] Updated Linux/Windows plans to 2.2.6

.bldr.toml, CODEOWNERS, base-plans.txt, python-minimal/README.md, python-minimal/plan.sh, python-minimal/tests/test.sh
With glibc2.29, python was introduced as a build dependency. If we were to include `core/python` as a build dependency for `core/glibc` it would increase the number of items that are considered "base plans", i.e. plans that are required in order to bootstrap the Habitat ecosystem. This would make packages like Python and sqlite more difficult to update. Having `core/python` as a build dependency for `core/glibc` also would mean that the footprint of packages that would cause the world to rebuild would be greatly increased, resulting in slower updates for those packages, or more churn across our entire ecosystem.
As a result, this package (`python-minimal`) was introduced so that we have a version of Python that has minimal dependencies, should need infrequent updates, and keeps the number …
=> [python-minimal] New plan 

sed/plan.sh, sed/tests/test.bats, sed/tests/test.sh
Replaces PR https://github.com/habitat-sh/core-plans/pull/2401 that was pointing at master.
=> [sed] Add tests

cmake/plan.ps1, cmake/tests/test.bats, cmake/tests/test.pester.ps1, cmake/tests/test.ps1, cmake/tests/test.sh
The core/cmake fails to build within the windows docker studio on Azure Windows 2016 ``hab studio enter -D``.  The error is "**Move-Item...is denied**":
```powershell
d-----         7/2/2019   5:20 AM                cmake-3.13.2
Move-Item : Access to the path 'C:\src\cmake\cmake-3.13.2-win64-x64\SourceDir\cmake' is denied.
At C:\src\cmake\plan.ps1:17 char:3
+   Move-Item "cmake-$pkg_version-win64-x64/SourceDir/cmake" "$HAB_CACH ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : WriteError: (C:\src\cmake\cm...SourceDir\cmake:DirectoryInfo) [Move-Item], IOException
+ FullyQualifiedErrorId : MoveDirectoryItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
[HAB-STUDIO] Habitat:\src>
```
If, however, the build is done from the windows …
=> [cmake] Fix so that builds in windows studio

elixir/plan.sh
```
hab pkg build elixir
hab studio run "./elixir/tests/test.sh ${pkg_ident}"
```
```
```
=> [elixir] Update elixir to 1.9.1

terraform/plan.sh
=> [terraform] Update terraform to 0.12.5

strace/plan.sh
```
hab pkg build strace
hab studio run "./strace/tests/test.sh ${pkg_ident}"
```
```
✓ Can strace
```
=> [strace] Update strace to 5.2

bin/ci/test_helpers.sh, gnatsd/plan.sh, gnatsd/tests/test.bats, gnatsd/tests/test.sh
`nats-io/gnatsd` has been renamed to `nats-io/nats-server`. The upstream provider has also repackaged their tarballs with the updated name.  This PR is in place to correct that.
This package should be renamed to `core/nats-server`, however they have also released a new major version that doesn't appear to be backwards compatible and the 1.x series don't appear to be released anymore.  
I think the right thing to do in this case is to take this PR as-is (barring any errors in CI), so that we have a gnatsd artifact post-refresh to allow people to make that transition.   
Once the refresh is complete, a new nats-server package that tracks the 2.x series should be released and this package can be deprecated.  
This should give users an upgrade path through the refresh, and allow them to make …
=> [gnatsd] Update build process

artifactory-pro/plan.sh
[Release notes](https://bintray.com/jfrog/artifactory/jfrog-artifactory-oss-zip/6.11.3)
```
hab pkg build artifactory-pro
hab studio run "./artifactory-pro/tests/test.sh ${pkg_ident}"
```
=> [artifactory-pro] minor version up 6.11.3

scaffolding-gradle/plan.sh
Typo/ oversight fix. No promotion necessary after merge.
=> [scaffolding-gradle] Update gradle scaffolding URI

dotnet-core-sdk/plan.ps1, dotnet-core-sdk/plan.sh, dotnet-core-sdk/tests/test.bats, dotnet-core-sdk/tests/test.sh
Hey all,
To test this update, please run the following:
```
hab pkg build dotnet-core-sdk
hab studio run "./dotnet-core-sdk/tests/test.sh ${pkg_ident}"
```
```
✓ Info command
```
Let me know if there are any questions. Thanks!
=> [dotnet-core-sdk] Updating Linux/Windows plans to 2.2.301 w/new tests

cerebro/config/application.conf, cerebro/plan.sh, cerebro/tests/test.bats, cerebro/tests/test.sh
* Update testing
* Update version to 0.8.4
* Migrate to openjdk
```
hab pkg build cerebro
hab studio run "./cerebro/tests/test.sh ${pkg_ident}"
```
```
Waiting 5 seconds for service to start...
```
=> [cerebro] Update Cerebro to 0.8.4, update tests, migrate to openjdk

cockroach/plan.sh, cockroach/tests/test.bats, cockroach/tests/test.sh
```
hab pkg build cockroach
hab studio run  "./cockroach/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
✓ Listening on ports: 8080, 26257
```
=> [cockroach] Update cockroach to 19.1.3, Update tests

jetty/hooks/init, jetty/hooks/run, jetty/plan.sh, jetty/tests/test.bats, jetty/tests/test.sh
=> [jetty] Replace jdk with openjdk11

telegraf/plan.sh, telegraf/tests/test.bats, telegraf/tests/test.sh
```
hab pkg build telegraf
hab studio run "./telegraf/tests/test.sh ${pkg_ident}"
```
```
```
=> [telegraf] Update telegraf to 1.11.3

docs/dev/policy_documents/standards-for-tests.md
Creating this PR to update the testing standards document to use core/pester for windows plan testing.  This PR was necessary because the update was accidentally rolled back on the [previous PR](https://github.com/habitat-sh/core-plans/pull/2634).
=> [docs] Update standards-for-tests.md to use core/pester [version 2]

logstash2/plan.sh
=> [logstash2] Replace jdk8 with corretto8

kafka/config/server.properties, kafka/default.toml, kafka/hooks/run, kafka/plan.sh, kafka/tests/test.bats, kafka/tests/test.sh
Getting kafka working required a number of fixes not only the replacement of core/jdk8 with core/corretto8:
* Fix service logging to go beneath {{pkg.svc_var_path}}.  The /hab/svc/kafka/var is owned by 'hab' service user whereas /hab/svc/kafka/logs is owned by 'root'.  Any attempts of the kafka service to write to 'logs' directory fail silently
* Add kafka file appender to log4j.properties so that service health and kafka version can be verified in tests
* Replace core/jre8 with core/corretto8
* Add tests that verify the kafka service.  Before running the tests, the zookeeper service is setup.
=> [kafka] Replace jdk with openjdk

hugo/plan.sh, hugo/tests/test.bats, hugo/tests/test.sh
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.56.1

sccache/plan.sh, sccache/tests/test.bats, sccache/tests/test.sh
* Adds all backend features to the build
* Fixes the build so it doesn't compile twice
* Update to 0.2.9
* Add tests
```
hab pkg build sccache
hab studio run "./sccache/tests/test.sh ${pkg_ident}"
```
```
Waiting 5 seconds for service to start...
✓ Help command
✓ Listening on port 4226
```
=> [sccache] Update sccache to 0.2.9, add tests, fix build, add features

nginx/plan.ps1, nginx/plan.sh, nginx/tests/test.sh
```
hab studio run "./nginx/tests/test.sh ${pkg_ident}"
```
```
Waiting 5 seconds for service to start...
✓ Help command
```
=> [nginx] Update nginx to 1.17.2

dgraph/plan.sh, dgraph/tests/test.bats, dgraph/tests/test.sh
```
hab pkg build dgraph
hab studio run "./dgraph/tests/test.sh"
```
```
✓ Help command is functional
```
=> Update dgraph to 1.0.16, update tests

.gitignore, scaffolding-go/README.md, scaffolding-go/lib/go_module.sh, scaffolding-go/lib/gopath_mode.sh, scaffolding-go/lib/scaffolding.sh, scaffolding-go/plan.sh
From the introduction of Go version `1.11` we have available a new way of building go
applications called Go Module Mode (aka "module-aware mode"). This mode does not
require you to configure a Go Workspace and it also has an alternative to maintain your
app package dependencies.
Go Docs:
https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more
This change is introducing said mode to the Go Scaffolding, but keeping the previous
behavior available to build packages inside a Go Workspace. (GOPATH mode)
New scaffolding variable `scaffolding_go_module` to switch between modes.
When enabling ` scaffolding_go_module=on` the scaffolding will build in module mode,
Otherwise, it will default to GOPATH mode. 
_Note that I bumped the minor version of the plan to `0.2.0`._
=> [scaffolding-go] Go Module Mode 

perl/plan.ps1, perl/tests/test.bats, perl/tests/test.pester.ps1, perl/tests/test.ps1, perl/tests/test.sh
* for windows and linux
* fixing windows stdout according to Matt Wrock's #2745
=> [perl] Add tests to core/perl

yarn/plan.sh, yarn/tests/test.bats, yarn/tests/test.sh
```
hab studio run "./yarn/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [yarn] Update yarn to 1.17.3, update tests

kibana/plan.sh
Kibana currently fails to build because one of its dependencies (node-sass) does not support node12.  Newer versions of node-sass do support node12, however digging through the package.json and yarn.lock of releases, no versions of Kibana ship with that version yet.  
For now, we'll switch our dependency to node11 in order to get this package building again. A version bump at this point would be a major version up and require changing the build process. As this change is to unblock the base plans refresh, I'm splitting that work out to be done post-refresh. 
=> [kibana] Change node dependency to node11

scaffolding-go/lib/gopath_mode.sh, scaffolding-go/tests/go-module-app/go.mod, scaffolding-go/tests/go-module-app/habitat/plan.sh, scaffolding-go/tests/go-module-app/main.go, scaffolding-go/tests/go-path-app/habitat/plan.sh, scaffolding-go/tests/go-path-app/main.go, scaffolding-go/tests/test.sh
This is fixing a scaped bug that I just introduced with the new version of the Go
Scaffolding, but for this to not happen again, I have added some tests for both,
a GOPATH and Go Module app.
=> [scaffolding-go] Adds tests and a quick fix

scaffolding-go/lib/scaffolding.sh
Instead of using `_pkg_path_for_build_deps` that is not fully exposed inside
the habitat build process, use `pkg_path_for` that is the exposed version of
the helper function.
=> [scaffolding-go] Use public hab func pkg_path_for

graphviz/plan.sh, graphviz/tests/test.bats, graphviz/tests/test.sh
Graphviz has moved their downloads to a non-versioned tarball :joy:  This updates the download location and updates the tests to the current standard.
=> [graphviz] Fix download location

gzip/plan.sh, gzip/tests/test.bats, gzip/tests/test.sh
This minor version up allows gzip to build against glibc-2.29
[1.10 Release notes](https://savannah.gnu.org/forum/forum.php?forum_id=9339)
=> [gzip] Update version

bc/plan.sh, bc/tests/test.bats, bc/tests/test.sh
The current version and license info appear to be up-to-date, so the only thing needed for base plan refresh is to add some tests.
=> [bc] Add tests

automake/plan.sh, automake/tests/test.bats, automake/tests/test.sh
Automake 1.16.1 is a security release to address CVE-2012-3386:  https://lists.gnu.org/archive/html/automake/2012-07/msg00023.html
=> [automake] Update to 1.16.1

findutils/correct-glibc-fflush.patch, findutils/correct-glibc-makedev.patch, findutils/plan.sh, findutils/tests/test.bats, findutils/tests/test.sh
This adds two patches to allow findutils to build with glibc-2.29 
https://lists.gnu.org/r/bug-gnulib/2018-03/msg00000.html
https://lists.gnu.org/archive/html/autoconf/2016-09/msg00021.html
=> [findutils] Patch to work with glibc-2.29 

m4/glibc-change-workaround.patch, m4/plan.sh, m4/tests/test.bats, m4/tests/test.sh
After updating to glibc 2.29, m4 fails to build with the following error:
>freadahead.c:92:3: error:
error "Please port gnulib freadahead.c to your platform!
Look at the definition of fflush, fread, ungetc on your system,
then report this to bug-gnulib."
This adds a patch to allow m4 to build against glibc 2.29
=> [m4] Patch to build with glibc-2.29 

perl/no-sys-dirs.patch, perl/plan.ps1, perl/plan.sh, perl/tests/fixtures/hello.pl, perl/tests/test.bats, perl/tests/test.sh
This updates Perl to the latest stable release, 5.30.   Note: Perl uses odd numbered version to track development, so while there is a 5.31 available we should stay on 5.30. 
The no-sys-dirs patch has been updated to align with a small change made in the `Errno_pm.PL` file.  The remainder of changes in the file are line number changes to the diff to reflect changes made in the source file.
=> [perl] Update to 5.30

bin/ci/shellcheck.sh
This disables Shellchecks 1008 and 2239, which will almost always be false positives in the context of core-plans.  In the same way we disable [SC2148](https://github.com/koalaman/shellcheck/wiki/SC2148) because plan.sh shouldn't start with a `#!`, a number of our scripts start with template values that are evaluated at build to inject a correct, full path. 
https://github.com/koalaman/shellcheck/wiki/SC1008
https://github.com/koalaman/shellcheck/wiki/SC2239
=> Disable shellcheck 1008 and 2239

bin/ci/build-and-run-tests.sh, elasticsearch/plan.sh, elasticsearch/tests/test.bats, elasticsearch/tests/test.sh
This resolves the merge conflicts in #2308 and supersedes that PR.  Thanks for you work on this @itmustbejj  !
Signed-off-by: Josh Hudson <jhudson@chef.io>
=> [elasticsearch] Update elasticsearch plan to 6.6.1 and switch from jre8 to openjdk11

node10/plan.ps1, node10/plan.sh
```
hab pkg build node10
hab studio run "./node10/tests/test.sh"
```
```
✓ Help Command
```
=> [node10] Update node10 to 10.16.1

netdata/plan.sh, netdata/tests/test.bats, netdata/tests/test.sh
```
hab pkg build netdata
hab studio run "./netdata/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
✓ Listening on port 19999
```
=> [netdata] Update netdata to 1.16.1, add testing

minio/plan.sh, minio/tests/test.bats, minio/tests/test.sh
```
hab pkg build minio
hab studio run "./minio/tests/test.sh ${pkg_ident}"
```
```
✓ Version matches, via help output
✓ Listening on port 9000
```
=> [minio] Update minio to 2019-07-31T18-57-56Z, simplify version check

consul/plan.sh, consul/tests/test.sh
```
hab studio run "./consul/tests/test.sh ${pkg_ident}"
```
```
```
=> [consul] Update consul to 1.5.3

vault/plan.sh, vault/tests/test.bats, vault/tests/test.sh
```
hab pkg build vault
hab studio run "./vault/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [vault] Update vault to 1.1.5, update testing

terraform/plan.sh
=> [terraform] Update terraform to 0.12.6

bin/ci/build-and-run-tests.sh, bin/ci/verify-pr-build.sh, gcc-libs/plan.sh, gcc/cc-wrapper.sh, gcc/plan.sh, gcc/tests/bats/test.bats, gcc/tests/test.sh
Release Notes:
https://www.gnu.org/software/gcc/gcc-9/changes.html
This updates GCC to version 9.1 and adds some simple testing to ensure our wrapper scripts around the compilers are functioning as intended. 
One notable change is that we are enabling control-flow instrumentation. This is necessary in order to enable the same feature on glibc (#2717). 
>--enable-cet
>--disable-cet
>    Enable building target run-time libraries with control-flow instrumentation, see -fcf-protection option. When --enable-cet is specified target libraries are configured to add -fcf-protection and, if needed, other target specific options to a set of building options.
>
>    The option is disabled by default. When --enable-cet=auto is used, it is enabled on Linux/x86 if target binutils supports Intel CET …
=> [gcc][gcc-libs] Update to 9.1

gmp/plan.sh, gmp/tests/test.sh
This enables a build flag that should improve performance across systems where this library is used.  
>Fat binary, --enable-fat
>
>    Using --enable-fat selects a “fat binary” build on x86, where optimized low level subroutines are chosen at runtime according to the CPU detected. This means more code, but gives good performance on all x86 chips. (This option might become available for more architectures in the future.)
There are no version updates, but a small change to the build process was required to allow this to build outside of stage1/stage2 which is also  explained inline
> GCC will set the dynamic linker if we don't provide it. Since this package is built after glibc, but before GCC, we would end with segfaults during the
build process because it will set the RPATH to look at …
=> [gmp] Update and add tests

libmpc/plan.sh, libmpc/tests/test.sh
There are no version updates, but a small change to the build process was required to allow this to build outside of stage1/stage2 which is also  explained inline
> GCC will set the dynamic linker if we don't provide it. Since this package is built after glibc, but before GCC, we would end with segfaults during the
build process because it will set the RPATH to look at _new_ glibc, but the
dynamic linker will be the _old_ glibc. By setting it here, we ensure that
all the versions line up.
This package provides only libraries so the test is an empty stub to conform with our testing practices.
=> [libmpc] Update build and add tests

mpfr/plan.sh, mpfr/tests/test.sh
There are no version updates, but a small change to the build process was required to allow this to build outside of stage1/stage2 which is also  explained inline
> GCC will set the dynamic linker if we don't provide it. Since this package is built after glibc, but before GCC, we would end with segfaults during the
build process because it will set the RPATH to look at _new_ glibc, but the
dynamic linker will be the _old_ glibc. By setting it here, we ensure that
all the versions line up.
This package provides only libraries so the test is an empty stub to conform with our testing practices.
=> [mpfr] Update build and add tests

logstash/hooks/init, logstash/plan.sh, logstash/tests/test.bats, logstash/tests/test.sh
=> [logstash] Replace jdk with corretto8

zeromq/plan.ps1
This updates the library version references in the `Invoke-Install` phase of zeromq.  My Windows system isn't available at the moment so I haven't verified this works yet.  Once I've done that, I'll add a comment here that this is ready to be merged. 
=> [zeromq] Update lib references on Windows

jruby1/plan.sh, jruby1/tests/test.bats, jruby1/tests/test.sh
After replacing the jdk8/jre8 with openjdk11, core/ruby1 fails to build:
```java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jruby-core: Compilation failure
[ERROR] /hab/cache/src/jruby-1.7.27/core/src/main/java/org/jruby/management/BeanManagerImpl.java:[94,26] error: cannot find symbol
```
=> [jruby1] Replace jdk with openjdk

bzip2/plan.ps1, bzip2/plan.sh, bzip2/tests/test.bats, bzip2/tests/test.pester.ps1, bzip2/tests/test.ps1, bzip2/tests/test.sh
See #2741 and #2916 for background to this PR.
PR #2741 introduced windows and linux tests to the bzip2 core plan.  #2916 re-based the PR not off core-plans master but the refresh/2019q3 branch.  This PR removes a master commit that was incorrectly merged into the branch
=> [bzip2] Add windows and linux tests to core/bzip2 VERSION 3

openssl/plan.ps1, openssl/plan.sh, openssl/tests/test.bats, openssl/tests/test.pester.ps1, openssl/tests/test.ps1, openssl/tests/test.sh
See #2740 and #2917 for background to this PR.
PR #2740 introduced windows and linux tests to the openssl core plan but needed to be rebased not off core-plans master but rather the refresh/2019q3 branch.  #2917 handled rebase but introduced an incorrect master branch commit so this PR was created to clean up the commits.
=> [openssl] Add windows and linux tests to core/openssl VERSION 3

gocd-server/hooks/run, gocd-server/plan.sh, gocd-server/tests/test.bats, gocd-server/tests/test.sh
See #2883 and #2918 for background to this PR.
PR #2883 replaced jdk with corretto.  #2918 rebased the PR to be not off core-plans master but the refresh/2019q3 branch.  Since #2918 introduced an incorrect merge commit, this PR cleans up the change request
=> [gocd-server] Replace jdk with corretto8 VERSION 3

jenkins/hooks/run, jenkins/plan.sh, jenkins/tests/test.bats, jenkins/tests/test.sh
=> [jenkins]  Replace jdk with corretto

telegraf/plan.sh
```
hab pkg build telegraf
hab studio run "./telegraf/tests/test.sh ${pkg_ident}"
```
```
```
=> [telegraf] Update telegraf to 1.11.4

coreutils/plan.sh
Without diffutils, coreutils generate a different build and fails multiple tests. 
=> [coreutils] Re-add diffutils as a dependency

bundler/plan.sh, scaffolding-ruby/plan.sh
I think that the creator of these plans wanted to scape the DEBUG
environment variable for debugging, without scaping it the resulting
binary looks like:
```bash
set -e
if test -n ""; then set -x; fi
```
and instead we want this:
```bash
set -e
if test -n "$DEBUG"; then set -x; fi
```
=> [QUICK-FIX] Scape DEBUG env variable

dotnet-core-sdk/plan.ps1, dotnet-core-sdk/plan.sh
Hey all,
This PR updates dotnet-core-sdk to version 2.2.401. To test the build, please run:
```
hab pkg build dotnet-core-sdk
hab studio run "./dotnet-core-sdk/tests/test.sh ${pkg_ident}"
```
```
✓ Info command
```
Please let me know if there are any questions. Thanks!
=> [dotnet-core-sdk] Updating Linux/Windows plan to 2.2.401

clingo/README.md, clingo/plan.sh, clingo/tests/fixtures/examples/gringo/sort/RESULT_FOR_LUA.txt, clingo/tests/fixtures/examples/gringo/sort/RESULT_FOR_PYTHON.txt, clingo/tests/fixtures/examples/gringo/sort/encoding.lp, clingo/tests/fixtures/examples/gringo/sort/sort-lua.lp, clingo/tests/fixtures/examples/gringo/sort/sort-py.lp, clingo/tests/test.bats, clingo/tests/test.sh
This PR created to fix https://github.com/habitat-sh/core-plans/issues/2210.  Issue fixed by adding core/python and core/lua to $pkg_deps and verifying the runtime environment with bats tests
=> [clingo] Fix runtime core/clingo so that gringo works properly

bazel/plan.sh
This package currently doesn't build so this change hasn't been validated, but is a requirement to finish the deprecation of jre/jdk.  The complexity of this packages build process, and the low usage of this package have, unfortunately, made fixing the builds a low priority and are out of scope for the JRE/JDK deprecation. 
=> [bazel] Change jdk to coretto

vault/plan.sh
```
hab pkg build vault
hab studio run "./vault/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [vault] Update vault to 1.2.1

docs/dev/policy_documents/standards-for-tests.md
The sample bats tests needed to be updated
* with latest bzip bats test examples according to pr #2737
* in line with issue #2716
=> [docs] Remove [[..]] from bats examples in document

cuda/plan.sh
This package is currently unsupported, but remains in core as a reference and hope that we will be able to re-enable builds in the future #2325 .  In order to fully deprecate the jre/jdk packages, we need to move all dependencies off of it.  
=> [cuda] Change jre to coretto

go/plan.sh
This addresses the following CVEs:
- CVE-2019-9512
- CVE-2019-9514
- CVE-2019-14809
For more information see
https://groups.google.com/forum/#!msg/golang-nuts/fCQWxqxP8aA/DbI5QZnMAAAJ
=> [go] Bump version to 1.12.8

bash/bash-patches.sh, bash/plan.sh, bash/tests/test.bats, bash/tests/test.sh
This updates Bash to 5.0.7, with the latest set of patches (the .7) :wink: 
It also adds a small test to ensure that it can execute and sets internal variables correctly. 
=> [bash] Update to latest version 

CODEOWNERS, base-plans.txt
With the addition of libidn2 as a dependency to wget (#1981), it also needs to be considered base plan.  It bring with it two additional dependencies, libunistring and libiconv which are also added to the base-plans list.
=> Add libidn2 and deps to base-plans.txt

libunistring/plan.sh
This is a minor version bump required to allow libunistring to be built against glibc2.29 
This package provides no executable commands so the `pkg_bin_dirs` line has been removed. 
=> [libunistring] update to 0.9.10

libsodium-musl/plan.sh
This updates libsodium-musl to include required variables, and set pkg_dirname to allow builds to happen.
=> [libsodium-musl] Set pkg_dirname 

nghttp2/plan.sh
We don't currently build the binaries included in this, but let's still
bump for this:
https://github.com/nghttp2/nghttp2/releases/tag/v1.39.2
=> [nghttp2] bump: 1.34.0 -> 1.39.2

nginx/plan.ps1, nginx/plan.sh
Changelog is here: http://nginx.org/en/CHANGES
Changes with nginx 1.17.3                                        13 Aug 2019
*) Security: when using HTTP/2 a client might cause excessive memory
consumption and CPU usage (CVE-2019-9511, CVE-2019-9513,
CVE-2019-9516).
*) Bugfix: "zero size buf" alerts might appear in logs when using
gzipping; the bug had appeared in 1.17.2.
*) Bugfix: a segmentation fault might occur in a worker process if the
"resolver" directive was used in SMTP proxy.
---------
⚠️ I've changed the `plan.ps1` without having the slightest idea how to test this. Let's see if CI does 🤔
=> [nginx] bump: 1.17.2 -> 1.17.3

hugo/plan.sh, hugo/tests/test.bats
Update the hugo plan.sh to properly build the extended version of the hugo binary. Update the tests to reflect this.
=> [hugo] 0.57 + extended version fixes

at-spi2-core/plan.sh
=> [at-spi2-core] add zlib runtime dependancy

boringssl/plan.sh
This moves the build dependencies to pkg_build_deps rather than
pkg_deps. Further, it overrides do_unpack to ensure we don't unpack
directly in the HAB_CACHE_SRC_PATH.
=> [boringssl] Move deps to pkg_build_deps, cleanup unpacking

pngquant/plan.sh, pngquant/tests/test.bats, pngquant/tests/test.sh
Requires #2914 to be merged first.
```
hab pkg build pngquant
hab studio run "./pngquant/tests/test.sh ${pkg_ident}"
```
```
```
=> [pngquant] Update pngquant to 2.12.5

CODEOWNERS
=> Fix habitat-core-maintainers team name in codeowners

caddy/tests/test.sh
Updated the test.sh so that the service testing is now successful
```bash
★ Install of core/caddy/1.0.1/20190703150822 complete with 1 new packages installed.
--- :warning: Supervisor LOCK file found, not starting the supervisor
--- :habicat: Loading service core/caddy
The core/caddy service was successfully loaded
Waiting for core/caddy to start: 1
Waiting for core/caddy to start: 2
Waiting for core/caddy to start: 3
✓ Help command
Unloading core/caddy
```
=> [caddy] Fix the broken core/caddy tests

jenkins/hooks/run
This forgoes the use of `{{sys.ip}}`, allowing the Jenkins service to listen on _every_ network interface instead of [the first network interface with a route to Google's DNS](https://github.com/habitat-sh/habitat/issues/5079#issuecomment-494119508). This both overcomes the Habitat bug where `sys.ip` will sometimes resolve to the local loopback, as well as allowing this to be more flexible as a whole.
If there is a use-case for restricting the Jenkins server to a specific IP address, this should probably be addressed through the resolution to [this issue](https://github.com/habitat-sh/habitat/issues/6793) when it arrives.
=> [jenkins] Listen on multiple network interfaces

dnsmasq/tests/test.sh
Tests all continue to pass:
```bash
--- :warning: Supervisor LOCK file found, not starting the supervisor
--- :habicat: Loading service core/dnsmasq/2.80/20190821154320
The core/dnsmasq/2.80/20190821154320 service was successfully loaded
Waiting for core/dnsmasq/2.80/20190821154320 to start: 1
Waiting for core/dnsmasq/2.80/20190821154320 to start: 2
Waiting for core/dnsmasq/2.80/20190821154320 to start: 3
✓ dnsmasq service is running
✓ dnsmasq successfully finds debian.org
✓ dnsmasq binary matches version 2.80
✓ dnsmasq binary test returns success
Unloading core/dnsmasq/2.80/20190821154320
```
=> [dnsmasq] Source test_helper.sh relative to test.sh

curl/plan.sh
The changelog entries for the two releases contains the following
changes, all of which appear to be bug fixes (from
https://curl.haxx.se/changes.html):
- progress: make the progress meter appear again
- CIPHERS.md: Explain Schannel error SEC_E_ALGORITHM_MISMATCH
- CMake: Convert errant elseif() to else()
- CMake: Fix finding Brotli on case-sensitive file systems
- CURLMOPT_SOCKETFUNCTION.3: clarified
- CURLMOPT_SOCKETFUNCTION.3: fix typo
- CURLOPT_CAINFO.3: polished wording
- CURLOPT_HEADEROPT.3: Fix example
- CURLOPT_RANGE.3: Caution against using it for HTTP PUT
- CURLOPT_SEEKDATA.3: fix variable name
- DEPRECATE: fixup versions and spelling
- bindlocal: detect and avoid IP version mismatches in bind()
- build: fix Codacy warnings
- buildconf.bat: fix header filename
- c-ares: honor …
=> [curl] Upgrade to 7.65.3

node/plan.ps1, node/plan.sh, node12/plan.ps1, node12/plan.sh
```
hab pkg build node
hab studio run "./node/tests/test.sh ${pkg_ident}"
```
```
✓ Help Command
```
=> [node/node12] Update node to 12.9.0

terraform/plan.sh
Hey all,
This is just a simple version bump to Terraform. To test this build, run the following commands:
```
```
```
```
=> [terraform] Updating to 0.12.7

rsync/plan.sh
This includes two security fixes in addition to a number of bug fixes:
- Fixed a buffer overrun in the protocol's handling of xattr names
and ensure that the received name is null terminated.
- Fix an issue with --protect-args where the user could specify the
arg in the protected-arg list and short-circuit some of the
arg-sanitizing code.
https://download.samba.org/pub/rsync/src/rsync-3.1.3-NEWS
=> [rsync] Upgrade rsync to 3.1.3

terraform/plan.sh
Hey all,
This is a simple version bump. To test the build, run the following commands:
```
```
```
```
=> [terraform] Updating to 0.12.8

hugo/plan.sh
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.58.1

consul/plan.sh
```
hab studio run "./consul/tests/test.sh ${pkg_ident}"
```
```
```
=> [consul] Update consul to 1.6.0

opa/tests/test.sh
```bash
hab pkg build opa
hab studio run "opa/tests/test.sh ${pkg_ident}"
```
produces test results:
```bash
★ Install of core/opa/0.14.0/20190913140038 complete with 1 new packages installed.
--- :habicat: Starting the supervisor
Waiting for Supervisor to start: 1
Waiting for Supervisor to start: 2
--- :habicat: Loading service core/opa/0.14.0/20190913140038
The core/opa/0.14.0/20190913140038 service was successfully loaded
Waiting for core/opa/0.14.0/20190913140038 to start: 1
Waiting for core/opa/0.14.0/20190913140038 to start: 2
Waiting for core/opa/0.14.0/20190913140038 to start: 3
Waiting for opa to start (5s)
1..3
ok 1 Port Listen TCP/8181
ok 2 /v1/data/system/version endpoint returns version
ok 3 /v1/query endpoint returns an answer
Unloading …
```
=> [opa] Refactor tests to use ./bin/ci/test_helpers.sh

rust/plan.ps1, rust/plan.sh
https://blog.rust-lang.org/2019/09/26/Rust-1.38.0.html
=> Bump rust to 1.38.0

yarn/plan.ps1, yarn/plan.sh
```
hab studio run "./yarn/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [yarn] Update yarn to 1.18.0

telegraf/plan.sh
```
hab pkg build telegraf
hab studio run "./telegraf/tests/test.sh ${pkg_ident}"
```
```
```
=> [telegraf] Update telegraf to 1.12.2

php/plan.sh
```
hab pkg build php
hab studio run "./php/tests/test.sh ${pkg_ident}"
```
```
✓ Libzip is supported.
```
=> [php] Update PHP to 7.3.9

netdata/plan.sh
```
hab pkg build netdata
hab studio run "./netdata/tests/test.sh ${pkg_indent}"
```
```
✓ Help command
✓ Listening on port 19999
```
=> [netdata] Update netdata to 1.17.0

ant/plan.sh
```
hab pkg build ant
hab studio run "./ant/tests/test.sh ${pkg_ident}"
```
```
```
=> [ant] Update ant to 1.10.7

ruby24/plan.sh, ruby25/plan.sh, ruby26/plan.sh
There are a large number of CVEs and bugs in these releases of Ruby. Bump to the latest 2.4, 2.5, and 2.6 release. I've left the ruby plan alone because I'm going to bump that to 2.6 where it should be.
=> [ruby] Update ruby24, ruby25, and ruby26

php/plan.sh
```
hab pkg build php
hab studio run "./php/tests/test.sh ${pkg_ident}"
```
```
★ Install of rakops/php/7.3.10/20191001010231 complete with 11 new packages installed.
✓ Libzip is supported.
```
=> [php] Update PHP to 7.3.10

strace/plan.sh
```
hab pkg build strace
hab studio run "./strace/tests/test.sh ${pkg_ident}"
```
```
✓ Can strace
```
=> [strace] Update strace to 5.3

visual-build-tools-2017/plan.ps1
This accommodates a customer that is packaging database migrations using Visual Studio database projects by adding the `Microsoft.VisualStudio.Component.SQL.SSDTBuildSku` component.
This also attempts to make the installer command a little less cray cray.
=> [visual-build-tools-2017] add sql database project build capabilities to visual-build-tools-2017

ruby/plan.sh, ruby24/plan.sh, ruby25/plan.sh, ruby26/plan.sh
[2.5.7](https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-5-7-released/) and [2.6.5](https://www.ruby-lang.org/en/news/2019/10/01/ruby-2-6-5-released/) have CVE fixes:
- [CVE-2019-16255](https://www.ruby-lang.org/en/news/2019/10/01/code-injection-shell-test-cve-2019-16255/): A code injection vulnerability of Shell#[] and Shell#test
- [CVE-2019-16254](https://www.ruby-lang.org/en/news/2019/10/01/http-response-splitting-in-webrick-cve-2019-16254/): HTTP response splitting in WEBrick (Additional fix)
- [CVE-2019-15845](https://www.ruby-lang.org/en/news/2019/10/01/nul-injection-file-fnmatch-cve-2019-15845/): A NUL injection vulnerability of File.fnmatch and File.fnmatch?
- [CVE-2019-16201](https://www.ruby-lang.org/en/news/2019/10/01/webrick-regexp-digestauth-dos-cve-2019-16201/): Regular …
=> [ruby] new point releases for Ruby for CVEs

memcached/plan.sh
```
hab pkg build memcached
hab studio run "./memcached/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [memcached] Update memcached to 1.5.19

tcpdump/plan.sh, tcpdump/tests/test.bats, tcpdump/tests/test.sh
```
hab pkg build tcpdump
source results/last_build.env                                                  
```
```
✓ Help command
```
=> [tcpdump] Update tcpdump to 4.9.3, add simple tests

libatomic_ops/plan.sh
It appears that the author is still releasing 7.4 versions
here:
http://www.ivmaisoft.com/_bin/atomic_ops/
but I've tested a build of bdwgc against this 7.6 version
and all of the tests pass.
=> [libatomic_ops] Upgrade to version 7.6.10

yarn/plan.ps1, yarn/plan.sh
```
hab studio  run "./yarn/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
yawn, I mean yarn, is now up to date!
=> [yarn] Update yarn to 1.19.1

consul/plan.sh
```
```
```
Waiting 10 seconds for service to start...
```
=> [consul] Update consul to 1.6.1

terraform/plan.sh
=> [terraform] Update terraform to 0.12.10

sudo/plan.sh
I changed the URL from the FTP to HTTP as FTP was going tremendously slow.
Signed-off-by: Jeff Moody <fifthecho@gmail.com>
=> [sudo] Bumping Sudo version for CVE-2019-14287

bin/check-uploaded-version.sh
In addition to merging the relevant PRs to this repository, it is
important that we promote the build group produced by the
merge. However, sometimes we forgot to do this when the build take a
while or when the build group will promote something that we are
unsure about.
This is a small script maintainers can use to periodically get us back
up to date.
=> Add script to find packages we forgot to promote

CODEOWNERS, MAINTAINERS.md
@reset ,  thank you for your contributions to the Habitat Core Plans project! It's been a while since you've been active. We understand life gets busy and interests change so we're going to move you to `Alumni` status and remove CODEOWNER entries on the following plans:
```
libarchive
libsodium
nginx
postgresql
protobuf
protobuf-rust
zeromq
glibc
gcc-libs
openssl
libsodium-musl
libarchive-musl
rust
```
If you'd like to be a CODEOWNER/maintainer in the future we'd love to have you back. At that time, please open a PR adding yourself back to the appropriate entries.
=> CODEOWNERS cleanup - reset

CODEOWNERS, MAINTAINERS.md
@fnichol ,  thank you for your contributions to the Habitat Core Plans project! It's been a while since you've been active. We understand life gets busy and interests change so we're going to move you to `Alumni` status and remove CODEOWNER entries on the following plans:
```
libarchive
libsodium
nginx
postgresql
protobuf
protobuf-rust
zeromq
linux-headers
glibc
zlib
file
binutils
m4
gmp
mpfr
libmpc
gcc
gcc-libs
patchelf
bzip2
pkg-config
ncurses
attr
acl
libcap
sed
shadow
psmisc
procps-ng
coreutils
bison
flex
pcre
grep
readline
bash
bc
tar
gawk
libtool
gdbm
expat
db
inetutils
iana-etc
less
perl
diffutils
autoconf
automake
findutils
xz
gettext
gzip
make
patch
texinfo
util-linux
tcl
expect
dejagnu
check
libidn
cacerts
openssl
wget
unzip
rq
linux-headers-musl
musl
busybox-static
zlib-musl …
```
=> CODEOWNERS cleanup - fnichol

CODEOWNERS, MAINTAINERS.md
@rsertelon  ,  thank you for your contributions to the Habitat Core Plans project! It's been a while since you've been active. We understand life gets busy and interests change so we're going to move you to `Alumni` status and remove CODEOWNER entries on the following plans:
```
acbuild
atk
cairo
gdk-pixbuf
glib
gtk2
harfbuzz
jdk7
jdk8
jre7
jre8
monit
mosquitto
pango
shared-mime-info
```
If you'd like to be a CODEOWNER/maintainer in the future we'd love to have you back. At that time, please open a PR adding yourself back to the appropriate entries.
=> CODEOWNERS cleanup - rsertelon 

bind/plan.sh
`libxml` preferred method is via `pkg-config` now, adjusted build process to reflect that.
```
hab pkg build bind
souce results/last_build.env
```
```
✓ Dig
✓ Host
✓ ARPAname
✓ DNSSec Keygen
```
=> [bind] Update bind to 9.15.4

protobuf/plan.ps1, protobuf/plan.sh, protobuf/tests/test.bats, protobuf/tests/test.sh
```
hab pkg build protobuf
hab studio run "./protobuf/tests/test.sh ${pkg_ident}"
```
```
✓ Help command
```
=> [protobuf] Update protobuf to 3.9.2, add tests

elasticsearch/config/jvm.options, elasticsearch/config/log4j2.properties, elasticsearch/plan.sh, elasticsearch/tests/test.bats
* Update jvm opts to reflect defaults in the 6.8.3 distribution
* Fix deprecated console layout
* Bump to the latest stable 6.x version
=> [elasticsearch] update to 6.8.3

docker/plan.sh, docker/tests/test.bats, docker/tests/test.sh
```
hab pkg build docker
```
```
✓ Help command
```
=> [docker] Update docker for linux to 19.03.3, add tests

ruby/tests/test.bats, ruby/tests/test.sh, ruby24/tests/test.sh, ruby25/tests/test.sh, ruby26/tests/test.sh
Quick smoke check to make sure Ruby built and is the expected version.
One test definition for `core/ruby` and the others symlink the `tests/` directory because _they're the same tests_.
=> [ruby] add quick tests for Ruby plans

.bldr.toml, CODEOWNERS, nss-myhostname/README.md, nss-myhostname/plan.sh
[nss-myhostname](http://0pointer.de/lennart/projects/nss-myhostname/) is a plugin for the GNU Name Service Switch (NSS) functionality of the GNU C Library (glibc) providing host name resolution for the locally configured system hostname as returned by gethostname(2). This plugin is commonly enabled in the default `/etc/nsswitch.conf` NSS configuration of RHEL and RHEL-like Linux distributions, with a hosts entry like:
hosts:      files dns myhostname
`glibc` has `/etc/nsswitch.conf` hard-coded as the file location for configuration.  So long as `core/glibc` ships with that setting, this plugin is necessary for some software to perform name resolution with expected behavior.
It is common in the Ruby ecosystem to check if a domain name is resolvable by using the Ruby stdlib `Socket` class …
=> [nss-myhostname] add a new plan!

spark/hooks/run, spark/plan.sh, spark/tests/test.bats, spark/tests/test.sh
Fixes issue #2904 
To verify, enter a hab studio and load the service:
```bash
build spark
hab pkg install results/$pkg_artifact
hab svc load $pkg_ident
```
then check the supervisor log.  It should contain something like this:
```bash
40][default:/src:0]# sup-log
--> Tailing the Habitat Supervisor's output (use 'Ctrl+c' to stop)
spark.default(O): 19/09/18 12:36:00 INFO Utils: Successfully started service 'MasterUI' on port 8080.
spark.default(O): 19/09/18 12:36:00 INFO MasterWebUI: Bound MasterWebUI to 0.0.0.0, and started at http://:8080
spark.default(O): 19/09/18 12:36:01 INFO Utils: Successfully started service on port 6066.
spark.default(O): 19/09/18 12:36:01 INFO StandaloneRestServer: Started REST server for submitting applications on port 6066 …
```
=> [spark] Fix broken service

composer/plan.sh, composer/tests/test.bats, composer/tests/test.sh
```
hab pkg build composer
```
```
✓ Help command
```
=> [composer] Update composer to 1.9.0, add tests

.bldr.toml, nginx-prometheus-exporter/README.md, nginx-prometheus-exporter/default.toml, nginx-prometheus-exporter/hooks/run, nginx-prometheus-exporter/plan.sh
Adds a new plan for nginx-prometheus-exporter.
This is difficult to test. It requires a running Nginx instance, with stub_status enabled, and configured to listen on a separate port/path for stats. This would require embedding a configuration plan inside this plan path.
For the moment I have done private testing on a service I have on an internal builder that exposes the endpoint. Once that is loaded, I run nginx-prometheus-exporter, and it connects to the local Nginx.
Only once the Nginx connection is available does the exporter start listening. So there is no easy way to test this from a service perspective.
=> [nginx-prometheus-exporter] Add new plan: nginx-prometheus-exporter

jenkins/plan.sh
```
hab pkg build jenkins
```
```
✓ jenkins binary version matches 2.190.2
```
=> [jenkins] Update jenkins to 2.190.2

terraform/plan.sh
=> [terraform] Update terraform to 0.12.13

ghc86/plan.ps1
Added a ghc86 plan for windows.
This is needed to continue to build shellcheck as GHC 8.8 fails to build the current stable version of shellcheck.
=> [ghc86] Added ghc86 plan for windows

alex/plan.sh
Tests for alex fail if built with ghc 8.8
Pinning to ghc 8.6 for now
=> [alex] Fix alex builds for ghc 8.8

shared-mime-info/plan.sh
During a troubleshooting session with Michal Wronka it was discovered that on building the shared-mime-info it failed as follows:
```bash
...
...
shared-mime-info: Setting PKG_CONFIG_PATH=/hab/pkgs/core/expat/2.2.5/20190115012836/lib/pkgconfig:/hab/pkgs/core/glib/2.50.3/20190305224252/lib/pkgconfig:/hab/pkgs/core/libxml2/2.9.10/20191119234603/lib/pkgconfig:/hab/pkgs/core/pcre/8.42/20190115012526/lib/pkgconfig:/hab/pkgs/core/zlib/1.2.11/20190115003728/lib/pkgconfig
shared-mime-info: Preparing to build
--> Working on XML::Parser
Fetching http://www.cpan.org/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz ... OK
Configuring XML-Parser-2.46 ... N/A
! Configure failed for XML-Parser-2.46. See /root/.cpanm/work/1574435524.1223/build.log for details.
shared-mime-info: Build time: 0m48s …
```
=> [shared-mime-info] fix the broken build

shellcheck/plan.ps1, shellcheck/plan.sh
Updated shellcheck to 0.7.0
Building with ghc 8.6, as shellcheck does not yet support building with ghc 8.8
This is dependent on #3099
=> [shellcheck] Updated shellcheck to 0.7.0

haproxy/plan.sh
```
build haproxy
```
```
✓ Contains Prometheus exporter support
```
=> [haproxy] Update HAProxy to 2.0.9

hugo/plan.sh
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.59.1

autogen/plan.sh, autogen/tests/test.sh
No package promotion necessary after merge/build. Just a cleanup to follow current repo standards.
=> [autogen] Minor cleanup for autogen

alex/plan.sh, alex/tests/test.bats, alex/tests/test.sh, alex/tests/test.x
```
hab pkg build alex
```
```
✓ alex runs with exit status 1
✓ alex --help runs with exit status 0
✓ alex -v output mentions expected version
✓ alex simple token file succeeds
```
=> [alex] Update alex to 3.2.5, improve testing

googletest/plan.sh
```
DO_CHECK=1 build googletest
```
```
Test project /hab/cache/src/googletest-release-1.10.0/build
Start  1: gmock-actions_test
1/61 Test  #1: gmock-actions_test .........................   Passed    0.03 sec
Start  2: gmock-cardinalities_test
2/61 Test  #2: gmock-cardinalities_test ...................   Passed    0.01 sec
Start  3: gmock_ex_test
3/61 Test  #3: gmock_ex_test ..............................   Passed    0.01 sec
Start  4: gmock-function-mocker_test
4/61 Test  #4: gmock-function-mocker_test .................   Passed    0.01 sec
Start  5: gmock-generated-actions_test
5/61 Test  #5: gmock-generated-actions_test ...............   Passed    0.01 sec
Start  6: gmock-generated-function-mockers_test
6/61 Test …
```
=> [googletest] Update googletest to 1.10.0

curl-static-musl/plan.sh, curl/plan.sh
Update to the latest curl release
```
hab/pkgs/tas50/curl/7.67.0/20191130064650/bin/curl --help
Usage: curl [options...] <url>
--abstract-unix-socket <path> Connect via abstract Unix domain socket
--alt-svc <file name> Enable alt-svc with this cache file
--anyauth       Pick any authentication method
-a, --append        Append to target file when uploading
--basic         Use HTTP Basic Authentication
--cacert <file> CA certificate to verify peer against
--capath <dir>  CA directory to verify peer against
-E, --cert <certificate[:password]> Client certificate file and password
--cert-status   Verify the status of the server certificate
--cert-type <type> Certificate file type (DER/PEM/ENG)
--ciphers <list of ciphers> SSL ciphers to use
--compressed    Request compressed response …
```
=> Update curl to 7.67.0

bind/plan.sh
I'm not sure how this compiled before since 9.15 requires libuv, but
I've added that since it fails early if the lib is missing.
```
[32][default:/src/bind/results:0]# bind --help
bind: bind [-lpsvPSVX] [-m keymap] [-f filename] [-q name] [-u name] [-r keyseq] [-x keyseq:shell-command] [keyseq:readline-function or readline-command]
Set Readline key bindings and variables.
Bind a key sequence to a Readline function or a macro, or set a
Readline variable.  The non-option argument syntax is equivalent to
that found in ~/.inputrc, but must be passed as a single argument:
e.g., bind '"\C-x\C-r": re-read-init-file'.
Options:
-m  keymap         Use KEYMAP as the keymap for the duration of this
command.  Acceptable keymap names are emacs,
emacs-standard, emacs-meta, emacs-ctlx, vi, vi-move, …
```
=> [bind] Update bind to 9.15.6

base-plans.txt, libunistring/plan.sh
For the refresh/2019q3, the core/libunistring needs to be treated as a base-plan since the core/wget plan requires it.  In order for core/libunistring to build successfully with the new glibc 2.29, however, the libunistring version needed to be uplifted from 0.9.6 to 0.9.10.
Attempting to build libunistring version 0.9.6 with glibc 2.29 produces a failure:
```bash
gcc -DHAVE_CONFIG_H -DNO_XMALLOC -I. -I..  -I. -I. -I.. -I.. -DIN_LIBUNISTRING -DDEPENDS_ON_LIBICONV=1 -I/hab/pkgs/core/gcc/9.1.0/20190930135843/include -I/hab/pkgs/core/make/4.2.1/20191001153146/include -I/hab/pkgs/core/glibc/2.29/20190930110911/include  -I/hab/pkgs/core/gcc/9.1.0/20190930135843/include -I/hab/pkgs/core/make/4.2.1/20191001153146/include -I/hab/pkgs/core/glibc/2.29/20190930110911/include -c fseterr.c
fseterr.c: …
```
=> [libunistring] Uplift core/libunistring to 0.9.10

make/tests/test.bats
Test all pass:
```bash
★ Install of core/make/4.2.1/20190821165656 complete with 0 new packages installed.
✓ make matches version 4.2.1
✓ Make simple task
```
=> [make] Add version test for make

ansible/plan.sh
```
```
```
✓ Help Command
```
=> [ansible] Update ansible to 2.9.1

cmake/plan.ps1, cmake/plan.sh
```
hab pkg build cmake
```
```
✓ Version matches plan
```
=> [cmake] Update cmake to 3.16.0

tcl/tests/test.bats
Tests all pass:
```bash
★ Install of core/tcl/8.6.9/20190821164514 complete with 0 new packages installed.
✓ tclsh matches version 8.6.9
✓ simple tcl expression
[50][default:/src/tcl:0]#
```
=> [tcl] Add version check test

bin/ci/build-and-run-tests.sh, bin/ci/verify-pr-build.sh
@gavindidrichsen @predominant  This provides a workaround to the studio ssl issue caused by https://github.com/habitat-sh/habitat/issues/7219 until https://github.com/habitat-sh/habitat/pull/7259 lands. 
I've added a whitespace commit to a plan known to trigger the issue (ansible) to verify the workaround is functioning. That commit can be removed
=> Add workaround to studio ssl issue

go/plan.sh
Minor bug fixes:
https://golang.org/doc/devel/release.html#go1.13.minor
=> [go] Upgrade go to 1.13.5

libarchive/plan.ps1, libarchive/plan.sh
This includes a large number of fixes and support for new archive formats. We already mentioned this in chef-client release notes and this is necessary to make sure we have feature parity with omnnibus and hab builds.
=> [libarchive] Update from 3.3.3 to 3.4.0

openssl/plan.ps1, openssl/plan.sh
[CVE-2019-1547](https://nvd.nist.gov/vuln/detail/CVE-2019-1547)
[CVE-2019-1563](https://nvd.nist.gov/vuln/detail/CVE-2019-1563)
[CVE-2019-1552](https://nvd.nist.gov/vuln/detail/CVE-2019-1552)
=> [openssl] Update from 1.0.2r to 1.0.2t to resolve multiple CVEs

node/plan.ps1, node/plan.sh, node12/plan.ps1, node12/plan.sh
At the time of this commit, 12.13.x brings node into the "active LTS" phase, so suitable for production use.
SHAs extracted from:
https://nodejs.org/download/release/v12.13.1/SHASUMS256.txt
General Reference:
https://nodejs.org/en/about/releases/
```
hab pkg build node
hab studio run "./node/tests/test.sh ${pkg_ident}"
```
```
ok 1 Version matches
ok 2 Help Command
```
=> Update node to 12.13.1

hugo/plan.sh
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.61.0

nginx/plan.ps1, nginx/plan.sh, nginx/tests/test.sh
This PR addresses [CVE-2019-20372](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-20372).
```
```
```
✓ Help command
```
=> [nginx] Update nginx to 1.17.7

ansible/plan.sh
```
```
```
✓ Help Command
```
=> [ansible] Update ansible to 2.9.2

jenkins/plan.sh, jenkins/tests/test.sh
```
hab pkg build jenkins
```
```
✓ jenkins binary version matches 2.204.1
```
=> [jenkins] Update jenkins to 2.204.1

libgcrypt/plan.sh
Requires #3175 to be built and promoted first.
=> [libgcrypt] Update libgcrypt to 1.8.5

envconsul/plan.sh
```
hab pkg build envconsul
```
```
✓ Help command
```
=> [envconsul] Update envconsul to 0.9.1

e2fsprogs/plan.sh
```
hab pkg build e2fsprogs
```
```
✓ uuidgen works
```
=> [e2fsprogs] Update e2fsprogs to 1.45.4

sbt/plan.sh
```
hab pkg build sbt
```
```
✓ sbt matches version 1.3.7
```
=> [sbt] Update sbt to 1.3.7

gifsicle/plan.sh, gifsicle/tests/test.bats, gifsicle/tests/test.sh
```
hab pkg build gifsicle
```
```
```
=> [gifsicle] Update gifsicle to 1.92, and modernize tests

cabal-install/plan.ps1, cabal-install/plan.sh
Updated cabal-install to 3.0.0.0
Building with ghc 8.6, as cabal-install does not yet support building with ghc 8.8
This is dependent on #3099 
=> [cabal-install] Updated cabal-install to 3.0.0.0

caddy/plan.sh, caddy/tests/test.sh
```
hab pkg build caddy
```
```
✓ Help command
```
=> [caddy] Update caddy to 1.0.4

cerebro/plan.sh, cerebro/tests/test.sh
```
hab pkg build cerebro
```
```
```
=> [cerebro] Update cerebro to 0.8.5

memcached/plan.sh, memcached/tests/test.sh
```
hab pkg build memcached
```
```
✓ Help command
```
=> [memcached] Update memcached to 1.5.21

nginx/plan.ps1, nginx/plan.sh, nginx/tests/test.sh
```
```
```
✓ Help command
```
=> [nginx] Update nginx to 1.17.8

haproxy/plan.sh
```
hab pkg build haproxy
```
```
✓ Contains Prometheus exporter support
```
=> [haproxy] Update haproxy to 2.1.2

README.md
[Testing moved to BuildKite](https://github.com/habitat-sh/core-plans/pull/2767), so we should stop displaying project status from Travis.
Maybe merge in coordination with [the final removal of the Travis webhook](https://github.com/habitat-sh/core-plans/issues/2813)?
=> [docs] replace the Travis badge with a BuildKite badge in the README

terraform/plan.sh
Hello all,
This PR updates Terraform to version 0.12.20.
To test this, please run
```
```
```
```
=> [terraform] Upgrading to 0.12.20

bin/ci/test_helpers.sh, consul/plan.sh
Hello all,
This PR updates Consul to version 1.6.2.
To test this, please run
```
```
```
```
As a side note @predominant , I updated the test_helpers.sh ci_load_service() to a longer timeout. 5 was too fast and the service could not load in that time. I changed it to 10. Let me know what you think :)
=> Upgrading Consul to 1.6.2 and updated CI tests

mage/plan.sh, mage/tests/test.bats, mage/tests/test.sh
```
hab pkg build mage
```
```
✓ Help command
✓ Mage init works
```
=> [mage] Update mage to 1.9.0, update tests

elixir/plan.sh
```
hab pkg build elixir
```
```
```
=> [elixir] Update elixir to 1.10.0

tmux/plan.sh
```
hab pkg build tmux
```
```
```
=> [tmux] Update tmux to 3.0a

base-plans.txt
```bash
habitat/components/hab/habitat
habitat/components/plan-build/habitat
habitat/components/backline/habitat
habitat/components/studio/habitat
```
)and verify a refresh build from scratch
An example of an automated Builder setup is defined [here](https://github.com/chef-partners/habitat-coreplan-refresher).  In order to do baseplan refresh, this Builder must be setup with just-enough packages to enable all the building of the baseplans.  One way to achieve this has been to:  
- source all of the packages in the core-plans/base-plans.txt file to obtain a list of all $pkg_deps **AND** $pkg_build_deps defined for every baseplan.  Using this sorted and de-duped list of dependencies...
- ``hab pkg download`` all necessary artefacts, not only the dependencies for runtime but also for …
=> [base-plans.txt] Update base-plans.txt to ensure full path to habitat plan file

hugo/plan.sh
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.63.2

sqlite/plan.sh, sqlite/tests/test.bats, sqlite/tests/test.sh
This fixes the version specification in the sqlite plan, adds a dist_version, and adds tests.
=> [sqlite] Update sqlite to 3.31.1, change version spec, add tests

vault/plan.sh
Hello all,
This PR updates vault to version 1.3.2.
To test this, please run
```
hab pkg build vault
```
```
✓ Help command
```
=> [Vault] Upgrading Vault to 1.3.2

MAINTAINERS.md, docs/dev/policy_documents/merging-and-promoting-conventions.md
Graham Wilson identified a current problem with core-plan reviews [on slack](https://habitat-sh.slack.com/archives/CGS0MA3HV/p1579652201003400): it often takes a long time to get a PR reviewed, merged, and promoted.  His proposal is in effect that for certain 'veteran' core-plan contributors and for a subset of plans, the veteran should be able to merge and promote his plan if after some time (7+ days) there has been no feedback or movement.
This is a basic policy draft document.  Please add any more detail or questions to additionally answer.
=> [doc] Add policy for merging and promotion

php/plan.sh
```
hab pkg build php
```
```
✓ Libzip is supported.
```
=> [php] Update PHP to 7.4.2

nmap/plan.sh, nmap/tests/test.bats, nmap/tests/test.sh
Hello all,
This PR updates nmap to version 7.80.
To test this, please run
```
hab pkg build nmap
```
```
```
=> [nmap] Upgrading nmap to 7.80 and added tests

memcached/plan.sh
```
hab pkg build memcached
```
```
✓ Help command
```
=> [memcached] Update memcached to 1.5.22

php/plan.sh
This corrects php's deps to only depend on core packages.
=> [php] Correct pkg_deps

subversion/plan.sh, subversion/tests/test.bats, subversion/tests/test.sh
* Update version
* Add tests
* requires #3218 to be merged and promoted first
```
hab pkg build subversion
```
```
✓ Help command
✓ Create repository
```
=> [subversion] Update subversion to 1.13.0, add tests

lz4/plan.sh, lz4/tests/test.bats, lz4/tests/test.sh
```
hab pkg build lz4
```
```
✓ Help command
```
=> [lz4] Update lz4 to 1.9.2, add tests

inotify-tools/plan.sh, inotify-tools/tests/test.bats, inotify-tools/tests/test.sh
```
hab pkg build inotify-tools
```
```
```
=> [inotify-tools] Update inotify-tools to 3.20.2.2, add tests, update upstream URL

.bldr.toml, openssl11/README.md, openssl11/ca-dir.patch, openssl11/plan.sh, openssl11/tests/test.bats, openssl11/tests/test.sh
Some software only works with OpenSSL 1.1.0.
Differences from core/openssl:
- `ca-dir.patch` updated to match source
- FIPS configuration removed as OpenSSL 1.1.0 does not support FIPS.
- Stage 1 configuration commented until we decide to move to openssl
1.1.0 as our base version.
=> [openssl11] Add new plan for OpenSSL 1.1.0

ed/plan.sh, ed/tests/test.bats, ed/tests/test.sh
ed: hab-plan-build cleanup
ed:
ed: Source Path: /hab/cache/src/ed-1.16
ed: Installed Path: /hab/pkgs/ssd/ed/1.16/20200225003545
ed: Artifact: /src/results/ssd-ed-1.16-20200225003545-x86_64-linux.hart
ed: Build Report: /src/results/last_build.env
ed: SHA256 Checksum: 7b178f8eaea3d26b59bace1f3d12aca2656b31aff9b27bd377bc3f28ec485f7d
ed: Blake2b Checksum: a726f6a587dfee62078b26157ef21a3c2233aafafbca804b6816f574bf7c204f
ed:
ed: I love it when a plan.sh comes together.
ed:
ed: Build time: 0m24s
[3][default:/src:0]# # /hab/pkgs/ssd/ed/1.16/20200225003545/bin/ed --version
GNU ed 1.16
Copyright (C) 1994 Andrew L. Moore.
Copyright (C) 2020 Antonio Diaz Diaz.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute …
=> [ed] Update to 1.16

bind/plan.sh
```
hab pkg build bind
```
```
✓ Dig
✓ Host
✓ ARPAname
✓ DNSSec Keygen
```
=> [bind] Update bind to 9.16.0

gradle/plan.sh, gradle5/plan.sh
Both gradle and gradle5 updated in this PR.
```
hab pkg build gradle
```
```
✓ Run A Scan With Gradle
```
=> [gradle] Update gradle to 5.6.4

.expeditor/config.yml
This should mute the welcome messages for PRs opened by Habitat and core-plans maintainers. 
=> [ci] Don't send welcome message to maintainers

sqlserver-ha-ag/hooks/init, sqlserver-ha-ag/hooks/run
This is strictly adding comments to the sqlserver-ha-ag plan. So that potential customers/users can understand more clearly what they are doing.
=> [sqlserver-ha-ag] add extensive comments in sql ha hooks

curl-static-musl/plan.sh, curl/plan.sh
This updates curl and curl-static-musl
```
hab pkg build curl
```
```
✓ Curl against https sites
```
=> [curl] Update curl to 7.68.0

go/plan.ps1, go/plan.sh
This updates go to the latest release and uses a much more recent go
release to bootstrap itself. It fixes all but one error in the go test
suite, which fails because the test strips the `LD_LIBRARY_PATH` before
attempting to build cgo tests in a temporary directory.
* Update go to 1.14
* Update go bootstrap from 1.7 to 1.13.7
* Fix several existing test failures in the go distribution tests
* Fix shellcheck errors in plan.sh
=> [go] Update go to 1.14

consul/plan.sh
=> [consul] Update consul to 1.7.1

hugo/plan.sh
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.67.1

terraform/plan.sh
=> [terraform] Update terraform to 0.12.23

jenkins/plan.sh
```
hab pkg build __PKGNAME__
```
```
✓ jenkins binary version matches 2.204.5
```
=> [jenkins] Update jenkins to 2.204.5

.bldr.toml, ruby27/README.md, ruby27/plan.sh, ruby27/tests/test.sh
This is required for Chef Infra Client 16.0 development and should be considered a blocker for this quarters work.
=> [ruby27] Add Ruby 2.7

go/plan.sh
Creating this to fix refresh build for core/go according to issue https://github.com/habitat-sh/core-plans/issues/3266
=> [go] Revert latest dependency update so that core/go depends on core/go17

.refresh/remaining_plans_passed.txt
=> [refresh/2020q1] Remove core/bazel because it has been deprecated

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, pax-utils/plan.sh
Changes pax-utils to 1.2.5 to avoid dist location issue.
=> [refresh][pax-utils] - Upgrade pax utils to version 1.2.5

serf/pass-env-to-scons.patch, serf/plan.sh
- Set the path to ZLIB via the ZLIB flag
- Set CFLAGS and LINKFLAGS via the command line rather than via a
patch. This seems to fix a bug where scons was constructing invalid
arguments to gcc.
Fixes #3294
=> [refresh2020q1][serf]: fix missing zlib header in build

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, logback/plan.sh
Fixes #3312
This changes logback to use uncompressed download sorces for files, similarly to Rust/Bash pattern of downloading files.
Signed-off-by: MindNumbing SMarshall@chef.io
=> [refresh2020q1][logback] fix logback pkg source

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, buildkite-agent/plan.sh
This PR adds steps required to generate the go module list, and vendor file to fix an issue that was occuring with the latest updates to buildkite-agent.
Fixes #3287
=> [refresh2020q1][buildkite-agent] - Fix buildkite-agent go vendering

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, gox/plan.sh
This PR adds steps required to generate the go module list, and vendor file to fix an issue that was occuring with the latest updates to gox.
Fixes #3284
=> [refresh2020q1][gox] - Fix gox go vendering

.refresh/remaining_plans_failed.txt, .refresh/remaining_plans_passed.txt, img/plan.sh
Minor version bump from 0.5.4 -> 0.57
Adds steps to replace a module that is causing pseudo version issues and to get a module that wasn't included.
Fixes #3291
=> [refresh2020q1][img] - Fixing go pseudo version issue

imagemagick/plan.sh
ImageMagick uses `ImageMagick-<MAJOR VERSION>` to install its headers. This PR updates the metadata to reflect the major version bump from 6 to 7. 
=> [ImageMagick] Update include path to align with major version bump

ruby/plan.sh, ruby24/plan.sh, ruby25/plan.sh, ruby26/plan.sh, ruby27/plan.sh
* [ruby] Still using ruby 2.5 for major version, but now on latest 2.5.8 point release
* [ruby24] Upgrade to latest 2.4.10
* [ruby25] Upgrade to latest 2.5.8
* [ruby26] Upgrade to latest 2.6.6
* [ruby27] Upgrade to latest 2.7.1
As a note, Ruby 2.4.10 is now [out of support entirely](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/) so won't receive further updates.
=> [ruby][ruby24][ruby25][ruby26][ruby27] Upgrade all rubies for latest point releases

grpcurl/plan.sh, grpcurl/tests/test.bats
The plans that rely on the go scaffolding are producing broken builds
as they rely on glibc implicitly. We can easily build static binaries
with go.
=> Static grpcurl build

opa/plan.sh
The plans that rely on the go scaffolding are producing broken builds
as they rely on glibc implicitly.
Signed-off-by: Jay Mundrawala <jmundrawala@chef.io>
=> Static opa build

bin/ci/build-and-run-tests.sh, bin/ci/verify-pr-build.sh
This adds a change that wraps the habitat studio version check within "hab studio run" to ensure that it works locally on macs.
=> [ci] - Fixing habitat studio version checks in ci

opa/plan.sh
ℹ️ Release notes are here: https://github.com/open-policy-agent/opa/releases
(We're a few versions behind, so I'm not accumulating all that has changed here.)
=> [opa] bump 0.16.2 -> 0.19.2

sccache/plan.sh
```
hab pkg build sccache
```
```
✓ Help command
✓ Listening on port 4226
```
=> [sccache] Update sccache to 0.2.13

yarn/plan.ps1, yarn/plan.sh
```
```
```
✓ Help command
```
=> [yarn] Update yarn to 1.22.4

systemd/plan.sh
```
hab pkg build systemd
```
```
✓ systemctl matches version 245
```
=> [systemd] Update systemd to v245

memcached/plan.sh
```
hab pkg build memcached
```
```
✓ Help command
```
=> [memcached] Update memcached to 1.6.5

dnsmasq/plan.sh
Addresses [CVE-2019-14834](https://nvd.nist.gov/vuln/detail/CVE-2019-14834)
```
hab pkg build dnsmasq
```
```
✓ dnsmasq service is running
✓ dnsmasq successfully finds debian.org
✓ dnsmasq binary matches version 2.81
✓ dnsmasq binary test returns success
```
=> [dnsmasq] Update dnsmasq to 2.81

bind/plan.sh
```
hab pkg build bind
```
```
✓ Dig
✓ Host
✓ ARPAname
✓ DNSSec Keygen
```
=> [bind] Update bind to 9.17.1

e2fsprogs/plan.sh
```
hab pkg build e2fsprogs
```
```
✓ uuidgen works
```
=> [e2fsprogs]  Update e2fsprogs to 1.45.6

cerebro/plan.sh
```
hab pkg build cerebro
```
```
```
=> [cerebro] Update cerebro to 0.9.0

composer/plan.sh
```
hab pkg build composer
```
```
✓ Help command
```
=> [composer] Update composer to 1.10.5

sassc/plan.sh
```
hab pkg build sassc
```
```
✓ Package and library Version matches
✓ Help command
```
=> [sassc] Update sassc to 3.6.1, use do_verify for download verification

bin/check-bins.sh
This script now
- Makes sure all resolved libs are from a package in DEPS
- Makes sure any interpreter built into the ELF file is from a package in DEPS
- Warns if RPATH isn't set in an executable
For some reason, we didn't use shell arrays here originally so I kept
with that style, but we could probably benefit from using arrays in
this script. However, this is on the edge of what I think we might
want to built into its own tool.
=> [bin/check-bins.sh] Add more safety checks

libtiff/plan.sh
Addresses [CVE-2019-14973](https://nvd.nist.gov/vuln/detail/CVE-2019-14973)
```
hab pkg build libtiff
```
=> [libtiff] Update libtiff to 4.1.0

bundler/plan.sh
This is a major version number jump from bundler 1.17.3 to bundler 2.1.4.
There are some docs and gotchas listed on the Bundler website <https://bundler.io/guides/bundler_2_upgrade.html> around this upgrade.
In theory bundler 2 switches internal behaviour to run bundler 1.x if the `Gemfile.lock` specifies that version, so this change is backwards compatible. We don't have plans for below ruby 2.3, so we shouldn't be affected by the minimum version change.
=> [bundler] Upgrade to release 2.1.4

libarchive/plan.ps1, libarchive/plan.sh
This resolves nearly a dozen security issues and two published CVEs plus
it fixes critical bugs in the archive parsing. This has been updated in Chef Infra Client and we need this updated in core plans so that effortless packages match.
```
libarchive: hab-plan-build cleanup
libarchive:
libarchive: Source Path: /hab/cache/src/libarchive-3.4.2
libarchive: Installed Path: /hab/pkgs/tas50/libarchive/3.4.2/20200402054048
libarchive: Artifact: /src/libarchive/results/tas50-libarchive-3.4.2-20200402054048-x86_64-linux.hart
libarchive: Build Report: /src/libarchive/results/last_build.env
libarchive: SHA256 Checksum: 0bb8113e002e2d09dcc79b1db19a2bb9fa5752df46df2e8277b7287459d8836e
libarchive: Blake2b Checksum: 2affe8038489a2484c4f274de8ac5cbd305c4f02bc2d6b434067dabe6149ac0c
libarchive: …
```
=> [libarchive] Update libarchive to 3.4.2

docker/plan.sh, docker/tests/test.bats
Docker has renamed some of its binaries so `docker*` won't work anymore
fixes #3355
Signed-off-by: DekusDenial <dekusdenial@hotmail.com>
=> Fix missing binaries and update docker@19.03.8

nghttp2/plan.sh
The in-development check-bin script found:
```
/hab/pkgs/core/nghttp2/1.39.2/20200310022350/lib/libnghttp2.so.14.18.0:
core/glibc/2.29/20200305172459 is not listed in TDEPS but is used as a dependency
```
=> [nghttp2] link against glibc, update to 1.40.0

devicemapper/plan.sh, devicemapper/tests/test.bats, devicemapper/tests/test.sh
This allows packages that depend on `core/devicemapper` to configure themselves properly during build.
=> [devicemapper] Add pkg-config support

cmake/plan.ps1, cmake/plan.sh
The changelog for this release can be found here:
https://cmake.org/cmake/help/v3.17/release/3.17.html
More specifically, this bug
https://gitlab.kitware.com/cmake/cmake/-/issues/20065
is supposedly fixed. I think that bug is the most proximate cause for
the build failures of core/sentinel.
=> [cmake] Upgrade to 3.17.2

runc/plan.sh, runc/tests/test.bats, runc/tests/test.sh
In addition to updating to the current version of `runc`, this commit
addresses a handful of problems with the `runc` plan.
First, despite a `pkg_version` being specified in the plan, the build
logic from the Go scaffolding resulted in unspecified code being
built. You would end up building whatever happened to be on the master
branch of https://github.com/opencontainers/runc at the time of your
build.
Now, the download logic has been overridden to grab the code on the
branch specified by `pkg_version` so we can a) reliably build the same
thing over and over, and b) have `pkg_version` correspond to the
contents of the resulting package.
Second, we now create a static binary.
Third, the installation logic of the Go scaffolding has been
overridden. Previously, despite running `make` in the …
=> [runc] Update to runc 1.0.0-rc10

.bldr.toml, buildah/README.md, buildah/plan.sh, buildah/tests/test.bats, buildah/tests/test.sh
Before this merges, the following PRs will need to be merged, and their packages promoted to `stable` first:
=> [buildah] Add new core/buildah plan

CODEOWNERS, docs/dev/README.md, docs/dev/guide_documents/base-plans.md
> As a maintainer of core-plans I want to understand why some plans are considered
'base plans', and why only some of those can be updated outside of a refresh,
and why some need to wait.
> As a user of core plans, I want to know what the base plans refresh is, why
it is necessary and what it entails.
This PR attempts to explain at a high level what a base plan is and why they require
extra care when merging. It also breaks apart which plans require a refresh to be
updated, and why, and which can be updated outside of a refresh.
Finally, the process around the refresh, why it exists and how it might change as
Builder is able to handle more complex workloads is covered.
=> [Docs] Add guide document for base plans

python2/plan.ps1, python2/plan.sh
This updates python2 from 2.7.15 to 2.7.18.
This will be the [last release of python2](https://pythoninsider.blogspot.com/2020/04/python-2718-last-release-of-python-2.html). 🎉 
=> [python2] - Updating python2 to 2.7.18

.bldr.toml
Ruby24 was deprecated by #3309
This will remove it from the .bldr.toml to ensure it isn't linked with builder
=> [ruby24] Removing ruby24 from bldr.toml

packer/plan.ps1, packer/plan.sh
```
hab pkg build packer
```
```
✓ Help command
```
=> [packer] Update packer to 1.5.6

openresty/plan.sh, openresty/tests/test.sh
```
hab pkg build openresty
```
```
```
=> [openresty] Update openresty to 1.15.8.3, update tests

curl-static-musl/plan.sh, curl-static-musl/tests/test.bats, curl-static-musl/tests/test.sh, curl/plan.sh, curl/tests/test.bats, curl/tests/test.sh
Also tried to deduplicate the test scripts. Haven't found a simple way
to do the same to test.bats.
=> [curl] bump 7.68.0 -> 7.70.0

kafka2/plan.sh
Builder reads the file without evaluating it to assert that the pkg_name is a valid set of characters. Since this isn't being evaluated in a bash context, it is read as a string literal and doesn't support variable interpolation in pkg_name.
=> [kafka2] Update pkg_name

terraform/plan.sh
=> [terraform] Update terraform to 0.12.26

grafana/plan.sh
```
hab pkg build grafana
```
```
```
=> [grafana] Update grafana to 7.0.1

sbt/plan.sh
```
hab pkg build sbt
```
```
✓ sbt matches version 1.3.12
```
=> [sbt] Update sbt to 1.3.12

strace/plan.sh
```
hab pkg build strace
```
```
✓ Can strace
```
=> [strace] Update strace to 5.7

elasticsearch/default.toml, elasticsearch/hooks/run
In testing some other packages we found that the elasticsearch package does not run out of box. These changes to the default value allow the service to start in a standalone state without any extra configuration. They match the default configuration provided by upstream elasticsearch config files.
Signed-off-by: Ian Henry <ianjhenry00@gmail.com>
=> [elasticsearch] Corrects config issues that prevent package from running out of the box

dsc-core/DSCCore.psm1, dsc-core/README.md, dsc-core/plan.ps1, dsc-core/tests/test.pester.ps1
fixes #3364, #2554 
This PR makes the following changes:
* `Set` calls to the LCM are retryable. The LCM, by default, will perform a "consistency check" every 15 minutes and shortly after a restart. Exactly when these are invoked is completely beyond Habitat's or a service hook's control. While we have waited for the LCM to be in an `idle` state before performing a `set` (it is `busy` during a consistency check), we have seen cases where we find it is `idle` but then begins the check before the `set`. So this takes the extra measure of retrying and waiting again for an `idle` state before the next attempt.
* `Get` calls on LCM state are also now retryable. I more rare case is where we check the state of the LCM while another hook might be performing a `set` which results in an error.
* …
=> [dsc-core] fix concurrency issues

hugo/plan.sh
```
```
```
✓ Help command
```
=> [hugo] Update hugo to 0.72.0

filebeat/plan.sh
```
hab pkg build filebeat
```
```
✓ Help command
```
=> [filebeat] Update filebeat to 7.7.1

windows-10-sdk/plan.ps1
Currently plans that consume this package for building native apps need to magically know to set this or go through the pain of debugging msbuild target files which might lead them to this knowledge.
=> [windows-10-sdk] set WindowsSdkDir_10 so msbuild uses this package path

visual-build-tools-2017/plan.ps1
Setting these variables is ideal in a habitat based build where we provide a visual studio and windows sdk environment not installed via the visual studio installers which populate the registry with lots of base paths that will override many environment variable set paths. This also ensures that PATH, LIB and INCLUDE dirs are all honored.
Many windows native builds will break without these set and few users of msbuild will know to set these without some weeping and gnashing of teeth.
=> [visual-build-tools-2017] Ensure msbuild honors environment variables above registry

.bldr.toml, dotnet-45-dev-pack/plan.ps1, dotnet-462-dev-pack/plan.ps1, dotnet-47-dev-pack/plan.ps1
When using the visual studio build tools package's `msbuild` to build .Net projects that use any of our dev pack packages, one needs to know to set `TargetFrameworkRootPath` to the right path in those packages which very few will know to do.
This ensures that when declaring a dependency on these packages, `msbuild`'s ability to find the correct reference assemblies path will "just work."
=> add TargetFrameworkRootPath variable to all .net dev packs

postgresql11-client/plan.ps1, postgresql11-client/plan.sh, postgresql11/plan.sh
Updated postgresql 11 from 11.2 to 11.8
As a general reminder, PostgreSQL changed versioning after 9.x, and is 11.8 would be equivalent from changing 9.6.2 to 9.6.5.
=> [postgresql11] Upgraded postgresql 11 to 11.8

.github/stale.yml
This change will add stale bot to the core-plans repo.
This will mark any pr as stale if it hasn't received any update for a period of 90 days.
After a further 14 days the stale pr will be closed.
Exemptions to this are any pr with the following labels:
- c-base-plan
- r-refresh
- t-security
- type: Design Proposal
=> [meta] Adding stalebot to core-plans

kubectl/plan.sh, kubectl/tests/test.bats, kubectl/tests/test.sh
Replaces #2657 because its branch name was tied to a version, this PR bumps to the latest stable release and includes a basic test
=> [kubectl] update to 1.18.5 and add test

protobuf-cpp/plan.sh, protobuf/plan.ps1, protobuf/plan.sh
This brings us up to date with the latest upstream version.  The
changelog is a bit too long to include here:
https://github.com/protocolbuffers/protobuf/releases
=> [protobuf, protobuf-cpp] Upgrade to 3.12.3

netdata/plan.sh, netdata/tests/test.sh
```
hab pkg build netdata
```
```
✓ Help command
✓ Listening on port 19999
```
=> [netdata] Update netdata to 1.22.1

boringssl/tests/test.bats, boringssl/tests/test.sh
Adds a test to run sample command for boringssl.
```bash
hab pkg build boringssl; source results/last_build.env; hab studio run "./${pkg_name}/tests/test.sh ${pkg_ident}"
```
> ★ Install of mindnumbing/boringssl/3538/20200710135239 complete with 1 new packages installed.
> ✓ Encodes successfully
>
>1 test, 0 failures
=> [boringssl] Adds a test for boringssl

scaffolding-ruby/doc/reference.md, scaffolding-ruby/lib/scaffolding.sh
This PR is related to #2837 
I need to be able to choose the version of node, in my case I need `core/node10` but the scaffolding will always default to `core/node`.
This PR updates to the `_detect_execjs` function to search the pkg_deps array to see if a node package is already defined, if not then it will add `core/node` to `pkg_deps` array as it currently does.
Hope that's OK
Gary
Signed-off-by: Gary Bright <digitalgaz@hotmail.com>
=> [scaffolding-ruby] allow user to choose node package

scaffolding-ruby/lib/scaffolding.sh
I noticed that running `rake -P --trace | grep -q '^rake assets:precompile$'` would error for me with a broken pipe, 
I noticed the same thing within studio when it got down to the scaffolding_run_assets_precompile() function and reported it in issue #2837
This pr splits out the command and the evaluation of the grep return code.
Hope that's ok
Best Regards
Gary
Signed-off-by: Gary Bright <digitalgaz@hotmail.com>
=> [scaffolding-ruby] fix broken pipe

corretto/plan.ps1, corretto/plan.sh
This provides a minor patch update to the corretto binary package. It also fixes a minor issue with the correct SPDX license, which should be `GPL-2.0-only WITH Classpath-exception-2.0`, since it has a classpath exception in the license. If you are unfamiliar with SPDX, you can find it here: https://spdx.org/licenses/
You can test with:
`hab studio build corretto`
=> [corretto] Update corretto to 11.0.8.10.1

.expeditor/generate_verify_pipeline.sh
It appears that expeditor now checks whether or not the generator
script passes shellcheck.
=> ci: shellcheck pipeline generator

.bldr.toml, erlang22/README.md, erlang22/plan.sh, erlang22/tests/test.bats, erlang22/tests/test.sh
This adds a core-plan for the latest version of erlang 22 to help with work around shipping a more modern Chef Server within Automate.
Signed-off-by: Thomas Cate <tcate@chef.io>
=> [erlang22] Added plan for erlang22.3

opa/plan.sh
Release notes for the bumped versions:
- https://github.com/open-policy-agent/opa/releases/tag/v0.23.0
- https://github.com/open-policy-agent/opa/releases/tag/v0.23.1
=> [opa] bump 0.22.0 -> 0.23.1

helm/.shellcheckrc, helm/README.md, helm/plan.sh
This PR upgrades helm to version 3.2.4. 
I also tried to align the `plan.sh` and `README` to some of the better maintained plans (like prometheus).
A couple notes:
- `core/mercurial` was removed because I couldn't see anywhere that required it as a dependency.
- `core/which` was removed in favour of `command`
- go get is used instead of a github archive tarball. Not exactly why this was done but when I build it from the github tarball source the `helm version` shows "unreleased" so I left `do_download` as is.
=> [helm] Upgrade helm to 3.2.4

pax-utils/plan.sh
This updates pax-utils to latest version, v1.2.5 no longer available at source.
=> [pax-utils] update 1.2.5 -> 1.2.6

curl-static-musl/plan.sh
This adds the checksum from curl to curl-static-musl.
=> [curl-static-musl] - Add checksum

openresty/plan.sh
```
hab pkg build openresty
```
```
```
=> [openresty] Update OpenResty to 1.17.8.2

zookeeper/plan.sh
This updates zookeeper to the latest version so we can still use the upstream
=> [Refresh2020Q3][zookeeper] Update Zookeeper to latest version

MAINTAINERS.md
Moving @eeyun to alumni as requested in #3488.
=> Moving Ian to alumni

dex/plan.sh
This is now modelled after opa/plan.sh, downloading the tarball, working with
that.
Since 2.25.0, dex no longer vendors its dependencies, so there's no need to
tender any GOPATH.
To have `dex version` return its version correctly, this fiddles with one of the
scripts.  However, if it means we don't have to mess with `go install`, `go
build`, and the proper ldflags, but can use the make target instead, I think
that's preferable.
----
https://github.com/dexidp/dex/releases/tag/v2.25.0
=> [dex] bump v2.24.0 -> v2.25.0, simplify plan.sh

dotnet-core-sdk/plan.ps1
If building a .Net Core app via `MSBuild` insterad of the `dotnet` cli, the `MSBuildSDKsPath` must be set or else MSBuild will try to locate a shared (non-habitat installed) .net core sdk.
=> set MSBuildSDKsPath in dotnet core sdk runtime environment

MAINTAINERS.md
=> Remove Steven Danna from Active Maintainers

.bldr.toml, node/plan.ps1, node14/README.md, node14/plan.ps1, node14/tests/test.pester.ps1, node14/tests/test.ps1
I'm basically copying the work done by @msorens in https://github.com/habitat-sh/core-plans/pull/3158 so that we can bump Automate's node version up as well. (see https://github.com/chef/automate/issues/4698)
node 14.16.0 is now in the "active LTS" phase, so suitable for production use.
SHAs extracted from:
https://nodejs.org/download/release/latest-v14.x/SHASUMS256.txt
General Reference:
https://nodejs.org/en/about/releases/
=> Update node to 14.16.0

libassuan/plan.sh, libksba/plan.sh
Please review. For gpgme package, We need libassuan min version of 2.5.0 and libksba min version 1.3.5
=> Bumped version 2.4.2 -> 2.5.5

.bldr.toml
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Adds kernel2 target for package `core/ruby30` to support additional deployment targets.
This is to support adding kernel2 support with `core/ruby30` for `chef/chef-infra-client`
=> Adds kernel2 bldr target for ruby30 plan

acbuild/plan.sh
Looks like this is needed if using go 1.16 for this source.
=> use GO111MODULE=auto in acbuild

mercurial/plan.sh
Updated pkg_version 3.9.1 -> 3.9.2 in support of 2021 Q2 core plans refresh.
=> Update mercurial Plan Package Version

unibilium/plan.sh
Updated pkg_version "1.2.0" -> "1.2.1" in support of 2021 Q2 core plans refresh.
=> Update unibilium Plan Package Version

tomcat8/plan.sh
Updated pkg_version 8.5.9 -> 8.5.64 in support of 2021 Q2 core plans refresh.
=> Update tomcat8 Plan Package Version

benchmark/plan.sh, tmux/plan.sh, tmux/tests/test.bats
Updated pkg_version 3.0a -> 3.1c in support of 2021 Q2 core plans refresh.
=> Update tmux Plan Package Version

telegraf/plan.sh
Updated pkg_version 1.12.2 -> 1.18.0 in support of 2021 Q2 core plans refresh.
=> Update telegraf Plan Package Version

tap-xunit/plan.sh
Updated pkg_version 2.3.0 -> 2.4.1 in support of 2021 Q2 core plans refresh.
=> Update tap-xunit Plan Package Version

swig/plan.sh
Updated pkg_version 3.0.10 -> 3.0.12 in support of 2021 Q2 core plans refresh.
=> Update swig Plan Package Version

restic/plan.sh
Updated pkg_version "0.9.3" -> "0.12.0" in support of 2021 Q2 core plans refresh.
=> Update restic Plan Package Version

protobuf-c/plan.sh
Updated pkg_version 1.3.2 -> 1.3.3 in support of 2021 Q2 core plans refresh.
=> Update protobuf-c Plan Package Version

postgresql96-client/plan.sh
Updated pkg_version 9.6.11 -> 9.6.21 in support of 2021 Q2 core plans refresh.
=> Update postgresql96-client Plan Package Version

postgresql95-client/plan.sh
Updated pkg_version 9.5.13 -> 9.6.21 in support of 2021 Q2 core plans refresh.
=> Update postgresql95-client Plan Package Version

postgresql94-client/plan.sh
Updated pkg_version 9.4.18 -> 9.4.26 in support of 2021 Q2 core plans refresh.
=> Update postgresql94-client Plan Package Version

postgresql93-client/plan.sh
Updated pkg_version 9.3.23 -> 9.3.25 in support of 2021 Q2 core plans refresh.
=> Update postgresql93-client Plan Package Version

postgresql11-client/plan.sh
Updated pkg_version 11.8 -> 11.11 in support of 2021 Q2 core plans refresh.
=> Update postgresql11-client Plan Package Version

pax-utils/plan.sh
Updated pkg_version 1.2.6 -> 1.2.9 in support of 2021 Q2 core plans refresh.
=> Update pax-utils Plan Package Version

utf8proc/plan.sh
Updated pkg_version "2.4.0" -> "2.6.1" in support of 2021 Q2 core plans refresh.
=> Update utf8proc Plan Package Version

openldap/plan.sh
Updated pkg_version 2.4.46 -> 2.4.58 in support of 2021 Q2 core plans refresh.
=> Update openldap Plan Package Version

nspr/plan.sh
Updated pkg_version 4.21 -> 4.30 in support of 2021 Q2 core plans refresh.
=> Update nspr Plan Package Version

nginx-prometheus-exporter/plan.sh
Updated pkg_version "0.4.2" -> "0.9.0" in support of 2021 Q2 core plans refresh.
=> Update nginx-prometheus-exporter Plan Package Version

netcat-openbsd/plan.sh
Updated pkg_version 1.105 -> 1.217 in support of 2021 Q2 core plans refresh.
=> Update netcat-openbsd Plan Package Version

ncdu/plan.sh
Updated pkg_version 1.11 -> 1.15 in support of 2021 Q2 core plans refresh.
=> Update ncdu Plan Package Version

monit/plan.sh
Updated pkg_version "5.25.2" -> "5.27.2" in support of 2021 Q2 core plans refresh.
=> Update monit Plan Package Version

mksh/plan.sh
Updated pkg_version "R56c" -> "R59c" in support of 2021 Q2 core plans refresh.
=> Update mksh Plan Package Version

man-pages/plan.sh
Updated pkg_version 5.01 -> 5.11 in support of 2021 Q2 core plans refresh.
=> Update man-pages Plan Package Version

libzip/plan.sh
Updated pkg_version 1.5.1 -> 1.7.3 in support of 2021 Q2 core plans refresh.
=> Update libzip Plan Package Version

libvterm/plan.sh
Updated pkg_version "0+bzr681" -> "0+bzr726" in support of 2021 Q2 core plans refresh.
=> Update libvterm Plan Package Version

libtermkey/plan.sh
Updated pkg_version "0.20" -> "0.22" in support of 2021 Q2 core plans refresh.
=> Update libtermkey Plan Package Version

libtalloc/plan.sh
Updated pkg_version "2.1.14" -> "2.3.2" in support of 2021 Q2 core plans refresh.
=> Update libtalloc Plan Package Version

libssh2/plan.sh
Updated pkg_version 1.8.0 -> 1.9.0 in support of 2021 Q2 core plans refresh.
=> Update libssh2 Plan Package Version

libressl/plan.sh
Updated pkg_version 2.4.4 -> 2.9.2 in support of 2021 Q2 core plans refresh.
=> Update libressl Plan Package Version

libpq/plan.sh
Updated pkg_version 9.6.8 -> 9.6.21 in support of 2021 Q2 core plans refresh.
=> Update libpq Plan Package Version

libpcap/plan.sh
Updated pkg_version 1.8.1 -> 1.10.0 in support of 2021 Q2 core plans refresh.
=> Update libpcap Plan Package Version

krb5/plan.sh
Updated pkg_version 1.14.3 -> 1.19.1 in support of 2021 Q2 core plans refresh.
=> Update krb5 Plan Package Version

libtirpc/plan.sh
Updated pkg_version "1.0.3" -> "1.3.1" in support of 2021 Q2 core plans refresh.
=> Update libtirpc Plan Package Version

libnsl/autogen.patch, libnsl/plan.sh
Updated pkg_version "1.2.0" -> "1.3.0" in support of 2021 Q2 core plans refresh.
=> Update libnsl Plan Package Version

nasm/plan.sh
Updated pkg_version 2.12.02 -> 2.15.05 in support of 2021 Q2 core plans refresh.
=> Update nasm Plan Package Version

libimagequant/plan.sh
Updated pkg_version 2.12.5 -> 2.14.1 in support of 2021 Q2 core plans refresh.
=> Update libimagequant Plan Package Version

libidn/plan.sh
Updated pkg_version 1.35 -> 1.36 in support of 2021 Q2 core plans refresh.
=> Update libidn Plan Package Version

libfastjson/plan.sh
Updated pkg_version 0.99.8 -> 0.99.9 in support of 2021 Q2 core plans refresh.
=> Update libfastjson Plan Package Version

libev/plan.sh
Updated pkg_version 4.31 -> 4.33 in support of 2021 Q2 core plans refresh.
=> Update libev Plan Package Version

libcap-ng/plan.sh
Updated pkg_version 0.7.8 -> 0.8.2 in support of 2021 Q2 core plans refresh.
=> Update libcap-ng Plan Package Version

leveldb/plan.sh
Updated pkg_version "1.20" -> "1.23" in support of 2021 Q2 core plans refresh.
=> Update leveldb Plan Package Version

kmod/plan.sh
Updated pkg_version "24" -> "28" in support of 2021 Q2 core plans refresh.
=> Update kmod Plan Package Version

snappy/plan.sh
Updated pkg_version 1.1.4 -> 1.1.8 in support of 2021 Q2 core plans refresh.
=> Update snappy Plan Package Version

json-c/plan.sh
Updated pkg_version 0.13.1 -> 0.15 in support of 2021 Q2 core plans refresh.
=> Update json-c Plan Package Version

jfrog-cli/plan.sh
Updated pkg_version 1.7.1 -> 1.43.2 in support of 2021 Q2 core plans refresh.
=> Update jfrog-cli Plan Package Version

haproxy/plan.sh
Updated pkg_version 2.2.2 -> ~2.2.11~ 2.2.14 in support of 2021 Q2 core plans refresh.
**Update: 2020/05/03 Siraj:** Updated version + fixed tests
=> Update haproxy Plan Package Version

gsl/plan.sh
Updated pkg_version 2.3 -> 2.6 in support of 2021 Q2 core plans refresh.
=> Update gsl Plan Package Version

gperftools/plan.sh
Updated pkg_version 2.7 -> 2.9.1 in support of 2021 Q2 core plans refresh.
=> Update gperftools Plan Package Version

govc/plan.sh
Updated pkg_version "0.19.0" -> "0.24.1" in support of 2021 Q2 core plans refresh.
=> Update govc Plan Package Version

.bldr.toml, googlemock/plan.sh
Updated pkg_version "1.8.0" -> "1.10.0" in support of 2021 Q2 core plans refresh.
=> Update googlemock Plan Package Version

libjpeg-turbo/plan.sh
Updated pkg_version 1.5.0 -> 1.5.3 in support of 2021 Q2 core plans refresh.
=> Update libjpeg-turbo Plan Package Version

unixodbc/plan.sh
Updated pkg_version 2.3.6 -> 2.3.9 in support of 2021 Q2 core plans refresh.
=> Update unixodbc Plan Package Version

freetds/plan.sh
Updated pkg_version 1.00.109 -> 1.2.18 in support of 2021 Q2 core plans refresh.
=> Update freetds Plan Package Version

flatbuffers/plan.sh, flatbuffers/tests/test.bats
Updated pkg_version 1.11.0 -> 1.12.0 in support of 2021 Q2 core plans refresh.
=> Update flatbuffers Plan Package Version

fish/plan.sh
Updated pkg_version "2.5.0" -> "2.7.0" in support of 2021 Q2 core plans refresh.
=> Update fish Plan Package Version

mage/plan.sh, mage/tests/test.bats
Updated pkg_version 1.9.0 -> 1.11.0 in support of 2021 Q2 core plans refresh.
=> Update mage Plan Package Version

foulkon/glide.patch, foulkon/plan.sh
[One of the weirdest ones i've seen](https://github.com/Masterminds/glide/issues/1077) - glide's (a go package manager) website has disappeared. Install it by downloading the install script from source and patching it to hardcode the tag (it references glide.sh to get latest tag). It can then install from the source repository, and we can follow the rest of the install steps.
=> Foulkon Version Bump

libtasn1/plan.sh
Updated pkg_version "4.13" -> "4.16.0" in support of 2021 Q2 core plans refresh.
=> Update libtasn1 Plan Package Version

e2fsprogs/plan.sh
Updated pkg_version 1.45.6 -> 1.46.2 in support of 2021 Q2 core plans refresh.
=> Update e2fsprogs Plan Package Version

libunwind/plan.sh
Updated pkg_version 1.2.1 -> 1.4.0 in support of 2021 Q2 core plans refresh.
=> Update libunwind Plan Package Version

dpkg/plan.sh, dpkg/tests/test.bats
Updated pkg_version 1.19.7 -> 1.20.7.1 in support of 2021 Q2 core plans refresh.
=> Update dpkg Plan Package Version

lttng-ust/plan.sh
Updated pkg_version 2.8.1 -> 2.12.1 in support of 2021 Q2 core plans refresh.
=> Update lttng-ust Plan Package Version

cpio/plan.sh
Updated pkg_version '2.12' -> '2.13' in support of 2021 Q2 core plans refresh.
=> Update cpio Plan Package Version

lz4/plan.sh, lz4/tests/test.bats
Updated pkg_version 1.9.2 -> 1.9.3 in support of 2021 Q2 core plans refresh.
=> Update lz4 Plan Package Version

coreutils-static/plan.sh
Updated pkg_version 8.30 -> 8.32 in support of 2021 Q2 core plans refresh.
=> Update coreutils-static Plan Package Version

compositeproto/plan.sh
Updated pkg_version 0.4 -> 0.4.2 in support of 2021 Q2 core plans refresh.
=> Update compositeproto Plan Package Version

doxygen/plan.sh
Updated pkg_version 1.8.17 -> 1.9.1 in support of 2021 Q2 core plans refresh.
=> Update doxygen Plan Package Version

concourse-fly/plan.sh
Updated pkg_version "4.2.2" -> "4.2.3" in support of 2021 Q2 core plans refresh.
=> Update concourse-fly Plan Package Version

nss/plan.sh
Updated pkg_version 3.44 -> 3.63 in support of 2021 Q2 core plans refresh.
=> Update nss Plan Package Version

ccache/plan.sh
Updated pkg_version 3.5 -> 3.6 in support of 2021 Q2 core plans refresh.
=> Update ccache Plan Package Version

ocaml/plan.sh
Updated pkg_version "4.07.0" -> "4.12.0" in support of 2021 Q2 core plans refresh.
=> Update ocaml Plan Package Version

lzo/plan.sh
Updated pkg_version 2.09 -> 2.10 in support of 2021 Q2 core plans refresh.
=> Update lzo Plan Package Version

buildkite-agent/plan.ps1
Updated pkg_version "3.9.1" -> "3.29.0" in support of 2021 Q2 core plans refresh.
=> Update buildkite-agent Plan Package Version

libuv/plan.sh
Updated pkg_version 1.35.0 -> 1.41.0 in support of 2021 Q2 core plans refresh.
=> Update libuv Plan Package Version

bash-completion/plan.sh
Updated pkg_version 2.9 -> 2.11 in support of 2021 Q2 core plans refresh.
=> Update bash-completion Plan Package Version

dbus/plan.sh
Updated pkg_version "1.13.8" -> "1.13.18" in support of 2021 Q2 core plans refresh.
=> Update dbus Plan Package Version

asciinema/plan.sh, asciinema/tests/test.bats
Version bump & set version explicitly due to `pip search` now being deprecated/disabled:
```
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.
```
=> asciinema Version Bump

tor/plan.sh
Updated pkg_version 0.4.0.5 -> 0.4.5.7 in support of 2021 Q2 core plans refresh.
=> Update tor Plan Package Version

traefik/plan.sh
Updated pkg_version "1.7.7" -> "1.7.28" in support of 2021 Q2 core plans refresh.
=> Update traefik Plan Package Version

tcpdump/plan.sh, tcpdump/tests/test.bats
Updated pkg_version 4.9.3 -> 4.99.0 in support of 2021 Q2 core plans refresh.
=> Update tcpdump Plan Package Version

ruby26/plan.sh
Fixes SSL error in refresh env
=> Adding cacerts to build_deps ruby26, export SSL_CERT_FILE for gem update/install

rebar3/plan.sh
Updated pkg_version 3.11.0 -> 3.14.4 in support of 2021 Q2 core plans refresh.
=> Update rebar3 Plan Package Version

postfix/plan.sh
Updated pkg_version "3.3.2" -> "3.5.9" in support of 2021 Q2 core plans refresh.
=> Update postfix Plan Package Version

openresty/plan.sh
Updated pkg_version 1.17.8.2 -> 1.19.3.1 in support of 2021 Q2 core plans refresh.
=> Update openresty Plan Package Version

netdata/plan.sh
Updated pkg_version 1.22.1 -> 1.29.3 in support of 2021 Q2 core plans refresh.
=> Update netdata Plan Package Version

libxshmfence/plan.sh
Updated pkg_version 1.2 -> 1.3 in support of 2021 Q2 core plans refresh.
=> Update libxshmfence Plan Package Version

img/plan.sh
Updated pkg_version 0.5.7 -> 0.5.11 in support of 2021 Q2 core plans refresh.
=> Update img Plan Package Version

imagemagick/plan.sh
Updated pkg_version 7.0.9-9 -> 7.0.11-3 in support of 2021 Q2 core plans refresh.
Also had to update the `pkg_source` since the previous one no longer exists.
=> Update imagemagick Plan Package Version

ghc82-bootstrap/plan.sh
Updated pkg_version 8.2.1 -> 8.2.2 in support of 2021 Q2 core plans refresh.
=> Update ghc82-bootstrap Plan Package Version

kubectl/plan.sh
Updated pkg_version 1.18.5 -> 1.20.5 in support of 2021 Q2 core plans refresh.
=> Update kubectl Plan Package Version

fping/plan.sh
Updated pkg_version "4.2" -> "4.4" in support of 2021 Q2 core plans refresh.
=> Update fping Plan Package Version

p11-kit/plan.sh
Updated pkg_version "0.23.10" -> "0.23.22" in support of 2021 Q2 core plans refresh.
=> Update p11-kit Plan Package Version

libwebp/plan.sh
Updated pkg_version 0.5.1 -> 0.6.1 in support of 2021 Q2 core plans refresh.
=> Update libwebp Plan Package Version

gnutls/plan.sh
Updated pkg_version 3.6.13 -> 3.6.15 in support of 2021 Q2 core plans refresh.
=> Update gnutls Plan Package Version

dovecot/plan.sh
Updated pkg_version 2.3.4 -> 2.3.14 in support of 2021 Q2 core plans refresh.
=> Update dovecot Plan Package Version

dotnet-asp-core/plan.sh
Updated pkg_version 3.1.0 -> 3.1.13 in support of 2021 Q2 core plans refresh.
=> Update dotnet-asp-core Plan Package Version

dcrpm/plan.sh, dcrpm/tests/test.bats
Version bump & set version explicitly due to pip search now being deprecated/disabled:
```
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API is currently disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">
```
=> dcrpm Version Bump

camlp4/plan.sh
Updated pkg_version "4.07" -> "4.12" in support of 2021 Q2 core plans refresh.
=> Update camlp4 Plan Package Version

libice/plan.sh
Updated pkg_version 1.0.9 -> 1.0.10 in support of 2021 Q2 core plans refresh.
=> Update libice Plan Package Version

buildkite-cli/plan.ps1
Updated pkg_version "0.4.1" -> "0.5.0" in support of 2021 Q2 core plans refresh.
=> Update buildkite-cli Plan Package Version

aspcud/plan.sh
Updated pkg_version 1.9.4 -> 1.9.5 in support of 2021 Q2 core plans refresh.
=> Update aspcud Plan Package Version

wal-e/plan.sh
Updated pkg_version 1.1.0 -> 1.1.1 in support of 2021 Q2 core plans refresh.
=> Update wal-e Plan Package Version

serf/plan.sh
Updated pkg_version 1.3.8 -> 1.3.9 in support of 2021 Q2 core plans refresh.
=> Update serf Plan Package Version

rabbitmq/plan.sh
Updated pkg_version 3.8.3 -> 3.8.14 in support of 2021 Q2 core plans refresh.
=> Update rabbitmq Plan Package Version

pester/plan.sh
Updated pkg_version "4.8.1" -> "4.10.1" in support of 2021 Q2 core plans refresh.
=> Update pester Plan Package Version

percona-xtrabackup/plan.sh
Updated pkg_version 2.4.9 -> 2.4.18 in support of 2021 Q2 core plans refresh.
=> Update percona-xtrabackup Plan Package Version

libdrm/plan.sh
Updated pkg_version 2.4.88 -> 2.4.104 in support of 2021 Q2 core plans refresh.
=> Update libdrm Plan Package Version

omniORB/plan.sh
Updated pkg_version '4.2.2' -> '4.3.0' in support of 2021 Q2 core plans refresh.
=> Update omniORB Plan Package Version

mc/plan.sh
Updated pkg_version 4.8.21 -> 4.8.26 in support of 2021 Q2 core plans refresh.
=> Update mc Plan Package Version

lcms2/plan.sh
Updated pkg_version 2.8 -> 2.12 in support of 2021 Q2 core plans refresh.
=> Update lcms2 Plan Package Version

httpd/plan.sh, httpd/tests/test.bats
Updated pkg_version 2.4.39 -> 2.4.46 in support of 2021 Q2 core plans refresh.
=> Update httpd Plan Package Version

metricbeat/plan.sh
Updated pkg_version 7.2.0 -> 7.12.0 in support of 2021 Q2 core plans refresh.
=> Update metricbeat Plan Package Version

shared-mime-info/plan.sh
Updated pkg_version 1.9 -> 1.10 in support of 2021 Q2 core plans refresh.
=> Update shared-mime-info Plan Package Version

fluentd/plan.sh
Updated pkg_version 1.0.2 -> 1.12.1 in support of 2021 Q2 core plans refresh.
=> Update fluentd Plan Package Version

openjpeg/plan.sh
Updated pkg_version 2.3.1 -> 2.4.0 in support of 2021 Q2 core plans refresh.
=> Update openjpeg Plan Package Version

mysql-client/plan.sh
Updated pkg_version 5.7.21 -> 5.7.32 in support of 2021 Q2 core plans refresh.
=> Update mysql-client Plan Package Version

dotnet-core-sdk/plan.sh, dotnet-core-sdk/tests/test.bats
Updated pkg_version 3.1.100 -> 3.1.113 in support of 2021 Q2 core plans refresh.
=> Update dotnet-core-sdk Plan Package Version

dotnet-core/plan.sh
Updated pkg_version 3.1.0 -> 3.1.13 in support of 2021 Q2 core plans refresh.
=> Update dotnet-core Plan Package Version

nginx/plan.ps1
Updated pkg_version "1.18.0" -> "1.20.0" in support of 2021 Q2 core plans refresh.
=> Update nginx Plan Package Version

.bldr.toml, wix/plan.ps1
Updated pkg_version "3.10.3" -> "${_base_version}.2" in support of 2021 Q2 core plans refresh.
=> Update wix Plan Package Version

cppcheck/plan.sh
Updated pkg_version 1.86 -> 1.90 in support of 2021 Q2 core plans refresh.
=> Update cppcheck Plan Package Version

raml2html/plan.ps1
Updated pkg_version "6.3.0" -> "6.7.0" in support of 2021 Q2 core plans refresh.
=> Update raml2html Plan Package Version

libgd/plan.sh
Updated pkg_version "2.2.4" -> "2.3.2" in support of 2021 Q2 core plans refresh.
=> Update libgd Plan Package Version

libsm/plan.sh
Updated pkg_version 1.2.2 -> 1.2.3 in support of 2021 Q2 core plans refresh.
=> Update libsm Plan Package Version

shellcheck/plan.sh
Updated pkg_version 0.7.0 -> 0.7.1 in support of 2021 Q2 core plans refresh.
=> Update shellcheck Plan Package Version

mosquitto/plan.sh
Updated pkg_version "1.4.15" -> "1.6.14" in support of 2021 Q2 core plans refresh.
=> Update mosquitto Plan Package Version

libxmu/plan.sh
Updated pkg_version 1.1.2 -> 1.1.3 in support of 2021 Q2 core plans refresh.
=> Update libxmu Plan Package Version

libcxx/plan.sh
Updated pkg_version 5.0.1 -> 5.0.2 in support of 2021 Q2 core plans refresh.
=> Update libcxx Plan Package Version

harfbuzz/plan.sh
Updated pkg_version 1.3.4 -> 1.9.0 in support of 2021 Q2 core plans refresh.
=> Update harfbuzz Plan Package Version

mssql/plan.sh
Updated pkg_version 14.0.3025.34-3 -> 14.0.3381.3-2 in support of 2021 Q2 core plans refresh.
=> Update mssql Plan Package Version

libxcursor/plan.sh
Updated pkg_version 1.1.15 -> 1.2.0 in support of 2021 Q2 core plans refresh.
=> Update libxcursor Plan Package Version

libxcomposite/plan.sh
Updated pkg_version 0.4.4 -> 0.4.5 in support of 2021 Q2 core plans refresh.
=> Update libxcomposite Plan Package Version

libxdamage/plan.sh
Updated pkg_version 1.1.4 -> 1.1.5 in support of 2021 Q2 core plans refresh.
=> Update libxdamage Plan Package Version

clojure/plan.sh
Updated pkg_version 1.10.0.442 -> 1.10.1.763 in support of 2021 Q2 core plans refresh.
=> Update clojure Plan Package Version

tomcat-native/plan.sh
Updated pkg_version '1.2.8' -> '1.2.26' in support of 2021 Q2 core plans refresh.
=> Update tomcat-native Plan Package Version

sbt/plan.sh
Updated pkg_version 1.3.12 -> 1.4.9 in support of 2021 Q2 core plans refresh.
=> Update sbt Plan Package Version

leiningen/plan.sh, leiningen/tests/test.bats
Updated pkg_version "2.8.1" -> "2.9.5" in support of 2021 Q2 core plans refresh.
=> Update leiningen Plan Package Version

kafka/plan.sh
Updated pkg_version 2.5.0 -> 2.7.0 in support of 2021 Q2 core plans refresh.
=> Update kafka Plan Package Version

kafka0/plan.sh
Updated pkg_version 0.10.2.2 -> 0.11.0.3 in support of 2021 Q2 core plans refresh.
=> Update kafka0 Plan Package Version

jetty/plan.sh
Updated pkg_version 9.1.5 -> 9.4.38 in support of 2021 Q2 core plans refresh.
=> Update jetty Plan Package Version

jenkins/plan.sh
Updated pkg_version 2.204.5 -> 2.277.1 in support of 2021 Q2 core plans refresh.
=> Update jenkins Plan Package Version

libepoxy/plan.sh
Updated pkg_version 1.4.3 -> 1.5.5 in support of 2021 Q2 core plans refresh.
=> Update libepoxy Plan Package Version

zookeeper/plan.sh
Updated pkg_version "3.6.2" -> "3.7.0" in support of 2021 Q2 core plans refresh
=> Update Zookeeper Plan Package Version

cerebro/plan.sh
Updated pkg_version 0.9.0 -> 0.9.3 in support of 2021 Q2 core plans refresh.
=> Update cerebro Plan Package Version

logstash/plan.sh, logstash/tests/test.bats
Updated pkg_version 6.4.3 -> 6.8.15 in support of 2021 Q2 core plans refresh.
=> Update logstash Plan Package Version

gocd-server/plan.sh
Updated pkg_version "18.9.0" -> "18.12.0" in support of 2021 Q2 core plans refresh.
=> Update gocd-server Plan Package Version

dnsmasq/plan.sh, dnsmasq/tests/test.bats
Updated pkg_version 2.81 -> 2.84 in support of 2021 Q2 core plans refresh.
=> Update dnsmasq Plan Package Version

leproxy/plan.sh
Updated pkg_version "20180113" -> "20191014" in support of 2021 Q2 core plans refresh.
=> Update leproxy Plan Package Version

kubernetes-proxy/plan.sh
Updated pkg_version 1.11.2 -> 1.20.5 in support of 2021 Q2 core plans refresh.
=> Update kubernetes-proxy Plan Package Version

ghc/plan.ps1
Updated pkg_version "8.8.1" -> "8.10.4" in support of 2021 Q2 core plans refresh.
=> Update ghc Plan Package Version

happy/plan.sh
Updated pkg_version 1.19.12 -> 1.20.0 in support of 2021 Q2 core plans refresh.
=> Update happy Plan Package Version

hspec-discover/plan.sh
Updated pkg_version 2.7.0 -> 2.7.9 in support of 2021 Q2 core plans refresh.
=> Update hspec-discover Plan Package Version

grpcurl/plan.sh
Updated pkg_version "1.5.1" -> "1.8.0" in support of 2021 Q2 core plans refresh.
=> Update grpcurl Plan Package Version

drupal/plan.sh
Updated pkg_version "8.3.2" -> "8.9.13" in support of 2021 Q2 core plans refresh.
=> Update drupal Plan Package Version

kafka2/plan.sh
Updated pkg_version 2.5.0 -> 2.7.0 in support of 2021 Q2 core plans refresh.
=> Update kafka2 Plan Package Version

coredns/plan.sh, coredns/tests/test.bats
Updated pkg_version 1.7.0 -> 1.8.3 in support of 2021 Q2 core plans refresh.
=> Update coredns Plan Package Version

.bldr.toml, clang-tools-extra/plan.sh
Updated pkg_version 7.0.0 -> 7.1.0 in support of 2021 Q2 core plans refresh.
=> Update clang-tools-extra Plan Package Version

llvm7/plan.sh
Updated pkg_version 7.0.1 -> 7.1.0 in support of 2021 Q2 core plans refresh.
Also had to update the `pkg_source` since the old one no longer exists.
=> Update llvm7 Plan Package Version

ffmpeg/plan.sh
Updated pkg_version 4.2.2 -> 4.3.2 in support of 2021 Q2 core plans refresh.
=> Update ffmpeg Plan Package Version

c-ares/plan.sh
Updated pkg_version "1.15.0" -> "1.17.1" in support of 2021 Q2 core plans refresh.
=> Update c-ares Plan Package Version

clang7/plan.sh
Updated pkg_version 7.0.1 -> 7.1.0 in support of 2021 Q2 core plans refresh.
=> Update clang7 Plan Package Version

clang/plan.sh
Updated pkg_version 7.0.1 -> 7.1.0 in support of 2021 Q2 core plans refresh.
=> Update clang Plan Package Version

ruby25/plan.sh
Fixes SSL issues in refresh env
=> Adding cacerts to build_deps, export SSL_CERT_FILE for gem update/install

postgresql12-client/plan.sh
Updated pkg_version 12.5 -> 12.6 in support of 2021 Q2 core plans refresh.
=> Update postgresql12-client Plan Package Version

nload/plan.sh
=> Fixing DSO missing from command line using --copy-dt-needed-entries

dotnet-5-runtime/plan.ps1
Updated pkg_version "5.0.0" -> "5.0.6" in support of 2021 Q2 core plans refresh.
=> Update dotnet-5-runtime Plan Package Version

postgresql-client/plan.ps1
Updated pkg_version "9.6.11" -> "9.6.21" in support of 2021 Q2 core plans refresh.
=> Update postgresql-client Plan Package Version

concourse/plan.ps1
Updated pkg_version "4.2.2" -> "4.2.3" in support of 2021 Q2 core plans refresh.
=> Update concourse Plan Package Version

packer/plan.ps1
Updated pkg_version "1.5.6" -> "1.7.2" in support of 2021 Q2 core plans refresh.
=> Update packer Plan Package Version

protobuf/plan.ps1
Updated pkg_version "3.12.3" -> "3.16.0" in support of 2021 Q2 core plans refresh.
=> Update protobuf Plan Package Version

python36/plan.ps1
Updated pkg_version "3.6.6" -> "3.6.13" in support of 2021 Q2 core plans refresh.
=> Update python36 Plan Package Version

cabal-install/plan.ps1
Signed-off-by: Ravi Duddela <rduddela@progress.com>
=> Bumped 'cabal-install' version 2.0.0.0 -> 3.4.0.0 for windows

libarchive/plan.ps1
Updated pkg_version "3.4.2" -> "3.5.1" in support of 2021 Q2 core plans refresh.
=> Update libarchive Plan Package Version

openssl11/ca-dir.patch, openssl11/plan.sh, openssl11/tests/test.bats, openssl11/tests/test.sh
#3751 - fixes a regression from the removal of the sed
This will source the cacerts directories for ca certs; previous patch left empty directory in openssl pkg path
also added a test to the run.
Signed-off-by: Jeff Stasko <jeff.stasko@progress.com>
prior to openssl11 change - these ssl directories are empty
```bash
hab pkg exec y-me-y/python/3.7.11/20210920224958 python -c "import ssl; print(ssl.get_default_verify_paths())"
DefaultVerifyPaths(cafile=None, capath='/hab/pkgs/core/openssl11/1.1.1j/20210826185634/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/hab/pkgs/core/openssl11/1.1.1j/20210826185634/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/hab/pkgs/core/openssl11/1.1.1j/20210826185634/ssl/certs')
```
corresponding python package is sourced …
=> This will source the cacerts directories for ca certs; previous patch

packer/plan.sh, pax-utils/plan.sh
https://github.com/habitat-sh/core-plans/issues/4100
packer bumped from 1.7.0 to 1.7.8
pax-utils bumped from 1.3.2 to 1.3.3
=> Issue4100 [packer and pax-utils bumped]

oniguruma/plan.sh, opa/plan.sh, openldap/plan.sh, openssl11/plan.sh
opensll11 bumped from 1.1.1j to 1.1.1k
openldap bumped from 2.4.58 to 2.6.0 and requires openssl11 to build
opa bumped from 0.27.1 to 0.34.2
oniguruma bumped from 6.9.6 to 6.9.7.1
=> Issue4101 [openssl11, openldap, opa and oniguruma bumped]

gnupg2/plan.sh, libgcrypt/plan.sh, libksba/plan.sh
https://github.com/habitat-sh/core-plans/issues/4149
libksba bumped from 1.5.1 to 1.6.0
libgcrypt bumped from 1.9.2 to 1.9.4
gnupg2 bumped from 2.2.27 to 2.2.32
=> Issue4149 [libksba, libgcrypt and gnupg2 bumped]

ncdu/plan.sh, netcat-openbsd/plan.sh
https://github.com/habitat-sh/core-plans/issues/4104
ncdu from 1.15 to 1.16
netcat-openbsd from 1.217 to 1.218
=> Issue 4104: [ncdu and netcat-openbsd bumped]

restic/plan.sh
https://github.com/habitat-sh/core-plans/issues/4095
=> restic bumped from 0.12.0 to 0.12.1

libzip/plan.sh, userspace-rcu/plan.sh
https://github.com/habitat-sh/core-plans/issues/4107
libzip from 1.7.3 to 1.8.0 bumped 
userspace-rcu from 0.12.3 to 0.13.0 bumped
=> Issue 4107 [libzip and userspace-rcu bumped]

libssh2/plan.sh, libtalloc/plan.sh
https://github.com/habitat-sh/core-plans/issues/4108
libssh2 from 1.9.0 to 1.10.0
libtalloc from 2.3.2 to 2.3.3 bumped
=> Issue 4108 [libssh2 and libtalloc bumped]

libpcap/plan.sh, libpq/plan.sh
https://github.com/habitat-sh/core-plans/issues/4109
libpcap from 1.10.0 to 1.10.1
libpq from 9.6.21 to 9.6.24
=> Issue 4109 [libpcap and libpq bumped]

jfrog-cli/plan.sh, kmod/plan.sh
https://github.com/habitat-sh/core-plans/issues/4113
jfrog-cli from 1.43.2 to 1.52.0
kmod from 28 to 29
=> Issue 4113 [jfrog-cli and kmod bumped]

jemalloc/plan.sh
https://github.com/habitat-sh/core-plans/issues/4114
jemalloc from 4.4.0 to 4.5.0 bumped
=> Issue 4114 [jemalloc from 4.4.0 to 4.5.0 bumped]

composer/plan.sh
Should not be a breaking change for anyone. Packagist has started forcing deprecation of composer 1.x
=> [composer] bump version 1.10.20 -> 2.1.9

libtasn1/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4124
libtasn1 bumped from 4.16.0 to 4.18.0
=> libtasn1 bumped from 4.16.0 to 4.18.0

filebeat/plan.sh, fish/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4123
fish from 2.7.0 to 2.7.1
filebeat from 7.12.0 to 7.15.2
=> Issue 4123: [fish from 2.7.0 to 2.7.1  & filebeat from 7.12.0 to 7.15.2 bumped]

postgresql95-client/plan.sh
https://github.com/habitat-sh/core-plans/issues/4245
=> postgresql95-client pinning to 9.5 version instead of 9.6

elfutils/plan.sh, envconsul/plan.sh
https://github.com/habitat-sh/core-plans/issues/4126
elfutils from 0.183 to 0.186 And envconsul from 0.11.0 to 0.12.1 bumped
=> Issue4126: [elfutils from 0.183 to 0.186 And envconsul from 0.11.0 to 0.12.1 bumped]

dpkg/plan.sh, e2fsprogs/plan.sh, lttng-ust/plan.sh
https://github.com/habitat-sh/core-plans/issues/4127
dpkg from 1.19.7 to 1.20.9
e2fsprogs from 1.46.2 to to 1.46.4
lttng-ust from 2.12.1 to 2.13.0
=> Issue4127 [dpkg to 1.20.9, e2fsprogs to 1.46.4 and lttng-ust to 2.13.0 bumped]

libcerf/plan.sh
https://github.com/habitat-sh/core-plans/issues/4152
libcerf from 1.13 to 1.17 bumped
=> Issue4152 [libcerf from 1.13 to 1.17 bumped]

curator/plan.sh, curl-static-musl/plan.sh, valgrind/plan.sh
https://github.com/habitat-sh/core-plans/issues/4131
curator from 5.8.3 to 5.8.4
curl-static-musl from 7.75.0 to 7.80.0
valgrind from 3.17.0 to 3.18.1
=> Issue4131 [curator to 5.8.4, curl-static-musl to 7.80.0 and valgrind to 3.18.1 bumped]

consul/plan.sh, coreutils-static/plan.sh
https://github.com/habitat-sh/core-plans/issues/4133
consul from 1.9.4 to 1.10.4 
coreutils-static from 8.32 to 9.0
=> Issue4133 [consul to 1.10.4 and coreutils-static to 9.0 bumped]

monit/plan.sh, mono5/plan.sh, nats-streaming-server/plan.sh
https://github.com/habitat-sh/core-plans/issues/4105
monit from 5.27.2 to 5.29.0 and 
mono5 from 5.10.1.47 to 5.20.1.34 and
nats-streaming-server from 0.21.1 to 0.23.1 bumped
=> Issue 4105 [monit, mono5 and nats-streaming-server bumped]

googlemock/plan.sh, govc/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4119
govc bumped from 0.24.1 to 0.27.1
googlemock from 1.10.0 to 1.11.0
=> Issue4119 [govc and googlemock bumped]

pngquant/plan.sh, postfix/plan.sh, rebar3/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4145
rebar3 from 3.14.14to 3.17.0, 
postfix from 3.5.9 o 3.6.3 
pngquant from 2.13.1 to 2.17.0
=> Issue4145 [rebar3 to 3.17.0, postfix to 3.6.3 and pngquant to 2.17.0 bumped]

netdata/plan.sh, nmap/plan.sh, openresty/plan.sh, powershell/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4146
poershell from 7.1.3 to 7.2.0, 
netdata from 1.29.3 to 1.32.0, 
openresty 1.19.3.1 to 1.19.9.1
nmap from 7.91 to 7.92 
=> Issue 4146[powershell to 7.2.0, netdata to 1.32.0, openresty to 1.19.9.1 and nmap to 7.92 bumped]

gifsicle/plan.sh
https://github.com/habitat-sh/core-plans/issues/4120
gifsicle bumped from 1.92 to 1.93
=> Issue4120 [gifsicle bumped from 1.92 to 1.93]

drush/plan.sh, ffmpeg/plan.sh, ffmpeg3/plan.sh, ffmpeg4/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4175
ffmpeg bumped from 4.3.2 to 4.4.1
ffmpeg3 bumped from 3.4.8 to 3.4.9
ffmpeg4 bumped from 4.4 to 4.4.1
Drush from 8 to 8.4.8
=> Issue4175 [ffmpeg, ffmpeg3, ffmpeg4 and drush bumped]

bdwgc7/plan.sh, bdwgc8/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4158
bdwgc7 from 7.6.12 to 7.6.14
bdwgc8 from 8.0.4 to 8.2.0
=> Issue4158 [bdwgc7 to 7.6.14 and bdwgc8 to 8.2.0 bumped]

kubernetes-apiserver/plan.sh, kubernetes-controller-manager/plan.sh, kubernetes-kubelet/plan.sh, kubernetes-proxy/plan.sh, kubernetes-scheduler/plan.sh, kubernetes/plan.sh
https://github.com/habitat-sh/core-plans/issues/4188
Kubernetes from 1.20.5 to 1.23.0
Kubernetes-apiserver from 1.20.5 to 1.23.0
Kubernetes-kubelet from 1.20.5 to 1.23.0
Kubernetes-proxy from 1.20.5 to 1.23.0
Kubernetes-scheduler from 1.20.5 to 1.23.0
Kubernetes-controller-manager from 1.20.5 to 1.23.0
=> Issue 4188 [All Kubernetes components bumped from 1.20.5 to 1.23.0]

shellcheck/plan.sh, tlog/plan.sh, wordpress/plan.sh
Issue: #4172
Wordpress from 4.7.19 to 4.9.18
tlog from 11 to 12
shellcheck from 0.7.1 to 0.8.0
=> Issue4172 [wordpress to 4.9.18, tlog to 12 and shellcheck to 0.8.0 bumped]

github_changelog_generator/plan.sh, libgd/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4166
github_changelog_generator from 1.16.1 to 1.16.4
libgd from 2.3.2 to 2.3.3
=> Issue4166 [github_changelog_generator to 1.16.4 and libgd to 2.3.3 bumped]

elasticsearch/plan.sh
=> upgraded elasticsearch to v6.8.21 due to CVE44228

libcxxabi/plan.sh, mosquitto/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4173
libcxxabi from 5.0.1 to 5.02
mosquito from 1.6.14 to 1.6.15
=> Issue4173 [libcxxabi to 5.0.2 and mosquitto to 1.6.15 bumped]

dotnet-core-sdk/plan.sh, dotnet-core/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4168
dotnet-core-sdk from 3.1.113 to 3.1.416
botnet-core from 3.1.13 to 3.1.22
=> Issue4168 [dotnet-core-sdk to 3.1.416 and dotnet-core to 3.1.22 bumped]

grpc-cpp/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4174
grace-cpp from 1.38.0 to 1.42.0
journalbeat : https://github.com/habitat-sh/core-plans/pull/4318
=> Issue4174 [grpc-cpp bumped from 1.38.0 to 1.42.0]

jetty/plan.sh, kafka/plan.sh, leiningen/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4181
jetty 9.4.38 to 9.4.44
kafka 2.7.0 o 2.7.2
leiningen from 2.9.5 to 2.9.8
=> Issue4181 [jetty to 9.4.44, kafka to 2.7.2 and leiningen to 2.9.8 bumped]

snappy/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4112
snappy bumped from 1.1.8 to 1.1.9 and fixed build issue
=> Issue4112 [snappy bumped from 1.1.8 to 1.1.9 and fixed build issue]

mssql/plan.sh, xeyes/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4176
xeyes from 1.1.2 to 1.2.0
mssql from 14.0.3381.3-2 to 14.0.3421.10-2
=> Issue4176 [xeyes to 1.2.0 and mssql to 14.0.3421.10-2 bumped]

prometheus/plan.sh, prometheus2/plan.sh, protobuf-c/plan.sh, pv/plan.sh
https://github.com/habitat-sh/core-plans/issues/4098
pv bumped from 1.6.6 to 1.6.20
protobuf-c bumped from 1.3.3 to 1.4.0
=> Issue4098 [pv,protobuf-c,prometheus and prometheus2 bumped]

.bldr.toml, postgresql13-client/plan.sh
We have corresponding client packages for each of the server versions. Added the missing client version for Postgres 13. 
Once the PR is approved and merged to main, we need to trigger a new build and publish to 'stable', and 'stable2021-q2' (required by automate) channels.
Signed-off-by: Phani Sajja <psajja@progress.com>
=> Add Postgres 13 Client

atk/plan.sh, glib/plan.sh, libdrm/plan.sh, meson/plan.sh, msodbcsql17/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4162
glib 2.68.0 to 2.70.2, 
libdrm from 2.4.104 to 2.4.109, 
meson from 0.57.1 to 0.60.2 
msodbcsql from 17.7.2.1-1 to 17.8.1.1-1
ask from 2.28.1 to 2.36.0
=> Issue4162 [glib to 2.70.2, libdrm to 2.4.109, meson to 0.60.2, msodbcsql to 17.8.1.1-1 and atk to 2.36.0 bumped]

gtk2/plan.sh, jenkins/plan.sh, libepoxy/plan.sh
Issue: https://github.com/habitat-sh/core-plans/issues/4182
Jenkins from 2.277.1 to 2.319.1, 
gtk2 from 2.24.31  to 2.24.33
libepoxy from 1.5.5 to 1.5.9
=> Issue4182: [Jenkins to 2.319.1, gtk2 to 2.24.33 and libepoxy to 1.5.9 bumped]

lsyncd/plan.sh
due to incompatibility with Lua v5.4.2, it is been decided to revert upgrade of package and add to skip list for refresh
fixes #4147 
=> revert lsyncd upgrade to v2.2.1

haproxy18/plan.sh
Issue: https://chefio.atlassian.net/browse/HABP-103
=> adding build function as haproxy19 is deprecated.fixing build issue

asciinema/plan.ps1, buildkite-agent/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-36
asciinema bumped from 2.0.1 to 2.1.0
aws-cli bumped from 1.20.33 to 1.22.71 (No change in plan.ps1 as pkg-version calculated at runtime)
buildkite-agent bumped from 3.29.0 to 3.34.0
=> issue-HABP-36 [asciinema, aws-cli and buildkite-agent bumped for windows]

cabal-install/plan.ps1, cmake/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-37
cmake bumped from 3.20.2 to 3.23.3
cabal-install bumped from 3.4.0.0 to 3.6.2.0
carets from 21.07.05 to 22.02.01 (No change in plan.ps1 as pkg-version calculated at runtime)
=> Issue-HABP-37 [cmake, cacerts and cabal-install bumped for windows]

perl/plan.ps1, postgresql-client/plan.ps1, postgresql11-client/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-47
perl bumped from 5.33.9 to 5.34.0
postgresql-client from 9.6.21 to 9.6.24
postgresql11-client from 11.11 to 11.15
=> Issue HABP-47 [perl, postgresql-client and postgresql11-client bumped for windows]

nginx/plan.ps1, node/plan.ps1, node12/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-45
nginx bumped from 1.20.0 to 1.21.6
node from 14.16.0 to 14.19.0
node12 from 12.22.1 to 12.22.10
=> issue-HABP-45 [nginx, node and node12 bumped for windows]

node14/plan.ps1, openssl/plan.ps1, packer/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-46
node14 bumped from 14.16.0 to 14.19.0
openssl bumped from 1.1.1k to 1.1.1L
packer bumped from 1.7.2 to 1.8.0
=> Issue-HABP-46 [node14,openssl and packer bumped for windows]

ghc/plan.ps1, go/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-42
ghc bumped from 8.10.4 to 8.10.7
go bumped from 1.16.4 to 1.16.15
=> Issue-HABP-42 [ghc and go bumped for windows]

dotnet-47-dev-pack/plan.ps1, dotnet-471-dev-pack/plan.ps1, dotnet-472-dev-pack/plan.ps1, dotnet-472-runtime/plan.ps1, dotnet-5-runtime/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-40
dotnet-5-runtime bumped from 5.0.6 to 5.0.15
pkg_source value changed for dotnet-472-runtime,dotnet-472-dev-pack,dotnet-471-dev-pack and dotnet-47-dev-pack
=> Issue-HABP-40 [dotnet-5-runtime bumped and dotnet-47,471 and 472 url changed for windows]

postgresql96-client/plan.ps1, powershell/plan.ps1, protobuf/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-48
Postgresql96-client from 9.6.21 to 9.6.24
Powershell from 7.1.3 to 7.2.2
protobuf from 3.16.0 to 3.19.4
=> Issue-HABP-48 [postgresql96-client,powershell and protobuf bumped for Windows]

visual-build-tools-2017/plan.ps1, visual-build-tools-2019/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-52
visual-build-tools-2017 from 15.9.21 to 15.9.45
visual-build-tools-2019 from 16.10.4 to 16.11.11
=> Issue-HABP-52 [visual-build-tools for 2017 and 2019 bumped for Windows]

docker-credential-helper/plan.ps1, git/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-54
docker-credential-helper bumped from 0.6.3 to 0.6.4
git bumped from 2.33.1 to 2.35.1
=> docker-cred-helper and git bumped for windows

zlib/plan.ps1
Issue: https://chefio.atlassian.net/browse/HABP-54
zlib bumped from 1.2.11 to 1.2.12
=> bump and fix windows zlib to 1.2.12

windows-10-sdk/plan.ps1
This fixes the location of the bin, include and lib dirs so that packages built using this sdk will correctly compile.
=> fix paths for bin, include and lib directories to line up with version

rust/plan.ps1, rust/plan.sh
modified plan files as part of bumping core/rust from 1.67.1 to 1.68.0
=> bump core/rust from 1.67.1 to 1.68.0

haproxy/plan.sh
This PR updates HAProxy to 2.2.29, which has a fix for CVE-2023-25725.
=> [haproxy] update to 2.2.29, containing CVE-2023-25725 fix

postfix/fix-aws-kernel-version.patch, postfix/plan.sh
updated source code to include kernel release 6.x to build postfix on Ubuntu 22.04 Amazon AMI
=> [postfix] fix for unidentified kernel release

mongodb/plan.sh, shield-agent/plan.sh, shield/plan.sh
pre-build pyyaml package is downloaded by pip while building MongoDB as an incompatible dependency hence v5.3.1 is configured to be used.
=> [mongodb] fix for python package pyyaml incompatibility

minio/plan.sh, minio/tests/test.bats
https://chefio.atlassian.net/browse/CHEF-6357
Minio bumped to latest version 2023-09-23T03-47-50Z to fix CVE issues.
=> Minio bumped to 2023-09-23T03-47-50Z for fixing CVE-2023-28434

python/plan.sh
downgraded python to v3.11 from v3.12 due to compatibility issues in dependents
=> [python] downgraded python to v3.11 from v3.12

netcat-openbsd/plan.sh
upgraded version to v1.226 as v1.218 is unavailable for download
=> [netcat-openbsd] upgraded version to v1.226

fd/plan.sh
once_cell is unstable feature and only available in nightly builds of rust
For more information about this error, try `rustc --explain E0658`
=> [fd] changed to rust-nightly for once_cell feature

nginx/plan.ps1
https://chefio.atlassian.net/browse/CHEF-9071
As we moved the Windows and Linux plan files in the root folder, hooks from Linux are copied to Windows folder.  Added new function to fix the error.
=> Fixing the build error as we moved linux and Winodws plan files in same folder [CHEF-9071]

ruby26/plan.sh
older ruby version is incompatible with new releases of rubygems-update.
change gem update version to match compatibility with older ruby version
=> change gem update version to match compatibility with older ruby version

rust/plan.ps1, rust/plan.sh
- updates plan.ps1 for rust 1.79.0
- updates plan.sh for rust 1.79.0
- updates shared object find stmt for patchelf in plan.sh to account for changes in rust shared objects
=> Update rust to 1.79.0

.bldr.toml, go22/README.md, go22/cacerts.patch, go22/plan.ps1, go22/plan.sh, go22/tests/hello.go, go22/tests/test.bats, go22/tests/test.sh
https://chefio.atlassian.net/browse/CHEF-12605
core/go22 needed on **stable** channel for Linux and Windows platforms for Courier and node agents.
=> New package go22 with version 1.22.4 added for Linux/Wondows[CHEF-12605]

go22/plan.ps1
go22 from 1.22.4 to 1.225 for courier team.
=> go22 bumped from 1.22.4 to 1.22.5 for windows

ruby31/plan.sh
Installing gem ffi with version 1.16.3.
Installing gem ffi-libarchive with version 1.1.14.
Adding core/libarchive as pkg_dep for ffi and ffi-libarchive gems.
=> Installing ffi and ffi-libarchive gems to fix the Infra-client runtime errors for ruby 3.1.6 version.

curl/plan.sh, curl/tests/test.bats, qemu/plan.sh
=> [curl] upgraded to v8.7.1
